/* ===== pronúncia extra para a leitura em voz alta (somem do texto, só mudam o áudio) ===== */
var PRONX={
 TPM:'tê pê ême',OEE:'ô é é',MTBF:'ême tê bê éfe',MTTR:'ême tê tê érre',SLA:'ésse éle á',SLO:'ésse éle ô',SLI:'ésse éle í',
 K8s:'cá oito ésse',CI:'cê í',CD:'cê dê',CDN:'cê dê ene',IaaS:'iás',PaaS:'pás',SaaS:'sás',BaaS:'bás',
 EC2:'ê cê dois',S3:'ésse três',RDS:'érre dê ésse',GCP:'gê cê pê',VPC:'vê pê cê',VPS:'vê pê ésse',VM:'vê ême',VMs:'vê êmes',
 SMTP:'ésse ême tê pê',SPF:'ésse pê éfe',DKIM:'dikim',DMARC:'dimárc',WSDL:'dábliu ésse dê éle',SOAP:'soup',CORS:'córs',CMS:'cê ême ésse',RLS:'érre éle ésse',
 OpenAPI:'ôupen á pê í',Swagger:'suéguer',WebSocket:'uébsóquete',Webhook:'uébruque',Webhooks:'uébruques',
 NestJS:'nést jê ésse',FastAPI:'fést á pê í',Pydantic:'paidântic',Zod:'zód',Prisma:'prisma',SQLAlchemy:'ésse quê éle álquemi',
 Hibernate:'raibernêit',Eloquent:'élocuent',ActiveRecord:'áctiv récord',RabbitMQ:'rábit ême quê',SQS:'ésse quê ésse',BullMQ:'bul ême quê',
 Lambda:'lâmbda',Cloudflare:'claudflér',Strapi:'estrápi',Contentful:'contentful',Sanity:'sâniti',WordPress:'uórdpress',Joomla:'djumla',Drupal:'drúpal',
 Supabase:'supabeis',Appwrite:'ápraite',Kong:'cóng',SendGrid:'sendgrid',Mailgun:'meilgân',Resend:'risend',Rails:'reils',Symfony:'símfoni',
 Ansible:'ânsibol',Jenkins:'djênkins',Jenkinsfile:'djênkins fáil',Helm:'rélm',ArgoCD:'árgo cê dê',Flux:'flâx',Istio:'ístio',Azure:'ájure',Entra:'êntra',
 Datadog:'deitadogue',Loki:'lôqui',Sentry:'séntri',ELK:'é éle cá',Elasticsearch:'elástic sêrch',Kibana:'quibana',Nagios:'nágios',Zabbix:'zábix',
 OpenTelemetry:'ôupen telémetri',Jaeger:'iéiguer',Traefik:'tráfic',HAProxy:'eiche próxi',Apache:'apátchi',Caddy:'cédi',
 Netlify:'nétlifai',Heroku:'herôku',Render:'rênder',Railway:'reilueí',DigitalOcean:'dígital ôuchan',Vagrant:'vêigrant',VirtualBox:'vírtual box',
 VMware:'vi ême uér',Proxmox:'próxmox',KVM:'cá vê ême',Certbot:'sértbot',MinIO:'mínio',R2:'érre dois',D1:'dê um',Workers:'uórkers',Fastly:'fástli',
 Akamai:'acamái',CloudFront:'claud frant',CloudFormation:'claud formêichon',Pulumi:'pulumi',OpenTofu:'ôupen tôfu',HashiCorp:'rachicorp',
 MLflow:'ême éle flou',Kubeflow:'kiubflou',DVC:'dê vê cê',SageMaker:'seidjmêiker',Vertex:'vértex',BigQuery:'big quéri',GKE:'gê cá é',
 WAF:'uáf',NAT:'nát',DHCP:'dê agá cê pê',VLAN:'vê lán',FTP:'éfe tê pê',SFTP:'ésse éfe tê pê',
 chmod:'tchê mód',chown:'tchê ôun',sudo:'sudô',systemd:'sistêm dê',systemctl:'sistêm cê tê éle',journalctl:'jórnal cê tê éle',
 crontab:'cron táb',cron:'crôn',Cron:'crôn',rsync:'érre sink',restic:'réstic',bcrypt:'bê-cript',Protobuf:'proto bâf',
 YAML:'iâmel',Pandas:'pândas',Uvicorn:'iuvicórn',Gunicorn:'guni córn',Nodemailer:'nôud meiler',Zapier:'zêipier',n8n:'ene oito ene',UiPath:'iu í pat',
 SLOs:'ésse éle ôs',SLIs:'ésse éle ís',SLAs:'ésse éle ás',
 '2D':'dois dê',
 AI:'ei ai',AJAX:'ájax',ASCII:'ásqui',CAD:'cád',CAM:'cám',CCNA:'cê cê ene á',CLPs:'cê éle pês',CNC:'cê ene cê',COBOL:'cóbol',D3:'dê três',DOM:'dóm',
 ERPs:'é érre pês',ESLint:'ê ésse lint',FinOps:'fin ops',GitOps:'guit ops',GB:'gigabaites',KB:'quilobaites',MB:'megabaites',GPL:'gê pê éle',HD:'agá dê',
 IBM:'í bê ême',ID:'í dê',IHMs:'í agá êmes',JPG:'jota pê gê',JSX:'jê ésse xis',JVM:'jota vê ême',JetBrains:'djét breins',LAN:'lán',LoRa:'lôra',LoRaWAN:'lôra uán',
 MATLAB:'mátlab',MIT:'ême í tê',MX:'ême xis',NuGet:'nu guét',OSI:'ô ésse í',OpenID:'ôupen ai dê',PC:'pê cê',PDFs:'pê dê éfes',PWAs:'pê dáblio ás',PowerShell:'páuer chél',
 RGB:'érre gê bê',RPA:'érre pê á',SDK:'ésse dê cá',SES:'ésse í ésse',SPA:'ésse pê á',SSD:'ésse ésse dê',SSG:'ésse ésse gê',SVG:'ésse vê gê',SvelteKit:'esvélt quit',
 SwiftUI:'suíft iu ai',TI:'tê í',TV:'tê vê',UI:'iu ai',UX:'iu éx',V8:'vê oito',VBA:'vê bê á',WebAssembly:'ueb assémbli',WhatsApp:'uótsap',a11y:'ê onze uai',
 IndexedDB:'índexed dê bê',iPad:'ai pád',iPhone:'ai fôn',localStorage:'lôcal storidge',sessionStorage:'séchon storidge',macOS:'mac ô ésse',setTimeout:'set táim aut',
 ECharts:'í charts',CloudWatch:'claud uótch',HttpOnly:'agá tê tê pê ônli',GET:'guét',POST:'pôst',PUT:'pút',DELETE:'dilít',PATCH:'pétch',Base64:'bêise sessenta e quatro',
 '3D':'três dê','4G':'quatro gê','5G':'cinco gê',
 TypeORM:'taip érre ô ême',Sequelize:'sícuelaiz',Joi:'djoi',
 SELECT:'selécti',FROM:'fróm',WHERE:'uér',INSERT:'insérti',UPDATE:'apdêit',JOIN:'djóin',JOINs:'djóins',INNER:'íner',LEFT:'léft',RIGHT:'ráit',FULL:'fúl',NULL:'nal',
 BEGIN:'bigin',COMMIT:'comít',GROUP:'grúp',ORDER:'órder',BY:'bai',EXPLAIN:'expléin',ANALYZE:'ânalaiz',
 DAG:'dégue',DAX:'dáks',DER:'dê é érre',CAP:'cáp',CSVs:'cê ésse vês',ELT:'é éle tê',OLAP:'ôlap',OLTP:'ô éle tê pê',LAMP:'lémp',MERN:'mérn',M8:'ême oito',
 SGBD:'ésse gê bê dê',SSMS:'ésse ésse ême ésse',XLSX:'xis éle ésse xis',PROCV:'pro cê vê',
 MapReduce:'mép ridiús',MariaDB:'maria dê bê',DuckDB:'dâc dê bê',DynamoDB:'dáinamo dê bê',InfluxDB:'influx dê bê',QuestDB:'quest dê bê',TimescaleDB:'táimscêil dê bê',
 Neo4j:'nêo quatro jota',PostGIS:'pôst guis',Postgres:'pôstgres',PySpark:'pai espárk',Spark:'espárk',Databricks:'dêitabricks',Snowflake:'snôuflêik',Redshift:'rédchift',
 Parquet:'parquê',Pinecone:'páincôun',Qdrant:'quê drant',Weaviate:'uívieit',Chroma:'crôma',Milvus:'mílvus',pgvector:'pê gê véctor',
 Airflow:'érflou',Prefect:'prífect',Dagster:'dégster',Luigi:'luíji',Talend:'tálend',Fivetran:'faivtrán',dbt:'dê bê tê',Jinja:'djínja',
 Tableau:'tablô',Looker:'lúquer',Metabase:'métabeis',Superset:'súperset',Qlik:'clic',
 Excel:'écsel',Sheets:'chits',Airtable:'értêibol',Notion:'nôuchon',Smartsheet:'smartchit',Office:'ófis',LibreOffice:'líbre ófis',LinkedIn:'línkedin',SharePoint:'chérpôint',
 Microsoft:'maicrosóft',Oracle:'órakol',Valkey:'válquei',Memcached:'mem cácht',Dragonfly:'drágonflai',KeyDB:'quí dê bê',Cypher:'sáifer',CQL:'cê quê éle',
 Bigtable:'big têibol',ScyllaDB:'sila dê bê',HBase:'êiche bêis',CouchDB:'cautch dê bê',DocumentDB:'dóquiument dê bê',Cosmos:'cósmos',Kinesis:'quinísis',
 Pulsar:'púlsar',Redpanda:'rédpanda',Delta:'déuta',Iceberg:'áisberg',Hudi:'rudi',Trino:'trino',Presto:'présto',Polars:'pôlars',Dask:'dásk',Flink:'flink',
 Hadoop:'radúp',Logstash:'lógstach',Solr:'sólar',Meilisearch:'mêili sérch',Typesense:'taip sense',Lucene:'lucín',Alembic:'alêmbic',Flyway:'flaiuei',Liquibase:'líquibeis',
 DBeaver:'dê bíver',Neon:'níon',Mongoose:'múngus',
 '2FA':'dois éfe á',ANPD:'á ene pê dê',Argon2:'argon dois',CEH:'cê é agá',CIA:'cê í á',CIS:'cê í ésse',CPF:'cê pê éfe',CSP:'cê ésse pê',
 CTF:'cê tê éfe',CTFs:'cê tê éfes',CVSS:'cê vê ésse ésse',DAST:'dást',SAST:'sást',IAST:'iást',SCA:'ésse cê á',DSS:'dê ésse ésse',DVWA:'dê vê dáblio á',
 EDR:'é dê érre',XDR:'xis dê érre',MDR:'ême dê érre',NDR:'ene dê érre',FIDO2:'fido dois',HackerOne:'ráquer uân',ICS:'í cê ésse',IEC:'í é cê',ISO:'ízo',LGPD:'éle gê pê dê',
 Log4j:'lóg quatro jota',MD5:'ême dê cinco',MITRE:'máiter',ModSecurity:'mód sequiúriti',NIST:'nist',NVD:'ene vê dê',ORMs:'ô érre êmes',OSCP:'ô ésse cê pê',OSINT:'ósint',
 OT:'ô tê',OverTheWire:'ôver dê uáier',PCI:'pê cê í',PIN:'pín',PicoCTF:'pícou cê tê éfe',QRadar:'quiu rádar',RBAC:'érre bê á cê',RDP:'érre dê pê',SHA:'ésse agá á',
 SMS:'ésse ême ésse',SSO:'ésse ésse ô',STRIDE:'estráid',SameSite:'seime sáit',TryHackMe:'trái ráque mi',WebAuthn:'uéb ô ên',eJPT:'ê jota pê tê',textContent:'téxt cóntent',
 innerHTML:'iner agá tê ême éle',scrypt:'ésse cript',WireGuard:'uáier gard',OpenVPN:'ôupen vê pê ene',IPsec:'í pê séc',Tailscale:'têilscêil',Bitwarden:'bit uórden',
 KeePassXC:'quí pás xis cê',YubiKey:'iúbi quí',passkey:'páskí',passkeys:'páskís',Vault:'vólt',gitleaks:'guit líks',Dependabot:'dipéndabót',Renovate:'rênovêit',
 Lynis:'lái nis',OpenSCAP:'ôupen ésse cáp',STIG:'estig',CrowdStrike:'craud estráik',SentinelOne:'séntinel uân',Wazuh:'uázu',Okta:'ôkta',Keycloak:'quí clóque',
 Nessus:'nésus',OpenVAS:'ôupen vás',Trivy:'trívi',ZAP:'záp',ASVS:'á ésse vê ésse',Falco:'fálco',Kyverno:'kaivérno',OPA:'ô pê á',Grype:'gráipe',Semgrep:'sém grép',
 CodeQL:'côud quê éle',SonarQube:'sónar quiub',Snyk:'snique',Prowler:'práuler',ScoutSuite:'scáut suít',Nuclei:'niúclei',Claroty:'clároti',Nozomi:'nozômi',Dragos:'drágos',
 Maltego:'maltêgo',Shodan:'xôdan',Censys:'sênsis',theHarvester:'dê rárvester',Autopsy:'ótopsi',Volatility:'volatíliti',Velociraptor:'velocirráptor',Intigriti:'intigríti',
 Bugcrowd:'bug craud',Parrot:'párrot',BlackArch:'blác árch',Kali:'cáli',Graylog:'gréilog',Metasploitable:'metasploitábol',Meterpreter:'meterpréter',PICERL:'pícerl',
 Purdue:'púrdiu',Profinet:'profinét',Snort:'snórt',Suricata:'suricata',Zeek:'zík',Tshark:'tê chárk',tshark:'tê chárk',tcpdump:'tê cê pê dâmp',Nikto:'níctô',sqlmap:'ésse quê éle mép',
 Hydra:'ráidra',Hashcat:'rách cát',Autorize:'otoráiz',Ghidra:'guídra',pentest:'péntest',Pentest:'péntest',Pentests:'péntests',
 Claude:'clód',ChatGPT:'tchát gê pê tê',Gemini:'djêmini',Copilot:'cópailot',Anthropic:'antrópic',OpenAI:'ôupen ei ai',Llama:'lâma',Mistral:'mistrál',Qwen:'tchuên',
 DeepSeek:'dip sic',Perplexity:'perplécsiti',Cursor:'cârsor',Codex:'côudecs',Windsurf:'uind sârf',Ollama:'olâma',Transformers:'transfórmers',
 LangChain:'lêng tchêin',LlamaIndex:'lâma índex',XGBoost:'ecs gê búst',LightGBM:'láit gê bê ême',Keras:'quéras',OpenCV:'ôupen cê vê',YOLO:'iôlo',
 LoRA:'lôra',QLoRA:'quiú lôra',RLHF:'érre éle agá éfe',VRAM:'vê rã',CUDA:'cúda',NVIDIA:'envídia',TPU:'tê pê u',TPUs:'tê pê us',NPU:'ene pê u',
 GPT4All:'gê pê tê fór ól',vLLM:'vê éle éle ême',Gemma:'djéma',Midjourney:'mid djârni',MAE:'ême á é',RMSE:'érre ême ésse é',ROC:'érre ó cê',AUC:'á u cê',
 F1:'éfe um',CNN:'cê ene ene',RNN:'érre ene ene',LSTM:'éle ésse tê ême',GAN:'gân',XAI:'xis á í',Whisper:'uísper',DataFrame:'dêita frêim',
 Matplotlib:'métplótlib',Seaborn:'sibórn',Kaggle:'cégol',Colab:'cólab',spaCy:'spêi ci',NLTK:'ene éle tê cá',Canny:'cáni',JAX:'djêics',SciPy:'sai pái',CuPy:'quiú pái',
 OCR:'ó cê érre',PLN:'pê éle ene',EPI:'é pê í',EPIs:'é pê ís',GPUs:'gê pê us',LLMs:'éle éle êmes',GPS:'gê pê ésse',ReLU:'rélu',Diceware:'dáiceuér',Grok:'gróc',
 ElevenLabs:'ilévn lábs',Cognex:'cógnex',Keyence:'quiêns',MediaPipe:'mídia páip',Kornia:'córnia',Detectron:'ditécron',AutoML:'ótou ême éle',BGE:'bê gê é',E5:'é cinco',Cohere:'coír'
};
var PRONSX=[
 [/HTTP\/2/g,'agá tê tê pê dois'],[/UTF-8/g,'iu tê éfe oito'],[/N\+1/g,'ene mais um'],[/3-2-1/g,'três, dois, um'],[/PUC-Rio/g,'púc rio'],
 [/EtherNet\/IP/g,'íther nét í pê'],[/Chart\.js/g,'chárt jê ésse'],[/D3\.js/g,'dê três jê ésse'],
 [/\.com\.br/g,' ponto com ponto bê érre'],[/\.com\b/g,' ponto com'],[/\.org\b/g,' ponto org'],[/\.io\b/g,' ponto ai ô'],
 [/Access-Control-Allow-Origin/g,'ácsses control alou orijin'],[/Object-Relational Mapping/g,'óbject rilêichonal méping'],
 [/ASP\.NET/g,'ásp dot net'],[/Let's Encrypt/g,'lets encrípt'],[/Hyper-V/g,'ráiper vê'],[/Express\.js/g,'expréss jê ésse'],
 [/GitHub Actions/g,'guit rab équechons'],[/GitHub Pages/g,'guit rab pêidjes'],[/Spring Boot/g,'espring bút'],[/Docker Compose/g,'dóquer compôuse'],
 [/Docker Hub/g,'dóquer râb'],[/Red Hat/g,'red rét'],[/Cloud Run/g,'claud rân'],[/Google Cloud/g,'gúgol claud'],
 [/pull request/gi,'pul riquést'],[/post-mortems?/gi,'pôst mórtem'],[/round robin/gi,'raund róbin'],[/blue-green/gi,'blu grin'],
 [/stand-by/gi,'estandibái'],[/failover/gi,'feilôver'],[/rollback/gi,'rôlbéc'],[/shift left/gi,'chift léft'],[/on-call/gi,'on cól'],
 [/runbooks?/gi,'ranbuc'],[/Protocol Buffers/g,'prótocol bâfers'],[/Server-Sent Events/g,'sérver sent ivents'],[/Web Socket/g,'uéb sóquete'],
 [/Material Design/g,'matíriol dizáin'],[/Power Automate/g,'páuer otomêit'],[/Active Directory/g,'áctiv dairétori'],
 [/PL\/SQL/g,'pê éle ésse quê éle'],[/T-SQL/g,'tê ésse quê éle'],[/SQL Server/g,'ésse quê éle sérver'],[/Power BI/g,'páuer bi ai'],[/Power Query/g,'páuer quéri'],
 [/Google Sheets/g,'gúgol chits'],[/Apps Script/g,'éps escrípt'],[/Linux Foundation/g,'línux faundêichon'],[/Row Level Security/g,'rôu lével sequiúriti'],
 [/Big Data/g,'big dêita'],[/data warehouses?/gi,'dêita uérrauz'],[/data lakes?/gi,'dêita lêik'],[/data marts?/gi,'dêita márts'],[/data historians?/gi,'dêita ristórians'],
 [/warehouse/gi,'uérrauz'],[/lakehouses?/gi,'lêik raus'],[/pipeline(s?)/gi,'páiplain$1'],[/dashboard(s?)/gi,'déchbórd$1'],[/embedding(s?)/gi,'embéding$1'],
 [/ DB\b/g,' dê bê'],[/EXPLAIN ANALYZE/g,'expléin ânalaiz'],[/Looker Studio/g,'lúquer stúdio'],[/Cosmos DB/g,'cósmos dê bê'],
 [/\bphishing\b/gi,'fíchin'],[/\bmalwares?\b/gi,function(m){return m.length>7?'málueirs':'málueir'}],[/\bransomwares?\b/gi,function(m){return m.length>10?'ránsomuérs':'ránsomuér'}],
 [/\bfirewall(s?)\b/gi,'faieruól$1'],[/\bhacker(s?)\b/gi,'ráquer$1'],[/\bhacking\b/gi,'ráquin'],[/\bexploit(s?)\b/gi,'ecsplóit$1'],[/\bpayload(s?)\b/gi,'peilôud$1'],[/\bbackdoor(s?)\b/gi,'béc dor$1'],
 [/\bbotnet(s?)\b/gi,'bótnét$1'],[/\bsniffer(s?)\b/gi,'snífer$1'],[/\bspoofing\b/gi,'spúfin'],[/\bkeylogger(s?)\b/gi,'quílóguer$1'],[/brute force/gi,'brut fórs'],[/\btoken(s?)\b/gi,'tôquen$1'],
 [/\blogin(s?)\b/gi,'lóguin$1'],[/\blogout\b/gi,'lógaut'],[/\bproxy\b/gi,'próxi'],[/bug bounty/gi,'bug báunti'],[/red team/gi,'réd tim'],[/blue team/gi,'blu tim'],[/purple team/gi,'pârpol tim'],
 [/Burp Suite/g,'bârp suít'],[/Hack The Box/gi,'rác dê bóx'],[/Juice Shop/g,'djus chóp'],[/Offensive Security/g,'ofênsiv sequiúriti'],[/Threat Dragon/g,'thrét drágon'],
 [/Capture The Flag/gi,'cápchur dê flégue'],[/Open Source Intelligence/gi,'ôupen sôrs intélidjens'],[/Security Operations Center/gi,'sequiúriti operêichons sênter'],
 [/Security Information and Event Management/gi,'sequiúriti informêichon énd ivént ménadjment'],[/Endpoint Detection and Response/gi,'éndpoint ditécchon énd rispónss'],
 [/zero trust/gi,'zíro trást'],[/CVE-(\d+)-(\d+)/g,'cê vê é $1 $2'],[/62443/g,'sessenta e dois quatrocentos e quarenta e três'],[/SP 800-(\d+)/g,'ésse pê oitocentos $1'],
 [/SHA-1\b/g,'ésse agá á um'],[/SHA-256/g,'ésse agá á duzentos e cinquenta e seis'],[/SHA-512/g,'ésse agá á quinhentos e doze'],[/ATT&CK/g,'atác'],[/1Password/g,'uân pásuord'],
 [/Dependency-Check/g,'dipéndensi chéc'],
 [/llama\.cpp/gi,'lâma cê pê pê'],[/scikit-learn/gi,'sáiquit lérn'],[/\bscikit\b/gi,'sáiquit'],[/LM Studio/g,'éle ême stúdio'],[/Hugging Face/g,'ráguin feis'],
 [/machine learning/gi,'maxín lérnin'],[/deep learning/gi,'dip lérnin'],[/\bfine-tuning\b/gi,'fáin tiúnin'],[/\boverfitting\b/gi,'ôverfítin'],[/\bclustering\b/gi,'clásterin'],
 [/speech-to-text/gi,'spích tu téxt'],[/text-to-speech/gi,'téxt tu spích'],[/retrieval-augmented generation/gi,'ritrívol ógmentid djenerêichon'],
 [/\bdeepfake(s?)\b/gi,'dip fêik$1'],[/\bfeedback\b/gi,'fidbéc'],[/\boutliers?\b/gi,'autlaier'],[/\bprompts?\b/gi,'prômpt'],[/\bchatbots?\b/gi,'tchátbót'],
 [/\bK-means\b/g,'câ mins'],[/DALL-E/g,'dáli'],[/\bAI Act\b/g,'ei ai áct'],[/Jupyter Notebook/g,'djúpiter nôutbuc'],[/Stable Diffusion/g,'stêibol difiúchon'],
 [/Google Colab/g,'gúgol cólab'],[/Meta AI/g,'méta ei ai'],[/\bdataset(s?)\b/gi,'dêita sét$1']
];
