/* ===== Fundamentos ===== */
C('base',[
E('bits','Bits, bytes e binário','Tudo no computador é ligado ou desligado',1,
 'O computador só entende dois estados: **ligado (1)** e **desligado (0)**. Cada um desses é um **bit**. Oito bits juntos formam um **byte**, e com um byte dá para representar 256 valores diferentes, como uma letra ou um número pequeno.',
 'É uma fileira de **chaves liga e desliga** num painel elétrico. Uma chave sozinha só diz sim ou não, mas com oito chaves você forma 256 combinações. Texto, foto, música e vídeo são só combinações de chaves.',
 ['Entender o tamanho dos arquivos: KB, MB e GB são múltiplos de bytes','Base para entender endereço IP, cores (RGB), letras (ASCII) e permissões','Ajuda a ler CLPs e redes industriais, onde você vê bits de entrada e saída o tempo todo'],
 ['binário',L('01000001  =  65  =  letra A','00000001  =  1','11111111  =  255','','Valor de cada posição, da esquerda para a direita:','128  64  32  16  8  4  2  1'),'Cada posição vale o dobro da anterior. Some só as que estão ligadas: 01000001 liga o 64 e o 1, então 64 + 1 = 65.'],
 'binary',['hardware','unicode','ip','cripto'],{tags:'binario zero um byte kilobyte megabyte'}),

E('hardware','CPU, memória e disco','As peças que fazem o computador funcionar',1,
 'A **CPU** é o cérebro que executa as instruções. A **memória RAM** guarda o que está em uso agora: é rápida, mas esquece tudo quando desliga. O **disco** (SSD ou HD) guarda de forma permanente e é mais lento. A **GPU** é um segundo chip, ótimo para fazer muitas contas simples ao mesmo tempo (gráficos e inteligência artificial).',
 'Numa oficina, a **CPU** é o mecânico, a **RAM** é a bancada onde ficam as ferramentas e peças do serviço atual, e o **disco** é o almoxarifado. Bancada grande deixa o mecânico trabalhar sem ir ao almoxarifado toda hora.',
 ['Entender por que o computador fica lento (pouca RAM, disco cheio, CPU no limite)','Escolher a máquina ou o servidor certo para cada tipo de trabalho','Saber a diferença entre CPU e GPU: IA usa muita GPU','Base para ler especificações de CLP, painel ou mini PC industrial'],
 ['terminal (Linux)',L('lscpu       # mostra o processador','free -h     # mostra a memória RAM','df -h       # mostra o espaço nos discos'),'Cada comando mostra uma peça da máquina. O -h só deixa os números legíveis (GB em vez de bytes).'],
 null,['so','bits','linux','embarcados'],{tags:'processador ram memoria ssd hd gpu placa de video'}),

E('so','Sistema operacional','O gerente que organiza o hardware e os programas',1,
 'O **sistema operacional** (Windows, Linux, macOS, Android, iOS) fica entre o hardware e os programas. Ele decide quem usa a CPU e a memória, guarda os arquivos e controla teclado, tela e rede. Os programas não conversam direto com as peças: pedem ao sistema.',
 'É o **supervisor de produção**. Os operadores (os programas) não vão sozinhos ao almoxarifado nem mexem na máquina quando querem: pedem ao supervisor, que organiza a fila e evita que um atrapalhe o outro.',
 ['Rodar vários programas ao mesmo tempo sem um derrubar o outro','Dar a cada programa só a permissão de que ele precisa (segurança)','Servir de base para tudo: sem ele, cada programa teria que saber operar o hardware inteiro','Cada tipo de equipamento tem o seu: servidores usam Linux, celulares usam Android ou iOS'],
 ['terminal (Linux)',L('ps aux | head -5     # programas em execução','ls /                 # pastas principais do sistema','whoami               # quem sou eu aqui'),'O ps lista os programas rodando agora. O | passa o resultado para o próximo comando, que aqui só mostra as primeiras linhas.'],
 null,['linux','processos','terminal','hardware'],{alt:'Windows, macOS, Linux, Android, iOS, FreeRTOS (tempo real)',tags:'windows macos android ios kernel'}),

E('linux','Linux','O sistema aberto que roda boa parte do mundo',1,
 '**Linux** é um sistema operacional criado por Linus Torvalds em 1991 e mantido por milhares de pessoas. É **livre**: qualquer um pode ver, usar e alterar o código. Existem várias versões chamadas **distribuições** (Ubuntu, Debian, Fedora, Arch). A maior parte dos servidores da internet roda Linux, e o Android é construído sobre o núcleo (kernel) do Linux.',
 'É um **motor de projeto aberto**: a planta é pública e qualquer fábrica pode montar a sua versão, melhorar e usar sem pagar licença. Cada distribuição é uma montadora diferente usando o mesmo motor.',
 ['Rodar servidores, sites e aplicações na nuvem','Base de containers, Docker e Kubernetes','Estudar programação e segurança (é o sistema favorito de quem faz hacking ético)','Rodar em equipamentos pequenos e industriais, como gateways, roteadores e painéis'],
 ['terminal',L('ls -l            # lista arquivos com detalhes','cd /var/log       # entra numa pasta','cat arquivo.txt   # mostra o conteúdo','sudo apt update   # atualiza a lista de programas (Ubuntu e Debian)'),'O sudo executa o comando como administrador. Os comandos mudam pouco entre distribuições, mas o gerenciador de pacotes (apt, dnf, pacman) varia.'],
 null,['terminal','so','docker','kali'],{alt:'Windows Server, FreeBSD, macOS',tags:'ubuntu debian fedora distro kernel',also:['ops']}),

E('terminal','Terminal e linha de comando','Conversar com o computador por texto',1,
 'O **terminal** é uma tela onde você manda ordens ao computador digitando, em vez de clicar. O programa que interpreta as ordens chama-se **shell** (Bash, Zsh, PowerShell). Parece antigo, mas é mais rápido e permite **automatizar**: o que você digita pode ser salvo num script e repetido mil vezes.',
 'Clicar é apertar botões de uma **IHM**. O terminal é falar direto com o **CLP**: você manda a ordem exata, sem tela bonita no meio. Para tarefa repetitiva, uma linha de comando vale mais do que cem cliques.',
 ['Mexer em servidores, que muitas vezes nem têm interface gráfica','Automatizar tarefas repetitivas com scripts','Usar ferramentas de desenvolvimento (git, npm, docker, python)','Procurar texto em milhares de arquivos em segundos'],
 ['bash',L('pwd                       # onde estou','ls                        # o que tem aqui','mkdir projeto             # cria uma pasta','cd projeto                # entra nela','echo "oi" > nota.txt      # cria arquivo com texto','grep -r "erro" .          # procura a palavra erro em tudo'),'Cada linha é um comando. O > manda a saída para um arquivo. O # começa um comentário, que o computador ignora.'],
 null,['linux','bash','git','ssh'],{tags:'cmd prompt shell console powershell zsh cli comando'}),

E('camadas','Abstração e camadas','Esconder detalhes para poder construir em cima',1,
 '**Abstração** é esconder os detalhes de baixo para você usar só a parte de cima. Você dirige sem saber como a injeção eletrônica funciona. Na informática tudo é feito em **camadas**: hardware, sistema operacional, linguagem, biblioteca, framework e o seu app. Cada camada usa a de baixo sem se preocupar com os detalhes dela.',
 'É o **painel do carro**: volante, acelerador e freio escondem o motor e a transmissão. A interface simples permite que milhões dirijam sem ser mecânicos. Quando o motor falha, aí sim é preciso abrir o capô e descer uma camada.',
 ['Entender por que existe tanta tecnologia empilhada','Saber que dá para trabalhar numa camada sem dominar todas','Reconhecer quando "descer de camada" ajuda a achar um problema difícil'],
 ['camadas de um app web',L('Seu código            -> regras do sistema','Framework (Express)  -> rotas e requisições','Runtime (Node.js)    -> executa o JavaScript','Sistema operacional  -> arquivos, rede, memória','Hardware             -> CPU, RAM, disco, placa de rede'),'Cada linha confia na de baixo. Um bug pode estar em qualquer andar.'],
 null,['so','framework','biblioteca','osi'],{tags:'abstracao arquitetura niveis'}),

E('compilador','Compilador e interpretador','Duas formas de transformar código em ação',1,
 'O processador só entende código de máquina, que são zeros e uns. Um **compilador** traduz o programa inteiro antes de rodar e gera um executável (C, C++, Go, Rust). Um **interpretador** lê e executa o programa na hora, passo a passo (Python, JavaScript, Ruby). Hoje muitas linguagens misturam as duas ideias.',
 'Compilar é **traduzir o manual inteiro** antes da viagem e levar o livro pronto. Interpretar é ter um **intérprete ao seu lado**, traduzindo frase por frase enquanto você fala: mais flexível, mais lento.',
 ['Entender por que Python é considerado lento e C rápido','Entender mensagens de erro: erro de compilação aparece antes de rodar, erro de execução aparece durante','Escolher a linguagem conforme o projeto','Entender o que significa "build" quando o projeto manda compilar'],
 ['bash',L('# C: compila e depois executa','gcc motor.c -o motor','./motor','','# Python: executa direto','python3 motor.py'),'No C são dois passos (compilar, rodar). No Python é um só. O erro de sintaxe aparece em momentos diferentes.'],
 'compilacao',['runtime','c','python','java','js'],{tags:'build compilar interpretar traduzir'}),

E('runtime','Runtime e máquina virtual','O motor que roda o seu programa',2,
 'O **runtime**, ou ambiente de execução, é o que faz o seu código rodar de verdade: ele oferece memória, tempo, arquivos e rede. O **Node.js** roda JavaScript fora do navegador, a **JVM** roda Java, o **.NET** roda C#. Uma **máquina virtual** executa um código intermediário igual em qualquer sistema, por isso a frase "escreva uma vez, rode em qualquer lugar".',
 'O código é a **receita** e o runtime é a **cozinha completa**: fogão, panelas, bancada. A mesma receita precisa de uma cozinha equipada. Trocar de cozinha pode mudar o que dá para cozinhar.',
 ['Entender por que o JavaScript roda no navegador e também no servidor (Node)','Saber o que instalar para rodar um programa (Python, Java, Node)','Entender erros de "versão do runtime incompatível"'],
 ['bash',L('node --version         # runtime do JavaScript','python3 --version      # runtime do Python','java -version          # runtime do Java'),'Antes de rodar um projeto, confira se o runtime certo, na versão certa, está instalado.'],
 null,['compilador','node','java','python','docker'],{tags:'jvm v8 dotnet ambiente de execucao'}),

E('processos','Processos e threads','Programas rodando e as linhas de trabalho dentro deles',2,
 'Um **processo** é um programa em execução, com a sua própria memória. Dentro dele pode haver várias **threads**: linhas de execução que dividem a mesma memória e fazem coisas em paralelo. O sistema operacional reveza os processos na CPU tão rápido que parece tudo ao mesmo tempo (e com vários núcleos roda mesmo ao mesmo tempo).',
 'Um processo é uma **célula de fábrica**, com seu próprio espaço e ferramentas. As threads são os **operadores dentro da célula**, dividindo as mesmas ferramentas: rende mais, mas dois operadores pegando a mesma peça ao mesmo tempo causam problema.',
 ['Entender por que um app trava e o outro continua','Usar o gerenciador de tarefas para achar o programa que está pesando','Entender conceitos como paralelismo, concorrência e condição de corrida'],
 ['bash',L('top                       # processos por uso de CPU','ps aux | grep python     # procura processos Python','kill 1234                 # pede para o processo 1234 encerrar'),'Cada processo tem um número (PID). O kill pede para encerrar; o kill -9 força.'],
 null,['so','async','linux','concorrencia'],{tags:'thread paralelismo concorrencia pid multitarefa'}),

E('redes','Redes de computadores','Como as máquinas conversam entre si',1,
 'Uma **rede** é um conjunto de dispositivos ligados para trocar dados, por cabo ou por wi-fi. Em casa você tem uma **LAN** (rede local). A **internet** é uma rede de redes espalhada pelo mundo. O **roteador** liga uma rede à outra e o **switch** liga os aparelhos dentro da mesma rede.',
 'Pense nas **vias de uma fábrica**: o switch são os corredores entre os setores, o roteador é o portão que liga a fábrica à rodovia, e cada pacote de dados é uma carga com etiqueta de destino.',
 ['Entender por que o wi-fi cai, por que o ping demora e o que é "estar na mesma rede"','Base de qualquer coisa online: sites, apps, nuvem, IoT','Configurar CLPs, IHMs e inversores em rede, que usam endereço IP','Trabalhar com segurança: firewall, VPN e segmentação são conceitos de rede'],
 ['terminal',L('ping google.com         # testa se alcança e quanto demora','ipconfig                # Windows: mostra o seu IP','ip addr                 # Linux: mostra o seu IP','traceroute google.com   # mostra por onde o caminho passa'),'O ping manda um "tem alguém aí?" e mede o tempo da resposta, em milissegundos (ms).'],
 null,['ip','dns','tcp','osi','http'],{tags:'lan wan roteador switch ethernet cabo',also:['ind']}),

E('ip','IP, portas e máscara','O endereço do aparelho e a porta do serviço',1,
 'O **endereço IP** identifica um dispositivo na rede, como `192.168.0.10` (quatro números de 0 a 255). A **porta** diz qual serviço dentro dele deve receber o dado: site é 443, SSH é 22, por exemplo. A **máscara de rede** (como /24) define quais endereços fazem parte da mesma rede.',
 'O IP é o **endereço do prédio** e a porta é o **número da sala**. Para entregar uma encomenda você precisa dos dois. A máscara diz até onde vai o bairro: quem está dentro vocês alcançam direto, para fora só pelo portão (o roteador).',
 ['Configurar equipamentos: CLP, câmera, impressora e servidor precisam de IP','Entender erros como "conflito de IP" (dois aparelhos com o mesmo endereço)','Liberar ou bloquear serviços no firewall pela porta','Diferenciar IP público (internet) de IP privado (dentro da empresa ou de casa)'],
 ['exemplo',L('IP:        192.168.0.10','Máscara:   255.255.255.0   (também escrita /24)','Rede:      192.168.0.0','Aparelhos: de 192.168.0.1 até 192.168.0.254','Gateway:   192.168.0.1      (o roteador)','','http://192.168.0.10:8080   <- IP + porta 8080'),'Com /24, os três primeiros números são o "bairro" e o último é a "casa". Dois aparelhos só se falam direto se estiverem no mesmo bairro.'],
 'subnet',['redes','bits','dns','http'],{tags:'ipv4 ipv6 mascara subrede gateway dhcp porta',also:['ind']}),

E('osi','Modelo OSI e camadas de rede','A rede dividida em andares',2,
 'O **modelo OSI** divide a comunicação em 7 camadas, da mais física (cabo e sinal) até a mais próxima do usuário (o aplicativo). Cada camada só conversa com a de cima e a de baixo e não precisa saber como a outra funciona. Na prática se usa o **modelo TCP/IP**, parecido, com 4 camadas. Serve principalmente como mapa para achar onde está o problema.',
 'É uma **linha de montagem com estações**: quem embala não sabe como a peça foi feita, e quem transporta não sabe o que tem dentro da caixa. Quando algo dá errado, você investiga estação por estação.',
 ['Diagnosticar problemas: é o cabo, é o IP, é a porta ou é o aplicativo?','Conversar com o pessoal de redes e entender a documentação','Entender redes industriais (Profinet, Modbus, EtherNet/IP), que seguem a mesma ideia','Aparece muito em provas de certificação (CCNA, Network+)'],
 ['camadas',L('7  Aplicação   HTTP, DNS, MQTT         (o que o app diz)','4  Transporte   TCP, UDP               (entrega e portas)','3  Rede         IP                    (endereço e rota)','2  Enlace       Ethernet, Wi-Fi, MAC  (vizinho direto)','1  Física       cabo, fibra, rádio    (os sinais)'),'Mostrei só as camadas mais usadas. As 7 completas incluem também Sessão (5) e Apresentação (6).'],
 null,['redes','tcp','ip','http'],{tags:'camadas modelo osi tcpip enlace',also:['ind']}),

E('wifi','Wi-Fi, Bluetooth e redes sem fio','Dados pelo ar',1,
 'Redes sem fio levam dados por ondas de rádio. **Wi-Fi** é para redes locais, com bom alcance e velocidade. **Bluetooth** é para curtas distâncias e pouco consumo (fones, sensores). **4G e 5G** cobrem áreas enormes. **LoRaWAN** alcança quilômetros com pouquíssima energia e velocidade baixa, ótimo para sensores. **Zigbee** forma redes de pequenos dispositivos em casa e em automação predial.',
 'Cada rede é um **tipo de comunicação na fábrica**: o Wi-Fi é o rádio de mão com bom sinal no pátio, o Bluetooth é o aviso boca a boca entre dois colegas lado a lado, o LoRa é o apito que se ouve de longe mas só dá para dizer uma palavra.',
 ['Escolher a tecnologia certa para sensores, câmeras e dispositivos','Entender os limites: alcance, velocidade, consumo de bateria e interferência','Conhecer as opções para IoT e chão de fábrica sem cabeamento, com os cuidados de segurança'],
 ['comparação',L('Tecnologia     Alcance     Velocidade    Energia','Wi-Fi          dezenas m   alta          média/alta','Bluetooth LE   10 a 100 m  baixa/média   muito baixa','Zigbee         10 a 100 m  baixa         muito baixa','4G / 5G        km          alta          alta','LoRaWAN        km          muito baixa   muito baixa'),'Valores aproximados, só para comparar ordem de grandeza. Paredes, metal e interferência mudam muito o resultado.'],
 null,['redes','iot','mqtt','latencia'],{tags:'wireless 5g 4g lora zigbee rede sem fio',also:['ind']}),

E('latencia','Latência, banda e velocidade','A estrada larga não é a viagem curta',2,
 '**Banda** é quanto dado cabe por segundo, como a largura de uma estrada. **Latência** é quanto tempo um dado leva para ir e voltar, como a duração da viagem. Dá para ter estrada larga e viagem demorada (como no satélite) ou estrada estreita e viagem curta. Em jogos e em controle em tempo real importa a latência. Para baixar arquivo grande, importa a banda.',
 'Banda é a **quantidade de caminhões** que passam por hora. Latência é **quanto demora um caminhão** de uma ponta à outra. Para um bilhete urgente você quer pouca latência. Para mudar uma fábrica inteira de lugar, muita banda.',
 ['Entender por que a internet "tem velocidade" mas o jogo dá lag','Escolher conexão para sistemas em tempo real, como telemetria e controle remoto','Interpretar o resultado do ping e dos testes de velocidade'],
 ['terminal',L('ping -c 4 google.com','# 64 bytes from ...: time=12.4 ms     <- latência'),'O tempo que aparece no ping é a latência de ida e volta. O teste de velocidade mede a banda (Mbps). São coisas diferentes.'],
 null,['redes','tcp','cdn','websocket'],{tags:'ping lag banda velocidade internet'}),

E('dns','DNS','A lista telefônica da internet',1,
 'O **DNS** traduz nomes que humanos lembram, como `google.com`, em endereços IP que as máquinas usam. Sem ele você teria que decorar o número de cada site. Quando você troca de servidor, normalmente precisa atualizar os **registros DNS** do seu domínio.',
 'É a **lista de ramais** da fábrica: você sabe o nome ("Manutenção") e o DNS diz o ramal (o IP). Se o ramal muda, só a lista é atualizada e ninguém precisa decorar de novo.',
 ['Fazer um domínio (meusite.com.br) apontar para o servidor certo','Configurar o e-mail do domínio (registros MX)','Entender por que uma mudança de site demora a "propagar"','Reconhecer ataques: muita fraude começa com DNS falso'],
 ['terminal',L('nslookup google.com          # pergunta o IP de um nome','dig google.com +short        # (Linux e Mac) resposta curta'),'Registros comuns: A (nome para IP), CNAME (apelido de outro nome), MX (servidor de e-mail), TXT (textos de verificação).'],
 'dns',['internet','ip','redes','cdn'],{tags:'dominio nome registro propagacao nslookup'}),

E('http','HTTP e HTTPS','A língua que o navegador e o servidor falam',1,
 '**HTTP** é o protocolo, ou seja, o conjunto de regras da web: o cliente faz um **pedido** e o servidor devolve uma **resposta** com um número de status (200 deu certo, 404 não achou, 500 deu erro no servidor). Os pedidos têm um **método**: GET busca, POST cria, PUT altera, DELETE apaga. O **HTTPS** é o mesmo HTTP, mas com a conversa criptografada.',
 'É o **formulário padrão de pedido de peças** do almoxarifado: sempre os mesmos campos (o que quer, de qual prateleira, quem pediu). O almoxarife responde com um código: entregue (200), não temos esse item (404), sistema fora do ar (500).',
 ['Base de sites, APIs e quase todo app que usa internet','Entender erros como 404, 401, 403 e 500','Testar e depurar APIs','Entender por que o HTTPS é obrigatório hoje: senha e dados viajam protegidos'],
 ['http',L('GET /maquinas/7 HTTP/1.1','Host: api.fabrica.exemplo','Accept: application/json','','--- resposta ---','HTTP/1.1 200 OK','Content-Type: application/json','','{"id":7,"nome":"Fresadora 04","status":"parada"}'),'A primeira linha do pedido é método + caminho. A primeira da resposta traz o status. Depois vêm os cabeçalhos (headers) e, por fim, o corpo.'],
 'http',['tls','rest','api','tcp','internet'],{tags:'get post status 404 500 requisicao resposta protocolo'}),

E('tcp','TCP e UDP','Duas formas de entregar dados na rede',2,
 'O **TCP** garante que os dados cheguem completos e na ordem: confirma cada pedaço e reenvia o que se perdeu. O **UDP** só joga os pacotes sem confirmar, então é mais rápido e aceita perder alguns. Site, e-mail e download usam TCP. Chamada de vídeo, jogo online e streaming costumam usar UDP.',
 'O TCP é a **carta registrada com aviso de recebimento**: demora mais, mas você sabe que chegou. O UDP é **gritar um aviso do outro lado da fábrica**: rápido, e se o barulho cobrir uma palavra, não vale a pena repetir.',
 ['Entender por que alguns serviços usam um e outros usam o outro','Saber que TCP e UDP têm números de porta próprios','Diagnosticar redes: conexão que abre e fecha, pacote perdido, lentidão'],
 ['comparação',L('TCP: abre conexão (3 passos) -> envia -> confirma -> reenvia se perdeu','UDP: envia -> pronto (sem confirmação)','','Portas conhecidas:','80 / 443   site (HTTP / HTTPS)   TCP','22         SSH                  TCP','53         DNS                  UDP (e TCP)','502        Modbus TCP           TCP'),'A escolha vem do problema: precisa de tudo certo (TCP) ou prefere rapidez e aceita perder um pouco (UDP)?'],
 'tcp',['ip','http','redes','osi','websocket'],{tags:'pacote handshake porta syn confiavel',also:['ind']}),

E('tls','TLS e certificados','O cadeado do HTTPS por dentro',2,
 '**TLS** é a camada que criptografa a conversa entre você e o site. Ele faz duas coisas: prova que o servidor é quem diz ser, usando um **certificado** emitido por uma autoridade confiável, e embaralha os dados para ninguém no caminho conseguir ler. O nome antigo era SSL. O cadeado do navegador indica que o TLS está ativo.',
 'O certificado é o **crachá com foto** do servidor, emitido por uma portaria que o navegador conhece. A criptografia é o **malote lacrado**: mesmo que alguém o pegue no caminho, não consegue abrir.',
 ['Proteger logins, pagamentos e dados pessoais','Evitar que alguém no mesmo wi-fi leia ou altere o que você envia','Obter e renovar certificados do seu site (o Let’s Encrypt oferece de graça)','Entender avisos de "certificado expirado" ou "sua conexão não é particular"'],
 ['terminal',L('openssl s_client -connect google.com:443 -servername google.com </dev/null \\','  | openssl x509 -noout -dates -issuer'),'Mostra quem emitiu o certificado do site e as datas de validade. Certificado vencido é uma das causas mais comuns de site fora do ar por susto.'],
 'tls',['http','cripto','dns','mfa'],{tags:'ssl https certificado cadeado letsencrypt',also:['seg']}),

E('internet','O que acontece ao abrir um site','Do toque no link até a página na tela',1,
 'Quando você digita um endereço e aperta Enter, uma sequência acontece em menos de um segundo: o navegador descobre o IP do site pelo **DNS**, abre uma conexão segura, faz o **pedido HTTP**, o servidor consulta o **banco de dados** se precisar, devolve HTML, CSS e JavaScript, e o navegador desenha a página.',
 'É como **pedir uma peça pelo sistema**: você consulta o ramal do almoxarifado (DNS), liga (conexão), faz o pedido (HTTP), o almoxarife confere o estoque (banco de dados) e entrega a peça embalada (a página).',
 ['Ter uma visão do todo antes de estudar cada parte','Saber onde procurar quando "o site não abre": DNS, servidor ou o seu código?','Ligar front-end, back-end, rede e banco de dados numa história só'],
 ['passo a passo',L('1. Aperte F12 no navegador (ferramentas do desenvolvedor)','2. Abra a aba Rede (Network)','3. Recarregue a página','','Você vai ver cada pedido que o navegador fez: HTML, CSS, imagens,','scripts e chamadas de API, com o status e o tempo de cada um.'),'É a forma mais direta de ver essa história acontecendo ao vivo.'],
 'navegador',['dns','http','tls','cliente-servidor','devtools'],{tags:'como funciona a internet navegador url pagina'}),

E('cliente-servidor','Cliente e servidor','Quem pede e quem atende',1,
 '**Cliente** é quem pede, como o navegador ou o app do celular. **Servidor** é quem atende e guarda as coisas: um computador, geralmente em outro lugar e sempre ligado. Um mesmo computador pode ser cliente de um serviço e servidor de outro. A palavra "servidor" também descreve o **programa** que atende pedidos, não só a máquina.',
 'É um **balcão de atendimento**: o cliente chega com o pedido, o atendente (o servidor) busca no estoque e entrega. Um servidor atende muita gente ao mesmo tempo, como um balcão com fila.',
 ['Base de quase tudo na web, em apps e em sistemas corporativos','Entender de onde vem cada dado e quem é responsável por ele','Conhecer alternativas, como o peer-to-peer (torrent), em que todo mundo é cliente e servidor ao mesmo tempo'],
 ['terminal',L('# Servidor: transforma esta pasta num site de teste na porta 8000','python3 -m http.server 8000','','# Cliente: abra no navegador','# http://localhost:8000'),'Em uma linha você cria um servidor web de teste. O navegador é o cliente. O localhost significa "esta mesma máquina".'],
 null,['http','api','backend','internet','redes'],{tags:'client server servidor web'}),

E('cripto','Criptografia e hash','Embaralhar para proteger, ou resumir para conferir',2,
 'São três ideias diferentes. O **hash** transforma qualquer texto num "resumo" de tamanho fixo, sem volta; serve para conferir se algo mudou e para guardar senhas. A **criptografia simétrica** usa uma mesma chave para trancar e destrancar. A **assimétrica** usa um par de chaves, uma pública (qualquer um tem) e uma privada (só você): o que uma tranca, só a outra abre.',
 'O hash é a **impressão digital** de um documento: dá para conferir se é o mesmo, mas não dá para recriar o documento a partir dela. A chave simétrica é **uma chave só** para o armário. A assimétrica é uma **caixa de correio**: qualquer um põe a carta pela fresta (chave pública), só o dono abre (chave privada).',
 ['Guardar senhas com segurança: nunca em texto puro, sempre como hash com sal','Assinar documentos e provar quem enviou','Proteger conexões (HTTPS), arquivos e mensagens','Verificar se um download veio sem alteração (checksum)'],
 ['bash',L('echo -n "oi" | sha256sum      # sai uma sequência de 64 caracteres','echo -n "Oi" | sha256sum      # uma letra diferente muda tudo'),'Troque uma letra e o hash muda por completo. Experimente na demonstração logo abaixo.'],
 'hash',['tls','base64','jwt','senhas'],{tags:'hash sha256 md5 chave publica privada aes rsa criptografar',also:['seg']}),

E('unicode','Texto: ASCII, Unicode e UTF-8','Como as letras viram números',2,
 'O computador só guarda números, então cada letra tem um número. O **ASCII**, dos anos 60, tinha 128 símbolos e servia só para inglês. O **Unicode** é a tabela mundial, com cerca de 150 mil símbolos, de "ç" a emojis e ideogramas. O **UTF-8** é a forma mais comum de gravar o Unicode em bytes: usa 1 byte para as letras simples e mais bytes para as outras.',
 'É um **código de peças**: cada peça do almoxarifado tem um número de catálogo. O ASCII era o catálogo de uma fábrica só. O Unicode é o catálogo de todas as fábricas do mundo, e o UTF-8 é a etiqueta que gasta pouco papel nas peças comuns.',
 ['Evitar o clássico "AcentuaÃ§Ã£o quebrada": arquivo salvo numa codificação e lido em outra','Entender por que o "ç" ocupa 2 bytes e um emoji ocupa 4','Usar UTF-8 sempre que puder: é o padrão da web','Entender por que contar caracteres e contar bytes dão números diferentes'],
 ['javascript',L('"A".charCodeAt(0)                  // 65','"ç".charCodeAt(0)                  // 231','new TextEncoder().encode("ç")      // 2 bytes: 195, 167','new TextEncoder().encode("😀")     // 4 bytes'),'O mesmo texto vira números diferentes conforme a codificação. Na demonstração você vê os bytes de qualquer texto que digitar.'],
 'utf8',['bits','formatos','base64','regex'],{tags:'acento codificacao charset ascii emoji caracteres'}),

E('formatos','JSON, XML, YAML e CSV','Formatos para guardar e trocar dados',1,
 'São jeitos de escrever dados em texto para que programas se entendam. O **JSON** é o mais usado em APIs: organiza tudo em pares de nome e valor. O **XML** usa etiquetas e é mais antigo e mais comprido. O **YAML** foi feito para humanos lerem e aparece muito em configuração (Docker, Kubernetes). O **CSV** é uma tabela simples separada por vírgula ou ponto e vírgula.',
 'São **formulários de papel** em estilos diferentes: o JSON é o formulário enxuto que todo mundo preenche rápido, o XML é o formulário cheio de carimbos e campos obrigatórios, o YAML é o rascunho legível e o CSV é a planilha de papel.',
 ['Receber e enviar dados em APIs (JSON)','Escrever arquivos de configuração (YAML e JSON)','Importar e exportar planilhas e relatórios (CSV)','Integrar com sistemas mais antigos (XML), comum em ERPs e notas fiscais'],
 ['json, yaml e csv',L('JSON:  {"nome":"Prensa 01","horas":1280,"ativa":true}','','YAML:','nome: Prensa 01','horas: 1280','ativa: true','','CSV:','nome;horas;ativa','Prensa 01;1280;sim'),'É o mesmo dado escrito de três jeitos. O JSON é exigente com aspas e vírgulas. O YAML depende dos recuos (espaços).'],
 'json',['api','rest','base64','unicode'],{tags:'json xml yaml csv dados serializacao toml'}),

E('base64','Base64','Disfarçar bytes de texto para viajar em qualquer lugar',2,
 '**Base64** converte qualquer dado (imagem, arquivo, bytes) em texto, usando só letras, números e poucos símbolos. Serve para transportar dados por sistemas que só aceitam texto, como e-mail e JSON. **Não é criptografia**: qualquer um desfaz com um clique. O texto fica uns 33% maior.',
 'É **embalar uma peça numa caixa padrão** para caber no malote do correio. A caixa não esconde nada, só facilita o transporte. Quem recebe abre e usa.',
 ['Enviar imagens ou arquivos dentro de JSON ou de e-mail','Entender tokens (JWT) e cabeçalhos de autenticação básica','Reconhecer trechos que parecem "senha criptografada" mas são só Base64, um erro de segurança comum'],
 ['bash',L('echo -n "Linha 3 parada" | base64','# TGluaGEgMyBwYXJhZGE=','','echo "TGluaGEgMyBwYXJhZGE=" | base64 -d'),'O -d desfaz. Se você consegue reverter sem chave nenhuma, não é segredo.'],
 'base64',['cripto','jwt','formatos','unicode'],{tags:'codificar decodificar atob btoa'}),

E('regex','Expressões regulares (regex)','Procurar padrões em texto',2,
 'Uma **regex** é uma "máscara" que descreve um padrão de texto. "Dois dígitos, uma barra, dois dígitos, uma barra, quatro dígitos" vira uma fórmula curta. Com ela você acha, valida ou troca trechos como datas, e-mails e códigos de peça. Parece enigma no começo, mas é só um alfabeto pequeno de símbolos combinados.',
 'É um **gabarito de inspeção**: em vez de conferir peça por peça com o olho, você passa o gabarito e só passa o que tem o formato certo.',
 ['Validar campos (e-mail, telefone, placa)','Procurar em logs: achar todas as linhas com erro de uma máquina','Trocar textos em massa no editor de código','Extrair partes de um texto (data, valor, código)'],
 ['regex',L('\\d{2}/\\d{2}/\\d{4}      data como 12/03/2025','\\d+                    um ou mais dígitos','[A-Z][a-z]+            palavra com inicial maiúscula','^\\S+@\\S+\\.\\S+$      e-mail simples (não é perfeito)'),'\\d é um dígito, {2} é "exatamente duas vezes", + é "uma ou mais", ^ e $ marcam início e fim. O e-mail perfeito por regex não existe: valide mandando um e-mail de verdade.'],
 'regex',['js','python','grep','unicode'],{tags:'regexp expressao regular padrao busca validar',also:['ferr']}),

E('biblioteca','Biblioteca (library)','Um conjunto de ferramentas que você chama quando quiser',1,
 'Uma **biblioteca** é código pronto, feito por outra pessoa, que resolve um problema específico: datas, gráficos, PDFs, contas. **Você** continua no comando: escolhe quando e como chamar cada função dela. Exemplos: jQuery, Lodash, NumPy, Chart.js. O React também se descreve como uma biblioteca, embora na prática o uso pareça o de um framework.',
 'É uma **caixa de ferramentas**: você abre, pega a chave de fenda quando precisa e guarda. A obra continua sendo sua e quem decide o que fazer é você.',
 ['Não reescrever do zero o que já existe e funciona','Ganhar tempo em tarefas comuns (datas, gráficos, requisições, PDF)','Ler a documentação de uma biblioteca é uma habilidade central de quem programa'],
 ['javascript',L('// formatar data na mão dá trabalho.','// Com uma biblioteca (exemplo: dayjs):','import dayjs from "dayjs";','console.log(dayjs().format("DD/MM/YYYY"));'),'Você importa a biblioteca e chama as funções dela dentro do SEU código. Você manda, a biblioteca obedece.'],
 null,['framework','pacotes','sdk','api'],{tags:'library lib dependencia pacote'}),

E('framework','Framework','Uma estrutura pronta onde você encaixa o seu código',1,
 'Um **framework** é um esqueleto de projeto com regras e pastas já definidas: você escreve só as partes específicas do seu sistema, e o framework chama o seu código na hora certa. É a chamada "inversão de controle": **você não chama o framework, ele chama você**. Exemplos: Django, Spring, Laravel, Angular, Next.js e Ruby on Rails.',
 'A biblioteca é a caixa de ferramentas. O framework é a **linha de montagem já instalada**: você só coloca a sua estação (o seu pedaço de código) no lugar indicado, e a esteira decide quando ela trabalha. Ganha velocidade e padrão, perde liberdade.',
 ['Começar projetos rápido, com login, rotas, banco e segurança já resolvidos','Manter times no mesmo padrão','Evitar reinventar a roda em tarefas comuns','Escolher com consciência: framework grande demora para aprender e prende você ao jeito dele'],
 ['python (Flask)',L('from flask import Flask','app = Flask(__name__)','','@app.route("/")','def inicio():','    return "Olá, fábrica"','','app.run()'),'Você não escreve o servidor web. Só diz "quando alguém pedir a página inicial, rode esta função". O Flask cuida do resto e chama a sua função na hora certa.'],
 null,['biblioteca','sdk','react','django','spring','nextjs'],{tags:'estrutura arcabouco inversao de controle'}),

E('sdk','SDK','Kit de desenvolvimento de um fabricante ou serviço',2,
 'SDK significa **Software Development Kit**: um pacote que o dono de uma plataforma entrega para você desenvolver para ela. Costuma trazer bibliotecas, ferramentas, documentação e exemplos. Você usa o SDK do Android para fazer apps Android, o da AWS para falar com a AWS pelo seu código, o do Stripe para cobrar pagamentos.',
 'É o **kit de manutenção que vem junto com o equipamento**: manual, chaves especiais, peças de teste e gabaritos. Foi montado pelo fabricante para você mexer na máquina do jeito certo.',
 ['Integrar com serviços sem montar chamadas de API na mão','Compilar e testar apps para uma plataforma','Seguir o jeito oficial, com menos risco de erro'],
 ['python (AWS)',L('import boto3','s3 = boto3.client("s3")','s3.upload_file("relatorio.pdf", "meu-bucket", "relatorios/relatorio.pdf")'),'Em vez de montar à mão o pedido HTTP, as assinaturas e a autenticação, o SDK oferece funções prontas como upload_file.'],
 null,['api','biblioteca','framework','aws'],{tags:'kit desenvolvimento software development'}),

E('pacotes','Gerenciador de pacotes','A loja de bibliotecas do seu projeto',1,
 'Um **gerenciador de pacotes** baixa, instala e atualiza as bibliotecas (as dependências) que o projeto usa, nas versões certas. Cada ecossistema tem o seu: **npm** para JavaScript, **pip** para Python, **Maven** para Java, **NuGet** para C#, **Cargo** para Rust, **apt** para Linux. Um arquivo lista tudo o que o projeto precisa, para qualquer pessoa reproduzir.',
 'É o **almoxarifado com requisição automática**: você escreve a lista de peças do projeto e o sistema busca todas, nas versões certas, e ainda traz as peças de que as peças precisam.',
 ['Instalar tudo que um projeto precisa com um comando só','Atualizar bibliotecas e corrigir falhas de segurança','Garantir que a sua máquina e a do colega usem as mesmas versões','Publicar as suas próprias bibliotecas para outros usarem'],
 ['bash',L('npm init -y                    # cria um projeto Node','npm install dayjs               # instala uma biblioteca','npm install                     # instala tudo o que está listado','','pip install requests            # Python','pip freeze > requirements.txt   # salva a lista'),'O pacote vai para uma pasta (node_modules, por exemplo). Essa pasta não vai para o git: ela é refeita a partir da lista.'],
 null,['biblioteca','node','python','git'],{tags:'npm pip maven nuget cargo yarn pnpm dependencias',also:['ferr']}),

E('opensource','Código aberto e licenças','Código que você pode ver, usar e mudar',1,
 'Num projeto **open source** o código-fonte é público, e a **licença** diz o que você pode fazer com ele. MIT e Apache permitem quase tudo, até uso comercial. A GPL permite, mas exige que o que você derivar também seja aberto. Código público sem licença **não é livre para usar**. Linux, Python, React e Firefox são exemplos.',
 'É a **planta de um equipamento publicada** para qualquer fábrica construir, consertar e melhorar. A licença é a nota ao pé da planta: "pode copiar e vender" (MIT) ou "pode copiar, mas as melhorias também devem ser publicadas" (GPL).',
 ['Aprender lendo código de projetos de verdade','Usar ferramentas gratuitas e auditáveis, sem depender de um único fornecedor','Contribuir com projetos e montar um portfólio público no GitHub','Evitar problema legal ao usar código de terceiros no seu produto'],
 ['licenças',L('MIT          use, copie, modifique e venda; mantenha o aviso de copyright','Apache 2.0   parecida com a MIT, com cláusula de patentes','GPL          derivados precisam continuar abertos (copyleft)','Sem licença  todos os direitos reservados ao autor'),'Resumo informal, não é aconselhamento jurídico. Antes de usar em produto comercial, leia a licença e, se for relevante, consulte um advogado.'],
 null,['git','github','linux','licencas'],{tags:'oss livre gpl mit apache licenca software livre',also:['eng']}),

E('stack','Front-end, back-end e full-stack','As partes de um sistema e quem cuida de cada uma',1,
 '**Front-end** é o que o usuário vê e toca: telas e botões. **Back-end** é o que roda no servidor e ele não vê: regras, login e banco de dados. **Full-stack** é quem faz os dois. O conjunto de tecnologias que um projeto usa se chama **stack**, por exemplo React com Node e PostgreSQL.',
 'Num restaurante, o front-end é o **salão** (cardápio, mesas, atendimento) e o back-end é a **cozinha** (estoque, fogão, receitas). Full-stack é o dono que sabe fazer tudo: útil, mas ninguém domina tudo com a mesma profundidade.',
 ['Entender a divisão de vagas e de times','Escolher por onde começar a estudar','Ver como cada tecnologia se encaixa: HTML, CSS, JS e React no front; Node, Python, Java e bancos no back'],
 ['exemplo de stack',L('Front-end:   HTML + CSS + JavaScript + React','Back-end:    Node.js + Express','Banco:       PostgreSQL','Hospedagem:  Vercel (front) + Render (back)'),'É uma stack comum. Existem milhares de combinações e nenhuma é "a certa".'],
 null,['backend','html','api','banco-dados'],{tags:'frontend backend fullstack pilha tecnologias'}),

E('ambientes','Dev, homologação e produção','Os ambientes por onde um sistema passa',1,
 'O **ambiente de desenvolvimento** (dev) é onde você escreve e testa à vontade, na sua máquina. A **homologação** (staging) é uma cópia parecida com a real, para testar com calma e mostrar ao cliente. A **produção** é o sistema de verdade, que os usuários usam. **Deploy** é o ato de colocar uma nova versão no ar.',
 'É o caminho de uma peça nova: **bancada de protótipo** (dev), **linha-piloto** (homologação), **linha de produção** (produção). Ninguém testa uma alteração arriscada direto na linha rodando.',
 ['Evitar quebrar o sistema real com testes','Manter configurações separadas: senhas e endereços de cada ambiente','Entender deploy, rollback (voltar a versão) e variáveis de ambiente'],
 ['arquivos .env',L('# .env.development','API_URL=http://localhost:3000','','# .env.production','API_URL=https://api.minhaempresa.com'),'O mesmo código lê configurações diferentes conforme o ambiente. Arquivos .env com senhas não vão para o git.'],
 null,['cicd','docker','git','devops'],{tags:'deploy staging producao homologacao dev rollback env',also:['ops']}),

E('bug-debug','Bug, debug e log','Achar e consertar o que não funciona',1,
 '**Bug** é um defeito no programa. **Debug**, ou depurar, é o trabalho de investigar e corrigir. As principais ferramentas são os **logs** (mensagens que o programa escreve sobre o que faz), o **debugger** (pausa a execução e deixa você olhar cada variável) e os **testes automáticos**. A maior parte do trabalho de programar é depurar, e isso é normal.',
 'É o trabalho do **técnico de manutenção**: tem um sintoma, você levanta hipóteses, mede (log), isola a causa dividindo o sistema em partes e só então troca a peça. Trocar peça no escuro só gera mais falha.',
 ['Resolver problemas de forma sistemática, em vez de tentar tudo','Ler mensagens de erro: a resposta costuma estar na primeira linha e na última','Usar logs para entender o que aconteceu em produção','Reproduzir o bug antes de consertar. Sem reproduzir, você não sabe se consertou'],
 ['javascript',L('function media(lista) {','  console.log("entrada:", lista);','  const soma = lista.reduce((a, b) => a + b, 0);','  console.log("soma:", soma);','  return soma / lista.length;','}','media([]);   // 0 / 0 dá NaN  <- achamos o problema'),'O console.log mostra o que está acontecendo por dentro. Ao testar com lista vazia aparece NaN: um caso que você não tinha previsto.'],
 null,['devtools','testes','logs','git'],{tags:'erro depurar debugger console log falha',also:['eng']})
]);
