/* ===== Front-end ===== */
C('front',[
E('frontend','Front-end','Tudo o que o usuário vê e toca',1,
 'O **front-end** é a parte do sistema que roda **no aparelho do usuário**, normalmente no navegador: tudo que aparece na tela, os botões, os formulários, as animações. É feito com **HTML**, que dá a estrutura, **CSS**, que dá a aparência, e **JavaScript**, que dá o comportamento, geralmente com apoio de frameworks como React, Vue ou Angular. Ele não deve guardar dados importantes nem regras secretas, porque o usuário consegue ver e alterar tudo que está no navegador. Para isso existe o back-end.',
 'Se o sistema é um restaurante, o front-end é o **salão e o cardápio**: o que o cliente vê e toca. A cozinha, o back-end, fica nos fundos. O salão pode ser lindo, mas se a cozinha não funcionar, o prato não sai.',
 ['Criar o que as pessoas veem e usam: sites, painéis e aplicativos web','Fazer a ponte entre o usuário e as APIs do back-end','Cuidar da experiência: velocidade, acessibilidade e adaptação ao celular'],
 ['html',L('<button id="botao">Ligar motor</button>','<p id="estado">Motor desligado</p>','','<style>','  button { background: #1f6fdb; color: white; padding: 8px 16px; }','</style>','','<script>','  document.getElementById("botao").onclick = () => {','    document.getElementById("estado").textContent = "Motor ligado";','  };','</script>'),'As três camadas juntas: a estrutura (HTML), a aparência (style) e o comportamento (script). Em projetos reais, cada uma costuma ficar num arquivo separado.'],
 null,['html','css','js','backend','react','responsivo'],{tags:'frontend front end cliente interface navegador tela ui'}),

E('html','HTML','O esqueleto da página',1,
 '**HTML** é a linguagem que diz **o que existe** numa página: título, parágrafo, imagem, botão, lista, formulário. Não é uma linguagem de programação, porque não tem lógica nem contas. É uma forma de **marcar** o conteúdo com etiquetas chamadas **tags**. O navegador lê as tags e monta a página.',
 'É a **planta estrutural** de um galpão: mostra onde ficam paredes, portas e vigas. Não fala de cor nem de acabamento. Só diz o que existe e onde.',
 ['Montar a estrutura de qualquer site ou sistema web','Dar significado ao conteúdo (isto é título, isto é menu), o que ajuda buscadores e leitores de tela','Criar formulários que enviam dados','É o primeiro a estudar: o resto da web se apoia nele'],
 ['html',L('<h1>Oficina Central</h1>','<p>Manutenção de motores.</p>','<ul>','  <li>Motores</li>','  <li>Painéis</li>','</ul>','<button>Pedir orçamento</button>'),'`<h1>` é o título, `<p>` é um parágrafo, `<ul>` é uma lista e `<li>` é cada item dela. Quase toda tag abre e fecha: `<p>` ... `</p>`.'],
 'html',['css','js','dom','a11y'],{tags:'tag elemento pagina web estrutura markup'}),

E('css','CSS','A aparência: cores, tamanhos e posição',1,
 '**CSS** diz **como** cada coisa do HTML deve parecer: cor, tamanho, fonte, espaço, posição. Você escolhe elementos (os seletores) e define as propriedades deles. Também adapta o layout para celular, tablet e computador, e cuida de animações simples.',
 'Se o HTML é a planta estrutural, o CSS é o **projeto de acabamento**: pintura, piso, iluminação, posição dos móveis. A mesma estrutura pode ficar com cara de escritório, de fábrica ou de loja só trocando o acabamento.',
 ['Dar identidade visual a qualquer página','Fazer o layout se adaptar a telas diferentes (responsivo)','Criar animações e efeitos ao passar o mouse','Trocar o tema do site (claro e escuro) sem mexer no HTML'],
 ['css',L('button {','  background: #e0a100;     /* cor de fundo */','  color: #1a1200;          /* cor do texto */','  padding: 12px 18px;      /* espaço interno */','  border-radius: 8px;      /* cantos arredondados */','}','','button:hover {','  background: #ffc24b;     /* ao passar o mouse */','}'),'Primeiro o seletor (button) e, entre chaves, as propriedades. O :hover é um estado: só vale enquanto o mouse está em cima.'],
 'css',['html','flexbox','grid','tailwind','responsivo'],{tags:'estilo cores layout folha de estilo css3 design'}),

E('js','JavaScript','A lógica que dá vida à página',1,
 '**JavaScript** é a única linguagem que roda dentro do navegador. Com ele a página reage: clique, digitação, dados que chegam da internet, atualização da tela sem recarregar. Também roda fora do navegador, no servidor, por meio do **Node.js**. Apesar do nome, não tem relação com o Java.',
 'Se o HTML é a estrutura e o CSS é o acabamento, o JavaScript é a **instalação elétrica e os automatismos**: o sensor que acende a luz, o botão que liga a esteira. Sem ele a página é uma maquete bonita e parada.',
 ['Fazer botões, menus, formulários e telas dinâmicas funcionarem','Buscar dados de APIs e mostrar sem recarregar a página','Criar aplicações completas com React, Vue, Angular e outros','Programar servidores (Node.js), apps de celular (React Native) e programas de PC (Electron)'],
 ['javascript',L('const botao = document.querySelector("button");','','botao.addEventListener("click", () => {','  botao.textContent = "Pedido enviado!";','});'),'Procura o botão na página e diz: quando clicarem, rode isto. É assim que a página passa a reagir.'],
 'js',['html','dom','typescript','node','react','async'],{tags:'javascript js ecmascript script programacao web',also:['lang']}),

E('dom','DOM','A página vista como uma árvore de objetos',2,
 'Quando o navegador lê o HTML, ele monta na memória uma **árvore de objetos** chamada **DOM** (Document Object Model). O JavaScript não mexe no arquivo HTML: mexe nessa árvore. Cada mudança nela atualiza a tela na hora. Procurar um elemento, criar, apagar, trocar texto ou cor, tudo isso é feito pelo DOM.',
 'O HTML é a **planta**. O DOM é a **maquete viva** montada a partir dela: dá para tirar uma parede, pintar uma sala ou colocar uma porta, e você vê a mudança. Mexer na planta no papel não muda a maquete.',
 ['Entender o que o JavaScript faz de verdade na página','Procurar, criar, remover e alterar elementos','Entender o que frameworks como o React tentam gerenciar para você','Usar a aba Elementos do navegador para inspecionar qualquer site'],
 ['javascript',L('const lista = document.querySelector("ul");','','const item = document.createElement("li");','item.textContent = "Calibrar sensor";','lista.appendChild(item);            // aparece na tela','','lista.firstElementChild.remove();  // some da tela'),'Cria um item, coloca na lista e apaga o primeiro. O arquivo HTML continua igual; só a árvore da memória mudou.'],
 'dom',['html','js','react','devtools'],{tags:'document object model arvore elementos querySelector'}),

E('formularios','Formulários HTML','Como a página recebe dados do usuário',1,
 'Um **formulário** é a parte da página que recebe dados: campos de texto, caixas de seleção, listas, botões. O HTML já traz tipos prontos (e-mail, número, data, senha) com **validação básica** do navegador, como campo obrigatório e formato de e-mail. Ao enviar, o navegador manda os dados ao servidor, ou o JavaScript os lê e envia por fetch.',
 'É a **ficha de cadastro de manutenção**: campos com formato definido (data, número da máquina), obrigatórios marcados e um botão para entregar no setor. A ficha já barra uma entrega incompleta antes de chegar ao escritório.',
 ['Login, cadastro, pesquisa, checkout e qualquer entrada de dados','Validar campos sem escrever JavaScript','Teclado certo no celular: o tipo do campo escolhe o teclado numérico, de e-mail e assim por diante','Sempre validar de novo no servidor, porque a validação do navegador pode ser burlada'],
 ['html',L('<form>','  <label>E-mail <input type="email" required></label>','  <label>Quantidade <input type="number" min="1" max="99"></label>','  <label>Prioridade','    <select><option>Baixa</option><option>Alta</option></select>','  </label>','  <button>Enviar</button>','</form>'),'O type="email" e o required já impedem o envio de dados mal formados. No celular, o tipo muda o teclado que aparece. Mas quem manda é o servidor; o navegador só ajuda.'],
 null,['html','js','fetch','a11y','xss'],{tags:'input campo formulario validacao enviar'}),

E('responsivo','Design responsivo','O mesmo site se adaptando a qualquer tela',1,
 '**Responsivo** quer dizer que a página se adapta ao tamanho da tela: no celular as colunas empilham, o menu vira botão, o texto aumenta. No computador tudo se espalha. Usa três coisas: a tag **viewport** no HTML, medidas flexíveis (porcentagem, rem, fr) e **media queries** do CSS, que aplicam regras só acima ou abaixo de certa largura. A prática comum é começar pelo celular (**mobile first**).',
 'É uma **peça com regulagem**: o mesmo suporte ajustável serve para vários tamanhos de equipamento, em vez de um suporte diferente para cada um.',
 ['Um site só que serve celular, tablet e computador','Atender ao fato de que a maior parte do acesso hoje vem do celular','Evitar manter dois sites separados'],
 ['css',L('/* padrão (celular): uma coluna */','.cartoes { display: grid; grid-template-columns: 1fr; gap: 8px; }','','/* a partir de 600px de largura: três colunas */','@media (min-width: 600px) {','  .cartoes { grid-template-columns: repeat(3, 1fr); }','}'),'O @media é a pergunta: a tela tem pelo menos 600 pixels de largura? Se sim, as regras de dentro valem.'],
 'resize',['css','flexbox','grid','pwa'],{tags:'mobile first celular media query viewport adaptavel'}),

E('flexbox','Flexbox','Alinhar itens em linha ou em coluna',2,
 '**Flexbox** é um modo de layout do CSS para organizar itens **em uma direção**: em linha ou em coluna. Você define a direção, como distribuir o espaço que sobra e como alinhar no outro sentido. Resolve com simplicidade coisas que eram chatas, como centralizar, espaçar igual ou empurrar um item para o canto.',
 'É uma **esteira com guias ajustáveis**: você decide se as peças andam na horizontal ou na vertical, se ficam coladas, espalhadas ou centralizadas, e a esteira se adapta ao tamanho de cada peça.',
 ['Menus, barras de ferramentas e cartões lado a lado','Centralizar algo na tela, o clássico problema do centro','Fazer itens quebrarem de linha quando faltar espaço','Layouts de uma dimensão em geral'],
 ['css',L('.caixa {','  display: flex;                   /* liga o flexbox */','  justify-content: space-between;  /* espaça no sentido da linha */','  align-items: center;             /* centraliza no outro sentido */','  gap: 12px;                       /* espaço entre os itens */','}'),'A caixa de fora (o container) manda e os itens de dentro obedecem. O justify-content cuida do eixo principal; o align-items cuida do eixo cruzado.'],
 'flexbox',['css','grid','responsivo','tailwind'],{tags:'flex layout alinhar centralizar justify align'}),

E('grid','CSS Grid','Layout em linhas e colunas, como uma planilha',2,
 'O **Grid** é o modo de layout do CSS para organizar em **duas dimensões ao mesmo tempo**: linhas e colunas. Você desenha a grade, por exemplo três colunas iguais, ou menu fixo mais conteúdo flexível, e coloca cada coisa numa área. É ideal para o layout geral da página. O flexbox é melhor dentro de cada pedaço.',
 'É uma **planilha**, ou o **mapa de ocupação do galpão**: você divide o piso em quadrículas e diz que o setor A ocupa duas colunas e o B ocupa três linhas. Cada setor sabe o seu lugar.',
 ['Layout de página inteira: cabeçalho, menu lateral, conteúdo e rodapé','Galerias e vitrines de produtos em grade','Alinhar em linhas e colunas ao mesmo tempo','Combinar com flexbox: grid para o esqueleto, flex para os detalhes'],
 ['css',L('.galeria {','  display: grid;','  grid-template-columns: repeat(3, 1fr);   /* 3 colunas iguais */','  gap: 8px;','}'),'1fr significa uma fração do espaço disponível. repeat(3, 1fr) cria três colunas do mesmo tamanho.'],
 'grid',['css','flexbox','responsivo'],{tags:'grade colunas linhas layout areas'}),

E('a11y','Acessibilidade web','Sites que todo mundo consegue usar',2,
 '**Acessibilidade** (a11y) é fazer sites e apps que funcionam para todas as pessoas: quem não enxerga e usa **leitor de tela**, quem não usa mouse, quem tem baixa visão ou daltonismo, quem está com a mão ocupada. A maior parte vem de usar o HTML certo (botão de verdade, rótulo no campo, texto alternativo na imagem), contraste bom e navegação por teclado.',
 'É a **norma de segurança e ergonomia** da fábrica: rampa além de escada, sinalização que o daltônico entende, botão de emergência que qualquer um alcança. Bem feita, ajuda todo mundo, não só quem tem uma limitação.',
 ['Chegar a mais usuários e cumprir leis de acessibilidade, que existem em vários países','Melhorar o SEO: o que ajuda o leitor de tela ajuda o buscador','Fazer sistemas internos que qualquer funcionário consegue usar','Evitar retrabalho: acessibilidade barata é a que se faz desde o começo'],
 ['html',L('<img src="motor.jpg" alt="Motor elétrico trifásico azul">','','<label for="nome">Nome completo</label>','<input id="nome">','','<button>Enviar</button>   <!-- botão de verdade, não uma div -->'),'O alt descreve a imagem para quem não vê. O label liga o texto ao campo. A tag button já vem com foco, teclado e significado prontos.'],
 'a11y',['html','css','seo','uxui'],{tags:'acessibilidade leitor de tela contraste teclado aria wcag inclusao'}),

E('seo','SEO','Ajudar o Google a encontrar e entender seu site',2,
 '**SEO**, otimização para buscadores, é o conjunto de cuidados para o seu site aparecer bem nas pesquisas. Começa pelo básico técnico: título e descrição de cada página, HTML bem estruturado, site rápido, funcionando no celular e com HTTPS. Depois vêm conteúdo útil e links de outros sites apontando para o seu.',
 'É **colocar placa legível, endereço certo e entrada desimpedida** na sua oficina, para quem procura achar. Não adianta ter o melhor serviço se ninguém acha a porta.',
 ['Fazer as páginas aparecerem nas buscas sem pagar anúncio','Entender por que sites muito pesados ou feitos só em JavaScript perdem posição','Escolher entre renderização no servidor (SSR) e no navegador (SPA)','Controlar a prévia que aparece ao colar o link no WhatsApp'],
 ['html',L('<head>','  <title>Manutenção de motores elétricos | Oficina Central</title>','  <meta name="description" content="Revisão e reparo de motores, painéis e inversores.">','  <meta property="og:image" content="https://exemplo.com/capa.jpg">','</head>'),'O title e a description são o que aparece nos resultados do Google. As tags og (Open Graph) definem a prévia ao compartilhar o link.'],
 null,['ssr','html','a11y','spa'],{tags:'google busca buscador otimizacao ranking meta tags'}),

E('fetch','Fetch e AJAX','Buscar dados de uma API sem recarregar a página',2,
 'O **fetch** é a função do navegador para fazer pedidos HTTP pelo JavaScript: buscar dados, enviar um formulário, salvar algo no servidor, tudo sem recarregar a página. Essa ideia antes se chamava **AJAX**. O fetch devolve uma **promessa**, então se usa o `await` para esperar a resposta com calma. A resposta mais comum vem em JSON.',
 'É o **chamado pelo rádio**: "central, me manda o estado da linha 3". O operador continua trabalhando enquanto espera e, quando a resposta chega, atualiza o painel. Não precisa parar a fábrica para perguntar.',
 ['Mostrar na tela os dados de uma API','Enviar formulários e salvar informações','Atualizar partes da página (lista, contador, notificações) sem recarregar','Base de qualquer SPA ou painel que fale com um servidor'],
 ['javascript',L('async function carregar() {','  const resposta = await fetch("https://api.exemplo.com/maquinas");','  if (!resposta.ok) throw new Error("Erro " + resposta.status);','  const maquinas = await resposta.json();','  console.log(maquinas);','}','carregar();'),'O await pausa só essa função até a resposta chegar, sem travar o resto da página. Sempre confira resposta.ok: um 404 não é erro do fetch, é uma resposta.'],
 null,['async','api','http','formatos','cors'],{tags:'ajax xhr requisicao promise axios consumir api'}),

E('storage','Cookies e armazenamento local','O navegador guardando dados no seu aparelho',2,
 'O navegador pode guardar dados no aparelho do usuário. **Cookies** são pequenos textos enviados junto com todo pedido ao servidor: servem para login e rastreamento. O **localStorage** guarda dados sem prazo de validade, e só o JavaScript lê. O **sessionStorage** some quando a aba fecha. O **IndexedDB** guarda grandes quantidades de dados organizados. Nada disso é cofre: o usuário vê e edita tudo.',
 'O cookie é o **crachá de visitante** que vai e volta com você em toda entrada. O localStorage é a **gaveta do seu armário**: fica com você, mas qualquer pessoa que abrir o armário vê tudo. Não guarde ali nada secreto.',
 ['Lembrar tema escuro, idioma e rascunhos','Manter o usuário logado (cookies de sessão)','Guardar dados offline em PWAs (IndexedDB)','Entender o que significa "aceitar cookies"'],
 ['javascript',L('localStorage.setItem("tema", "escuro");','const tema = localStorage.getItem("tema");   // "escuro"','','// para guardar um objeto: converter em texto','localStorage.setItem("config", JSON.stringify({ rate: 1.3 }));','const cfg = JSON.parse(localStorage.getItem("config"));'),'O localStorage só guarda texto. Por isso os objetos passam por JSON.stringify na ida e JSON.parse na volta.'],
 null,['pwa','js','serviceworker','sessao'],{tags:'cookie localstorage sessionstorage indexeddb lgpd',also:['back']}),

E('bundler','Bundler (Vite, Webpack)','Junta e otimiza os arquivos do projeto',2,
 'Um projeto web moderno tem centenas de arquivos: seu código, bibliotecas, imagens, CSS. O **bundler** lê tudo, resolve quem depende de quem, converte o que for preciso (TypeScript, JSX, Sass) e entrega poucos arquivos otimizados e menores para o navegador. **Vite**, **Webpack**, **esbuild**, **Rollup** e **Parcel** são os mais conhecidos.',
 'É a **linha de embalagem** da fábrica: recebe peças soltas de vários setores, confere, empacota em caixas padronizadas e etiqueta para expedição. O cliente, que é o navegador, recebe poucos volumes bem fechados.',
 ['Transformar o código que você escreve no que o navegador entende','Deixar o site menor e mais rápido (minificação e divisão em partes)','Ter um servidor de desenvolvimento que atualiza ao salvar'],
 ['bash',L('npm create vite@latest meu-app    # cria um projeto','cd meu-app','npm install','npm run dev       # servidor de desenvolvimento','npm run build     # gera os arquivos finais na pasta dist'),'O dev é para você trabalhar (rápido, com recarga automática). O build é o que vai para a produção (otimizado).'],
 null,['vite','pacotes','react','typescript','node'],{tags:'webpack esbuild rollup parcel build empacotar minificar'}),

E('vite','Vite','O bundler moderno, rápido para desenvolver',2,
 'O **Vite** é uma ferramenta de desenvolvimento e de build para projetos web. Em desenvolvimento ele sobe quase na hora e atualiza a tela assim que você salva. Para a versão final, empacota e otimiza. Funciona com React, Vue, Svelte, TypeScript e JavaScript puro, e é uma das escolhas mais comuns para começar um projeto novo.',
 'É a **bancada de protótipo com ferramenta elétrica**: você muda a peça e já vê o resultado, sem esperar a montagem inteira. Quando o produto fica pronto, o mesmo sistema monta a versão final.',
 ['Criar projetos React, Vue ou Svelte em segundos','Trabalhar com recarga instantânea ao salvar','Gerar a versão otimizada para publicar'],
 ['javascript (vite.config.js)',L('import { defineConfig } from "vite";','import react from "@vitejs/plugin-react";','','export default defineConfig({','  plugins: [react()],','  server: { port: 3000 },','});'),'O arquivo de configuração é pequeno. Os plugins ensinam o Vite a entender cada tecnologia.'],
 null,['bundler','react','vue','node'],{alt:'Webpack (mais antigo e configurável), esbuild, Parcel, Rollup, Turbopack'}),

E('jsx','JSX','HTML escrito dentro do JavaScript',2,
 '**JSX** é um jeito de escrever, dentro do JavaScript, algo que parece HTML. O navegador não entende JSX: uma ferramenta, como o Vite ou o Babel, converte para JavaScript comum antes de rodar. Entre chaves você coloca qualquer expressão JavaScript, o que mistura estrutura e lógica num lugar só. É a forma mais comum de escrever componentes React. Os arquivos costumam ter a extensão .jsx, ou .tsx quando usam TypeScript.',
 'É a **ordem de serviço já preenchida com campos variáveis**: parece um documento comum, mas dentro dele há espaços onde entram dados na hora, como o nome da máquina e o status. Depois o escritório converte a ordem para a linguagem do chão de fábrica.',
 ['Escrever componentes React de forma legível','Misturar estrutura e lógica (listas, condições) sem texto solto','Entender por que existem arquivos .jsx e .tsx'],
 ['jsx',L('function Placa({ nome, ok }) {','  return (','    <div className="placa">','      <h2>{nome}</h2>','      <p>{ok ? "Rodando" : "Parada"}</p>','    </div>','  );','}'),'Repare que se escreve className e não class, porque class é palavra reservada do JavaScript. O que está entre chaves é JavaScript puro.'],
 'jsx',['react','js','typescript','vite'],{tags:'tsx react sintaxe babel'}),

E('react','React','Biblioteca para montar telas com componentes',2,
 'O **React**, criado no Facebook e hoje mantido pela Meta, monta interfaces a partir de **componentes**: pedaços reutilizáveis de tela (botão, cartão, tabela) que recebem dados e devolvem o que deve aparecer. Você descreve **como a tela deve ficar para um dado estado** e, quando o estado muda, o React atualiza só o que mudou. É uma das bibliotecas de interface mais usadas do mundo.',
 'É a **linha de montagem modular**: em vez de construir cada tela do zero, você tem módulos padronizados (cartão, botão) que encaixa em qualquer lugar. Trocou o módulo, vale para o produto inteiro. E o painel de controle (o estado) manda: mudou o sinal, só as lâmpadas ligadas àquele sinal reagem.',
 ['Painéis, dashboards e aplicativos web complexos','Equipes grandes que precisam reaproveitar telas','Base do React Native (apps de celular) e do Next.js (sites completos)','Mercado de trabalho: está entre as tecnologias de front-end mais pedidas em vagas'],
 ['jsx',L('import { useState } from "react";','','function Contador() {','  const [n, setN] = useState(0);        // estado: começa em 0','  return (','    <button onClick={() => setN(n + 1)}>','      Peças: {n}','    </button>','  );','}'),'O useState guarda o número. Ao clicar, o setN muda o estado e o React redesenha o botão com o valor novo. Você nunca mexe na tela diretamente.'],
 'react',['jsx','estado','nextjs','vite','js','reactnative'],{alt:'Vue, Angular, Svelte, Solid, Preact',tags:'componentes hooks usestate meta facebook biblioteca'}),

E('estado','Gerenciamento de estado','Quem guarda e distribui os dados do app',3,
 '**Estado** é o conjunto de dados que o app guarda e que muda com o tempo: usuário logado, itens do carrinho, filtro escolhido. Quando vários pedaços da tela precisam do mesmo dado, é preciso decidir **onde ele mora** e como mudá-lo. Bibliotecas como **Redux**, **Zustand**, **Pinia** (no Vue) e a **Context API** (no React) ajudam a organizar isso. Outras, como o React Query, cuidam de buscar e guardar em cache os dados do servidor.',
 'É o **quadro de controle de produção** que todos os setores consultam. Se cada setor mantivesse a sua própria anotação, os números divergiriam. Um quadro central, com regras claras sobre quem pode atualizar, evita discussão.',
 ['Evitar dados duplicados e telas que mostram valores diferentes','Organizar apps médios e grandes','Entender por que "estado" aparece em toda conversa sobre React e Vue'],
 ['javascript (Zustand)',L('import { create } from "zustand";','','const useCarrinho = create((set) => ({','  itens: [],','  adicionar: (item) => set((s) => ({ itens: [...s.itens, item] })),','}));','','// em qualquer componente:','const itens = useCarrinho((s) => s.itens);'),'O estado vive fora dos componentes. Qualquer tela pode ler os itens ou chamar adicionar, e todas as telas que usam o dado se atualizam.'],
 null,['react','vue','js','spa'],{tags:'redux zustand pinia context store state'}),

E('vue','Vue','Framework de interface fácil de aprender',2,
 'O **Vue** é um framework JavaScript para construir interfaces, criado por Evan You. É conhecido pela curva de aprendizado suave: o código de cada componente fica num arquivo único, com três blocos separados, o template (HTML), o script (lógica) e o style (CSS). Faz o mesmo que o React, com um estilo mais próximo do HTML que você já conhece.',
 'Se o React é um **kit de peças soltas** que você monta do seu jeito, o Vue é um **kit com manual de montagem** e as peças já separadas por caixa. Dá menos liberdade, mas guia melhor quem está começando.',
 ['Painéis e apps web, principalmente em equipes que querem começar rápido','Sites que crescem aos poucos: dá para usar só um pedaço do Vue numa página antiga','Combinar com o Nuxt para sites completos'],
 ['vue',L('<script setup>','import { ref } from "vue";','const n = ref(0);','</script>','','<template>','  <button @click="n++">Peças: {{ n }}</button>','</template>'),'O ref guarda o número. O @click liga o clique à ação, e as chaves duplas mostram o valor. Quando n muda, o Vue atualiza o botão.'],
 null,['react','nuxt','vite','angular','svelte'],{tags:'vuejs vue.js composition api pinia'}),

E('angular','Angular','Framework completo do Google para apps grandes',3,
 'O **Angular**, mantido pelo Google, é um framework completo para aplicações web grandes. Traz tudo junto: rotas, formulários, requisições, injeção de dependências e testes. Usa **TypeScript** por padrão e impõe uma organização rígida de pastas e conceitos. É comum em empresas grandes e em sistemas corporativos.',
 'É uma **fábrica inteira pronta**, com setores definidos, procedimentos escritos e padrões obrigatórios. Demora para aprender e dá pouca liberdade, mas quando há muita gente trabalhando junto, todo mundo fala a mesma língua.',
 ['Sistemas corporativos grandes, com muitos desenvolvedores','Projetos que valorizam padronização e longa duração','Vagas em bancos, seguradoras e grandes empresas'],
 ['typescript',L('import { Component } from "@angular/core";','','@Component({','  selector: "app-contador",','  template: `<button (click)="n = n + 1">Peças: {{ n }}</button>`,','})','export class ContadorComponent {','  n = 0;','}'),'O @Component é um decorador: uma etiqueta que diz ao Angular como tratar a classe. A estrutura é bem mais formal do que no React e no Vue.'],
 null,['typescript','react','vue','spa'],{tags:'google ng typescript corporativo'}),

E('svelte','Svelte','Framework que some na hora de compilar',2,
 'O **Svelte** é um framework de interface que faz o trabalho pesado **na hora de compilar**, e não no navegador. O resultado é um código pequeno e rápido, sem uma biblioteca grande rodando por baixo. A sintaxe é enxuta e bem próxima de HTML, CSS e JavaScript puros. O **SvelteKit** é o equivalente do Next.js para ele.',
 'Em vez de mandar o **operador experiente com o manual** para a obra (a biblioteca no navegador), o Svelte manda a **peça já usinada na medida certa**. A obra recebe menos coisa e monta mais rápido.',
 ['Sites e apps leves e rápidos','Quem quer pouca cerimônia para escrever componentes','Projetos pequenos a médios e interatividade em páginas estáticas'],
 ['svelte',L('<script>','  let n = 0;','</script>','','<button on:click={() => n++}>Peças: {n}</button>'),'Aqui o n++ já atualiza a tela: o compilador do Svelte insere o código de atualização por você. (As versões novas têm uma sintaxe um pouco diferente, chamada runes.)'],
 null,['react','vue','vite','nextjs'],{tags:'sveltekit compilador'}),

E('nextjs','Next.js','React com servidor, rotas e tudo incluído',3,
 'O **Next.js** é um framework criado em cima do React que acrescenta o que falta para um site completo: **rotas** automáticas pelas pastas, **renderização no servidor** (SSR) ou antes da publicação (SSG), otimização de imagens e até um back-end simples dentro do mesmo projeto. É mantido pela Vercel e muito usado para sites, lojas e produtos web.',
 'O React é o **motor**. O Next.js é o **carro montado em volta do motor**: chassi, painel, freio e sistema elétrico já instalados. Dá para tirar o motor e montar o seu próprio carro, mas quase ninguém precisa.',
 ['Sites que precisam de bom SEO e carga rápida','Aplicações completas, com front e back no mesmo projeto','Publicação fácil na Vercel'],
 ['javascript',L('// app/sobre/page.js  ->  vira a página /sobre automaticamente','export default function Sobre() {','  return <h1>Sobre a oficina</h1>;','}'),'Não existe arquivo de rotas para configurar: a estrutura de pastas é o mapa do site.'],
 null,['react','ssr','vercel','nuxt'],{tags:'next vercel ssr ssg app router'}),

E('nuxt','Nuxt','O Next.js do mundo Vue',3,
 'O **Nuxt** é para o Vue o que o Next.js é para o React: um framework que acrescenta rotas por pastas, renderização no servidor ou estática, gerenciamento de dados e um servidor integrado. Você cria páginas na pasta pages e o Nuxt cuida do resto.',
 'É a mesma ideia do Next.js, só que a **montadora usa o motor Vue**. Os modelos e a organização são parecidos. Muda a marca do motor.',
 ['Sites e lojas em Vue com bom SEO','Projetos que misturam páginas estáticas e dinâmicas','Aproveitar o ecossistema Vue com tudo organizado'],
 ['vue',L('<!-- pages/sobre.vue  ->  vira a página /sobre -->','<template>','  <h1>Sobre a oficina</h1>','</template>'),'Mesma lógica de pastas do Next.js: criar o arquivo já cria a rota.'],
 null,['vue','nextjs','ssr','vite'],{tags:'nuxt vue ssr'}),

E('astro','Astro','Sites rápidos com pouco JavaScript',2,
 'O **Astro** é um framework para sites cheios de conteúdo, como blogs, documentação e portfólios. Ele entrega HTML pronto e **só carrega JavaScript onde a página realmente precisa**. Permite usar componentes de React, Vue ou Svelte no mesmo projeto. O resultado costuma ser muito leve.',
 'É uma oficina que deixa **quase tudo já montado** e só liga os motores onde há uma parte que precisa se mexer. O resto é peça fixa, sem gasto de energia.',
 ['Blogs, documentação, sites institucionais e landing pages','Páginas que precisam carregar muito rápido','Misturar tecnologias sem pagar o custo de todas'],
 ['astro',L('---','const titulo = "Oficina Central";','---','<h1>{titulo}</h1>','<p>Revisão de motores elétricos.</p>'),'O trecho entre os traços roda no servidor, na hora de gerar o site. O navegador recebe HTML puro.'],
 null,['ssr','react','vue','svelte'],{tags:'ssg ilhas islands site estatico'}),

E('spa','SPA','O site que troca a tela sem recarregar',2,
 'Uma **SPA**, aplicação de página única, carrega o esqueleto do site **uma vez** e depois, a cada clique, o JavaScript troca só o miolo da tela, pedindo ao servidor apenas os dados necessários. A sensação é de aplicativo: sem piscar, rápido. Gmail e Trello funcionam assim. O custo é a primeira carga maior e mais cuidado com o SEO.',
 'É uma **bancada fixa onde só trocamos a peça em usinagem**: em vez de desmontar e remontar a oficina inteira a cada serviço, o posto continua montado e só entra o novo trabalho.',
 ['Sistemas, painéis e aplicativos web que precisam de resposta rápida','Dashboards e ferramentas de uso contínuo','Base de React, Vue e Angular quando usados sem renderização no servidor'],
 ['javascript',L('// troca o conteúdo sem recarregar a página','async function abrir(caminho) {','  const resp = await fetch("/api/" + caminho);','  const dados = await resp.json();','  document.querySelector("#miolo").innerHTML = montarTela(dados);','  history.pushState({}, "", "/" + caminho);   // atualiza o endereço','}'),'Pede só os dados, desenha só o miolo e ajusta o endereço da barra para o botão Voltar continuar funcionando.'],
 'spa',['ssr','react','vue','angular','fetch'],{tags:'single page application pagina unica'}),

E('ssr','SSR, CSR e SSG','Onde a página é montada: servidor, navegador ou antes',3,
 'O **CSR** monta a página no navegador com JavaScript, como numa SPA clássica. O **SSR** monta no servidor a cada pedido e entrega o HTML pronto. O **SSG** monta tudo uma vez, antes de publicar, e serve arquivos prontos. SSR e SSG deixam a primeira tela aparecer rápido e ajudam o SEO. Next.js, Nuxt, Astro e SvelteKit oferecem esses modos.',
 'O CSR é **entregar o móvel desmontado com o manual** para o cliente montar. O SSR é **montar na hora no seu galpão** e entregar pronto. O SSG é ter **estoque de móveis já montados** na prateleira: o mais rápido, mas só serve para o que não muda a cada pedido.',
 ['Deixar a primeira tela rápida mesmo em celular fraco','Melhorar o SEO e a prévia dos links','Escolher o modo certo por página: blog (SSG), painel logado (CSR), loja com preço ao vivo (SSR)'],
 ['javascript (Next.js)',L('// app/produtos/page.js: roda no servidor','export default async function Produtos() {','  const lista = await buscarProdutos();   // os dados chegam antes da página sair','  return <ul>{lista.map(p => <li key={p.id}>{p.nome}</li>)}</ul>;','}'),'O navegador recebe o HTML já com a lista. Não precisa esperar o JavaScript baixar para ver os produtos.'],
 'ssr',['spa','nextjs','nuxt','seo','astro'],{tags:'server side rendering client static generation hidratacao'}),

E('pwa','PWA','Site que se comporta como aplicativo',2,
 'Um **PWA**, aplicativo web progressivo, é um site com superpoderes: pode ser instalado na tela inicial do celular, funcionar sem internet graças ao **service worker**, receber notificações e abrir em tela cheia. É feito com HTML, CSS e JavaScript comuns, sem passar pela loja de aplicativos.',
 'É um **equipamento portátil com bateria própria**: funciona ligado na tomada (a internet), mas se faltar energia continua operando com o que guardou localmente.',
 ['Ter um "app" sem publicar na Play Store ou na App Store','Painéis e checklists de campo que precisam funcionar sem sinal','Um código só para todos os aparelhos'],
 ['json (manifest)',L('{','  "name": "Checklist de Manutenção",','  "short_name": "Checklist",','  "start_url": "/",','  "display": "standalone",','  "background_color": "#ffffff",','  "icons": [{ "src": "/icone-192.png", "sizes": "192x192", "type": "image/png" }]','}'),'O manifest diz ao celular o nome, o ícone e como abrir o app. O service worker, que é outro arquivo, cuida do funcionamento offline.'],
 null,['serviceworker','spa','responsivo','storage'],{tags:'progressive web app instalar offline manifest',also:['app']}),

E('serviceworker','Service Worker','O assistente que fica entre o site e a internet',3,
 'O **service worker** é um script que o navegador roda em segundo plano, separado da página. Ele intercepta os pedidos de rede e pode responder com cópias guardadas (o cache), o que permite que o site funcione **offline**. Também habilita notificações push e sincronização em segundo plano. É a peça central dos PWAs.',
 'É o **porteiro com almoxarifado próprio**: todo pedido passa por ele. Se o fornecedor externo está fora do ar, ele entrega a cópia que tem guardada, e o cliente nem percebe.',
 ['Fazer sites e PWAs funcionarem sem internet','Carregar páginas mais rápido usando cache','Receber notificações mesmo com a aba fechada'],
 ['javascript (sw.js)',L('self.addEventListener("fetch", (e) => {','  e.respondWith(','    caches.match(e.request).then((guardado) => guardado || fetch(e.request))','  );','});'),'Para cada pedido, olha primeiro no cache. Se tiver, devolve; se não, vai para a rede. As estratégias reais são mais elaboradas.'],
 null,['pwa','storage','fetch'],{tags:'sw offline cache push notificacoes'}),

E('jquery','jQuery','A biblioteca que dominou a web antiga',1,
 'O **jQuery** surgiu em 2006 para facilitar o JavaScript numa época em que cada navegador se comportava de um jeito. Com comandos curtos você procurava elementos e reagia a eventos. Hoje o próprio JavaScript e os frameworks resolvem isso, mas o jQuery ainda aparece em muito sistema antigo e em plugins, incluindo o WordPress.',
 'É o **adaptador universal de tomada** de uma época em que cada navegador tinha um plugue diferente. Hoje o padrão unificou e o adaptador ficou desnecessário em projeto novo, mas há muita instalação antiga que ainda depende dele.',
 ['Dar manutenção em sistemas legados','Entender código antigo que você vai herdar','Lembrar que muita coisa do JavaScript moderno nasceu para substituí-lo'],
 ['javascript',L('// jQuery','$("#salvar").on("click", function () {','  $("#msg").text("Salvo!");','});','','// JavaScript atual (equivalente)','document.querySelector("#salvar").addEventListener("click", () => {','  document.querySelector("#msg").textContent = "Salvo!";','});'),'São dois jeitos de fazer a mesma coisa. O de baixo é o padrão do navegador e não exige biblioteca.'],
 null,['js','dom','biblioteca','cms'],{tags:'jquery legado dolar'}),

E('tailwind','Tailwind CSS','Estilizar com classes prontas direto no HTML',2,
 'O **Tailwind CSS** é um framework de CSS em que, em vez de escrever regras num arquivo à parte, você coloca **classes utilitárias** direto no HTML: uma para o espaço interno, outra para a cor de fundo, outra para arredondar os cantos. Cada classe faz uma coisa pequena. Você monta o visual empilhando classes. Depois o Tailwind remove as que você não usou, e o arquivo final fica pequeno.',
 'É um **catálogo de peças padronizadas** (parafusos, suportes, chapas). Em vez de mandar usinar cada peça sob medida, que seria o CSS escrito à mão, você monta o equipamento combinando itens do catálogo. Rápido e consistente, só que o desenho fica com muita peça à mostra.',
 ['Montar telas rápido sem sair do HTML','Manter um padrão visual consistente em equipe','Projetos com React, Vue e Next.js, onde ele é muito popular','Criar protótipos e painéis internos em pouco tempo'],
 ['html',L('<button class="px-4 py-2 rounded-lg bg-blue-600 text-white font-bold shadow-lg">','  Salvar','</button>'),'Os px-4 e py-2 são espaços internos, rounded-lg arredonda, bg-blue-600 é o fundo azul e text-white é a letra branca. Cada classe é uma regra de CSS pronta.'],
 'tailwind',['css','bootstrap','react','nextjs','sass'],{alt:'Bootstrap, Bulma, CSS Modules, styled-components',tags:'utilitario utility first classes css framework'}),

E('bootstrap','Bootstrap','Componentes de interface prontos',1,
 'O **Bootstrap** é um conjunto de estilos e componentes prontos: botões, menus, cartões, formulários, grade de colunas, janelas modais. Você usa as classes no HTML e a página já fica com um visual padrão decente e adaptado ao celular. Foi criado no Twitter e dominou os anos 2010. Ainda é muito usado em sistemas internos e painéis administrativos.',
 'É um **kit de painel elétrico pré-montado**: botoeiras, sinaleiros e canaletas já padronizadas. Você só encaixa. Fica parecido com os painéis de todo mundo, mas fica pronto rápido e funciona.',
 ['Montar telas de sistema rapidamente, mesmo sem experiência em design','Painéis administrativos e protótipos','Entender código antigo ou projetos corporativos'],
 ['html',L('<button class="btn btn-primary">Reiniciar</button>','<button class="btn btn-danger">Apagar</button>','','<div class="row">','  <div class="col-md-6">Coluna A</div>','  <div class="col-md-6">Coluna B</div>','</div>'),'As classes btn e btn-primary formam o botão azul padrão. Na grade, as 12 colunas se dividem: duas de 6 formam metade e metade em telas médias.'],
 'bootstrap',['tailwind','css','responsivo','grid'],{tags:'twitter componentes ui kit'}),

E('sass','Sass','CSS com variáveis, aninhamento e funções',2,
 'O **Sass** é uma extensão do CSS que permite usar **variáveis**, **aninhamento**, pedaços reutilizáveis e até contas. Você escreve em arquivos .scss e uma ferramenta converte para CSS comum. Muitos recursos que nasceram no Sass, como as variáveis, hoje existem no próprio CSS, mas ele continua popular em projetos grandes.',
 'É escrever o **procedimento de manutenção com campos reutilizáveis**: em vez de repetir a cor da marca em cem lugares, você define uma vez e usa por nome. Mudou a marca? Muda em um ponto só.',
 ['Organizar o CSS de projetos grandes','Reaproveitar cores, espaçamentos e trechos','Entender frameworks como o Bootstrap, que são feitos em Sass'],
 ['scss',L('$azul: #0b5cc4;','','.botao {','  background: $azul;','  &:hover { background: darken($azul, 8%); }','}'),'O $azul é uma variável. O & dentro das chaves significa este mesmo elemento, o que dispensa repetir o seletor. O resultado vira CSS normal.'],
 null,['css','tailwind','bootstrap'],{tags:'scss less preprocessador css'}),

E('webcomponents','Web Components','Componentes nativos do navegador',3,
 '**Web Components** são um padrão do próprio navegador para criar suas **tags personalizadas**, como um elemento chamado painel-maquina, com estilo e comportamento isolados. Funcionam em qualquer página e com qualquer framework. São a base de bibliotecas como o **Lit**.',
 'É criar uma **peça padronizada com encaixe universal**, que funciona em qualquer máquina de qualquer fabricante, em vez de uma peça feita só para o equipamento de uma marca (React ou Vue).',
 ['Componentes que precisam funcionar em vários sistemas e frameworks','Bibliotecas de design system independentes de framework','Entender o que é um componente no nível mais básico'],
 ['javascript',L('class PainelMaquina extends HTMLElement {','  connectedCallback() {','    this.innerHTML = `<b>${this.getAttribute("nome")}</b>`;','  }','}','customElements.define("painel-maquina", PainelMaquina);','','// uso no HTML:  <painel-maquina nome="Prensa 01"></painel-maquina>'),'Depois do define, a tag nova passa a existir em qualquer página. Tags personalizadas sempre têm um hífen no nome.'],
 null,['react','vue','designsystem','dom'],{tags:'custom elements shadow dom lit'}),

E('designsystem','Design system','O manual de peças da identidade visual',2,
 'Um **design system** é o conjunto de regras e peças prontas de uma marca ou produto: cores, tipografia, espaços, botões, campos, avisos, com código reutilizável e explicação de quando usar cada um. Garante que telas feitas por pessoas diferentes tenham a mesma cara e o mesmo comportamento. Exemplos: Material Design (do Google), Carbon (da IBM) e Polaris (da Shopify).',
 'É o **catálogo de componentes padronizados da fábrica**: a mesma botoeira, o mesmo sinaleiro, a mesma cor de fiação em qualquer painel que sai dali. Quem monta o painel sabe como cada peça se comporta.',
 ['Manter o visual consistente em vários produtos','Acelerar o trabalho: ninguém redesenha um botão de novo','Facilitar a conversa entre design e desenvolvimento'],
 ['css (tokens)',L(':root {','  --cor-primaria: #0b5cc4;','  --espaco-m: 16px;','  --raio: 8px;','}','.botao {','  background: var(--cor-primaria);','  padding: var(--espaco-m);','  border-radius: var(--raio);','}'),'Os "tokens" são variáveis com os valores oficiais. Mudou a cor da marca? Troca num lugar e tudo acompanha.'],
 null,['figma','webcomponents','css','uxui'],{tags:'tokens componentes marca material design carbon'}),

E('uxui','UX e UI','Como a experiência funciona e como ela se parece',1,
 '**UX**, experiência do usuário, é se o produto é fácil, claro e resolve o problema de quem usa: o caminho percorrido, o que confunde, onde a pessoa desiste. **UI**, interface do usuário, é a parte visual: cores, botões, tipografia, ícones. Uma tela pode ser linda e péssima de usar, ou feia e funcionar perfeitamente. Bons produtos precisam dos dois.',
 'O UX é o **fluxo do processo na fábrica**: a ordem das estações, o caminho do operador, onde estão os gargalos. A UI é o **painel de operação**: o desenho das botoeiras e as cores dos sinaleiros. Painel bonito num processo ruim continua sendo um processo ruim.',
 ['Projetar sistemas internos que o pessoal usa sem treinamento longo','Reduzir erros com avisos claros e botões bem posicionados','Conversar melhor com designers','Testar com pessoas de verdade: poucos usuários já revelam a maior parte dos problemas'],
 ['princípios',L('1. Clareza: um objetivo principal por tela','2. Feedback: toda ação mostra que foi recebida','3. Prevenção: avisar antes de apagar algo importante','4. Consistência: o mesmo botão sempre faz a mesma coisa','5. Teste com usuários reais, não com você mesmo'),'São princípios gerais, inspirados nas heurísticas de usabilidade de Nielsen. Servem tanto para app de celular quanto para tela de IHM de máquina.'],
 null,['figma','a11y','designsystem','responsivo'],{tags:'usabilidade experiencia design interface prototipo',also:['eng']}),

E('canvas','Canvas','Uma tela em branco para desenhar com código',2,
 'O **canvas** é um elemento do HTML que funciona como uma folha em branco onde o JavaScript **desenha pixel a pixel**: linhas, formas, imagens, texto. Repetindo o desenho várias vezes por segundo, você cria animações, jogos, gráficos e editores de imagem. Tem bom desempenho, mas o que foi desenhado vira pixel: o navegador não sabe mais que aquilo era um círculo.',
 'É uma **lousa**: você desenha o que quiser e tem controle total, mas depois de desenhado é só tinta. Para mover o desenho é preciso apagar e redesenhar. Já os elementos do HTML são como **ímãs**: dá para mover cada um separadamente.',
 ['Gráficos e animações rápidas, com muitos elementos','Jogos 2D simples','Editores de imagem e assinaturas na tela','Painéis tipo manômetros e medidores'],
 ['javascript',L('const c = document.querySelector("canvas");','const x = c.getContext("2d");','','x.fillStyle = "#1f6fdb";','x.fillRect(20, 20, 100, 60);         // retângulo','x.beginPath();','x.arc(180, 50, 30, 0, 2 * Math.PI);  // círculo','x.fill();'),'O getContext("2d") pega o pincel. As coordenadas começam no canto superior esquerdo e crescem para a direita e para baixo.'],
 'canvas',['svg','threejs','js','chartjs'],{tags:'desenho 2d animacao jogo grafico pixel'}),

E('svg','SVG','Imagens vetoriais que nunca perdem a nitidez',1,
 '**SVG** é um formato de imagem feito de **fórmulas e formas** (linha, círculo, curva) em vez de pixels. Por isso pode ser ampliado sem perder qualidade e costuma ser bem leve. É texto, então dá para estilizar com CSS, animar e controlar com JavaScript. Ideal para ícones, logos, diagramas e gráficos.',
 'É o **desenho técnico em CAD**: guarda as medidas e as formas, não uma foto. Pode ser impresso em tamanho de cartão ou de outdoor que as linhas continuam finas e nítidas. A foto (JPG) é feita de pixels e, ampliada, vira quadradinho.',
 ['Ícones e logos que ficam nítidos em qualquer tela','Gráficos e diagramas interativos','Animações leves','Reduzir o peso do site em comparação com imagens grandes'],
 ['svg',L('<svg viewBox="0 0 100 100" width="100">','  <circle cx="50" cy="50" r="40" fill="#1f6fdb" />','  <path d="M50 50 L80 30" stroke="#fff" stroke-width="6" />','</svg>'),'O viewBox define o sistema de coordenadas e o resto é desenhado dentro dele. O tamanho final na tela pode ser qualquer um.'],
 'svg',['canvas','css','html','chartjs'],{tags:'vetor vetorial icone logo imagem escalavel'}),

E('threejs','WebGL e Three.js','Gráficos 3D no navegador',3,
 'O **WebGL** é a tecnologia do navegador que usa a **placa de vídeo** para desenhar em 3D. Escrever WebGL puro é trabalhoso, então se usa o **Three.js**, uma biblioteca que oferece cena, câmera, luzes e modelos 3D de forma simples. Serve para visualizadores de produto, mapas, jogos e gêmeos digitais de máquinas e fábricas.',
 'O WebGL é a **mesa de CNC** que sabe usinar em 3D, mas exige o código G. O Three.js é o **software de CAM** que gera esse código a partir de um desenho que você entende.',
 ['Mostrar o modelo 3D de uma máquina ou produto na web','Gêmeos digitais e visualização de plantas','Jogos e experiências interativas no navegador'],
 ['javascript',L('import * as THREE from "three";','','const cena = new THREE.Scene();','const cubo = new THREE.Mesh(','  new THREE.BoxGeometry(1, 1, 1),','  new THREE.MeshNormalMaterial()',');','cena.add(cubo);'),'Cena, objeto (malha, que é forma mais material), câmera e renderizador são os blocos básicos. Faltam ainda a câmera e o renderer para ver na tela.'],
 null,['canvas','unity','blender','twin'],{tags:'3d webgl three gpu cena modelo',also:['app']}),

E('chartjs','Gráficos na web','Chart.js, D3 e companhia: números viram imagem',2,
 'Para mostrar dados em gráficos na web existem bibliotecas. O **Chart.js** é fácil: você diz o tipo (barra, linha, pizza) e entrega os números. O **D3** dá controle total e permite criar visualizações sob medida, porém exige mais trabalho. **Plotly**, **ECharts** e **Recharts** ficam no meio-termo. Quase todo dashboard usa uma delas.',
 'O Chart.js é o **gráfico pronto do supervisório**: você escolhe o modelo e liga ao sinal. O D3 é a **oficina de ferramentas**: dá para construir qualquer indicador do zero, só que cada um dá trabalho.',
 ['Painéis de produção, indicadores e relatórios','Dashboards de IoT e telemetria','Mostrar tendências em vez de tabelas de números'],
 ['javascript (Chart.js)',L('new Chart(document.querySelector("canvas"), {','  type: "line",','  data: {','    labels: ["Seg", "Ter", "Qua", "Qui"],','    datasets: [{ label: "Peças", data: [120, 135, 98, 142] }],','  },','});'),'O tipo e os dados bastam para um gráfico de linha completo. O resto (cores, eixos, legendas) é ajuste fino.'],
 null,['canvas','svg','js','bi'],{tags:'chart d3 plotly echarts dashboard grafico visualizacao dados'})
]);
