/* ===== Linguagens e conceitos de programação ===== */
C('lang',[
E('variaveis','Variáveis e tipos de dados','Caixas com nome para guardar valores',1,
 'Uma **variável** é um espaço na memória com um nome, onde o programa guarda um valor para usar depois. Cada valor tem um **tipo**: número inteiro, número com vírgula, texto, verdadeiro ou falso, lista. O tipo define o que dá para fazer com ele: você soma números, mas não soma uma letra com um parafuso.',
 'É uma **gaveta etiquetada** do almoxarifado. A etiqueta é o nome da variável, o conteúdo é o valor, e o formato da gaveta (parafusos, óleo, papel) é o tipo. Dá para trocar o que está dentro, mas gaveta de parafuso não guarda óleo.',
 ['Guardar resultados de contas, nomes e leituras de sensor','Dar nome às coisas para o código ficar legível','Entender erros de tipo: somar texto com número dá resultado inesperado'],
 ['javascript',L('let maquina = "Prensa 01";     // texto','let horas = 1280;            // número','let ativa = true;            // verdadeiro ou falso','','const limite = 5000;        // const: não pode ser trocada depois','horas = horas + 8;           // troca o valor da gaveta'),'O let cria uma variável que pode mudar; o const cria uma que não pode ser reatribuída. O // começa um comentário.'],
 null,['tipagem','funcoes','controle','js','python'],{tags:'variavel tipo dado string numero boolean let const var'}),

E('funcoes','Funções','Um bloco de código com nome que você reutiliza',1,
 'Uma **função** é um pedaço de código com um nome, que recebe valores de entrada (os **parâmetros**), faz um trabalho e pode devolver um resultado. Em vez de repetir o mesmo código dez vezes, você escreve uma vez e chama pelo nome. Funções pequenas, com um propósito só, deixam o programa fácil de entender e de testar.',
 'É uma **rotina de manutenção escrita no procedimento**: tem nome ("lubrificar rolamento"), entradas (qual máquina, qual graxa) e um resultado (rolamento lubrificado). Qualquer técnico executa seguindo o procedimento, sem inventar de novo.',
 ['Evitar copiar e colar código','Quebrar problemas grandes em partes pequenas','Reutilizar e testar pedaços separadamente','Entender bibliotecas: tudo que você usa delas é função de alguém'],
 ['javascript',L('function consumo(potenciaKw, horas) {','  return potenciaKw * horas;       // devolve o resultado','}','','const gasto = consumo(7.5, 8);    // 60 (kWh)','console.log(gasto);'),'A função recebe dois parâmetros, multiplica e devolve. Quem chama não precisa saber como ela calcula.'],
 null,['variaveis','controle','js','python','recursao'],{tags:'function metodo parametro retorno def'}),

E('controle','Condições e laços','Decidir e repetir: if, for e while',1,
 'Um programa não executa só em linha reta. As **condições** (if e else) fazem o código escolher um caminho conforme o valor de algo: se a temperatura passou do limite, dispare o alarme. Os **laços** (for e while) repetem um bloco várias vezes, por exemplo para cada item de uma lista ou enquanto uma condição for verdadeira.',
 'É a lógica de um **CLP**: "se o sensor de nível estiver alto, desliga a bomba" é uma condição. "Enquanto o botão estiver apertado, mantém a esteira" é um laço. A leitura é a mesma que você faz no ladder, só que escrita em texto.',
 ['Programar qualquer regra de negócio','Percorrer listas de dados','Evitar o erro clássico do laço infinito, em que a condição de parada nunca acontece'],
 ['javascript',L('const temperatura = 92;','','if (temperatura > 90) {','  console.log("ALARME: superaquecimento");','} else {','  console.log("normal");','}','','for (let i = 1; i <= 3; i++) {','  console.log("Verificando motor " + i);','}'),'O if escolhe o caminho. O for repete: começa em 1, continua enquanto for menor ou igual a 3 e soma 1 a cada volta.'],
 null,['variaveis','funcoes','colecoes','clp'],{tags:'if else for while loop repeticao condicional laco'}),

E('colecoes','Listas e dicionários','Guardar vários valores juntos',1,
 'Quando você precisa de vários valores relacionados, usa uma **coleção**. A **lista** (ou array) guarda itens em ordem, acessados pela posição. O **dicionário** (ou objeto, ou map) guarda pares de nome e valor, acessados pelo nome. Quase todo dado do mundo real cabe numa combinação dos dois, e o JSON que as APIs usam é exatamente isso.',
 'A lista é a **fila de máquinas na linha**: a primeira, a segunda, a terceira. O dicionário é a **ficha de uma máquina**: modelo, potência e setor, cada campo com o seu nome.',
 ['Guardar leituras de sensores, itens de pedido e usuários','Percorrer, filtrar e transformar dados','Entender JSON, bancos de dados e APIs, que são listas e dicionários'],
 ['python',L('maquinas = ["Prensa 01", "Torno 02", "Esteira A"]   # lista','print(maquinas[0])                              # Prensa 01','','ficha = {"nome": "Prensa 01", "kw": 7.5}         # dicionário','print(ficha["kw"])                              # 7.5'),'Na lista, o primeiro item fica na posição 0, porque a contagem começa do zero. No dicionário você busca pelo nome do campo.'],
 null,['variaveis','controle','formatos','array'],{tags:'array lista dict dicionario objeto map'}),

E('tipagem','Tipagem estática e dinâmica','Quando a linguagem confere os tipos',2,
 'Em linguagens de **tipagem estática** (Java, C#, Go, TypeScript) você declara o tipo de cada variável e o compilador reclama dos erros **antes** do programa rodar. Em linguagens de **tipagem dinâmica** (Python, JavaScript, Ruby) o tipo vem do valor e os erros aparecem **durante** a execução. A estática pega mais erro cedo. A dinâmica é mais rápida de escrever.',
 'A estática é a **inspeção de recebimento**: a peça é conferida na porta, antes de entrar na linha. A dinâmica é descobrir que a peça estava errada **quando a máquina trava** na produção. O custo do erro muda muito conforme o ponto em que ele é encontrado.',
 ['Escolher a linguagem conforme o tamanho do projeto: projetos grandes ganham muito com tipos','Entender por que o TypeScript existe','Ler mensagens do tipo "type error"'],
 ['typescript',L('function dobro(n: number): number {','  return n * 2;','}','','dobro(5);        // ok','dobro("cinco");  // ERRO apontado antes de rodar'),'O ": number" diz o tipo esperado. No JavaScript puro, a segunda chamada só falharia (ou produziria lixo) durante a execução.'],
 null,['typescript','python','java','compilador'],{tags:'tipos estatica dinamica type forte fraca'}),

E('excecoes','Erros e exceções','Tratar o que dá errado sem derrubar o programa',2,
 'Programas falham: arquivo que não existe, rede fora do ar, dado em formato errado. Uma **exceção** é um sinal de que algo deu errado. Com **try e catch** (ou try e except, no Python) você tenta executar um trecho e, se der erro, trata de forma controlada: mostra uma mensagem, tenta de novo ou registra no log. Sem tratar, o programa inteiro pode parar.',
 'É o **plano de contingência**: se o sensor falhar, vai para o modo seguro, aciona o alarme e anota a ocorrência, em vez de simplesmente desligar a linha inteira sem explicação.',
 ['Evitar que um erro pequeno derrube o sistema','Dar mensagens claras ao usuário','Registrar o problema para investigar depois','Distinguir erro esperado (usuário digitou errado) de erro grave (bug)'],
 ['python',L('try:','    leitura = float(input("Temperatura: "))','    print("Leitura:", leitura)','except ValueError:','    print("Digite um número, por favor.")','finally:','    print("Fim da verificação")'),'O try tenta. Se o texto digitado não for número, o except trata o erro. O finally roda sempre, com ou sem erro.'],
 null,['bug-debug','funcoes','testes','python'],{tags:'try catch except erro exception throw'}),

E('async','Assíncrono, Promises e async/await','Esperar sem travar o resto',2,
 'Algumas tarefas demoram: ler um arquivo, buscar dados na rede, consultar um banco. Se o programa ficasse parado esperando, a tela travaria. No **modo assíncrono** o programa dispara a tarefa, continua com outras coisas e volta quando ela termina. No JavaScript isso é feito com **Promises**, e a sintaxe **async e await** deixa o código parecido com o modo comum, de cima para baixo.',
 'É o **forno que apita**: você coloca a peça para esquentar, vai usinar outra e volta quando o aviso toca. O modo síncrono seria ficar parado olhando o forno até acabar.',
 ['Fazer chamadas a APIs sem congelar a tela','Rodar tarefas em paralelo e ganhar tempo, com várias consultas ao mesmo tempo','Entender erros de "promessa não resolvida" e ordens estranhas de execução'],
 ['javascript',L('function esperar(ms) {','  return new Promise((ok) => setTimeout(ok, ms));','}','','async function rotina() {','  console.log("1: ligando o forno");','  await esperar(2000);            // espera 2 s sem travar a página','  console.log("2: forno pronto");','}','rotina();','console.log("3: isso aparece antes do 2");'),'O 3 aparece antes do 2 porque o await só pausa a função rotina, não o programa inteiro.'],
 'async',['fetch','js','eventloop','processos','node'],{tags:'promise await then callback assincrono sincrono',also:['front']}),

E('eventloop','Event loop','Como o JavaScript faz uma coisa por vez sem travar',3,
 'O JavaScript executa **uma coisa de cada vez**. Para não travar, as tarefas demoradas (tempo, rede, clique) são entregues ao navegador, e quando terminam, a função combinada entra numa **fila**. O **event loop** é o laço que só pega o próximo item da fila quando a pilha de execução está vazia. Entender isso explica a ordem estranha de alguns resultados.',
 'É o **torneiro com uma fila de ordens de serviço**: ele só pega a próxima ordem quando termina a peça que está no torno. As ordens esperam na fila, em ordem, sem ninguém interromper o trabalho.',
 ['Entender por que um setTimeout com tempo zero ainda roda depois do código atual','Evitar travar a tela com cálculos longos','Entender como o Node.js atende milhares de conexões com uma thread só'],
 ['javascript',L('console.log("A");','setTimeout(() => console.log("B"), 0);','Promise.resolve().then(() => console.log("C"));','console.log("D");','// saída: A, D, C, B'),'O código normal roda primeiro (A e D). Depois as promessas (C), que têm prioridade. Por último os timers (B), mesmo com tempo zero.'],
 'eventloop',['async','js','node','processos'],{tags:'fila pilha callstack microtask macrotask settimeout',also:['front']}),

E('typescript','TypeScript','JavaScript com verificação de tipos',2,
 'O **TypeScript**, criado pela Microsoft, é o JavaScript com uma camada extra: você escreve os **tipos** dos dados e a ferramenta aponta erros **antes** do código rodar. No final ele é convertido para JavaScript comum, que é o que o navegador executa. É muito usado em projetos médios e grandes, e é a base do Angular.',
 'É o JavaScript com **etiquetas de especificação nas peças**: a tolerância, o material e a medida estão escritos, e a inspeção reprova antes da peça entrar na linha.',
 ['Evitar erros bobos, como chamar uma função com o dado errado','Ter autocompletar melhor no editor','Manter projetos grandes organizados e fáceis de mudar','Trabalhar em equipe com contratos claros entre as partes do código'],
 ['typescript',L('interface Maquina {','  nome: string;','  horas: number;','  ativa: boolean;','}','','function resumo(m: Maquina): string {','  return m.nome + ": " + m.horas + " h";','}','','resumo({ nome: "Prensa 01", horas: 1280, ativa: true });  // ok','resumo({ nome: "Torno 02" });                            // erro: faltam campos'),'A interface descreve o formato esperado. O editor sublinha o erro enquanto você digita, antes de qualquer teste.'],
 null,['js','tipagem','angular','node','react'],{alt:'Flow, JSDoc com checagem de tipos',tags:'ts tipos microsoft',also:['front']}),

E('python','Python','A linguagem versátil de leitura fácil',1,
 'O **Python**, criado em 1991 por Guido van Rossum, é uma linguagem de sintaxe limpa, fácil de ler. Serve para quase tudo: automação, análise de dados, inteligência artificial, sites e APIs, scripts de administração e ciência. É interpretada, então roda direto, e tem uma biblioteca gigante pronta para usar.',
 'É a **chave multiuso** da caixa de ferramentas: não é a mais rápida em nenhuma tarefa, mas serve para quase todas e qualquer pessoa aprende a usar logo. Quando o serviço pede precisão extrema, aí você pega a ferramenta especializada (C, Rust).',
 ['Automatizar tarefas repetitivas: renomear arquivos, ler planilhas, gerar relatórios','Ciência de dados e IA, com pandas, NumPy e PyTorch','Back-end com Django, Flask e FastAPI','Scripts para equipamentos, sensores e Raspberry Pi'],
 ['python',L('import csv','','total = 0','with open("producao.csv") as f:','    for linha in csv.DictReader(f):','        total += int(linha["pecas"])','','print("Total produzido:", total)'),'Abre um arquivo CSV, soma a coluna pecas e imprime. Em poucas linhas você automatiza um trabalho que no Excel seria manual.'],
 null,['pandas','django','fastapi','pytorch','bash'],{alt:'JavaScript, Ruby, Lua',tags:'py script automacao dados ia guido'}),

E('java','Java','A linguagem corporativa que roda em qualquer lugar',2,
 'O **Java**, lançado em 1995 pela Sun e hoje da Oracle, é compilado para um código intermediário que roda na **JVM**, a máquina virtual, em qualquer sistema. É rigoroso, fortemente tipado e orientado a objetos. Domina sistemas de bancos, seguradoras e grandes empresas, e é a base histórica do Android. Não tem relação com o JavaScript, apesar do nome.',
 'É a **prensa hidráulica pesada**: lenta para preparar e exige todo um procedimento, mas aguenta produção contínua por décadas com segurança. É por isso que as grandes empresas confiam nela para sistemas que não podem parar.',
 ['Sistemas corporativos e bancários de grande porte','Back-end com Spring Boot','Apps Android (hoje mais comuns em Kotlin)','Muitas vagas e muita estabilidade no mercado'],
 ['java',L('public class Principal {','    public static void main(String[] args) {','        String maquina = "Prensa 01";','        int horas = 1280;','        System.out.println(maquina + ": " + horas + " h");','    }','}'),'Tudo vive dentro de uma classe. O main é o ponto de partida. Os tipos (String e int) são obrigatórios: é a tipagem estática.'],
 null,['spring','kotlin','csharp','runtime','poo'],{tags:'jvm oracle spring maven'}),

E('c','C','A linguagem que fala quase direto com o hardware',3,
 'O **C**, criado por Dennis Ritchie em 1972, é uma linguagem compilada, pequena e muito rápida, que dá acesso direto à memória e ao hardware. Sistemas operacionais, drivers, microcontroladores e boa parte do software que o mundo usa foram escritos em C. Em troca, você gerencia a memória sozinho, o que dá poder e abre espaço para erros graves.',
 'É a **torneira de alta pressão sem válvula de segurança**: entrega a vazão máxima e o controle total, mas errou a mão, estourou o cano. Por isso dá tanto desempenho e exige tanto cuidado.',
 ['Programar microcontroladores e sistemas embarcados, como Arduino e firmware de equipamentos','Criar sistemas operacionais, drivers e bibliotecas básicas','Entender como a memória realmente funciona, com os ponteiros','Base para aprender C++, Rust e quase tudo que veio depois'],
 ['c',L('#include <stdio.h>','','int main(void) {','    int horas = 1280;','    printf("Horas: %d\\n", horas);','    return 0;','}'),'O #include traz a biblioteca de entrada e saída. O %d é onde entra o inteiro no texto e o \\n é a quebra de linha. Compile com: gcc programa.c -o programa'],
 null,['cpp','rust','embarcados','arduino','compilador'],{tags:'ponteiro ponteiros memoria gcc ritchie'}),

E('cpp','C++','O C com orientação a objetos e muita potência',3,
 'O **C++**, de Bjarne Stroustrup (1985), estende o C com classes, templates e uma biblioteca padrão rica. Mantém o desempenho máximo e o controle sobre a memória. Domina jogos (Unreal Engine), navegadores, bancos de dados, sistemas de alta performance e software embarcado. É vasto e difícil de dominar por completo.',
 'É o **centro de usinagem de cinco eixos**: faz peças que nenhuma outra máquina faz, com precisão e velocidade, mas exige um operador experiente e programação cuidadosa.',
 ['Motores de jogos e gráficos em tempo real','Sistemas onde cada milissegundo e cada byte contam','Software industrial e embarcado de alto desempenho','Muito código legado importante que precisa de manutenção'],
 ['c++',L('#include <iostream>','#include <vector>','','int main() {','    std::vector<int> pecas = {120, 135, 98};','    int soma = 0;','    for (int p : pecas) soma += p;','    std::cout << "Total: " << soma << std::endl;','}'),'O vector é uma lista que cresce sozinha. O for (int p : pecas) percorre cada item. O std:: indica que a função vem da biblioteca padrão.'],
 null,['c','rust','unreal','godot'],{tags:'cplusplus cpp stroustrup stl'}),

E('csharp','C#','A linguagem da Microsoft para apps, jogos e sistemas',2,
 'O **C#**, que se lê C sharp, é uma linguagem moderna da Microsoft que roda sobre a plataforma **.NET**. É parecida com o Java, mas mais enxuta. Serve para sistemas corporativos, APIs (ASP.NET), aplicativos Windows e jogos, já que é a linguagem do Unity. Com o .NET atual, funciona também em Linux e Mac.',
 'É o **conjunto de máquinas e ferramentas de um mesmo fabricante**, todas desenhadas para trabalhar juntas. Se a fábrica já é toda dessa marca, a integração é simples e bem suportada.',
 ['Jogos com Unity','Sistemas corporativos e APIs em empresas que usam o ecossistema Microsoft','Aplicações desktop para Windows','Integração com Azure e SQL Server'],
 ['c#',L('using System;','','class Programa {','    static void Main() {','        string maquina = "Prensa 01";','        int horas = 1280;','        Console.WriteLine($"{maquina}: {horas} h");','    }','}'),'O $ antes do texto permite colocar variáveis entre chaves. O resto lembra bastante o Java.'],
 null,['dotnet','unity','java','typescript'],{tags:'c sharp csharp microsoft dotnet net'}),

E('go','Go','Simples, rápido e feito para servidores',2,
 'O **Go**, também chamado Golang, foi criado no Google e lançado em 2009. É compilado, simples de aprender, muito rápido e traz a concorrência embutida, com as **goroutines**, que permitem tratar milhares de tarefas ao mesmo tempo. Gera um único executável sem dependências, o que facilita a instalação. O Docker e o Kubernetes são escritos em Go.',
 'É a **ferramenta enxuta de campo**: poucas peças, fácil de aprender a usar, vai direto à solução. Quem aprende em um fim de semana já produz coisa útil.',
 ['Back-end, APIs e microsserviços de alto desempenho','Ferramentas de linha de comando e de infraestrutura','Sistemas em nuvem: muitas ferramentas de DevOps são em Go'],
 ['go',L('package main','','import "fmt"','','func main() {','    maquinas := []string{"Prensa 01", "Torno 02"}','    for i, m := range maquinas {','        fmt.Println(i+1, m)','    }','}'),'O := cria a variável e deduz o tipo. O range percorre a lista, devolvendo a posição e o item.'],
 null,['docker','kubernetes','rust','api'],{tags:'golang goroutine google'}),

E('rust','Rust','Rápido como C, mas com a memória protegida',3,
 'O **Rust** é uma linguagem compilada que entrega o desempenho do C e do C++ com **segurança de memória** garantida pelo compilador, sem coletor de lixo. O compilador é rigoroso: se há risco de uso indevido da memória, o programa nem compila. Por isso é adotado em sistemas, navegadores, infraestrutura e segurança. Tem uma curva de aprendizado íngreme.',
 'É a **máquina com intertravamento de segurança em tudo**: não deixa operar numa condição perigosa. Dá trabalho para configurar e entender, mas depois a fábrica opera com muito menos acidentes.',
 ['Software de sistema, ferramentas de linha de comando e motores','WebAssembly e partes críticas de desempenho','Segurança e infraestrutura, onde falha de memória custa caro','Embarcados modernos'],
 ['rust',L('fn main() {','    let maquinas = vec!["Prensa 01", "Torno 02"];','    for m in &maquinas {','        println!("{}", m);','    }','}'),'O & empresta a lista sem tomar posse dela. É a regra de ownership do Rust que evita erros de memória em tempo de compilação.'],
 null,['c','cpp','go','wasm'],{tags:'ownership cargo mozilla memoria segura'}),

E('php','PHP','A linguagem que move boa parte da web',1,
 'O **PHP**, de 1995, foi feito para criar páginas dinâmicas no servidor e ainda move uma fatia enorme da web, incluindo o **WordPress**. Ele roda no servidor, gera o HTML e responde ao navegador. O PHP moderno, com Laravel e Symfony, é bem diferente da fama antiga: tem tipos, boas práticas e desempenho decente.',
 'É o **funcionário antigo da casa**: conhece tudo, está em toda parte e muita coisa só funciona por causa dele, mesmo que as pessoas novas brinquem com o jeito dele de trabalhar.',
 ['Sites em WordPress, lojas virtuais e CMS','Sistemas web com Laravel','Manutenção de sistemas legados','Hospedagem barata e fácil em qualquer lugar'],
 ['php',L('<?php','$maquinas = ["Prensa 01", "Torno 02"];','foreach ($maquinas as $m) {','    echo "<li>$m</li>";','}'),'O PHP roda no servidor e escreve HTML no meio da página. As variáveis começam com $.'],
 null,['laravel','cms','mysql','backend'],{tags:'wordpress laravel hospedagem'}),

E('ruby','Ruby','Linguagem pensada para a felicidade do programador',2,
 'O **Ruby**, de Yukihiro Matsumoto (1995), tem uma sintaxe elegante, quase em linguagem natural. Ficou famoso com o framework **Ruby on Rails**, que popularizou o desenvolvimento rápido de aplicações web. É usado em startups, em sites como GitHub e Shopify, e em scripts de automação.',
 'É o **trabalho feito num ateliê**: bonito, fluido e agradável de executar. Não é a linha de produção mais rápida, mas é ótimo para criar e testar ideias depressa.',
 ['Protótipos e produtos web com Rails','Scripts e automação','Aprender ideias de programação orientada a objetos'],
 ['ruby',L('maquinas = ["Prensa 01", "Torno 02"]','','maquinas.each do |m|','  puts "Verificando #{m}"','end'),'O each percorre a lista. O #{} coloca a variável dentro do texto.'],
 null,['rails','python','php'],{tags:'rails matz'}),

E('kotlin','Kotlin','Java moderno, a linguagem oficial do Android',2,
 'O **Kotlin**, da JetBrains, roda na JVM e é totalmente compatível com o Java, mas tem uma sintaxe bem mais curta e segura. É a linguagem recomendada pelo Google para criar apps Android, e também serve para back-end (Spring, Ktor) e para apps multiplataforma.',
 'É o **Java com ferramentas novas na bancada**: faz o mesmo trabalho com menos passos, e já tem proteção contra os erros mais comuns.',
 ['Aplicativos Android nativos','Back-end moderno na JVM','Código compartilhado entre Android e iOS, com o Kotlin Multiplatform'],
 ['kotlin',L('data class Maquina(val nome: String, val horas: Int)','','fun main() {','    val m = Maquina("Prensa 01", 1280)','    println("${m.nome}: ${m.horas} h")','}'),'O data class cria a classe com poucas linhas. O val é uma variável que não muda; o var seria mutável.'],
 null,['java','android','swift','spring'],{tags:'jetbrains android jvm'}),

E('swift','Swift','A linguagem da Apple para iPhone e Mac',2,
 'O **Swift** é a linguagem moderna da Apple para criar aplicativos de iPhone, iPad, Mac, Apple Watch e Apple TV. É rápido, seguro (evita muitos erros por padrão) e agradável de ler. É usado junto com o **SwiftUI**, o jeito atual de desenhar telas nas plataformas da Apple.',
 'É a **ferramenta oficial do fabricante** para mexer no equipamento dele: foi feita sob medida, tem tudo no lugar, mas serve basicamente para aquela marca.',
 ['Apps nativos para iOS e macOS','Aproveitar todos os recursos do aparelho: câmera, sensores e notificações','Trabalhar no ecossistema Apple'],
 ['swift',L('let maquina = "Prensa 01"','var horas = 1280','horas += 8','print("\\(maquina): \\(horas) h")'),'O let é constante e o var é variável. A barra com parênteses coloca valores dentro do texto.'],
 null,['ios','kotlin','flutter'],{tags:'apple iphone swiftui'}),

E('dart','Dart','A linguagem do Flutter',2,
 'O **Dart** é uma linguagem do Google criada para fazer interfaces. Sua grande aplicação é o **Flutter**, um framework que gera aplicativos para Android, iOS, web e desktop a partir de um único código. Tem tipagem, é rápida e traz boas ferramentas para quem desenha telas.',
 'É a **linguagem de comando de uma única máquina universal**, o Flutter: você aprende ela para operar essa máquina, e a máquina produz peças para várias linhas.',
 ['Apps multiplataforma com Flutter','Interfaces com animações fluidas','Um único time cuidando de Android e iOS'],
 ['dart',L('void main() {','  final maquinas = ["Prensa 01", "Torno 02"];','  for (final m in maquinas) {','    print("Verificando $m");','  }','}'),'O final é uma variável que só recebe valor uma vez. O $ dentro do texto insere a variável.'],
 null,['flutter','kotlin','swift','reactnative'],{tags:'flutter google multiplataforma'}),

E('r','R','Linguagem para estatística e análise de dados',2,
 'O **R** é uma linguagem feita por estatísticos para estatística e visualização de dados. Tem milhares de pacotes para testes, modelos e gráficos de qualidade de publicação. É forte em pesquisa, saúde, finanças e em qualquer lugar onde a análise estatística é o centro do trabalho.',
 'É o **laboratório de metrologia**: instrumentos de medição e análise muito precisos e especializados. Não serve para construir a fábrica toda, mas quando o assunto é medir e interpretar, é referência.',
 ['Análise estatística e pesquisa','Gráficos para relatórios e artigos','Ciência de dados, ao lado do Python'],
 ['r',L('horas <- c(1280, 3410, 760, 5120)','mean(horas)         # média','sd(horas)           # desvio padrão','hist(horas)         # histograma'),'O <- atribui valor. O c() cria um vetor, que é uma lista de números. As funções de estatística já vêm prontas.'],
 null,['python','pandas','matlab','datascience'],{tags:'estatistica rstudio'}),

E('matlab','MATLAB e Octave','Cálculo numérico para engenharia',2,
 'O **MATLAB** é um ambiente e uma linguagem para cálculo numérico, matrizes, simulação e controle, muito usado em engenharia e pesquisa. O **Simulink** simula sistemas com blocos. É pago, mas existe o **Octave**, gratuito e compatível com boa parte do código. Em muitas áreas o Python já ocupa o espaço dele.',
 'É a **bancada de cálculo do engenheiro**: calculadora científica, régua, planilha e osciloscópio juntos numa tela, pronta para modelar um motor ou um controlador antes de construir qualquer coisa.',
 ['Simular sistemas de controle, motores e sinais','Tratar dados de ensaios e medições','Prototipar algoritmos antes de passar para outra linguagem'],
 ['matlab',L('t = 0:0.01:2;                 % tempo de 0 a 2 s','y = 1 - exp(-3*t);           % resposta de um sistema de 1ª ordem','plot(t, y)'),'O 0:0.01:2 cria o vetor de tempo. A conta é feita em todos os pontos ao mesmo tempo, sem laço.'],
 null,['python','pid','r'],{tags:'simulink octave engenharia matriz',also:['ind']}),

E('lua','Lua','Linguagem pequena para embutir em outros programas',2,
 'O **Lua** é uma linguagem minúscula e rápida, criada no Brasil, na PUC-Rio, em 1993, feita para ser **embutida** em outros programas. Muitos jogos usam Lua para scripts, como o World of Warcraft, e o Roblox usa uma variante dela. Também aparece em equipamentos e softwares que aceitam pequenos scripts. É simples de aprender e leve.',
 'É a **linguagem do botão "personalizar"**: o programa principal é fechado, mas deixa uma porta para você escrever pequenos comportamentos próprios.',
 ['Scripts de jogos e mods','Automação em equipamentos e softwares que aceitam Lua','Sistemas embarcados leves'],
 ['lua',L('local maquinas = {"Prensa 01", "Torno 02"}','','for i, m in ipairs(maquinas) do','  print(i, m)','end'),'A tabela {} serve como lista e como dicionário. As listas do Lua começam na posição 1.'],
 null,['c','python','embarcados'],{tags:'roblox script embutida'}),

E('bash','Bash e shell script','Automatizar tarefas no terminal',1,
 '**Bash** é o shell mais usado no Linux e no Mac. Um **shell script** é um arquivo de texto com uma sequência de comandos do terminal, que roda tudo de uma vez. É perfeito para automatizar tarefas do dia a dia no servidor: backup, limpeza de arquivos, instalação e rotina de deploy.',
 'É o **procedimento operacional padrão** escrito em passos: em vez de você repetir manualmente cada comando, você entrega o roteiro ao sistema e ele executa sempre igual.',
 ['Automatizar backups, cópias, limpeza e relatórios','Preparar e colocar servidores no ar','Juntar ferramentas de linha de comando em rotinas'],
 ['bash',L('#!/bin/bash','# backup.sh: copia a pasta de dados com a data no nome','data=$(date +%Y-%m-%d)','tar -czf "backup-$data.tar.gz" ./dados','echo "Backup feito: backup-$data.tar.gz"'),'O #!/bin/bash diz qual shell executar. O $(...) guarda a saída de um comando numa variável. Para rodar: chmod +x backup.sh && ./backup.sh'],
 null,['terminal','linux','python','cron'],{tags:'shell script sh zsh automacao',also:['ops']}),

E('powershell','PowerShell','O terminal poderoso do Windows',2,
 'O **PowerShell** é o shell e a linguagem de automação da Microsoft. Em vez de passar só texto entre os comandos, ele passa **objetos**, o que facilita filtrar e transformar dados. Serve para administrar Windows, Active Directory, Microsoft 365 e Azure, e hoje também roda em Linux e Mac.',
 'É o **Bash com ficha técnica**: cada resultado vem com campos nomeados (nome, tamanho, status), e você filtra pelo campo em vez de caçar texto.',
 ['Administrar máquinas Windows em escala','Automatizar tarefas de TI em ambientes Microsoft','Gerenciar usuários e serviços na nuvem do Azure e do 365'],
 ['powershell',L('Get-Process |','  Where-Object { $_.CPU -gt 100 } |','  Sort-Object CPU -Descending |','  Select-Object -First 5 Name, CPU'),'Lista os processos, filtra os que gastaram mais de 100 segundos de CPU, ordena e mostra os 5 primeiros. O | passa objetos adiante, não texto.'],
 null,['bash','terminal','azure'],{tags:'windows ps1 microsoft automacao',also:['ops']}),

E('assembly','Assembly','A linguagem mais próxima do processador',3,
 'O **Assembly** é a linguagem em que cada linha corresponde a uma instrução do processador, como somar, mover ou comparar. Cada família de processadores tem o seu. Quase ninguém escreve programas inteiros nela, mas ela aparece em partes críticas de desempenho, firmware, engenharia reversa e análise de malware.',
 'É operar a máquina **com o manual de comandos do fabricante**, botão por botão, sem nenhuma automação. Total controle, trabalho enorme.',
 ['Entender como o computador realmente executa um programa','Engenharia reversa e análise de segurança','Otimizações extremas e inicialização de sistemas'],
 ['assembly (x86)',L('mov eax, 5     ; coloca 5 no registrador eax','add eax, 3     ; soma 3, então eax = 8','cmp eax, 8     ; compara com 8','je  igual      ; se igual, pula para o rótulo igual'),'Cada linha é uma instrução. Os registradores, como o eax, são pequenas memórias dentro do processador. O ; começa um comentário.'],
 null,['c','compilador','hardware','malware'],{tags:'asm baixo nivel registrador maquina'}),

E('cobol','COBOL','A veterana que ainda guarda o dinheiro do mundo',2,
 'O **COBOL**, de 1959, foi criado para processar dados comerciais. Muitos bancos, seguradoras e governos ainda rodam sistemas COBOL em mainframes, processando enormes volumes de transações. A sintaxe parece frases em inglês. Há pouca gente nova aprendendo, e por isso quem conhece a linguagem é procurado.',
 'É a **prensa antiga que ninguém desliga**: a fábrica toda depende dela, e trocar sairia caro e arriscado. Os poucos mecânicos que sabem consertá-la são valorizados.',
 ['Manter sistemas bancários, de seguros e governamentais','Migrar sistemas antigos para tecnologias novas','Nicho com demanda constante e pouca concorrência'],
 ['cobol',L('IDENTIFICATION DIVISION.','PROGRAM-ID. OLA.','PROCEDURE DIVISION.','    DISPLAY "Ola, fabrica".','    STOP RUN.'),'O programa é dividido em seções com nomes em maiúsculas. O DISPLAY mostra um texto na tela.'],
 null,['java','fortran','banco-dados'],{tags:'mainframe legado banco antigo'}),

E('fortran','Fortran','A pioneira do cálculo científico',3,
 'O **Fortran**, de 1957, foi feito para cálculo científico e continua rápido e muito usado em simulação numérica: clima, física, engenharia e computação de alto desempenho. Grandes bibliotecas de álgebra e de simulação foram escritas nele e continuam em uso.',
 'É o **torno que fez a indústria nascer**: antigo, mas tão bem afinado para uma tarefa que, em certas aplicações, nada foi capaz de substituí-lo de verdade.',
 ['Simulações científicas e de engenharia','Código de supercomputadores','Entender bibliotecas numéricas que Python e R usam por baixo'],
 ['fortran',L('program media','  real :: v(4) = [1280.0, 3410.0, 760.0, 5120.0]','  print *, "Media:", sum(v) / size(v)','end program media'),'O sum e o size trabalham sobre o vetor inteiro de uma vez, algo que a linguagem faz naturalmente.'],
 null,['c','matlab','python'],{tags:'cientifico simulacao hpc'}),

E('vba','VBA e macros','Programar dentro do Excel e do Office',1,
 'O **VBA**, Visual Basic for Applications, é a linguagem das **macros** do Excel, Word e Access. Com ele você automatiza planilhas: copiar dados, gerar relatórios, enviar e-mails, criar botões e formulários. É muito comum em empresas, onde o Excel é a ferramenta central. Para projetos novos, o Python e os Office Scripts vêm ganhando espaço.',
 'É a **automação sobre a ferramenta que já está na bancada**: em vez de montar uma máquina nova, você programa a que o pessoal já usa o dia todo.',
 ['Automatizar planilhas e relatórios repetitivos','Criar ferramentas internas sem depender da TI','Manter planilhas legadas com macros'],
 ['vba',L('Sub MarcarParadas()','    Dim c As Range','    For Each c In Range("C2:C100")','        If c.Value = "parada" Then c.Interior.Color = vbRed','    Next c','End Sub'),'Percorre as células de C2 até C100 e pinta de vermelho as que dizem parada. Para criar uma macro: Alt+F11 abre o editor.'],
 null,['python','powershell','bi'],{tags:'excel macro office planilha visual basic'}),

E('elixir','Elixir','Sistemas que atendem milhões e não podem cair',3,
 'O **Elixir** roda na máquina virtual do **Erlang**, criada pela Ericsson para telefonia, onde a regra é nunca parar. É funcional e feito para concorrência massiva: milhões de tarefas leves isoladas entre si. Se uma falha, as outras continuam. É usado em mensageria, tempo real e sistemas de alta disponibilidade.',
 'É uma **central telefônica** projetada para continuar funcionando mesmo se um módulo queimar: cada módulo é isolado, e há um supervisor religando o que falhar.',
 ['Chats, notificações e sistemas em tempo real','Serviços que precisam de alta disponibilidade','Aprender programação funcional e concorrência'],
 ['elixir',L('maquinas = ["Prensa 01", "Torno 02"]','','Enum.each(maquinas, fn m ->','  IO.puts("Verificando " <> m)','end)'),'O fn cria uma função anônima. O <> junta textos. Os dados em Elixir nunca mudam: cada operação devolve uma versão nova.'],
 null,['haskell','go','scala'],{tags:'erlang beam phoenix concorrencia'}),

E('haskell','Haskell','Programar com funções puras',3,
 'O **Haskell** é uma linguagem funcional pura, em que as funções não têm efeitos escondidos e os dados não mudam. Isso torna o código previsível, fácil de testar e de provar correto. É mais usado na academia, em finanças e em ferramentas especializadas, mas suas ideias foram parar em Rust, Scala, JavaScript, Kotlin e Swift.',
 'É a **fábrica onde toda máquina é um processo fechado**: mesma entrada, mesma saída, sempre, sem depender do humor do dia nem do estado de outra máquina. Fica fácil prever e auditar.',
 ['Aprender um jeito diferente de pensar em programas','Software em que a correção é crítica','Entender imutabilidade e funções de ordem superior'],
 ['haskell',L('dobro :: Int -> Int','dobro x = x * 2','','main = print (map dobro [1, 2, 3])   -- [2,4,6]'),'A primeira linha declara o tipo: recebe um Int e devolve um Int. O map aplica a função a cada item da lista.'],
 null,['elixir','scala','funcional'],{tags:'funcional puro imutavel lambda'}),

E('scala','Scala','Java com superpoderes funcionais',3,
 'O **Scala** roda na JVM e mistura orientação a objetos com programação funcional. É conciso e poderoso. Ficou conhecido por ser a linguagem do **Apache Spark**, o motor de processamento de dados em larga escala, e por sistemas de grande volume em empresas de tecnologia.',
 'É uma **máquina CNC de múltiplas funções**: faz o que o torno simples (o Java) faz, mais fresamento e furação, tudo numa operação. Rende muito, mas o painel tem muito mais botões.',
 ['Engenharia de dados com Spark','Back-end de alto desempenho na JVM','Explorar programação funcional com acesso às bibliotecas Java'],
 ['scala',L('val maquinas = List("Prensa 01", "Torno 02")','maquinas.foreach(m => println(s"Verificando $m"))'),'O val é imutável. O s antes do texto permite inserir variáveis com $.'],
 null,['java','spark','kotlin','haskell'],{tags:'jvm spark funcional'})
]);
