/* ===== Back-end e APIs ===== */
C('back',[
E('backend','Back-end','A parte do sistema que roda no servidor',1,
 'O **back-end** é a parte do sistema que roda em um servidor, longe dos olhos do usuário. Ele recebe os pedidos do front-end, aplica as regras do negócio, conversa com o banco de dados e devolve uma resposta. Também cuida de login, permissões, pagamentos, envio de e-mail e de tudo que não pode ficar exposto no navegador.',
 'Se o site é um restaurante, o front-end é o **salão e o cardápio**. O back-end é a **cozinha**: o cliente não vê, mas é lá que o pedido vira prato, com estoque, receita e controle de qualidade. O garçom, que leva o pedido e traz a resposta, é a API.',
 ['Guardar e proteger os dados dos usuários','Aplicar regras de negócio: calcular preço, validar estoque, liberar acesso','Falar com bancos de dados e serviços externos, como pagamento, e-mail e mapas','Esconder chaves e senhas, que nunca devem ir para o navegador'],
 ['javascript',L('// servidor.js - rode com: node servidor.js','const http = require("http");','','const servidor = http.createServer((req, res) => {','  res.setHeader("Content-Type", "application/json");','  res.end(JSON.stringify({ mensagem: "Olá do servidor", caminho: req.url }));','});','','servidor.listen(3000, () => console.log("Ouvindo na porta 3000"));'),'O servidor fica ouvindo na porta 3000. Cada pedido que chega executa a função, que devolve um JSON. Com o programa rodando, abra http://localhost:3000 no navegador.'],
 null,['api','node','cliente-servidor','banco-dados','frontend'],{tags:'servidor server backend regra de negocio'}),

E('api','API','O contrato que permite um programa pedir coisas a outro',1,
 'Uma **API** (Application Programming Interface) é um jeito combinado de um programa pedir coisas a outro. Define quais pedidos existem, como fazer cada um e qual é o formato da resposta. Na web, quase sempre é um endereço que você chama e recebe dados em JSON. Quem usa a API não precisa saber como o outro sistema funciona por dentro, só o contrato.',
 'É o **garçom** do restaurante: você não entra na cozinha, faz o pedido pelo cardápio, ele leva e traz o prato pronto. Também lembra a **tomada** da parede: um padrão combinado, e qualquer aparelho que siga o padrão funciona.',
 ['Conectar o front-end ao back-end','Integrar sistemas diferentes: pagamento, mapas, previsão do tempo, WhatsApp','Deixar outras empresas usarem seus dados e serviços de forma controlada','Separar partes do sistema para equipes trabalharem sem se atrapalhar'],
 ['javascript',L('// Chamando uma API pública do GitHub','const resposta = await fetch("https://api.github.com/users/octocat");','const dados = await resposta.json();','console.log(dados.name, dados.public_repos);'),'O fetch faz o pedido ao endereço da API. O json() converte a resposta em objeto. Você usou o serviço do GitHub sem saber nada do código dele.'],
 'api',['rest','http','formatos','fetch','graphql','openapi','webhook'],{tags:'interface contrato endpoint integracao'}),

E('rest','REST','O estilo mais comum de desenhar APIs na web',1,
 '**REST** é um estilo de desenhar APIs em cima do HTTP. Cada coisa do sistema (usuário, pedido, produto) é um **recurso** com o seu endereço, e você age sobre ele com os verbos do HTTP: GET para ler, POST para criar, PUT ou PATCH para alterar e DELETE para apagar. A resposta vem com um código de status que diz se deu certo: 200 é sucesso, 404 é não encontrado, 500 é erro no servidor.',
 'É o **almoxarifado organizado por prateleira**: cada item tem endereço fixo e as ações são sempre as mesmas, consultar, guardar, trocar e retirar. Qualquer pessoa entende o padrão sem treinamento.',
 ['Ser o padrão da maioria das APIs da internet','Ter endereços previsíveis, fáceis de documentar e de testar','Aproveitar o que o HTTP já oferece: verbos, status e cache'],
 ['http',L('GET    /produtos        → lista os produtos','GET    /produtos/42     → busca o produto 42','POST   /produtos        → cria um produto novo','PUT    /produtos/42     → substitui o produto 42','PATCH  /produtos/42     → altera parte do produto 42','DELETE /produtos/42     → apaga o produto 42'),'O endereço é um substantivo no plural (produtos) e o verbo do HTTP diz a ação. Evite endereços como /apagarProduto: o verbo DELETE já diz isso.'],
 null,['api','http','crud','graphql','openapi'],{tags:'restful verbos get post put delete status'}),

E('graphql','GraphQL','Você pede exatamente os campos que quer',2,
 'O **GraphQL**, criado pelo Facebook, é uma linguagem para pedir dados a uma API. Em vez de vários endereços fixos, existe um só, e o cliente descreve **exatamente os campos** que quer. Isso evita receber dados demais ou fazer várias chamadas para montar uma tela. O servidor tem um **schema**, o mapa de tudo que pode ser pedido. Em troca, o cache fica mais difícil e consultas muito grandes precisam de limite.',
 'No REST, o garçom traz o **prato fechado do cardápio**. No GraphQL, você monta o prato: quero arroz, sem feijão, com dois ovos. Recebe só o que pediu, tudo numa viagem só.',
 ['Telas complexas e apps móveis que precisam de poucos dados por vez','Juntar dados de várias fontes em uma consulta só','Dar liberdade ao front-end sem pedir endpoints novos ao back-end'],
 ['graphql',L('query {','  usuario(id: 42) {','    nome','    pedidos(ultimos: 3) {','      numero','      total','    }','  }','}'),'Pede o nome do usuário 42 e, dentro dele, só o número e o total dos três últimos pedidos. A resposta vem em JSON, no mesmo formato do pedido.'],
 null,['rest','api','formatos','openapi'],{tags:'consulta query mutation schema facebook apollo'}),

E('grpc','gRPC','Conversa rápida e binária entre serviços',3,
 'O **gRPC**, criado pelo Google, é um jeito de serviços conversarem entre si. Em vez de texto em JSON, usa um formato **binário** compacto, o Protocol Buffers, sobre HTTP/2, a partir de um contrato escrito em um arquivo. Com ele, o código das duas pontas é gerado automaticamente em várias linguagens. É rápido e bem tipado, mas não é fácil de testar direto no navegador.',
 'É a **linha de ramal interno da fábrica**: código curto, rápido e padronizado entre os setores. Funciona muito bem dentro da empresa, mas não é para atender o público de fora.',
 ['Comunicação interna entre microsserviços com baixa latência','Streaming de dados nos dois sentidos','Contratos fortes entre equipes e entre linguagens diferentes'],
 ['protobuf',L('syntax = "proto3";','','service Maquinas {','  rpc Status (PedidoStatus) returns (RespostaStatus);','}','','message PedidoStatus { string id = 1; }','message RespostaStatus { string estado = 1; float temperatura = 2; }'),'O arquivo .proto é o contrato: diz qual chamada existe e qual o formato de entrada e de saída. Os números 1 e 2 identificam os campos no formato binário.'],
 null,['api','rest','microsservicos','http'],{tags:'protobuf protocol buffers google rpc http2'}),

E('websocket','WebSocket','Uma conexão aberta nos dois sentidos',2,
 'O **WebSocket** abre uma conexão que fica **aberta nos dois sentidos**. No HTTP comum, o cliente pergunta e o servidor responde, e acabou. Com WebSocket, o servidor também pode enviar dados quando quiser, sem ninguém pedir. É assim que chats, jogos online, cotações da bolsa e painéis ao vivo recebem atualização na hora.',
 'O HTTP é **mandar um bilhete e esperar a resposta**. O WebSocket é uma **ligação de rádio aberta**: os dois lados falam quando quiserem, sem precisar discar de novo.',
 ['Chats e notificações em tempo real','Jogos multiplayer e edição colaborativa','Painéis ao vivo com dados de sensores e cotações'],
 ['javascript',L('const ws = new WebSocket("wss://exemplo.com/painel");','','ws.onopen = () => ws.send("quero receber a temperatura");','','ws.onmessage = (evento) => {','  console.log("Chegou:", evento.data);   // o servidor manda quando quiser','};'),'O wss é o WebSocket com criptografia, como o https. O onmessage dispara a cada mensagem que o servidor empurrar.'],
 'websocket',['http','tcp','webhook','mqtt','tempo-real'],{alt:'Server-Sent Events (só do servidor para o cliente), polling (perguntar de tempos em tempos)',tags:'ws socket tempo real chat'}),

E('webhook','Webhook','A API ao contrário: o outro sistema avisa você',2,
 'Um **webhook** é uma API ao contrário. Em vez de você ficar perguntando se já aconteceu, o outro sistema **avisa você**, chamando um endereço seu quando o evento acontece. Pagamento aprovado, código enviado, mensagem recebida: o serviço faz um POST para o endereço que você cadastrou, com os detalhes do evento.',
 'Em vez de ligar toda hora para a transportadora perguntando se a peça chegou, o que se chama **polling**, você deixa o seu número e ela liga quando a peça chegar.',
 ['Receber o aviso de pagamento aprovado','Disparar um deploy quando alguém envia código ao GitHub','Integrar sistemas sem consultar de segundos em segundos'],
 ['javascript',L('app.post("/webhook/pagamento", (req, res) => {','  const evento = req.body;                    // o serviço manda o JSON aqui','  if (evento.tipo === "pagamento.aprovado") {','    liberarPedido(evento.pedidoId);','  }','  res.sendStatus(200);                        // confirma o recebimento','});'),'O serviço externo faz um POST nesse endereço. Responda 200 rápido, senão ele acha que falhou e tenta de novo. Em produção, confira também a assinatura do aviso, para saber que veio mesmo de quem diz.'],
 'webhook',['api','http','websocket','filas','cicd'],{tags:'callback evento notificacao integracao polling'}),

E('node','Node.js','JavaScript fora do navegador',1,
 'O **Node.js** é um ambiente que roda **JavaScript fora do navegador**, direto no computador ou no servidor. Foi criado em 2009 por Ryan Dahl, usando o motor V8 do Chrome. Com ele, o JavaScript passou a servir para back-end, ferramentas de linha de comando e automação. Vem com o **npm**, o gerenciador de pacotes que dá acesso a milhões de bibliotecas.',
 'O navegador é uma **oficina fechada**, onde o JavaScript só podia mexer nas coisas da página. O Node é o **mesmo mecânico levado para o galpão inteiro**: agora ele pode mexer em arquivos, redes e bancos de dados.',
 ['Criar APIs e servidores web','Rodar as ferramentas de front-end, como Vite, Webpack e ESLint','Fazer scripts de automação e ferramentas de linha de comando','Usar uma linguagem só, o JavaScript, no sistema inteiro'],
 ['javascript',L('// lerarquivo.js - rode com: node lerarquivo.js','const fs = require("fs");','','const texto = fs.readFileSync("producao.txt", "utf8");','console.log("O arquivo tem " + texto.split("\\n").length + " linhas");'),'O módulo fs lê arquivos do computador, algo que o JavaScript do navegador não pode fazer. Para instalar o Node, baixe em nodejs.org.'],
 null,['js','express','pacotes','eventloop','deno-bun','bundler'],{tags:'nodejs node js npm v8 servidor javascript',also:['lang']}),

E('express','Express','O framework mínimo do Node.js',1,
 'O **Express** é o framework mínimo mais popular do Node.js. Ele pega o trabalho repetitivo de um servidor, como rotas, leitura de pedidos, respostas e middlewares, e deixa tudo em poucas linhas. Não impõe estrutura: você escolhe o banco e as bibliotecas. É um ótimo primeiro back-end para quem já sabe JavaScript.',
 'É um **kit de ferramentas básicas** de bancada: chave, alicate e fita. Não vem com a oficina montada, mas deixa você montar a sua do seu jeito.',
 ['Criar uma API em poucos minutos','Aprender como o back-end funciona: rotas, requisições e respostas','Servir de base para vários outros frameworks do ecossistema Node'],
 ['javascript',L('const express = require("express");','const app = express();','app.use(express.json());                // entende JSON no corpo do pedido','','app.get("/maquinas/:id", (req, res) => {','  res.json({ id: req.params.id, estado: "ligada" });','});','','app.listen(3000, () => console.log("Rodando na porta 3000"));'),'O app.get cria uma rota: quando alguém pedir /maquinas/7, a função devolve um JSON. O :id é um pedaço variável do endereço. Para instalar: npm install express'],
 null,['node','middleware','rest','nestjs','crud'],{tags:'expressjs node framework rotas'}),

E('nestjs','NestJS','Node.js organizado, em TypeScript',2,
 'O **NestJS** é um framework para Node.js em TypeScript que traz uma **estrutura pronta e organizada**: módulos, controladores e serviços, no estilo do Angular e do Spring. Onde o Express deixa tudo livre, o Nest impõe um padrão. Isso ajuda muito em projetos grandes e em equipes.',
 'Enquanto o Express é a caixa de ferramentas, o Nest é a **linha de montagem já desenhada**, com postos, procedimentos e fichas de inspeção. Demora mais para aprender, mas todo mundo trabalha do mesmo jeito.',
 ['APIs corporativas grandes, com muitos módulos','Equipes que precisam de padrão e de testes fáceis','Aplicações com TypeScript do começo ao fim'],
 ['typescript',L('@Controller("maquinas")','export class MaquinasController {','  constructor(private readonly servico: MaquinasService) {}','','  @Get(":id")','  buscar(@Param("id") id: string) {','    return this.servico.buscar(id);','  }','}'),'Os @ são decoradores: etiquetas que dizem esta classe é um controlador e este método responde ao GET. O serviço chega pronto, entregue pelo próprio framework.'],
 null,['express','typescript','angular','injecao-dependencia','mvc'],{tags:'nest typescript framework decorators'}),

E('deno-bun','Deno e Bun','Concorrentes modernos do Node.js',2,
 '**Deno** e **Bun** são outros ambientes para rodar JavaScript e TypeScript fora do navegador, como o Node. O Deno, do mesmo criador do Node, roda TypeScript direto e é seguro por padrão: o programa precisa de permissão para acessar arquivos e rede. O Bun aposta em velocidade e já traz junto o gerenciador de pacotes, o empacotador e o executor de testes.',
 'Se o Node é a **furadeira de coluna** que todo mundo conhece, Deno e Bun são os **modelos novos**: alguns recursos já vêm montados e a velocidade é maior. O Node continua tendo mais peças de reposição e mais gente que sabe operar.',
 ['Projetos novos que querem TypeScript sem configuração','Scripts rápidos e ferramentas de linha de comando','Reduzir a quantidade de ferramentas separadas no projeto'],
 ['bash',L('# Deno: roda TypeScript direto e pede permissão de rede','deno run --allow-net servidor.ts','','# Bun: instala pacotes e roda arquivos','bun install','bun run servidor.ts'),'O --allow-net é o Deno pedindo licença para usar a rede. O Bun faz o papel do npm e do node juntos.'],
 null,['node','typescript','pacotes'],{alt:'Node.js continua sendo a opção mais usada e com mais vagas',tags:'deno bun runtime javascript typescript'}),

E('django','Django','Python com tudo incluído',2,
 'O **Django** é o framework de baterias incluídas do Python. Já vem com painel de administração automático, sistema de login, ORM para o banco de dados, formulários, proteção contra ataques comuns e muito mais. Segue um padrão parecido com o MVC. É ótimo para criar sistemas completos rápido, como portais, intranets e sistemas de cadastro.',
 'É a **máquina completa de fábrica**, com painel, proteções e manual: você liga e já trabalha. Perde um pouco em liberdade, mas ganha em segurança e rapidez de entrega.',
 ['Sistemas web completos, com login, cadastros e relatórios','Painel administrativo pronto, que economiza semanas','Projetos que precisam de segurança e organização desde o início'],
 ['python',L('# models.py - a tabela vira uma classe','from django.db import models','','class Maquina(models.Model):','    nome = models.CharField(max_length=80)','    horas = models.IntegerField(default=0)','','# views.py - devolve a lista em JSON','from django.http import JsonResponse','','def lista(request):','    dados = list(Maquina.objects.values("nome", "horas"))','    return JsonResponse(dados, safe=False)'),'A classe Maquina vira uma tabela no banco. Registrando o modelo no admin, o Django cria sozinho as telas de cadastro dele.'],
 null,['python','orm','mvc','flask','fastapi','auth'],{tags:'python framework web admin orm'}),

E('flask','Flask','Python pequeno e simples para servidores',1,
 'O **Flask** é um micro-framework do Python: pequeno, simples e flexível. Com poucas linhas você tem um servidor com rotas. Não traz banco, login nem painel; você adiciona o que precisar por extensões. É muito usado em APIs pequenas, protótipos e para colocar um modelo de inteligência artificial na web.',
 'É o **torno de bancada**: simples, enxuto e fácil de aprender. Para uma peça única funciona bem; para uma linha de produção, você vai precisar acoplar muita coisa.',
 ['APIs pequenas e protótipos rápidos','Colocar um modelo de IA ou um script Python na web','Aprender back-end sem muita cerimônia'],
 ['python',L('from flask import Flask, jsonify','','app = Flask(__name__)','','@app.get("/maquinas/<int:id>")','def maquina(id):','    return jsonify(id=id, estado="ligada")','','# rodar com: flask run'),'O @app.get liga a função ao endereço. O <int:id> pega um número do endereço e entrega como parâmetro.'],
 null,['python','django','fastapi','rest'],{tags:'python microframework web'}),

E('fastapi','FastAPI','APIs Python modernas, rápidas e documentadas sozinhas',2,
 'O **FastAPI** é um framework Python moderno para APIs. Usa as dicas de tipo do Python para validar os dados automaticamente e gerar **documentação interativa** da API sem esforço. É rápido, aceita código assíncrono e virou escolha comum para APIs de dados e de inteligência artificial.',
 'É o **torno CNC com a ficha de verificação embutida**: você declara a medida esperada e a máquina recusa a peça fora da tolerância antes de usinar, e ainda imprime o relatório.',
 ['APIs modernas com validação automática','Documentação pronta, para testar no navegador','Servir modelos de IA e serviços de dados'],
 ['python',L('from fastapi import FastAPI','from pydantic import BaseModel','','app = FastAPI()','','class Leitura(BaseModel):','    maquina: str','    temperatura: float','','@app.post("/leituras")','def receber(l: Leitura):','    return {"ok": True, "alarme": l.temperatura > 90}','','# rodar com: uvicorn arquivo:app --reload   (docs em /docs)'),'O tipo Leitura é validado sozinho: se chegar texto no lugar da temperatura, o FastAPI responde erro 422 explicando o problema. A página /docs é gerada automaticamente.'],
 null,['python','flask','openapi','validacao','api'],{tags:'python pydantic uvicorn api async'}),

E('spring','Spring Boot','O gigante do back-end em Java',3,
 'O **Spring Boot** é o framework de back-end mais usado no mundo Java. Entrega servidor embutido, configuração automática, acesso a bancos, segurança e integração com praticamente tudo. É a base de muito sistema bancário e corporativo. Tem uma curva de aprendizado grande, mas resolve problemas grandes com padrões consolidados.',
 'É a **linha de produção pesada de um grande fabricante**: cara de montar e cheia de manuais, mas projetada para produzir em escala por décadas, com auditoria e rastreabilidade.',
 ['Sistemas corporativos e bancários','Microsserviços em Java ou Kotlin','Empresas que valorizam estabilidade e padrão consolidado'],
 ['java',L('@RestController','@RequestMapping("/maquinas")','public class MaquinaController {','','    @GetMapping("/{id}")','    public Maquina buscar(@PathVariable Long id) {','        return repositorio.findById(id).orElseThrow();','    }','}'),'As anotações com @ dizem ao Spring o que cada coisa é: um controlador REST, um endereço, um parâmetro. O resto ele monta sozinho.'],
 null,['java','kotlin','orm','microsservicos','injecao-dependencia'],{tags:'java framework spring boot enterprise'}),

E('laravel','Laravel','O framework PHP mais popular',2,
 'O **Laravel** é o framework PHP mais popular. Tem sintaxe elegante e vem com rotas, ORM, autenticação, filas, envio de e-mail e um sistema de templates. É muito usado no Brasil para sistemas web, lojas virtuais e APIs.',
 'É o **kit completo de uma oficina moderna** para quem trabalha com PHP: bancadas, gavetas e ferramentas já organizadas no lugar certo.',
 ['Sistemas web e lojas virtuais','APIs com login e permissões prontos','Projetos de PHP que precisam de padrão e organização'],
 ['php',L('// routes/web.php','Route::get("/maquinas/{id}", function ($id) {','    return Maquina::findOrFail($id);   // devolve JSON automaticamente','});'),'A rota liga o endereço à função. O findOrFail busca no banco e, se não achar, responde 404 sozinho.'],
 null,['php','orm','mvc','mysql','auth'],{tags:'php framework eloquent artisan'}),

E('rails','Ruby on Rails','Convenção em vez de configuração',2,
 'O **Ruby on Rails** popularizou a ideia de convenção em vez de configuração: se você seguir os nomes e as pastas esperadas, quase tudo funciona sozinho. Com geradores, cria um cadastro completo em minutos. Foi usado para construir GitHub e Shopify.',
 'É a **linha de montagem com padronização total**: se todo mundo usa os mesmos encaixes, a peça entra sem ajuste e o produto sai rápido.',
 ['Criar produtos web depressa, com pouca gente','Protótipos que viram sistemas reais','Aprender boas práticas de organização de código'],
 ['bash',L('rails new loja','cd loja','rails generate scaffold Produto nome:string preco:decimal','rails db:migrate','rails server'),'Esses comandos criam um sistema completo de cadastro de produtos, com telas, rotas e tabela no banco.'],
 null,['ruby','mvc','orm'],{tags:'ruby framework convencao dhh'}),

E('dotnet','.NET e ASP.NET Core','A plataforma da Microsoft para back-end',2,
 'O **.NET** é a plataforma da Microsoft para criar aplicações com C# e outras linguagens. O **ASP.NET Core** é a parte para back-end e APIs web: rápido, multiplataforma, funciona em Windows, Linux e Mac, e é de código aberto. É muito usado em empresas que já têm ambiente Microsoft, com Azure e SQL Server.',
 'É o **conjunto de máquinas e ferramentas de um fabricante só**, todas projetadas para encaixar entre si. Se a fábrica já é toda dessa marca, a integração é natural e o suporte é forte.',
 ['APIs e sistemas corporativos','Integração com Azure, SQL Server e Active Directory','Aplicações desktop e jogos com Unity, usando C#'],
 ['csharp',L('var app = WebApplication.CreateBuilder(args).Build();','','app.MapGet("/maquinas/{id}", (int id) => new { id, estado = "ligada" });','','app.Run();'),'Em poucas linhas, o servidor responde um JSON no endereço /maquinas/7. Esse estilo mínimo é novidade das versões recentes do .NET.'],
 null,['csharp','azure','sql','orm'],{tags:'dotnet aspnet csharp microsoft',also:['lang']}),

E('auth','Autenticação e autorização','Quem é você, e o que você pode fazer',1,
 '**Autenticação** é provar **quem você é**: login com senha, digital, código no celular. **Autorização** é definir **o que você pode fazer** depois de entrar: ver, editar, apagar, ser administrador. São duas etapas diferentes e é comum confundir. O sistema precisa das duas: saber quem entrou e conferir a permissão a cada ação.',
 'A **catraca da fábrica** confere o seu crachá: quem é você, isso é autenticação. Depois, cada porta interna só abre se o crachá tiver a permissão, isso é autorização. O almoxarife não entra na sala do CLP.',
 ['Proteger áreas e dados restritos','Cadastrar perfis, como usuário, gerente e administrador','Registrar quem fez o quê, para auditoria','Reduzir risco com senha forte, segundo fator e senhas guardadas só como hash'],
 ['javascript',L('// 1) autenticação: quem é você?','app.post("/login", async (req, res) => {','  const user = await buscarUsuario(req.body.email);','  const ok = user && await bcrypt.compare(req.body.senha, user.senhaHash);','  if (!ok) return res.status(401).json({ erro: "credenciais inválidas" });','  res.json({ token: gerarToken(user) });','});','','// 2) autorização: pode fazer isso?','function soAdmin(req, res, next) {','  if (req.user.papel !== "admin") return res.sendStatus(403);','  next();','}'),'O erro 401 quer dizer não autenticado, não sei quem é você. O 403 quer dizer autenticado, mas sem permissão. A senha nunca é guardada em texto: só o hash, gerado por um algoritmo próprio como o bcrypt.'],
 null,['sessao','jwt','oauth','mfa','hash-senha','middleware'],{tags:'login senha permissao rbac 401 403 autenticacao autorizacao',also:['seg']}),

E('sessao','Sessões e cookies','Como o site lembra que você está logado',2,
 'O HTTP não lembra de você de um pedido para o outro. Para o site saber que você continua logado, existem os **cookies**, pequenos textos que o navegador guarda e devolve a cada pedido, e as **sessões**, que são dados do usuário guardados no servidor e ligados a um identificador que vai dentro do cookie. É o jeito clássico de manter o login.',
 'O cookie é a **etiqueta de identificação presa no jaleco**. A cada setor, você mostra a etiqueta e o segurança consulta a lista no computador dele, a sessão, para saber quem você é.',
 ['Manter o usuário logado','Guardar carrinho de compras e preferências','Entender os avisos de cookies e as flags HttpOnly e Secure'],
 ['http',L('# O servidor responde ao login com:','Set-Cookie: sessao=a8f3c1e9; HttpOnly; Secure; SameSite=Lax','','# E o navegador envia em todo pedido seguinte:','Cookie: sessao=a8f3c1e9'),'O HttpOnly impede que o JavaScript da página leia o cookie, o que protege contra roubo por XSS. O Secure só deixa viajar por HTTPS. O SameSite reduz ataques de CSRF.'],
 null,['auth','jwt','http','storage','xss','csrf'],{tags:'cookie session login estado'}),

E('jwt','JWT','Crachá digital assinado',2,
 'O **JWT** (JSON Web Token) é um **token** em texto com três partes separadas por pontos: cabeçalho, conteúdo e **assinatura**. O servidor assina; depois consegue confirmar que o token é dele e não foi alterado, sem guardar sessão. Atenção: o conteúdo é só **codificado**, não é secreto. Qualquer um consegue ler. Nunca coloque senha nem dado sensível dentro.',
 'É um **crachá com holograma**. As informações estão visíveis na frente: nome, setor, validade. O holograma só a fábrica sabe fazer. Se alguém adulterar o crachá, o holograma não bate.',
 ['Login em APIs sem manter sessão no servidor','Passar a identidade entre vários serviços','Entender o que o app guarda quando você faz login'],
 ['javascript',L('const jwt = require("jsonwebtoken");','','// no login: cria o token, válido por 1 hora','const token = jwt.sign({ sub: "42", papel: "admin" }, SEGREDO, { expiresIn: "1h" });','','// em cada pedido seguinte:','const dados = jwt.verify(token, SEGREDO);   // erro se alterado ou vencido'),'O sign cria e assina. O verify confere a assinatura e a validade. O SEGREDO fica só no servidor, nunca no front-end.'],
 'jwt',['auth','sessao','base64','hash','oauth','cripto'],{tags:'json web token bearer assinatura'}),

E('oauth','OAuth e login social','Autorizar sem entregar a senha',2,
 'O **OAuth 2.0** permite que um app acesse seus dados em outro serviço **sem você entregar a sua senha** a ele. É o que acontece no entrar com Google: você é levado ao Google, aprova o acesso, e o app recebe um **token** limitado e temporário. Para saber quem você é, usa-se por cima o **OpenID Connect**.',
 'É **autorizar o vizinho a pegar a encomenda na portaria por você**. Você não entrega a chave do apartamento, só uma autorização limitada que a portaria reconhece. E pode cancelar quando quiser.',
 ['Login com Google, GitHub e Microsoft','Permitir que um app leia a sua agenda ou os seus arquivos sem ver a sua senha','Integrações entre serviços com permissões limitadas, chamadas de escopos'],
 ['http',L('# 1) o app manda você para o Google, dizendo o que quer acessar','https://accounts.google.com/o/oauth2/v2/auth','  ?client_id=MEU_APP','  &redirect_uri=https://meusite.com/volta','  &scope=email profile','  &response_type=code','','# 2) você aprova; o Google devolve um código ao seu site','# 3) o servidor troca o código por um token, sem passar pelo navegador'),'O código volta pelo navegador, mas a troca pelo token é feita de servidor para servidor, onde a chave secreta do app está protegida.'],
 'oauth',['auth','jwt','http','api','cors'],{tags:'login google social openid connect token escopo',also:['seg']}),

E('cors','CORS','Por que o navegador bloqueia chamadas entre sites',2,
 '**CORS** é uma regra do **navegador**: uma página de um site só pode ler respostas de outro site se esse outro site permitir explicitamente. O servidor autoriza enviando cabeçalhos como Access-Control-Allow-Origin. Se não autorizar, o navegador bloqueia a leitura e mostra aquele erro vermelho no console. O servidor até recebeu o pedido; quem barra a resposta é o navegador.',
 'É a **portaria do prédio vizinho**: o morador do seu prédio até pode bater lá, mas só entra se o porteiro de lá tiver o nome dele na lista de visitantes autorizados.',
 ['Entender o erro mais famoso do front-end, o blocked by CORS policy','Liberar o seu front-end para chamar a sua API','Proteger o usuário de sites maliciosos que tentam usar a sessão dele'],
 ['javascript',L('// no servidor Express: libera só o site conhecido','const cors = require("cors");','','app.use(cors({ origin: "https://meusite.com" }));'),'Sem isso, o navegador bloqueia o fetch de meusite.com para a API. Evite origin com asterisco em API que usa login. Note que o CORS não protege o servidor: um programa fora do navegador ignora essa regra.'],
 'cors',['http','fetch','api','express','csrf'],{tags:'cross origin resource sharing blocked erro console'}),

E('middleware','Middleware','Etapas no caminho entre o pedido e a resposta',2,
 '**Middleware** é um passo no meio do caminho entre o pedido chegar e a resposta sair. Cada middleware faz uma tarefa, como registrar o log, conferir o login, ler o JSON ou limitar acessos, e passa o pedido para o próximo. Se algo estiver errado, ele pode interromper e responder na hora.',
 'São os **postos de inspeção ao longo da esteira**: a peça passa pelo posto de medição, depois pelo de pintura, depois pelo de embalagem. Qualquer posto pode reprovar e tirar a peça da linha.',
 ['Autenticação e permissões em um lugar só','Registrar logs de todos os pedidos','Validar dados, limitar acessos e tratar erros de forma central'],
 ['javascript',L('function registrar(req, res, next) {','  console.log(new Date().toISOString(), req.method, req.url);','  next();                                       // passa para o próximo passo','}','','function exigirLogin(req, res, next) {','  if (!req.headers.authorization) return res.sendStatus(401);   // barra aqui','  next();','}','','app.use(registrar);','app.get("/relatorio", exigirLogin, (req, res) => res.json({ ok: true }));'),'Os pedidos passam pelo registrar em todas as rotas. Só a rota /relatorio passa também pelo exigirLogin. Sem chamar o next, a corrente para.'],
 null,['express','auth','rate-limit','mvc','validacao'],{tags:'pipeline next interceptor filtro'}),

E('mvc','MVC','Dividir o sistema em dados, tela e controle',2,
 'O **MVC**, sigla de Model, View e Controller, divide o sistema em três papéis. O **Model** cuida dos dados e das regras. A **View** mostra a informação ao usuário. O **Controller** recebe o pedido, chama o model e escolhe qual view mostrar. Separar assim facilita mexer numa parte sem quebrar as outras. Rails, Laravel e Spring usam o MVC, e o Django usa uma variação.',
 'É **almoxarifado, vitrine e atendente**. O model é o estoque, onde estão os dados. A view é a vitrine, o que o cliente enxerga. O controller é o atendente: recebe o pedido, vai ao estoque e monta a vitrine.',
 ['Organizar projetos grandes em pastas com responsabilidade clara','Entender a estrutura de frameworks como Rails, Laravel e Spring','Permitir que cada parte seja testada separadamente'],
 ['estrutura',L('app/','├── models/        ← dados e regras (Maquina, Pedido)','├── views/         ← telas e templates (lista.html)','└── controllers/   ← recebe o pedido, chama o model, escolhe a view'),'O fluxo é sempre o mesmo: pedido, controller, model, volta ao controller, view, resposta.'],
 'mvc',['orm','django','rails','laravel','spring','padroes'],{tags:'model view controller arquitetura padrao mvvm'}),

E('orm','ORM','Mexer no banco usando objetos em vez de SQL',2,
 'O **ORM** (Object-Relational Mapping) é uma camada que deixa você mexer no banco de dados usando **objetos da linguagem**, em vez de escrever SQL na mão. Você cria uma classe Maquina e o ORM cuida da tabela, dos inserts e dos selects. Exemplos: Prisma e TypeORM no JavaScript, SQLAlchemy no Python, Hibernate no Java, Eloquent no Laravel. Cuidado: sem entender o SQL que ele gera por baixo, é fácil criar consultas lentas, como o famoso problema N+1.',
 'É o **intérprete entre dois mecânicos** que falam línguas diferentes. Facilita a conversa, mas se você não entende nada de nenhuma das línguas, não percebe quando ele traduz errado, ou pede cem peças uma de cada vez.',
 ['Escrever menos SQL repetitivo','Trocar de banco com menos retrabalho','Manter o esquema do banco versionado junto com o código, nas migrações'],
 ['javascript',L('// Prisma - sem escrever SQL','const maquina = await prisma.maquina.create({','  data: { nome: "Prensa 01", horas: 0 },','});','','const ativas = await prisma.maquina.findMany({','  where: { ativa: true },','  orderBy: { horas: "desc" },','});'),'O create vira um INSERT e o findMany vira um SELECT com WHERE e ORDER BY. Vale conferir o SQL que o ORM gera nos logs.'],
 null,['sql','banco-relacional','mvc','crud','django','spring'],{tags:'prisma sequelize typeorm sqlalchemy hibernate eloquent n+1 migracao',also:['dados']}),

E('filas','Filas e mensageria','Deixar a tarefa na fila e seguir a vida',2,
 'Uma **fila de mensagens** é um intermediário que guarda tarefas ou eventos até alguém estar pronto para processar. Quem envia coloca na fila e segue a vida. Do outro lado, um ou mais **trabalhadores** puxam e processam no seu ritmo. Se o trabalhador cair, a mensagem continua na fila. Exemplos: RabbitMQ, Amazon SQS, Redis com BullMQ e, para fluxos enormes de eventos, o Kafka.',
 'É a **caixa de ordens de serviço** na entrada da oficina: o cliente deixa o pedido e vai embora. Os mecânicos pegam a próxima ordem quando ficam livres. Se chegar uma enxurrada, a fila absorve e ninguém perde nada.',
 ['Tarefas demoradas, como gerar relatório, enviar e-mail e processar vídeo','Aguentar picos de acesso sem derrubar o sistema','Desacoplar serviços: quem envia não espera quem processa','Reenviar automaticamente quando algo falha'],
 ['javascript',L('// produtor: coloca a tarefa na fila e responde logo','await filaEmails.add("boas-vindas", { para: "ana@exemplo.com" });','','// trabalhador: processa em segundo plano','new Worker("emails", async (job) => {','  await enviarEmail(job.data.para);','});'),'O site não fica esperando o e-mail ser enviado. O trabalhador roda em outro processo e, se falhar, a tarefa pode ser repetida.'],
 'filas',['microsservicos','smtp','cron','cache','mqtt'],{tags:'rabbitmq kafka sqs bullmq mensageria queue worker assincrono'}),

E('cache','Cache','Guardar a resposta pronta para ser mais rápido',2,
 '**Cache** é guardar o resultado de algo caro, como uma consulta lenta, uma conta pesada ou uma imagem, para responder rápido da próxima vez. Pode ficar no navegador, na CDN, no servidor ou em um serviço dedicado de memória, como o **Redis**. O desafio clássico é saber **quando jogar o cache fora**, para não mostrar dado velho.',
 'É a **bancada de peças de uso frequente**, ao lado da máquina, em vez de ir ao almoxarifado central toda vez. Rápido, mas se a especificação da peça mudar lá no almoxarifado, a da bancada fica desatualizada.',
 ['Deixar sites e APIs muito mais rápidos','Reduzir a carga no banco de dados','Economizar dinheiro com menos processamento e menos tráfego'],
 ['javascript',L('async function buscarProduto(id) {','  const guardado = await redis.get("produto:" + id);','  if (guardado) return JSON.parse(guardado);        // acerto: rápido','','  const produto = await banco.buscarProduto(id);     // erro: vai ao banco (lento)','  await redis.set("produto:" + id, JSON.stringify(produto), { EX: 60 });','  return produto;                                    // vale por 60 segundos','}'),'Primeiro olha no cache. Se achou, devolve. Se não, busca no banco e guarda por 60 segundos. Esse tempo de validade (EX) é a forma mais simples de evitar dado velho.'],
 'cache',['redis','cdn','banco-dados','http'],{tags:'redis memcached ttl invalidacao hit miss'}),

E('microsservicos','Microsserviços','Vários serviços pequenos no lugar de um sistema grande',3,
 '**Microsserviços** dividem o sistema em vários serviços pequenos, cada um com uma função, como pagamentos, estoque ou notificações. Cada um tem seu próprio código e conversa com os outros por API ou fila. Podem ser atualizados e escalados separadamente. Em troca, a complexidade vai para a rede: há mais coisas para monitorar, mais pontos de falha, e fica difícil manter os dados consistentes. Para equipes pequenas, costuma ser exagero.',
 'É trocar uma **fábrica única** por várias **células de produção independentes**, cada uma com seu líder. Se uma pára, as outras seguem. Mas agora você precisa de transporte, comunicação e coordenação entre as células, e isso dá trabalho.',
 ['Sistemas muito grandes, com várias equipes','Escalar só a parte do sistema que está sobrecarregada','Usar tecnologias diferentes em partes diferentes'],
 ['yaml',L('# docker-compose.yml - três serviços independentes','services:','  pagamentos:','    build: ./pagamentos','  estoque:','    build: ./estoque','  notificacoes:','    build: ./notificacoes'),'Cada serviço tem a sua pasta, o seu código e o seu container. Eles se comunicam por API ou por fila.'],
 null,['monolito','api','filas','docker','kubernetes','gateway'],{tags:'microservices servicos arquitetura distribuido'}),

E('monolito','Monólito','Tudo num programa só, e está tudo bem',2,
 'Um **monólito** é uma aplicação em que tudo, telas, regras e acesso a dados, faz parte de um único programa publicado junto. É simples de desenvolver, testar e colocar no ar, e é o ponto de partida certo para a maioria dos projetos. Só vale dividir em microsserviços quando o tamanho da equipe ou do sistema realmente exigir. Um monólito bem organizado, o chamado monólito modular, leva muito longe.',
 'É **uma máquina multifuncional única**: um equipamento, uma manutenção, uma instalação. Enquanto a demanda for razoável, sai mais barata e simples que uma célula inteira de máquinas separadas.',
 ['Começar um projeto sem complicar','Equipes pequenas que precisam entregar rápido','Ter um só lugar para depurar, testar e publicar'],
 ['estrutura',L('loja/                     ← UM programa, UM deploy','├── pedidos/              ← módulo de pedidos','├── estoque/              ← módulo de estoque','├── pagamentos/           ← módulo de pagamentos','└── usuarios/             ← módulo de usuários'),'Tudo roda junto e os módulos conversam por chamadas de função, sem rede no meio. Se os módulos forem bem separados, dá para extrair um deles depois, caso seja preciso.'],
 null,['microsservicos','mvc','framework'],{tags:'monolitico arquitetura simples modular'}),

E('serverless','Serverless','Executar funções sem cuidar de servidor',2,
 '**Serverless**, que quer dizer sem servidor, não significa que o servidor não existe: significa que **você não gerencia nenhum**. Você sobe uma função, a nuvem executa quando alguém a chama e cobra só pelo tempo de execução. Se ninguém usa, custa zero. Se chegam mil pedidos juntos, escala sozinha. Exemplos: AWS Lambda, Vercel Functions, Cloudflare Workers. Limites: tempo máximo de execução, início a frio e dependência do fornecedor.',
 'É **alugar uma máquina por hora de uso** em vez de comprar. Liga só quando há serviço, e você paga só pelas horas trabalhadas. Ótimo para demanda irregular, ruim se a máquina fica ocupada o dia inteiro.',
 ['APIs e tarefas com uso irregular','Processar um arquivo quando ele chega, como redimensionar imagem','Protótipos baratos, que custam zero enquanto ninguém usa'],
 ['javascript',L('// AWS Lambda - roda só quando chamada','export const handler = async (evento) => {','  const nome = evento.queryStringParameters?.nome ?? "mundo";','  return { statusCode: 200, body: JSON.stringify({ msg: "Olá, " + nome }) };','};'),'Você escreve só a função. A nuvem cuida do servidor, da escala e da disponibilidade.'],
 null,['cloud','aws','vercel','baas','microsservicos'],{tags:'lambda functions faas cold start edge'}),

E('baas','BaaS: Firebase e Supabase','Back-end pronto, alugado como serviço',1,
 '**BaaS**, ou Backend as a Service, é um back-end pronto oferecido como serviço: banco de dados, login, armazenamento de arquivos e funções na nuvem, tudo configurado por um painel e acessado por uma biblioteca. Os mais conhecidos são o **Firebase**, do Google, e o **Supabase**, alternativa de código aberto baseada em PostgreSQL. Você ganha velocidade. Em troca, depende do fornecedor e pode pagar caro quando o projeto cresce.',
 'É **alugar a cozinha industrial já montada**, em vez de construir a sua. Você chega com a receita, o seu app, e já tem fogão, geladeira e equipe de limpeza. Rápido de começar, mas as regras da cozinha são do dono.',
 ['Criar um app completo sem escrever um back-end','Protótipos e projetos pequenos','Login, banco e arquivos em poucas horas'],
 ['javascript',L('import { createClient } from "@supabase/supabase-js";','const supabase = createClient(URL_DO_PROJETO, CHAVE_PUBLICA);','','// lê direto do banco, sem escrever back-end','const { data } = await supabase.from("maquinas").select("nome, horas").order("horas");'),'A chave pública pode ficar no front-end, porque o acesso é protegido por regras configuradas no próprio banco. A chave de serviço, a secreta, nunca vai para o front-end.'],
 null,['firebase','supabase','serverless','auth','postgres'],{tags:'firebase supabase backend as a service appwrite google'}),

E('cms','CMS','Sites com conteúdo editável por qualquer pessoa',1,
 'Um **CMS**, ou sistema de gerenciamento de conteúdo, permite que pessoas sem conhecimento de programação criem e editem o conteúdo de um site por um painel. O mais famoso é o **WordPress**, que move boa parte dos sites do mundo. Os **headless CMS**, como Strapi, Contentful e Sanity, só cuidam do conteúdo e o entregam por API, para qualquer front-end usar.',
 'É uma **placa de aviso com letras trocáveis**: a estrutura da placa já está pronta, e qualquer pessoa troca o texto sem chamar o serralheiro.',
 ['Blogs, sites institucionais e lojas virtuais','Equipes de marketing editando conteúdo sem depender de programador','Entregar o mesmo conteúdo para site e aplicativo, com o headless'],
 ['javascript',L('// Headless CMS: o conteúdo editado no painel chega ao site como JSON','const r = await fetch("https://cms.exemplo.com/api/artigos");','const artigos = await r.json();','artigos.forEach((a) => console.log(a.titulo));'),'O formato exato da resposta depende do CMS, mas a ideia é a mesma: quem edita usa o painel, e o seu site só consome a API.'],
 null,['php','api','astro','seo'],{tags:'wordpress strapi contentful sanity headless conteudo',also:['front']}),

E('crud','CRUD','As quatro operações básicas de qualquer sistema com dados',1,
 '**CRUD** são as quatro operações básicas de quase todo sistema com dados: **Create**, criar; **Read**, ler; **Update**, atualizar; e **Delete**, apagar. Cadastro de clientes, lista de tarefas, controle de estoque: tudo isso é CRUD. Quem sabe fazer um CRUD completo, com tela, API e banco, já domina o esqueleto de boa parte dos sistemas comerciais.',
 'É o **livro de registro da portaria**: anotar uma entrada, consultar quem entrou, corrigir um horário e riscar uma linha errada.',
 ['Entender como a maioria dos sistemas funciona por dentro','Primeiro projeto prático de quem está aprendendo back-end','Ligar ações da tela a comandos do banco de dados'],
 ['sql',L("INSERT INTO maquinas (nome, horas) VALUES ('Prensa 01', 0);   -- Create","SELECT * FROM maquinas WHERE nome = 'Prensa 01';              -- Read","UPDATE maquinas SET horas = 8 WHERE nome = 'Prensa 01';       -- Update","DELETE FROM maquinas WHERE nome = 'Prensa 01';                -- Delete"),'Cada operação do CRUD corresponde a um comando SQL. Na API REST, correspondem a POST, GET, PUT ou PATCH e DELETE.'],
 'crud',['rest','sql','http','orm','banco-relacional'],{tags:'create read update delete cadastro operacoes'}),

E('cron','Tarefas agendadas (cron)','Rodar um script sozinho em horário marcado',2,
 'O **cron** é o agendador do Linux: executa um comando ou script em horários definidos, sem ninguém apertar nada. Você escreve uma expressão de cinco campos, que são minuto, hora, dia do mês, mês e dia da semana, e depois o comando. Backups noturnos, relatórios, limpezas e sincronizações são o uso típico. Na nuvem existem equivalentes, como GitHub Actions agendadas e o Cloud Scheduler.',
 'É o **temporizador da máquina**: você programa toda segunda às seis da manhã faz a lubrificação automática, e a máquina executa sozinha, mesmo sem ninguém por perto.',
 ['Backup automático todas as noites','Gerar e enviar relatórios periódicos','Limpar arquivos antigos e sincronizar dados'],
 ['bash',L('# minuto hora dia-do-mês mês dia-da-semana  comando','0 2 * * *      /home/app/backup.sh      # todo dia às 02:00','*/15 * * * *   /home/app/coletar.sh     # a cada 15 minutos','0 8 * * 1      /home/app/relatorio.sh   # segundas às 08:00'),'O asterisco quer dizer qualquer valor. Para editar a sua tabela de tarefas: crontab -e. No último campo, 0 é domingo e 1 é segunda-feira.'],
 null,['bash','linux','cicd','filas','automacao'],{tags:'crontab agendador schedule rotina automatica',also:['ops']}),

E('rate-limit','Rate limiting','Limitar quantos pedidos cada cliente pode fazer',2,
 '**Rate limiting** é limitar quantos pedidos um mesmo cliente pode fazer em um intervalo de tempo, por exemplo, cem por minuto. Passou do limite, a API responde com o status **429**, Too Many Requests. Protege contra abuso, robôs e tentativas de adivinhar senhas, e evita que um único cliente derrube o serviço para todos.',
 'É o **limite de peças por ordem de serviço**: ninguém monopoliza a máquina. Passou da cota, espera a próxima janela.',
 ['Proteger o login contra tentativas em massa','Evitar que um cliente sobrecarregue a API','Cobrar por plano, com limites diferentes por cliente'],
 ['javascript',L('const rateLimit = require("express-rate-limit");','','app.use("/login", rateLimit({','  windowMs: 15 * 60 * 1000,    // janela de 15 minutos','  limit: 10,                   // 10 tentativas por IP nessa janela','}));'),'Depois de 10 tentativas em 15 minutos, o IP recebe erro 429. Em versões antigas da biblioteca, o campo limit se chamava max.'],
 null,['api','gateway','middleware','ddos','auth'],{tags:'429 throttle limite requisicoes protecao'}),

E('openapi','OpenAPI e Swagger','A ficha técnica oficial de uma API',2,
 'O **OpenAPI** é um formato padrão, um arquivo YAML ou JSON, para **descrever uma API REST**: quais endereços existem, o que cada um recebe e o que devolve. O **Swagger** é o conjunto de ferramentas mais conhecido em volta dele. Gera uma página de documentação interativa, na qual dá para testar cada chamada, e gera código de cliente em várias linguagens automaticamente.',
 'É a **ficha técnica do equipamento**, com todas as entradas, saídas e limites. Qualquer técnico lê e usa a máquina sem precisar abrir o painel nem perguntar ao fabricante.',
 ['Documentar APIs de um jeito que todo mundo entende','Testar chamadas direto no navegador','Gerar código de cliente e testes a partir do contrato'],
 ['yaml',L('openapi: 3.0.3','info: { title: API de Máquinas, version: "1.0" }','paths:','  /maquinas/{id}:','    get:','      summary: Busca uma máquina','      parameters:','        - { name: id, in: path, required: true, schema: { type: integer } }','      responses:','        "200": { description: A máquina encontrada }','        "404": { description: Não existe }'),'Descreve um endereço, o seu parâmetro e as respostas possíveis. Ferramentas como o Swagger UI transformam esse arquivo numa página navegável.'],
 null,['rest','api','fastapi','formatos','postman'],{tags:'swagger documentacao contrato spec api'}),

E('gateway','API Gateway','A portaria única de um conjunto de serviços',3,
 'Um **API Gateway** é a **porta de entrada única** de um conjunto de serviços. Todas as chamadas externas passam por ele, que cuida do que é comum a todos: autenticação, limites de uso, registro de logs, cache e roteamento para o serviço certo. Exemplos: Kong, AWS API Gateway, Azure API Management e o próprio Nginx configurado para isso.',
 'É a **portaria da fábrica**: todo visitante passa pela mesma entrada, apresenta o documento, recebe o crachá e é encaminhado ao setor certo, sem que cada setor precise ter a sua guarita.',
 ['Dar um ponto único de entrada para os microsserviços','Centralizar login, limites e logs','Esconder a estrutura interna dos clientes de fora'],
 ['nginx',L('server {','    listen 443 ssl;','    server_name api.minhaempresa.com;','','    location /pedidos/    { proxy_pass http://servico-pedidos:3000/; }','    location /pagamentos/ { proxy_pass http://servico-pagamentos:3000/; }','    location /usuarios/   { proxy_pass http://servico-usuarios:3000/; }','}'),'Um endereço só, api.minhaempresa.com, e três serviços atrás dele. Um gateway de verdade acrescenta login, limite de uso e logs nessa porta de entrada.'],
 null,['microsservicos','rate-limit','nginx','proxy-reverso','auth'],{tags:'kong nginx entrada unica roteamento'}),

E('variaveis-ambiente','Variáveis de ambiente e segredos','Senhas e chaves fora do código',1,
 'Senhas de banco, chaves de API e endereços que mudam de um ambiente para outro **não devem ficar escritos no código**. Ficam em **variáveis de ambiente**, normalmente lidas de um arquivo chamado ponto env em desenvolvimento e configuradas no painel do servidor em produção. Esse arquivo **nunca** vai para o Git. Se uma chave vazar num repositório público, robôs podem achá-la em minutos.',
 'É o **cofre de chaves da portaria**. O procedimento diz pegue a chave do cofre, sem ter a chave desenhada nele. Trocou o turno, trocou a chave, e o procedimento continua o mesmo.',
 ['Separar desenvolvimento, teste e produção','Evitar vazar senhas e chaves no GitHub','Trocar uma credencial sem alterar o código'],
 ['env',L('# --- arquivo .env (nunca vai para o Git: coloque .env no .gitignore) ---','DATABASE_URL=postgres://usuario:senha@localhost:5432/fabrica','CHAVE_API=abc123','','# --- no código JavaScript ---','# const url = process.env.DATABASE_URL;'),'O código lê o valor pelo nome. Quem tem acesso ao repositório não vê a senha. Se uma chave vazar, troque-a imediatamente: apagar o commit não basta.'],
 null,['git','ambientes','seguranca-basica','cloud','docker'],{tags:'env dotenv segredos secrets chaves credenciais 12 factor',also:['ops','seg']}),

E('validacao','Validação de dados','Nunca confie no que vem de fora',2,
 'Todo dado que chega de fora, seja de formulário, de API ou de arquivo, pode vir errado, vazio, grande demais ou **malicioso**. **Validar** é conferir formato, tipo, tamanho e limites antes de usar. Validar só no front-end não basta, porque o front-end pode ser contornado por qualquer pessoa. A validação que vale é a do servidor. Bibliotecas ajudam: Zod e Joi no JavaScript, Pydantic no Python.',
 'É a **inspeção de recebimento** na doca: confere o lote antes de entrar no estoque. Se a nota fiscal diz cem peças e a caixa tem quarenta, volta para o fornecedor.',
 ['Evitar dados quebrados no banco','Bloquear entradas maliciosas, como injeção de SQL','Dar mensagens de erro claras ao cliente da API'],
 ['javascript',L('import { z } from "zod";','','const Leitura = z.object({','  maquina: z.string().min(1),','  temperatura: z.number().min(-50).max(1000),','});','','const resultado = Leitura.safeParse(req.body);','if (!resultado.success) return res.status(400).json(resultado.error);'),'O schema descreve o formato aceito. Se o pedido não bater, o servidor responde erro 400 antes de tocar no banco.'],
 null,['formularios','sql-injection','fastapi','api','excecoes'],{tags:'sanitizacao zod joi pydantic entrada dados input',also:['seg']}),

E('paginacao','Paginação','Entregar listas grandes em pedaços',2,
 'Quando uma lista tem milhares de itens, a API não manda tudo de uma vez: manda **por páginas**. Duas formas comuns: por **página e deslocamento**, o offset, que é do tipo me dê vinte a partir do quadragésimo; e por **cursor**, do tipo me dê vinte depois deste item. O cursor é mais estável e mais rápido em listas enormes ou que mudam o tempo todo.',
 'É o **carrinho de transporte**: em vez de levar o almoxarifado inteiro até a linha, leva uma caixa por vez. O cursor é o marcador parei na caixa quarenta.',
 ['Telas com rolagem infinita ou botão carregar mais','Não derrubar o servidor com listas gigantes','Fazer buscas em grandes volumes de dados'],
 ['http',L('GET /pedidos?limite=20&pagina=3          # por página','GET /pedidos?limite=20&depois=ped_9f31c   # por cursor'),'No primeiro modelo você pede a página 3. No segundo, você manda o identificador do último item recebido e a API devolve os próximos.'],
 null,['rest','api','sql','crud'],{tags:'offset cursor limit pagina lista'}),

E('idempotencia','Idempotência','Repetir o pedido sem repetir o efeito',3,
 'Uma operação é **idempotente** quando repetir o mesmo pedido várias vezes dá o **mesmo resultado** de fazer uma vez só. Isso importa porque redes falham: o cliente não sabe se o pedido chegou e tenta de novo. Sem cuidado, o cliente poderia ser cobrado duas vezes. APIs de pagamento resolvem com uma **chave de idempotência**: um identificador do pedido, enviado junto, que o servidor usa para reconhecer a repetição.',
 'É o **botão de ligar a esteira**: apertar duas vezes não liga duas esteiras, ela continua ligada. Já adicionar uma caixa, apertado duas vezes, põe duas caixas, e isso não é idempotente.',
 ['Evitar cobrança dupla em pagamentos','Permitir que o cliente repita com segurança um pedido que falhou','Construir filas e webhooks que toleram mensagens repetidas'],
 ['http',L('POST /pagamentos','Idempotency-Key: 7c1f-4a2b-91de','Content-Type: application/json','','{ "valor": 150.00, "cliente": 42 }'),'Se a rede cair e o cliente repetir o POST com a mesma chave, o servidor devolve o resultado do primeiro e não cobra de novo.'],
 null,['rest','webhook','filas','http','api'],{tags:'idempotente retry repeticao pagamento chave'}),

E('smtp','E-mail transacional e SMTP','Como o sistema envia e-mails automáticos',2,
 'Mensagens automáticas do sistema, como confirmação de cadastro, recuperação de senha e nota fiscal, são e-mails **transacionais**. Para enviar, o servidor usa o protocolo **SMTP**, geralmente por meio de um serviço especializado, como SendGrid, Amazon SES, Resend ou Mailgun, que cuida da reputação e da entrega. Mandar e-mail direto do seu servidor costuma cair no spam. No domínio, é preciso configurar SPF, DKIM e DMARC.',
 'É o **correio contratado**: em vez de levar cada carta na mão até o destinatário, você entrega no balcão dos Correios, que tem a rede e a reputação para entregar.',
 ['Confirmar cadastros e recuperar senhas','Enviar recibos, alertas e relatórios','Entender por que e-mails caem no spam'],
 ['javascript',L('import nodemailer from "nodemailer";','','const transporte = nodemailer.createTransport({','  host: "smtp.exemplo.com", port: 587,','  auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },','});','','await transporte.sendMail({','  from: "avisos@minhaempresa.com",','  to: "ana@exemplo.com",','  subject: "Recuperação de senha",','  text: "Clique no link para criar uma nova senha.",','});'),'O usuário e a senha do SMTP vêm de variáveis de ambiente, nunca escritos no código.'],
 null,['filas','variaveis-ambiente','dns','api'],{tags:'email smtp sendgrid ses mailgun spf dkim dmarc spam'}),

E('soap','SOAP','O padrão antigo de serviços web em XML',3,
 'O **SOAP** é um protocolo antigo de serviços web em XML, com contrato rígido, o WSDL, e muitos recursos formais de segurança. Perdeu espaço para REST e JSON nos sistemas novos por ser pesado e verboso, mas continua vivo em bancos, governo e integrações com ERPs, como as notas fiscais eletrônicas, porque ali o contrato formal tem valor.',
 'É o **formulário em papel timbrado, com carimbo e protocolo**: burocrático e pesado, mas cada campo tem significado oficial e é aceito em qualquer repartição.',
 ['Integrar com sistemas legados e do governo','Entender por que integrações antigas parecem tão burocráticas','Ler um contrato WSDL quando for preciso'],
 ['xml',L('<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">','  <soap:Body>','    <ConsultaStatus>','      <Maquina>Prensa01</Maquina>','    </ConsultaStatus>','  </soap:Body>','</soap:Envelope>'),'Tudo vai dentro de um envelope XML. Compare com o mesmo pedido em REST: um simples GET com um endereço.'],
 null,['rest','formatos','api','erp'],{tags:'xml wsdl legado nfe integracao'})
]);
