/* ===== DevOps, nuvem e infraestrutura ===== */
C('ops',[
E('ops-geral','O que significa Ops','DevOps, MLOps, GitOps e toda a família com Ops no nome',1,
 '**Ops** vem de **Operations**, operação: a turma que **mantém o sistema funcionando** depois de pronto, com servidores, publicação, monitoramento e incidentes. Quando alguém junta uma palavra com Ops, como DevOps, MLOps ou GitOps, está dizendo o trabalho de operar e entregar aquilo, de forma automatizada. **Dev** é quem desenvolve, **Ops** é quem opera, e **DevOps** é a cultura e as ferramentas para os dois trabalharem juntos.',
 'Em fábrica, o desenvolvimento é o **projeto do produto** e a operação é a **produção e a manutenção**. Antigamente o projetista jogava o desenho por cima do muro e a manutenção que se virasse. A cultura de Ops é a do **TPM**: projeto, produção e manutenção na mesma mesa, com indicadores à vista.',
 ['Entender as siglas com Ops que aparecem em vagas e artigos','Enxergar o caminho do código até o sistema no ar','Saber por onde começar na carreira de infraestrutura'],
 ['mapa',L('Dev        → escreve o código','Ops        → coloca no ar e mantém funcionando','DevOps     → os dois no mesmo time, com automação','DevSecOps  → DevOps + segurança em cada etapa','GitOps     → o Git é a fonte da verdade da infraestrutura','MLOps      → DevOps para modelos de IA','DataOps    → DevOps para pipelines de dados','FinOps     → controle de custo na nuvem','AIOps      → IA ajudando a operar os sistemas','NoOps      → operação tão automatizada que quase some (serverless)'),'A parte antes do Ops muda conforme o assunto, mas a ideia é a mesma: automatizar a entrega e a manutenção, com medição e melhoria contínua.'],
 null,['devops','cicd','devsecops','mlops','gitops','finops','sre'],{tags:'ops operations operacao siglas devops mlops aiops dataops noops'}),

E('devops','DevOps','Quem desenvolve e quem opera trabalhando juntos',1,
 '**DevOps** é uma cultura e um conjunto de práticas para que quem **desenvolve** e quem **opera** trabalhem juntos, com automação do começo ao fim: código, testes, entrega e monitoramento. O objetivo é lançar mudanças pequenas, com frequência e com segurança, em vez de grandes pacotes arriscados a cada seis meses. Não é um cargo único nem uma ferramenta: é um jeito de trabalhar, apoiado em Git, CI/CD, containers e monitoramento.',
 'Antes, o projetista **jogava o projeto por cima do muro** e a produção descobria os problemas na linha. DevOps é como o **TPM** da fábrica: projeto, produção e manutenção na mesma mesa, com indicadores à vista, melhorando um pouco todo dia.',
 ['Publicar versões novas várias vezes por dia sem medo','Achar e corrigir falhas rápido, com monitoramento e automação','Acabar com o jogo de empurra entre desenvolvimento e infraestrutura','Tratar a infraestrutura como código versionado'],
 ['ciclo',L('planejar → codar → compilar → testar → publicar → implantar → operar → monitorar','   ↑______________________________________________________________________|'),'O ciclo nunca termina: o que o monitoramento descobre vira o próximo item de planejamento.'],
 null,['ops-geral','cicd','iac','docker','monitoramento','git'],{tags:'cultura entrega continua automacao sre'}),

E('cicd','CI/CD','A esteira automática do código até o ar',2,
 '**CI/CD** é a esteira automática que leva o seu código do computador até o ar. **CI**, integração contínua: a cada alteração enviada, o sistema compila e roda os testes sozinho. **CD** pode ser entrega contínua, que deixa tudo pronto para publicar, ou implantação contínua, que publica sozinho se tudo passar. O resultado é menos erro humano, menos trabalho manual e entregas mais frequentes.',
 'É a **linha de montagem com inspeção automática em cada posto**. A peça só avança se passar pelo calibrador. Se reprovar, a linha para e avisa quem mexeu, antes da peça chegar ao cliente.',
 ['Rodar testes automaticamente a cada alteração','Publicar o site ou o app sem ninguém copiar arquivos na mão','Descobrir o erro em minutos, e não depois do cliente reclamar','Padronizar a entrega entre toda a equipe'],
 ['yaml',L('# .github/workflows/ci.yml','name: CI','on: [push]','jobs:','  testar:','    runs-on: ubuntu-latest','    steps:','      - uses: actions/checkout@v4','      - uses: actions/setup-node@v4','        with: { node-version: 22 }','      - run: npm ci','      - run: npm test'),'A cada push, o GitHub abre uma máquina virtual, baixa o código, instala o Node, instala as dependências e roda os testes. Se algum passo falhar, a alteração aparece com um X vermelho.'],
 'cicd',['githubactions','jenkins','devops','docker','git','testes','deploy'],{tags:'integracao continua entrega pipeline esteira build deploy gitlab ci'}),

E('container','Containers','A maleta de manutenção que funciona igual em qualquer lugar',1,
 'Um **container** é um pacote isolado que leva o seu programa e **tudo o que ele precisa para rodar**: bibliotecas, configurações, versão da linguagem. Roda igual no seu notebook, no servidor do colega e na nuvem. Diferente de uma máquina virtual, não leva um sistema operacional completo: ele **compartilha o núcleo do sistema** do computador, por isso é leve e liga em segundos.',
 'É o **kit de manutenção em maleta**, com a ferramenta certa, a graxa certa e o procedimento junto. Não importa em que fábrica você abra a maleta, o serviço sai igual. A máquina virtual seria levar uma oficina inteira para cada serviço.',
 ['Acabar com o problema de na minha máquina funciona','Rodar vários serviços isolados no mesmo servidor','Subir ambientes de teste em segundos','Servir de base para Docker e Kubernetes'],
 ['bash',L('docker run -d -p 8080:80 nginx      # baixa e liga um servidor Nginx','docker ps                           # lista os containers rodando','docker stop <id>                    # desliga um container'),'O -p 8080:80 liga a porta 8080 do seu computador à porta 80 do container. Depois do primeiro comando, abra http://localhost:8080 no navegador.'],
 null,['docker','vm','kubernetes','linux'],{tags:'conteiner isolamento imagem namespaces cgroups'}),

E('docker','Docker','Empacotar o app com tudo dentro, num molde',1,
 'O **Docker** é a ferramenta que popularizou os containers. Você descreve o ambiente do programa num arquivo chamado **Dockerfile**, e o Docker constrói uma **imagem**, que é o molde, e a partir dela cria quantos **containers**, as instâncias rodando, você quiser. A imagem pode ser enviada a um registro, como o Docker Hub, e qualquer servidor consegue baixar e rodar.',
 'A **imagem** é o **molde** da peça. O **container** é cada peça produzida a partir dele. O **Docker Hub** é o catálogo onde os moldes ficam guardados. E o Dockerfile é a ficha de processo que descreve como fazer o molde.',
 ['Empacotar um app com tudo que ele precisa','Padronizar o ambiente da equipe inteira','Subir banco de dados e serviços de teste com um comando','Publicar aplicações em qualquer nuvem'],
 ['dockerfile',L('FROM node:22-alpine           # ponto de partida: Linux mínimo com Node','WORKDIR /app','COPY package*.json ./','RUN npm ci --omit=dev         # instala as dependências','COPY . .','EXPOSE 3000','CMD ["node", "servidor.js"]   # comando que roda ao ligar o container'),'Cada linha cria uma camada da imagem. Para construir, use docker build -t meuapp . (o ponto no final é a pasta atual). Para rodar, use docker run -p 3000:3000 meuapp'],
 'docker',['container','dockercompose','kubernetes','vm','cicd'],{tags:'dockerfile imagem container hub registro build run'}),

E('dockercompose','Docker Compose','Vários containers com um arquivo e um comando',2,
 'O **Docker Compose** sobe vários containers de uma vez a partir de um único arquivo YAML: o seu app, o banco de dados, o Redis, já ligados numa rede privada. Com um comando, o ambiente inteiro de desenvolvimento fica de pé, e com outro é derrubado. É a forma mais prática de montar o ambiente local de um projeto.',
 'É a **lista de montagem da bancada de teste**: motor, painel, sensor e cabos, todos listados numa folha. Quem recebe a folha monta tudo igual, sem esquecer nenhum item.',
 ['Ter app e banco prontos no ambiente local','Documentar a infraestrutura do projeto num arquivo','Fazer testes de integração com serviços reais'],
 ['yaml',L('services:','  app:','    build: .','    ports: ["3000:3000"]','    environment:','      DATABASE_URL: postgres://app:segredo@banco:5432/fabrica','    depends_on: [banco]','  banco:','    image: postgres:16','    environment:','      POSTGRES_USER: app','      POSTGRES_PASSWORD: segredo','      POSTGRES_DB: fabrica','    volumes: ["dados:/var/lib/postgresql/data"]','volumes:','  dados:'),'O app enxerga o banco pelo nome banco, como se fosse um endereço. O volume guarda os dados fora do container, senão eles somem quando o container é apagado. Para subir tudo: docker compose up'],
 null,['docker','postgres','variaveis-ambiente','formatos'],{tags:'compose yaml multi container ambiente local'}),

E('kubernetes','Kubernetes','O supervisor de produção para milhares de containers',3,
 'O **Kubernetes**, também chamado K8s, é o sistema que **gerencia containers em muitos servidores**. Você diz o estado desejado, por exemplo cinco cópias deste app rodando, e ele faz acontecer: se uma cai, sobe outra; se o tráfego cresce, aumenta as cópias; atualiza versões sem derrubar o serviço. Foi criado no Google e hoje é o padrão para rodar containers em grande escala. É poderoso e complexo; para projetos pequenos costuma ser exagero.',
 'Se o container é uma máquina, o Kubernetes é o **supervisor de produção** com o painel de todas as máquinas. Se uma quebra, ele redistribui o serviço para as outras. Se a demanda dobra, liga mais máquinas. Você dá a meta do turno, e ele cuida da escala.',
 ['Rodar muitos containers com alta disponibilidade','Atualizar versões sem parar o serviço','Escalar automaticamente conforme a demanda','Ser o padrão de mercado para microsserviços na nuvem'],
 ['yaml',L('apiVersion: apps/v1','kind: Deployment','metadata: { name: meuapp }','spec:','  replicas: 3                      # quero 3 cópias sempre rodando','  selector:','    matchLabels: { app: meuapp }','  template:','    metadata:','      labels: { app: meuapp }','    spec:','      containers:','        - name: meuapp','          image: meuregistro/meuapp:1.4.2','          ports: [{ containerPort: 3000 }]'),'Você declara o desejado: três réplicas desta imagem. O Kubernetes compara o desejado com o real o tempo todo e corrige a diferença. Para aplicar: kubectl apply -f arquivo.yaml'],
 'k8s',['docker','container','microsservicos','escalabilidade','gitops','loadbalancer'],{tags:'k8s kubectl pod deployment cluster helm orquestracao google'}),

E('vm','Máquinas virtuais','Um computador inteiro dentro de outro',2,
 'Uma **máquina virtual**, ou VM, é um computador simulado por software, com seu próprio sistema operacional, rodando dentro de um computador real. Um programa chamado **hipervisor**, como VMware, Hyper-V, KVM ou VirtualBox, divide o hardware entre várias VMs. Cada VM é isolada das outras. É a base da nuvem tradicional: quando você aluga um servidor na AWS, quase sempre é uma VM.',
 'É dividir um **galpão grande em salas com paredes e portas próprias**. Cada sala tem a sua instalação e a sua chave, e quem está numa não vê a outra. Já o container seria dividir o mesmo salão com divisórias leves.',
 ['Rodar Linux dentro do Windows para estudar','Servidores na nuvem, que são VMs alugadas','Isolar ambientes de teste e de risco, como analisar um malware','Aproveitar melhor o hardware, com vários sistemas num servidor só'],
 ['comparativo',L('              Máquina virtual           Container','Sistema       um completo por VM        compartilha o do computador','Tamanho       gigabytes                 megabytes','Inicia em     minutos                   segundos','Isolamento    forte                     bom, mas menor'),'Nenhum é melhor sempre. VMs isolam mais; containers são mais leves. Na prática, os containers costumam rodar dentro de VMs.'],
 null,['container','docker','cloud','so','linux'],{tags:'virtualizacao hipervisor vmware virtualbox hyper-v kvm vm'}),

E('cloud','Computação em nuvem','Alugar infraestrutura em vez de comprar',1,
 '**Nuvem** é usar computadores de outra empresa, pela internet, e pagar só pelo que usar, em vez de comprar e manter servidores próprios. Você aluga máquinas, bancos, armazenamento e até serviços prontos de IA. Os níveis: **IaaS**, em que você aluga a infraestrutura e cuida do resto; **PaaS**, em que a plataforma cuida do servidor e você sobe o código; e **SaaS**, em que você só usa o software pronto, como o Gmail.',
 'É a diferença entre **comprar um gerador** e **assinar a energia da rede**. Em vez de investir, instalar e fazer manutenção, você liga na tomada e paga pelo consumo. Se precisar de mais, é só puxar mais.',
 ['Subir um serviço em minutos, sem comprar hardware','Pagar só pelo uso e escalar conforme a demanda','Ter backup, redundância e segurança que seriam caros de montar sozinho','Usar IA, bancos e filas como serviços prontos'],
 ['quem cuida de quê',L('                 você cuida            o fornecedor cuida','On-premises      tudo                  nada','IaaS (EC2)       SO, app, dados        hardware, rede, prédio','PaaS (Heroku)    app e dados           SO, servidores, hardware','SaaS (Gmail)     só o uso              todo o resto'),'Quanto mais para baixo, menos trabalho de administração para você, e menos controle.'],
 null,['aws','azure','gcp','vm','serverless','finops'],{tags:'nuvem cloud iaas paas saas publica privada hibrida multicloud'}),

E('aws','AWS','A maior nuvem do mundo',2,
 'A **AWS**, Amazon Web Services, é a maior plataforma de nuvem, com mais de duzentos serviços. Os mais usados são o **EC2**, de servidores virtuais; o **S3**, de armazenamento de arquivos; o **RDS**, de bancos de dados gerenciados; o **Lambda**, de funções serverless; o **IAM**, de usuários e permissões; a **VPC**, de rede privada; e o **CloudFront**, de CDN. Aprender a AWS é aprender o vocabulário da nuvem que as outras também usam, com outros nomes.',
 'É o **grande catálogo de máquinas e utilidades** de uma distribuidora gigante: de furadeira a gerador, tudo disponível por hora. Poderoso, mas o catálogo é tão grande que é fácil se perder e gastar sem querer.',
 ['Hospedar sites, APIs e bancos em escala','Trabalhar em empresas que já usam AWS, que são muitas','Estudar para certificações, como a Cloud Practitioner'],
 ['bash',L('aws s3 cp relatorio.pdf s3://meu-bucket/relatorios/    # envia um arquivo','aws ec2 describe-instances                             # lista os servidores','aws iam list-users                                     # lista os usuários'),'O aws é a ferramenta de linha de comando. Antes, configure as credenciais com aws configure. Cuidado: recurso ligado gera cobrança mesmo sem uso.'],
 null,['cloud','s3','vpc','serverless','terraform','azure','gcp'],{tags:'amazon ec2 s3 rds lambda iam cloudfront'}),

E('azure','Microsoft Azure','A nuvem da Microsoft',2,
 'O **Azure** é a nuvem da Microsoft. O ponto forte é a integração com o mundo corporativo: Active Directory, hoje chamado Entra ID, Microsoft 365, Windows Server, SQL Server e .NET. Muitas empresas que já usam produtos Microsoft escolhem o Azure. Oferece máquinas virtuais, containers, funções, bancos de dados e serviços de inteligência artificial.',
 'É a **distribuidora do mesmo fabricante dos seus equipamentos de escritório**: tudo conversa com o que a empresa já usa, com um único contrato e um único login.',
 ['Empresas que usam Microsoft 365 e Windows Server','Aplicações em .NET e C#','Integrar login corporativo com o Entra ID'],
 ['bash',L('az login','az group create --name fabrica-rg --location brazilsouth','az vm list --resource-group fabrica-rg --output table'),'O az é a ferramenta de linha de comando do Azure. Todo recurso fica dentro de um grupo de recursos, que facilita apagar tudo de uma vez ao terminar o teste.'],
 null,['cloud','aws','gcp','dotnet','powershell'],{tags:'microsoft entra active directory 365'}),

E('gcp','Google Cloud','A nuvem do Google, forte em dados e IA',2,
 'O **Google Cloud Platform**, o GCP, é a nuvem do Google. É conhecido pela força em dados e inteligência artificial, com serviços como o BigQuery, para análise de dados em larga escala; o Vertex AI; o Cloud Run, que roda containers sem você gerenciar servidor; e o GKE, que é Kubernetes gerenciado. Tem fatia de mercado menor que a AWS e o Azure, mas é forte em startups e empresas de dados.',
 'É a **distribuidora especializada em instrumentos de medição e análise**: catálogo menor, mas referência quando o assunto é processar grandes volumes de dados.',
 ['Análise de dados com BigQuery','Publicar containers com pouca configuração, no Cloud Run','Projetos de IA e dados'],
 ['bash',L('gcloud run deploy meuapp --source . --region southamerica-east1'),'Esse único comando pega o código da pasta atual, empacota num container e publica no Cloud Run, na região de São Paulo.'],
 null,['cloud','aws','azure','kubernetes','serverless'],{tags:'google cloud platform bigquery cloud run gke vertex'}),

E('iac','Infraestrutura como código','Servidores descritos em arquivos, não em cliques',2,
 '**IaC** é descrever a infraestrutura, ou seja, servidores, redes e bancos, em **arquivos de código**, em vez de clicar em painéis. Você versiona no Git, revisa como qualquer código e roda uma ferramenta que cria ou altera tudo igual, quantas vezes precisar. Se o ambiente for destruído, recria do zero em minutos. Ferramentas: Terraform, Pulumi, CloudFormation e Ansible.',
 'É o **projeto elétrico e a lista de materiais da instalação**. Quem tem o projeto reconstrói a planta inteira, igual. Quem só tem a lembrança de quem instalou fica refém dessa pessoa.',
 ['Criar ambientes idênticos de teste e de produção','Recuperar a infraestrutura depois de um desastre','Revisar e auditar mudanças de infraestrutura como se revisa código','Evitar configuração feita na mão, impossível de repetir'],
 ['conceito',L('# Imperativo: você diz os passos','criar servidor; instalar nginx; abrir porta 80','','# Declarativo: você diz o resultado desejado','quero 1 servidor com nginx e a porta 80 aberta'),'O Terraform é declarativo: você descreve o destino e ele descobre os passos. Rodar de novo não duplica nada.'],
 null,['terraform','ansible','git','devops','gitops','cloud'],{tags:'iac pulumi cloudformation infra as code declarativo'}),

E('terraform','Terraform','Criar a infraestrutura da nuvem escrevendo arquivos',3,
 'O **Terraform**, criado pela HashiCorp, é a ferramenta mais usada de infraestrutura como código. Você escreve em arquivos o que quer na nuvem, como um servidor, um bucket ou uma rede, e ele compara com o que existe e **cria, altera ou apaga** o que for preciso. Funciona com AWS, Azure, Google e centenas de outros provedores. Guarda o estado atual num arquivo, que precisa ser protegido. Existe também o OpenTofu, uma alternativa aberta compatível.',
 'É o **gerente de obras com a planta na mão**: compara a obra atual com a planta e executa só o que falta ou o que mudou. Não derruba a parede inteira para trocar uma tomada.',
 ['Criar ambientes inteiros na nuvem com um comando','Registrar no Git toda mudança de infraestrutura','Destruir tudo ao fim de um teste para não pagar à toa'],
 ['hcl',L('provider "aws" {','  region = "sa-east-1"','}','','resource "aws_s3_bucket" "relatorios" {','  bucket = "fabrica-relatorios-2026"','}'),'O fluxo é terraform init, terraform plan, que mostra o que vai mudar, e terraform apply, que executa. Sempre leia o plan antes do apply.'],
 null,['iac','aws','ansible','gitops','cloud'],{tags:'hashicorp hcl tf opentofu provisionamento'}),

E('ansible','Ansible','Configurar dezenas de servidores com um roteiro',3,
 'O **Ansible**, da Red Hat, automatiza a **configuração de servidores**: instalar programas, copiar arquivos, ajustar serviços e criar usuários, em dezenas de máquinas ao mesmo tempo. Você escreve um roteiro em YAML, o **playbook**, e roda. Não precisa instalar nada nas máquinas, porque ele conecta por SSH. É idempotente: rodar duas vezes deixa o mesmo resultado.',
 'É a **ordem de serviço padrão entregue a todos os mecânicos ao mesmo tempo**. Cada um executa a mesma lista de passos na sua máquina. Se a máquina já estiver conforme, ele só confirma e segue.',
 ['Preparar vários servidores do mesmo jeito','Aplicar atualizações e configurações de segurança em escala','Documentar a configuração dos servidores em arquivos'],
 ['yaml',L('- hosts: servidores_web','  become: true','  tasks:','    - name: Instalar o Nginx','      apt: { name: nginx, state: present }','','    - name: Garantir que o Nginx esteja ligado','      service: { name: nginx, state: started, enabled: true }'),'Para rodar: ansible-playbook -i inventario.ini site.yml O state present significa garanta que está instalado, o que torna seguro repetir.'],
 null,['iac','ssh','terraform','linux','bash'],{tags:'playbook red hat configuracao automacao servidores yaml'}),

E('nginx','Nginx','O servidor web e proxy que fica na frente de meio mundo',2,
 'O **Nginx** é um servidor web rápido e leve. Serve arquivos estáticos, atua como **proxy reverso**, que recebe os pedidos e repassa para a sua aplicação, balanceia carga e termina o HTTPS. Em muitas arquiteturas ele fica na frente do app, cuidando do trabalho de portaria. O **Apache** é o concorrente mais antigo, e o **Caddy** é uma alternativa moderna que configura o HTTPS sozinha.',
 'É a **recepção** da empresa: atende o visitante, confere o que ele quer e o encaminha ao setor certo. Os setores, as aplicações, ficam sem se preocupar com o atendimento.',
 ['Servir sites estáticos com muita velocidade','Colocar uma aplicação Node, Python ou Java atrás de um proxy','Configurar HTTPS e redirecionamentos','Distribuir carga entre servidores'],
 ['nginx',L('server {','    listen 80;','    server_name meusite.com;','','    location / {','        proxy_pass http://127.0.0.1:3000;   # repassa para o app Node','        proxy_set_header Host $host;','    }','}'),'O Nginx escuta na porta 80 e entrega tudo ao app que roda na porta 3000. Para o HTTPS, use o Certbot, que pega o certificado gratuito da Let\'s Encrypt.'],
 null,['proxy-reverso','loadbalancer','tls','linux','cdn'],{tags:'nginx apache caddy servidor web proxy http'}),

E('proxy-reverso','Proxy e proxy reverso','Intermediários que ficam no meio do caminho',2,
 'Um **proxy** é um intermediário na comunicação. O **proxy comum** fica do lado do cliente: a empresa passa o tráfego por ele para filtrar sites e registrar acessos. O **proxy reverso** fica do lado do servidor: recebe os pedidos de fora e decide para qual servidor interno encaminhar. Ele esconde a estrutura interna, faz cache, termina o HTTPS e distribui a carga. Nginx, HAProxy e Traefik fazem esse papel.',
 'O proxy comum é o **porteiro que controla a saída dos funcionários**. O proxy reverso é a **portaria que controla a entrada dos visitantes** e os direciona para a pessoa certa, sem que o visitante precise saber onde fica cada sala.',
 ['Esconder os servidores internos da internet','Terminar o HTTPS em um só lugar','Filtrar o acesso à internet dentro de uma empresa'],
 ['diagrama',L('Cliente → [ Proxy reverso ] → Servidor A','                           → Servidor B','                           → Servidor C'),'O cliente só conhece o endereço do proxy reverso. Quem atende de verdade é um dos servidores atrás dele.'],
 null,['nginx','loadbalancer','vpn','gateway','tls'],{tags:'haproxy traefik squid forward reverse'}),

E('loadbalancer','Balanceador de carga','Distribuir os pedidos entre vários servidores',2,
 'O **balanceador de carga** distribui os pedidos entre vários servidores iguais, para nenhum ficar sobrecarregado. Ele também **verifica a saúde** dos servidores: se um parar de responder, sai da rotação. Alguns algoritmos comuns: round robin, que é um para cada um em ordem; menos conexões; e por endereço IP. Dá mais capacidade e mais disponibilidade: se um servidor cai, os outros seguem.',
 'É o **encarregado que distribui as ordens de serviço** entre as máquinas disponíveis, olhando quem está livre. Se uma máquina quebra, ele deixa de mandar serviço para ela e ninguém percebe.',
 ['Aguentar mais acessos do que um servidor só aguentaria','Manter o site no ar mesmo se um servidor falhar','Atualizar servidores um de cada vez, sem parar o serviço'],
 ['nginx',L('upstream meuapp {','    server 10.0.0.11:3000;','    server 10.0.0.12:3000;','    server 10.0.0.13:3000;','}','','server {','    listen 80;','    location / { proxy_pass http://meuapp; }','}'),'Sem mais nada, o Nginx reveza os pedidos entre os três servidores, no estilo round robin.'],
 'lb',['nginx','alta-disponibilidade','escalabilidade','proxy-reverso','kubernetes'],{tags:'load balancer round robin haproxy alb elb distribuicao'}),

E('cdn','CDN','Cópias do site espalhadas pelo mundo',2,
 'Uma **CDN**, Content Delivery Network, é uma rede de servidores espalhados pelo mundo que guardam cópias dos arquivos do seu site: imagens, scripts, vídeos. Quando alguém acessa, recebe do servidor mais próximo, e não do seu servidor original, que pode estar do outro lado do planeta. O site carrega mais rápido, o servidor original sofre menos e a CDN ainda ajuda a absorver ataques. Exemplos: Cloudflare, CloudFront e Fastly.',
 'É ter **filiais do almoxarifado** em várias cidades. O cliente de Manaus recebe a peça da filial de Manaus, em vez de esperar o caminhão que sai do galpão central, lá longe.',
 ['Deixar o site rápido para visitantes de qualquer lugar','Aguentar picos de acesso','Reduzir o custo de banda do servidor','Ajudar a proteger contra ataques de negação de serviço'],
 ['html',L('<!-- sem CDN: o arquivo vem do seu servidor, onde quer que ele esteja -->','<script src="/js/biblioteca.js"></script>','','<!-- com CDN: o arquivo vem do servidor mais próximo do visitante -->','<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"></script>'),'As bibliotecas públicas em CDN, como as do cdnjs, são servidas de pontos espalhados pelo mundo. Seus próprios arquivos também podem ficar atrás de uma CDN, como a Cloudflare.'],
 'cdn',['cache','cloudflare','dns','navegador','ddos'],{tags:'content delivery network cloudflare cloudfront fastly akamai edge cache'}),

E('monitoramento','Monitoramento','O painel de instrumentos do sistema',2,
 '**Monitorar** é coletar medidas do sistema o tempo todo, como uso de CPU e memória, tempo de resposta, taxa de erros e espaço em disco, e **avisar quando algo foge do normal**. A dupla clássica: o **Prometheus** coleta e guarda as métricas, e o **Grafana** desenha os painéis e os gráficos. Há também Zabbix, Nagios e Datadog. Sem monitoramento, você só descobre o problema quando o cliente liga.',
 'É o **painel de instrumentos da máquina**: temperatura, vibração, corrente e pressão, com alarme quando passa do limite. Um técnico de manutenção reconhece na hora. É a **manutenção preditiva** aplicada ao software.',
 ['Ser avisado antes do sistema parar','Descobrir gargalos e planejar capacidade','Provar o tempo de funcionamento do serviço','Investigar o que aconteceu depois de uma falha'],
 ['yaml',L('groups:','  - name: servidor','    rules:','      - alert: CPUAlta','        expr: 1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) > 0.9','        for: 10m','        labels: { severidade: aviso }','        annotations: { resumo: "CPU acima de 90% por 10 minutos" }'),'A regra calcula o uso de CPU nos últimos cinco minutos e dispara o alerta se ficar acima de 90% durante dez minutos seguidos. O for evita alarme falso por um pico curto.'],
 null,['logs','observabilidade','sre','incidentes','iiot'],{tags:'prometheus grafana zabbix nagios datadog metricas alertas dashboard'}),

E('logs','Logs','O diário de bordo do sistema',1,
 '**Log** é o registro de tudo que acontece num sistema, linha por linha, com data e hora: quem acessou, o que foi feito, qual erro ocorreu. É a primeira fonte para entender uma falha. Em sistemas grandes, os logs de todos os servidores vão para um lugar central, como ELK, Loki, CloudWatch ou Datadog, onde dá para buscar e filtrar. Dica de ouro: nunca registre senhas nem dados pessoais.',
 'É o **diário de bordo do operador** e o **histórico de alarmes da IHM**: cada ocorrência com data e hora. Quando a máquina para, é ali que se descobre o que veio antes.',
 ['Descobrir a causa de um erro','Auditar quem fez o quê','Alimentar alertas e painéis de monitoramento'],
 ['log',L('2026-10-07 14:32:08 INFO  Pedido 8841 criado por usuario=42','2026-10-07 14:32:09 WARN  Estoque baixo: produto=P-117 restante=3','2026-10-07 14:32:11 ERROR Falha ao cobrar pedido 8841: timeout no gateway'),'Três níveis: INFO é fato normal, WARN é atenção e ERROR é falha. Procure por ERROR e filtre pela hora para achar a causa. No Linux, o comando tail -f arquivo.log mostra o log ao vivo.'],
 null,['monitoramento','observabilidade','incidentes','bug-debug'],{tags:'log registro auditoria elk loki cloudwatch syslog',also:['seg']}),

E('observabilidade','Observabilidade','Entender o que acontece por dentro olhando por fora',3,
 '**Observabilidade** é a capacidade de entender o que está acontecendo dentro de um sistema a partir do que ele emite para fora. Se apoia em três pilares: **logs**, que dizem o que aconteceu; **métricas**, que são números ao longo do tempo; e **traces**, que mostram o caminho de um pedido por vários serviços. Vai além do monitoramento: o monitoramento diz **que** quebrou, a observabilidade ajuda a descobrir **por quê**. Ferramentas: OpenTelemetry, Jaeger, Datadog e New Relic.',
 'Monitorar é o **alarme que acende**. Observar é ter **sensores suficientes**, como vibração, temperatura, corrente e histórico, para diagnosticar a causa sem desmontar a máquina.',
 ['Achar a causa raiz em sistemas distribuídos','Descobrir qual serviço está deixando o pedido lento','Responder a perguntas que você não previu quando montou o painel'],
 ['os três pilares',L('Logs      → o que aconteceu       ERROR falha ao cobrar pedido 8841','Métricas  → quanto, quão rápido   95% das respostas em menos de 300 ms','Traces    → por onde passou        site → API → pagamentos → banco (2,1 s no banco)'),'Juntos, os três levam você do sintoma, o site está lento, até a causa, o banco de pagamentos está levando dois segundos para responder, sem precisar adivinhar.'],
 null,['monitoramento','logs','sre','microsservicos','incidentes'],{tags:'opentelemetry tracing jaeger datadog new relic metricas traces'}),

E('sre','SRE','Operar sistemas com engenharia de confiabilidade',3,
 '**SRE**, Site Reliability Engineering, é a abordagem criada no Google para operar sistemas grandes usando engenharia de software. Define metas mensuráveis de confiabilidade, os **SLOs**, mede com indicadores, os **SLIs**, e usa o **orçamento de erro**: se o serviço tem direito a pouca indisponibilidade, quando o orçamento acaba o time para de lançar novidades e foca em estabilidade. Também automatiza o trabalho repetitivo e faz **post-mortems** sem culpados depois dos incidentes.',
 'É a **engenharia de confiabilidade de uma planta**: meta de disponibilidade por equipamento, medição do tempo entre falhas e do tempo de reparo, análise de causa raiz sem caça às bruxas, e automação do que se repete.',
 ['Definir quanto de falha é aceitável, e agir quando passa','Trocar trabalho manual repetitivo por automação','Aprender com os incidentes, sem apontar culpados'],
 ['indicadores',L('SLI (medida):  % de pedidos respondidos em menos de 300 ms','SLO (meta):    99,9% dos pedidos no mês','Orçamento:     0,1% de falhas permitidas (cerca de 43 minutos por mês)','SLA (contrato): se ficar abaixo, a empresa devolve parte do valor ao cliente'),'SLI é o que se mede, SLO é a meta interna e SLA é o compromisso com o cliente, que costuma ser mais frouxo que a meta interna.'],
 null,['monitoramento','incidentes','alta-disponibilidade','devops','observabilidade'],{tags:'site reliability engineering slo sli sla orcamento de erro confiabilidade'}),

E('githubactions','GitHub Actions','A automação embutida no GitHub',2,
 'O **GitHub Actions** é o sistema de automação embutido no GitHub. Você descreve em arquivos YAML o que deve acontecer quando algo ocorre no repositório, como um push, um pull request ou um horário agendado: rodar testes, construir o projeto, publicar o site. As máquinas que executam são alugadas do GitHub, com uma cota gratuita. É a porta de entrada mais fácil para CI/CD.',
 'É o **robô de plantão** do repositório. Toda vez que alguém entrega uma peça nova, ele executa a lista de inspeção, e só deixa a peça seguir se estiver tudo certo.',
 ['Testar o código a cada alteração','Publicar um site no GitHub Pages automaticamente','Agendar tarefas, como gerar um relatório toda noite'],
 ['yaml',L('# .github/workflows/pages.yml - publica um site estático','name: Publicar','on:','  push:','    branches: [main]','permissions:','  contents: read','  pages: write','  id-token: write','jobs:','  deploy:','    runs-on: ubuntu-latest','    environment: { name: github-pages }','    steps:','      - uses: actions/checkout@v4','      - uses: actions/upload-pages-artifact@v3','        with: { path: . }','      - uses: actions/deploy-pages@v4'),'Para funcionar, no repositório vá em Settings, Pages, e escolha GitHub Actions como fonte. A cada push na branch main, o site é publicado.'],
 null,['cicd','git','github','deploy','formatos'],{tags:'github actions workflow yaml pages ci cd',also:['ferr']}),

E('jenkins','Jenkins','O servidor de automação veterano',3,
 'O **Jenkins** é um servidor de automação de código aberto, um dos mais antigos e ainda muito usado em empresas para CI/CD. Você o instala num servidor seu e configura os jobs, ou escreve um arquivo chamado **Jenkinsfile** com as etapas. Tem milhares de plugins. É flexível, mas dá mais trabalho de manter que soluções prontas como o GitHub Actions ou o GitLab CI.',
 'É a **esteira automatizada que você mesmo monta e mantém dentro da fábrica**: controle total e muita flexibilidade, mas a manutenção é sua.',
 ['Manter pipelines em empresas que já usam Jenkins','Automatizar builds em ambientes sem acesso à nuvem','Ler pipelines antigos que ainda existem por aí'],
 ['groovy',L('pipeline {','  agent any','  stages {','    stage("Testar")    { steps { sh "npm ci && npm test" } }','    stage("Construir") { steps { sh "npm run build" } }','    stage("Publicar")  { steps { sh "./publicar.sh" } }','  }','}'),'Cada stage é um posto da esteira. Se o primeiro falhar, os seguintes nem começam.'],
 null,['cicd','githubactions','devops'],{tags:'jenkinsfile pipeline groovy ci cd legado'}),

E('vercel','Vercel e Netlify','Hospedagem de sites que publica sozinha',1,
 '**Vercel** e **Netlify** são plataformas para hospedar sites e aplicações front-end. Você conecta o repositório do GitHub e, a cada push, elas constroem e publicam o site sozinhas, com HTTPS, CDN global e um endereço público. Também rodam funções serverless para a parte de back-end. O plano gratuito atende a maioria dos projetos pessoais. A Vercel é a criadora do Next.js.',
 'É o **serviço de entrega expressa**: você deixa o pacote pronto, e eles cuidam de embalar, transportar e entregar no endereço, sem você mexer no caminhão.',
 ['Publicar um portfólio ou um projeto em minutos','Ganhar uma prévia online a cada pull request','Ter domínio próprio e HTTPS automáticos'],
 ['bash',L('npm install -g vercel','vercel          # pergunta algumas coisas e publica uma prévia','vercel --prod   # publica na versão de produção'),'Também dá para conectar o repositório pelo site, sem instalar nada: a cada push, o site é atualizado. Alternativas: GitHub Pages, Cloudflare Pages, Render e Railway.'],
 null,['nextjs','hospedagem','cdn','serverless','cicd'],{tags:'vercel netlify hospedagem frontend deploy render railway github pages'}),

E('cloudflare','Cloudflare','CDN, DNS, proteção e funções na borda',2,
 'A **Cloudflare** é uma empresa que fica na frente do seu site. Oferece DNS rápido, CDN, proteção contra ataques, certificado HTTPS gratuito e um plano gratuito que atende muita gente. Também tem produtos para desenvolvedores: **Workers**, funções que rodam na borda; **Pages**, hospedagem de sites; **R2**, armazenamento de arquivos; e **D1**, um banco de dados.',
 'É a **portaria blindada com filiais do almoxarifado em todo canto**: filtra quem entra, guarda cópias perto do cliente e ainda resolve parte do pedido sem ele chegar à fábrica.',
 ['Proteger e acelerar um site','Gerenciar o DNS do domínio','Rodar funções perto do usuário, em dezenas de países'],
 ['javascript',L('// Cloudflare Worker - responde direto na borda, perto do visitante','export default {','  async fetch(request) {','    const pais = request.cf?.country ?? "?";','    return new Response("Olá, visitante de " + pais);','  },','};'),'O Worker roda no ponto de presença mais próximo de quem acessou. Não existe servidor para você administrar.'],
 null,['cdn','dns','ddos','serverless','edge'],{tags:'cloudflare workers pages r2 d1 waf dns cdn'}),

E('backup','Backup e recuperação','A cópia que salva o dia, se você testar',1,
 '**Backup** é uma cópia dos seus dados guardada em outro lugar, para você recuperar se algo der errado: disco que queima, arquivo apagado sem querer, ataque de ransomware. A regra clássica é a **3-2-1**: três cópias dos dados, em dois tipos diferentes de mídia, com uma delas fora do local. E o mais esquecido: **backup que nunca foi testado não é backup**. Teste a restauração de vez em quando.',
 'É a **peça sobressalente guardada no almoxarifado**, e não dentro da própria máquina. E, como todo técnico sabe, sobressalente que nunca foi testado pode ser justamente o que não encaixa na hora do reparo.',
 ['Recuperar dados depois de um erro humano ou de um desastre','Sobreviver a um ransomware','Cumprir exigências de retenção de dados'],
 ['bash',L('# cópia compactada, com a data no nome','tar -czf backup-$(date +%F).tar.gz /dados','','# envio para outro lugar (outro servidor ou nuvem)','rsync -avz backup-*.tar.gz usuario@servidor-reserva:/backups/'),'Junte com o cron para rodar toda noite. Ferramentas como restic e Borg fazem backups incrementais e criptografados.'],
 null,['cron','ssh','cloud','ransomware','s3'],{tags:'backup restore recuperacao 3-2-1 rsync restic ransomware',also:['seg']}),

E('devsecops','DevSecOps','Segurança em cada etapa da entrega',2,
 '**DevSecOps** é o DevOps com a **segurança embutida em cada etapa**, desde o começo, e não só uma inspeção no final. Na esteira de entrega entram verificadores automáticos: análise do código, checagem de bibliotecas com falhas conhecidas, busca de senhas esquecidas no código, escaneamento de imagens Docker e testes na aplicação rodando. As falhas são pegas quando custa pouco consertar. Esse movimento se chama **shift left**: empurrar a segurança para o início do processo.',
 'É colocar o **inspetor de qualidade em cada posto da linha**, e não só na saída. A peça com defeito é refugada no posto onde nasceu, e não depois de embalada e embarcada.',
 ['Achar vulnerabilidades antes de ir para produção','Impedir que senhas e chaves vazem no repositório','Cumprir exigências de segurança sem atrasar as entregas'],
 ['yaml',L('# etapas de segurança na esteira (GitHub Actions)','- name: Buscar senhas esquecidas no código','  uses: gitleaks/gitleaks-action@v2','- name: Verificar bibliotecas vulneráveis','  run: npm audit --audit-level=high'),'Se qualquer passo achar um problema grave, a esteira falha e a alteração não é publicada. Em ambientes sérios, fixe também a versão exata de cada action de terceiros.'],
 null,['devops','cicd','owasp','vulnerabilidades','seguranca-basica'],{tags:'sast dast sca shift left seguranca pipeline',also:['seg']}),

E('mlops','MLOps','DevOps para modelos de inteligência artificial',3,
 '**MLOps** é levar as práticas de DevOps para o mundo do machine learning. Um modelo não termina quando é treinado: precisa ser versionado, testado, publicado, monitorado e **retreinado** quando os dados do mundo real mudam e ele começa a errar, o chamado drift. O MLOps cuida dessa esteira toda: dados, treino, avaliação, publicação e vigilância. Ferramentas: MLflow, Kubeflow, DVC e plataformas de nuvem, como SageMaker e Vertex AI.',
 'É a **manutenção preditiva do próprio modelo de IA**: acompanha o desgaste, detecta quando a precisão cai e agenda a recalibração antes da peça sair fora de tolerância.',
 ['Colocar modelos em produção de forma repetível','Comparar versões de modelos e voltar para a melhor','Detectar quando o modelo piorou com o tempo'],
 ['python',L('import mlflow','','with mlflow.start_run():','    mlflow.log_param("arvores", 200)','    mlflow.log_metric("acuracia", 0.93)','    mlflow.sklearn.log_model(modelo, "modelo")'),'Cada treino fica registrado: com quais parâmetros foi feito, qual resultado deu e o arquivo do modelo. Assim dá para comparar versões e voltar para a melhor.'],
 null,['ml','devops','python','docker','ops-geral'],{tags:'mlflow kubeflow drift deploy modelo producao machine learning ops',also:['ia']}),

E('gitops','GitOps','O Git como fonte da verdade da infraestrutura',3,
 '**GitOps** é gerenciar a infraestrutura e as aplicações através do **Git**. O repositório descreve o estado desejado do sistema, e um agente dentro do cluster, como o ArgoCD ou o Flux, compara o que está rodando com o que está no Git e **corrige sozinho** qualquer diferença. Para mudar algo, você abre um pull request. O histórico do Git vira o histórico de auditoria, e voltar atrás é desfazer um commit.',
 'É manter o **projeto atualizado na pasta da planta** e uma regra: o que está instalado precisa ser igual ao que está no projeto. Se alguém mexe no campo sem registrar, o sistema reverte para o projeto.',
 ['Auditar toda mudança feita na infraestrutura','Recuperar um ambiente inteiro a partir do repositório','Revisar mudanças de infraestrutura com pull request'],
 ['yaml',L('apiVersion: argoproj.io/v1alpha1','kind: Application','metadata: { name: meuapp, namespace: argocd }','spec:','  source:','    repoURL: https://github.com/minhaempresa/infra','    path: k8s/meuapp','    targetRevision: main','  destination: { server: "https://kubernetes.default.svc", namespace: producao }','  syncPolicy:','    automated: { prune: true, selfHeal: true }'),'O ArgoCD vigia a pasta k8s/meuapp do repositório. Com o selfHeal ligado, se alguém alterar o cluster na mão, ele volta ao que está no Git.'],
 null,['git','kubernetes','iac','cicd','devops'],{tags:'argocd flux git infraestrutura declarativa'}),

E('finops','FinOps','Controlar o custo da nuvem',2,
 '**FinOps** é a prática de acompanhar e otimizar os **custos de nuvem** de forma conjunta entre engenharia, finanças e negócio. Na nuvem, qualquer pessoa cria recursos com um clique, e a conta chega no fim do mês. O FinOps traz visibilidade de quem gasta quanto, alertas de orçamento, desligamento do que está parado, escolha de tamanhos certos e descontos por compromisso de uso.',
 'É a **gestão de custos de uma planta**: medidores de energia por setor, meta de consumo, e alguém que passa desligando as luzes e as máquinas que ficaram ligadas sem ninguém usando.',
 ['Evitar susto na fatura da nuvem','Achar recursos esquecidos ligados','Dividir o custo por equipe e por projeto'],
 ['bash',L('# AWS: custo do mês por serviço','aws ce get-cost-and-usage \\','  --time-period Start=2026-10-01,End=2026-10-31 \\','  --granularity MONTHLY --metrics UnblendedCost \\','  --group-by Type=DIMENSION,Key=SERVICE'),'Boa prática para quem está aprendendo: crie um alerta de orçamento no primeiro dia e apague tudo que você criou para estudo.'],
 null,['cloud','aws','ops-geral','monitoramento'],{tags:'custo nuvem orcamento economia billing cloud cost'}),

E('edge','Edge computing','Processar perto de onde o dado nasce',3,
 '**Edge computing** é processar os dados **perto de onde eles nascem**, na borda da rede, em vez de mandar tudo para uma nuvem distante. Pode ser um mini servidor na fábrica, um gateway industrial ou uma função rodando num ponto de presença de uma CDN. Reduz o atraso, economiza banda e continua funcionando se a internet cair. É muito usado em IoT industrial, câmeras com visão computacional e veículos.',
 'É ter um **CLP local tomando decisões na máquina**, em vez de mandar cada leitura para a sala de controle central só para depois a ordem voltar. A decisão é rápida onde o processo acontece, e o relatório vai para a nuvem depois.',
 ['Decisões em tempo real, sem depender da internet','Reduzir o volume de dados enviados à nuvem','Visão computacional em câmeras de linha de produção'],
 ['python',L('# gateway na fábrica: decide localmente, avisa a nuvem só se importar','if temperatura > 90:','    desligar_motor()                    # ação imediata, sem depender da internet','    enviar_alerta_nuvem(temperatura)','else:','    guardar_para_resumo(temperatura)    # envia em lote, a cada 5 minutos'),'O que exige reação rápida fica no gateway local. O que serve para histórico e análise vai para a nuvem.'],
 null,['iiot','mqtt','cloudflare','cdn','clp'],{tags:'borda edge computing iot gateway latencia',also:['ind']}),

E('s3','Armazenamento de objetos (S3)','Prateleiras infinitas para arquivos na nuvem',2,
 'O **armazenamento de objetos**, cujo exemplo mais famoso é o **Amazon S3**, guarda arquivos como fotos, vídeos, backups e relatórios em baldes, os buckets, e entrega cada um por um endereço. Não é um disco de computador: não tem pastas de verdade, nem se edita um pedaço do arquivo; você envia e baixa o arquivo inteiro. É barato, praticamente ilimitado e muito durável. Alternativas compatíveis: Cloudflare R2, Google Cloud Storage, Azure Blob e MinIO.',
 'É o **almoxarifado externo com prateleira infinita**: cada caixa tem uma etiqueta, o nome do objeto, e você pede pela etiqueta. Não dá para abrir a caixa e trocar uma peça lá dentro; você manda uma caixa nova.',
 ['Guardar imagens e arquivos enviados pelos usuários','Hospedar sites estáticos','Guardar backups e dados para análise'],
 ['javascript',L('import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";','','const s3 = new S3Client({ region: "sa-east-1" });','','await s3.send(new PutObjectCommand({','  Bucket: "fabrica-relatorios",','  Key: "2026/10/producao.pdf",','  Body: arquivoPdf,','}));'),'A chave (Key) parece um caminho de pastas, mas é só o nome do objeto. Nunca deixe um bucket público sem querer: vazamentos de dados por esse motivo são comuns.'],
 null,['aws','cloud','backup','cdn','cloudflare'],{tags:'bucket objeto armazenamento minio r2 blob gcs'}),

E('vpc','Redes na nuvem (VPC)','A sua rede privada dentro da nuvem',3,
 'Uma **VPC**, Virtual Private Cloud, é a sua **rede privada dentro da nuvem**. Você define a faixa de endereços, divide em **sub-redes**, públicas, com acesso à internet, e privadas, sem acesso direto, e controla o tráfego com **security groups**, que são firewalls por máquina. O banco de dados fica numa sub-rede privada, e só o balanceador fica exposto.',
 'É a **planta da fábrica com cercas e portões**: o pátio de visitantes é público, a área de produção é restrita, a sala do cofre é trancada. Cada portão só abre para quem tem autorização.',
 ['Isolar o banco de dados da internet','Controlar quem fala com quem dentro da nuvem','Ligar a nuvem à rede da empresa por VPN'],
 ['desenho',L('VPC 10.0.0.0/16','├── sub-rede pública  10.0.1.0/24  → balanceador de carga (acesso da internet)','├── sub-rede privada  10.0.2.0/24  → servidores da aplicação','└── sub-rede privada  10.0.3.0/24  → banco de dados (só o app fala com ele)'),'O /16 e o /24 indicam o tamanho de cada faixa de endereços. É o mesmo conceito de sub-rede da entrada de IP.'],
 null,['ip','aws','vpn','firewall','cloud'],{tags:'vpc sub-rede subnet security group rede privada virtual cloud',also:['seg']}),

E('ssh','SSH','Entrar em outro computador com segurança, pelo terminal',1,
 'O **SSH**, Secure Shell, abre um terminal em outro computador pela rede, de forma criptografada. É assim que se administram servidores Linux: você conecta, executa comandos e copia arquivos como se estivesse na frente da máquina. Em vez de senha, o ideal é usar um **par de chaves**: a chave pública vai para o servidor, e a privada fica só com você, nunca compartilhada.',
 'É a **manutenção remota segura**: você assume o painel de uma máquina distante por uma linha criptografada, com a sua chave pessoal no lugar de uma senha anotada num papel.',
 ['Administrar servidores Linux','Copiar arquivos com segurança','Autenticar no GitHub sem digitar senha'],
 ['bash',L('ssh-keygen -t ed25519 -C "voce@notebook"      # cria o par de chaves','ssh-copy-id usuario@servidor.com                # instala a chave pública no servidor','ssh usuario@servidor.com                        # entra no servidor','scp relatorio.pdf usuario@servidor.com:/tmp/    # copia um arquivo'),'A chave privada fica em ~/.ssh e nunca sai do seu computador. Quem tem a privada entra como você.'],
 null,['linux','terminal','tls','vpn','ansible'],{tags:'ssh secure shell chave publica privada scp remoto',also:['seg']}),

E('deploy','Deploy e estratégias de publicação','Colocar a versão nova no ar sem derrubar nada',2,
 '**Deploy** é colocar uma nova versão do sistema no ar. Existem estratégias para fazer isso sem derrubar o serviço: **rolling**, que troca os servidores aos poucos; **blue-green**, que mantém dois ambientes completos e vira a chave de um para o outro; e **canary**, que libera para uma pequena parte dos usuários e só continua se tudo estiver bem. E um plano de **rollback**, a volta rápida para a versão anterior, é obrigatório.',
 'É a **troca de uma linha de produção**. Você não para tudo na sexta e reza. Monta a linha nova ao lado, no blue-green, testa com um lote pequeno, no canary, e se algo der errado volta a produzir na linha antiga em minutos, no rollback.',
 ['Atualizar o sistema sem parar o atendimento','Descobrir problemas com poucos usuários afetados','Voltar atrás rápido quando algo dá errado'],
 ['estratégias',L('Rolling:     v1 v1 v1 v1  →  v2 v1 v1 v1  →  v2 v2 v1 v1  →  v2 v2 v2 v2','Blue-green:  [azul v1 ativo] [verde v2 pronto]  →  chave vira  →  [verde v2 ativo]','Canary:      95% v1 + 5% v2  →  se estiver tudo bem: 50/50  →  100% v2'),'No blue-green, o rollback é virar a chave de volta. No canary, o risco fica limitado a uma fatia pequena dos usuários.'],
 null,['cicd','kubernetes','loadbalancer','git','ambientes'],{tags:'deploy rollback blue green canary rolling release publicacao'}),

E('hospedagem','Hospedagem e VPS','Onde o seu site mora',1,
 '**Hospedagem** é o lugar onde seu site ou sistema fica rodando, ligado o dia todo. Opções comuns: **hospedagem compartilhada**, barata, com vários sites num servidor e pouco controle; **VPS**, um servidor virtual só seu, com acesso total; **servidor dedicado**; **nuvem**, como AWS, Azure e Google; e **plataformas** como Vercel, Netlify, Render e Railway, que cuidam do servidor por você. Além disso, você precisa de um **domínio**, o nome do site, que se registra à parte.',
 'O domínio é o **endereço da rua**, e a hospedagem é o **terreno com o galpão**. Compartilhada é uma sala num galpão dividido. VPS é um galpão só seu, alugado. Dedicado é o prédio inteiro. E plataforma é alugar já com a equipe de manutenção incluída.',
 ['Escolher onde publicar um site ou sistema','Entender a diferença entre domínio e hospedagem','Saber quando vale sair do compartilhado para um VPS'],
 ['comparativo',L('Tipo              Custo            Controle     Bom para','Compartilhada     baixo            pouco        sites simples e WordPress','VPS               baixo a médio    total        APIs, sistemas e estudo','Plataforma        grátis a médio   médio        front-end e protótipos','Nuvem             paga pelo uso    total        sistemas em escala'),'Para estudar, comece por uma plataforma gratuita. Quando precisar mexer no servidor, vá para um VPS.'],
 null,['vercel','cloud','dns','nginx','linux'],{tags:'hospedagem vps hosting dominio servidor compartilhada dedicado hostinger'}),

E('alta-disponibilidade','Alta disponibilidade','Continuar no ar mesmo quando algo falha',3,
 '**Alta disponibilidade** é projetar o sistema para continuar funcionando mesmo quando uma peça falha. A receita é **redundância**: dois ou mais de tudo, como servidores, bancos, links de internet e até data centers, com **failover** automático, que é a troca para o reserva quando o principal cai. A disponibilidade se mede em noves: 99,9% permite cerca de 8,7 horas de parada por ano, e 99,99% permite cerca de 52 minutos.',
 'É a **máquina reserva com partida automática**: o gerador que assume sozinho quando a energia cai, o motor em stand-by que entra no lugar do principal. Custa dobrar o equipamento, mas a produção não para.',
 ['Sistemas que não podem parar, como bancos e hospitais','Cumprir acordos de nível de serviço','Atualizar partes do sistema sem derrubar o todo'],
 ['tabela dos noves',L('Disponibilidade   Parada permitida por ano','99%               3,65 dias','99,9%             8,76 horas','99,99%            52,6 minutos','99,999%           5,26 minutos'),'Cada nove a mais custa muito mais caro. Por isso é uma decisão de negócio: quanto vale uma hora de parada para essa empresa?'],
 null,['loadbalancer','escalabilidade','sre','backup','kubernetes'],{tags:'ha failover redundancia sla disponibilidade uptime noves'}),

E('escalabilidade','Escalabilidade','Aguentar mais carga: maior ou mais máquinas',2,
 '**Escalar** é aguentar mais carga. Há dois jeitos. O **vertical** troca a máquina por uma maior, com mais CPU e memória: é simples, mas tem teto e exige parada. O **horizontal** coloca mais máquinas iguais trabalhando juntas, com um balanceador na frente: é mais flexível e é a base da nuvem, mas o sistema precisa ser feito para isso, por exemplo sem guardar estado dentro do servidor. O **autoscaling** liga e desliga máquinas sozinho conforme a demanda.',
 'Vertical é **trocar o motor por um de maior potência**. Horizontal é **colocar mais motores em paralelo**. O segundo aguenta mais e continua rodando se um falhar, mas exige que o sistema divida bem a carga.',
 ['Preparar o sistema para picos, como a Black Friday','Gastar menos fora do horário de pico, com autoscaling','Evitar que um servidor único seja ponto de falha'],
 ['yaml',L('apiVersion: autoscaling/v2','kind: HorizontalPodAutoscaler','metadata: { name: meuapp }','spec:','  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: meuapp }','  minReplicas: 2','  maxReplicas: 10','  metrics:','    - type: Resource','      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }'),'Mantém entre 2 e 10 cópias do app, aumentando quando o uso médio de CPU passa de 70%.'],
 null,['loadbalancer','kubernetes','alta-disponibilidade','cache','cloud'],{tags:'escalar vertical horizontal autoscaling desempenho carga'}),

E('incidentes','Incidentes e post-mortem','O que fazer quando o sistema cai',2,
 'Um **incidente** é quando o serviço quebra ou degrada. O processo maduro tem: **detecção**, por alarme; **resposta**, em que alguém de plantão, o on-call, assume; **comunicação**, para avisar clientes e equipe; **mitigação**, em que primeiro se restaura o serviço e depois se investiga; e, no fim, o **post-mortem**: um documento sem culpados que conta a linha do tempo, a causa raiz e as ações para não repetir. Existem também os **runbooks**, roteiros prontos para as falhas conhecidas.',
 'É o **procedimento de parada de emergência**: plantão de manutenção, ordem de serviço e, depois, a **análise de causa raiz**, com os cinco porquês. O runbook é o procedimento operacional padrão de cada falha conhecida.',
 ['Restaurar o serviço rápido e com calma','Aprender com a falha em vez de procurar culpado','Reduzir o tempo para reparo na próxima vez'],
 ['modelo',L('# Post-mortem: API de pedidos fora do ar (07/10, 14h12 às 15h03)','Impacto:          cerca de 1.200 pedidos não concluídos','Causa raiz:       a migração rodou sem índice e travou a tabela','Linha do tempo:   14h12 alarme / 14h20 on-call assume / 14h48 migração revertida / 15h03 normal','O que funcionou:  o alerta disparou em 2 minutos','O que melhorar:   testar migrações com uma cópia do banco de produção','Ações:            revisar toda migração com EXPLAIN; ensaiar rollback todo mês'),'Escrito sem apontar culpados. A pergunta certa é o que no processo permitiu isso, e não quem errou.'],
 null,['sre','monitoramento','logs','alta-disponibilidade','bug-debug'],{tags:'incidente postmortem on-call plantao runbook causa raiz 5 porques mttr'}),

E('permissoes-linux','Permissões no Linux','Quem pode ler, escrever e executar cada arquivo',1,
 'No Linux, todo arquivo tem um **dono**, um **grupo** e três tipos de permissão para cada um: **ler**, **escrever** e **executar**. Isso forma três blocos: dono, grupo e outros. O comando **chmod** muda as permissões, e o **chown** muda o dono. Errar nisso é uma das causas mais comuns do erro permission denied, e também de falhas de segurança, como deixar um arquivo de senhas legível para todos.',
 'É o **controle de acesso por crachá em cada sala**. O dono da sala pode tudo. A equipe, o grupo, só entra e olha. Os visitantes, os outros, nem entram. Cada porta tem sua regra.',
 ['Resolver o erro permission denied','Tornar um script executável','Proteger arquivos sensíveis, como chaves e senhas'],
 ['bash',L('ls -l script.sh','# -rwxr-xr-- 1 usuario equipe 120 out 7 script.sh','#  │└┬┘└┬┘└┬┘','#  │ │  │  └ outros: só ler (r--)','#  │ │  └ grupo: ler e executar (r-x)','#  │ └ dono: ler, escrever, executar (rwx)','','chmod 750 script.sh     # 7=rwx  5=r-x  0=---','chmod +x script.sh      # dá permissão de executar'),'O número do chmod é uma soma: r vale 4, w vale 2 e x vale 1. Então 7 é tudo, 5 é ler e executar e 0 é nada. Nunca use chmod 777, que libera tudo para todo mundo.'],
 null,['linux','terminal','bash','ssh','seguranca-basica'],{tags:'chmod chown rwx permissao usuario grupo root sudo',also:['seg','base']}),

E('systemd','Serviços e systemd','Manter um programa rodando como serviço no Linux',2,
 'Um **serviço** é um programa que roda em segundo plano, sempre disponível: o servidor web, o banco de dados, a sua API. No Linux moderno, quem gerencia isso é o **systemd**: liga os serviços quando a máquina inicia, reinicia se caírem e guarda os logs. Você descreve o serviço num arquivo curto e controla tudo com o comando **systemctl**.',
 'É o **supervisor do turno**: liga as máquinas na partida, religa as que desarmaram e anota as ocorrências no livro de bordo.',
 ['Deixar a sua API rodando mesmo depois de reiniciar o servidor','Reiniciar automaticamente se o programa travar','Ver os logs de um serviço'],
 ['ini',L('# /etc/systemd/system/meuapp.service','[Unit]','Description=Minha API','After=network.target','','[Service]','User=app','WorkingDirectory=/opt/meuapp','ExecStart=/usr/bin/node servidor.js','Restart=on-failure','','[Install]','WantedBy=multi-user.target'),'Depois: sudo systemctl enable --now meuapp liga agora e na partida. Use systemctl status meuapp para ver o estado e journalctl -u meuapp -f para ver os logs.'],
 null,['linux','logs','nginx','processos','bash'],{tags:'systemd systemctl servico daemon linux unit journalctl'}),

E('automacao','Automação de tarefas','Fazer o computador repetir o que você repete',1,
 'Tudo que você faz mais de umas poucas vezes, do mesmo jeito, pode ser **automatizado**. Os níveis: **scripts** em Bash, Python ou PowerShell, para tarefas no computador; **agendadores**, como o cron, para rodar em horário marcado; **ferramentas sem código**, como n8n, Zapier, Make e Power Automate, que ligam aplicativos com blocos; e **RPA**, como UiPath, que opera telas de sistemas antigos como um robô que clica. A pergunta de ouro é quanto tempo se gasta nisso por mês, e quanto custa automatizar.',
 'É a mesma lógica de **automatizar um posto de trabalho**: se o operador repete o mesmo movimento mil vezes por turno, vale instalar um dispositivo. Mas só compensa se o investimento se pagar na produção.',
 ['Eliminar tarefas repetitivas e manuais','Reduzir erros de digitação e de esquecimento','Liberar tempo para o trabalho que exige raciocínio'],
 ['python',L('# renomeia todos os PDFs da pasta, colocando a data na frente','from pathlib import Path','from datetime import date','','hoje = date.today().isoformat()','for pdf in Path("relatorios").glob("*.pdf"):','    pdf.rename(pdf.with_name(f"{hoje}_{pdf.name}"))'),'Em seis linhas, um trabalho que seria de minutos de cliques repetidos. Teste primeiro numa cópia da pasta, porque renomear arquivos não tem volta fácil.'],
 null,['python','bash','cron','powershell','vba'],{tags:'automatizar rpa n8n zapier make power automate script scripts repetitivo'})
]);
