/* ===== IA e ciência de dados (parte 1: fundamentos) ===== */
C('ia',[
E('ia','Inteligência artificial','Máquinas que fazem tarefas que normalmente exigem inteligência humana',1,
 '**IA** é o nome do campo inteiro: fazer computadores executarem tarefas que, em geral, exigem inteligência humana, como reconhecer imagens, entender texto, traduzir, jogar ou decidir. Dentro dela ficam o **aprendizado de máquina**, em que o computador aprende com dados, o **deep learning**, com redes neurais grandes, e a **IA generativa**, que cria texto, imagem, áudio e código. Hoje, quando alguém fala de IA, quase sempre quer dizer um modelo treinado com muitos dados, e não um robô consciente. Ela erra, não entende como uma pessoa e precisa de supervisão.',
 'É como a **automação industrial** em geral: tem desde o relé simples até o sistema de visão que inspeciona peça. IA é o nome do guarda-chuva. Aprendizado de máquina, deep learning e modelos de linguagem são ferramentas de dentro dele, cada uma para um tipo de serviço.',
 ['Entender o mapa: IA, aprendizado de máquina, deep learning e IA generativa','Saber o que a IA faz bem (achar padrões em muitos dados) e o que faz mal (entender de verdade e ser sempre correta)','Ver onde ela já está no dia a dia: busca, tradução, câmera do celular, recomendações e assistentes','Escolher quando usar IA e quando uma regra simples resolve melhor'],
 ['estrutura',L('IA (o guarda-chuva)','└─ Aprendizado de máquina       aprende com dados','   └─ Deep learning            redes neurais grandes','      └─ IA generativa         cria texto, imagem, código','         └─ Modelos de linguagem   (LLMs)'),'Cada nível é uma parte do de cima. Nem toda IA usa aprendizado de máquina, porque existem sistemas feitos só de regras, mas quase toda a IA moderna usa.'],
 null,['ml','deeplearning','llm','ia-generativa','datascience','etica-ia'],{alt:'Em inglês: AI (Artificial Intelligence). Termos próximos: automação inteligente e sistemas especialistas (a IA antiga, baseada em regras).',tags:'ia inteligencia artificial ai machine learning aprendizado robo'}),

E('ml','Aprendizado de máquina','Em vez de escrever as regras, você mostra exemplos e o computador descobre as regras',1,
 'No **aprendizado de máquina** (machine learning), você não programa as regras na mão. Você entrega **muitos exemplos** e o computador **descobre sozinho o padrão** que liga a entrada ao resultado. Depois usa esse padrão em dados novos. Em vez de escrever “se a vibração passar de tanto, avise”, você mostra o histórico de milhares de leituras, marcando quais vieram antes de uma quebra, e o modelo aprende a reconhecer o que antecede a falha. A qualidade depende muito dos **dados**: lixo entrando, lixo saindo.',
 'É a diferença entre **escrever o manual** e **treinar um operador veterano**. Em vez de redigir a regra, você deixa o novato acompanhar mil ocorrências, e ele passa a sentir o barulho de um rolamento prestes a falhar, mesmo sem saber explicar a regra.',
 ['Resolver problemas em que escrever as regras à mão seria impossível, como reconhecer um rosto ou uma peça defeituosa','Prever a partir do histórico: falha de máquina, demanda, preço, cancelamento de cliente','Classificar e agrupar dados: spam ou não, tipos de cliente, tipos de falha','Entender por que dados bons e bem rotulados valem mais que um modelo sofisticado'],
 ['python',L('from sklearn.tree import DecisionTreeClassifier','','# [vibração em mm/s, temperatura em °C] de leituras antigas','leituras = [[2, 60], [3, 65], [2.5, 62], [9, 90], [8, 85], [10, 95]]','# 0 = funcionou bem, 1 = quebrou depois','resultado = [0, 0, 0, 1, 1, 1]','','modelo = DecisionTreeClassifier()','modelo.fit(leituras, resultado)       # aprende o padrão','','# uma leitura nova, que o modelo nunca viu','print(modelo.predict([[7, 88]]))     # [1]  ->  provável falha'),'O fit é o “treinamento”: o modelo olha os exemplos e descobre o padrão. O predict usa o padrão numa leitura nova. Os números são inventados, só para mostrar a ideia.'],
 'treino',['ia','tipos-aprendizado','classificacao-regressao','overfitting','scikit','datascience'],{alt:'Bibliotecas: scikit-learn, XGBoost e LightGBM. Em inglês: machine learning (ML).',tags:'ml machine learning aprendizado de maquina modelo treino dados padrao'}),

E('tipos-aprendizado','Aprendizado supervisionado, não supervisionado e por reforço','Três jeitos de uma máquina aprender',2,
 'Há três jeitos principais de treinar um modelo. No **supervisionado**, cada exemplo vem com a **resposta certa**, como a foto e o rótulo “peça boa” ou “peça ruim”, e o modelo aprende a acertar. No **não supervisionado**, não há resposta: o modelo procura **estrutura sozinho**, como agrupar clientes parecidos ou achar leituras estranhas. No **por reforço**, um agente age num ambiente e recebe **recompensas ou punições**, aprendendo por tentativa e erro, como um robô que aprende a andar. Os grandes modelos de linguagem misturam: aprendem prevendo a próxima palavra e depois são ajustados com feedback humano.',
 '**Supervisionado** é aprender com um instrutor que corrige cada peça. **Não supervisionado** é largar o aprendiz numa pilha de peças sem etiqueta, e ele separa em montes parecidos. **Por reforço** é ensinar o ajuste de uma máquina por tentativa e erro: acertou, ganha um elogio; errou, perde tempo.',
 ['Saber qual tipo serve para cada problema: prever um valor, agrupar, detectar anomalias ou aprender uma estratégia','Entender por que dados rotulados dão trabalho e custam caro','Reconhecer onde cada um aparece: filtro de spam, segmentação de clientes, robôs e jogos','Entender o que é o feedback humano de que se fala nos assistentes de IA'],
 ['comparativo',L('Tipo                Dados                        Exemplo','------------------  ---------------------------  ----------------------------','Supervisionado      entrada + resposta certa     foto -> peça boa ou ruim','Não supervisionado  só a entrada                 agrupar clientes parecidos','Por reforço         ações e recompensas          robô aprendendo a andar'),'A maior parte da IA que se vê no dia a dia é supervisionada. Rotular dados, ou seja, dizer qual é a resposta certa de milhares de exemplos, costuma ser a parte mais cara do projeto.'],
 null,['ml','classificacao-regressao','rede-neural','llm','anomalia'],{alt:'Variantes: semissupervisionado e autossupervisionado, que é o usado para treinar os modelos de linguagem. Em inglês: supervised, unsupervised e reinforcement learning.',tags:'supervisionado nao supervisionado reforco aprendizado rotulo reinforcement'}),

E('classificacao-regressao','Classificação, regressão e agrupamento','As três tarefas mais comuns: dar uma categoria, um número ou um grupo',2,
 'Quase todo problema de aprendizado de máquina cai numa destas tarefas. **Classificação**: o modelo escolhe uma **categoria**, como e-mail spam ou não, peça boa, duvidosa ou ruim. **Regressão**: o modelo devolve um **número**, como quantas horas faltam para a próxima falha, o preço de um imóvel ou o consumo de energia de amanhã. **Agrupamento**, ou clustering: sem categorias prontas, ele separa os dados em **grupos parecidos**. Saber qual das três é o seu problema é o primeiro passo para escolher o modelo e a forma de medir o resultado.',
 'Classificação é o **inspetor** que carimba “aprovada” ou “reprovada”. Regressão é o **medidor** que lê um número numa escala. Agrupamento é separar um **lote de parafusos** sem etiqueta em caixas, por tamanho parecido.',
 ['Transformar uma pergunta do negócio na tarefa certa de aprendizado de máquina','Escolher como medir o resultado: acerto para classificação, erro médio para regressão','Usar agrupamento para descobrir padrões quando ainda não existem categorias','Reconhecer cada tarefa nos produtos do dia a dia, como filtro de spam, previsão de demanda e segmentação de clientes'],
 ['estrutura',L('Pergunta                                    Tarefa','------------------------------------------  -------------','Esta peça tem defeito? (sim ou não)         classificação','Em quantas horas este rolamento vai falhar?  regressão','Que tipos de falha existem no histórico?     agrupamento'),'Se a resposta é uma categoria, é classificação. Se é um número numa escala, é regressão. Se você ainda nem sabe quais são as categorias, é agrupamento.'],
 null,['ml','tipos-aprendizado','metricas-ml','scikit','anomalia'],{alt:'Algoritmos conhecidos: regressão linear e logística, árvores de decisão, random forest, K-means (agrupamento) e redes neurais.',tags:'classificacao regressao agrupamento clustering kmeans previsao categoria numero'}),

E('rede-neural','Rede neural','Uma conta gigante feita de neurônios simples que ajustam os próprios pesos',2,
 'Uma **rede neural** é um modelo feito de muitas pequenas unidades, os **neurônios artificiais**. Cada neurônio recebe números, **multiplica cada um por um peso**, soma tudo e passa o resultado por uma função que decide o quanto ele “acende”. Camadas desses neurônios ligadas em sequência formam a rede. O **treinamento** ajusta os pesos aos poucos, para a saída chegar perto da resposta certa dos exemplos. Não tem nada de cérebro de verdade: é matemática, só que em escala enorme.',
 'Um neurônio é como um **inversor com potenciômetros nas entradas**: cada sinal passa por um ajuste, o peso, os sinais se somam e, se passar do limite, a saída liga. Treinar é ficar girando os potenciômetros até a máquina responder certo. A rede inteira é milhões desses ajustes juntos.',
 ['Reconhecer imagens, voz e texto, onde regras escritas à mão não dão conta','Entender o que são pesos e parâmetros: os potenciômetros ajustados no treino','Perceber por que treinar redes grandes exige tanto poder de cálculo','Mexer num neurônio de verdade na demonstração: ajustar pesos e ver a decisão mudar'],
 ['python',L('# Um neurônio, à mão: 2 entradas, 2 pesos e um limite (bias)','vibracao, temperatura = 7.0, 80.0','peso_v, peso_t, bias = 0.6, 0.3, -25.0','','soma = vibracao * peso_v + temperatura * peso_t + bias   # 4.2 + 24 - 25 = 3.2','decisao = 1 if soma > 0 else 0        # 1 = parar a máquina','print(soma, decisao)'),'Multiplica cada entrada pelo seu peso, soma tudo e compara com zero. O treino é o processo de achar os pesos e o bias que acertam os exemplos. Uma rede tem de milhares a bilhões desses números.'],
 'neuron',['deeplearning','ml','overfitting','pytorch','gpu-ia'],{alt:'Tipos de rede: perceptron, CNN (imagens), RNN e LSTM (sequências), Transformer (texto e muito mais), GAN e redes de difusão.',tags:'rede neural neuronio perceptron pesos bias camadas treinamento'}),

E('deeplearning','Deep learning','Redes neurais com muitas camadas, que descobrem sozinhas o que importa nos dados',2,
 'O **deep learning**, ou aprendizado profundo, usa redes neurais com **muitas camadas** empilhadas. A vantagem é que cada camada aprende algo mais abstrato que a anterior: numa imagem, as primeiras acham bordas, as do meio acham formas, as últimas reconhecem objetos. Antes, uma pessoa precisava desenhar à mão o que observar nos dados; agora a rede descobre sozinha. Isso exige **muitos dados** e **muito poder de cálculo**, e por isso explodiu quando as GPUs ficaram acessíveis. Está por trás do reconhecimento de imagem e voz, da tradução e dos modelos de linguagem.',
 'É uma **linha de produção em várias estações**: a primeira peneira o grosso, a segunda dá forma, a terceira refina e a última dá o veredito. Cada estação aprende a sua parte do serviço, sem que ninguém escreva o manual dela.',
 ['Entender por que a IA de imagem, voz e texto melhorou tanto nos últimos anos','Saber por que ela precisa de muitos dados e de GPU','Conhecer as arquiteturas mais citadas: CNN para imagens, RNN para sequências e Transformer para texto','Perceber que profundo quer dizer muitas camadas, e não que a máquina entende profundamente'],
 ['estrutura',L('Foto de uma peça','   │','   ▼','Camada 1:  bordas e contornos','Camada 2:  cantos, furos e texturas','Camada 3:  partes da peça','   │','   ▼','Saída:     "peça com trinca" (92%)'),'Cada camada recebe o que a anterior achou e monta algo mais complexo. Quem decide o que cada camada aprende é o treino, e não a pessoa que programa.'],
 null,['rede-neural','ia-generativa','llm','visao-computacional','pytorch','tensorflow','gpu-ia'],{alt:'Arquiteturas: CNN, RNN, LSTM, Transformer, GAN e modelos de difusão. Em inglês: deep learning (DL).',tags:'deep learning aprendizado profundo camadas cnn transformer redes neurais'}),

E('overfitting','Overfitting e dados de teste','Quando o modelo decora os exemplos em vez de aprender o padrão',2,
 'O **overfitting**, ou sobreajuste, acontece quando o modelo vai tão bem nos dados de treino que **decora** até o ruído e os acasos deles, e vai mal com dados novos. Para detectar, separa-se uma parte dos dados, os **dados de teste**, que o modelo nunca viu no treino. Se ele acerta 99% no treino e 70% no teste, decorou. Para evitar: mais dados, um modelo mais simples, parar o treino a tempo e técnicas de regularização. É um dos erros mais comuns de quem está começando.',
 'É o **aprendiz que decorou a prova do ano passado**: tira dez nela e reprova no exame com questões novas. O que vale é a prova que ele nunca viu. É também a máquina ajustada tão perfeitamente para uma única peça que não serve para a seguinte.',
 ['Avaliar um modelo de forma honesta, com dados que ele nunca viu','Entender por que se dividem os dados em treino, validação e teste','Desconfiar de modelos com resultados bons demais para ser verdade','Saber o que fazer quando o modelo vai bem no treino e mal na vida real'],
 ['python',L('from sklearn.model_selection import train_test_split','','# separa 80% para treinar e 20% para testar (o modelo nunca vê o teste)','x_treino, x_teste, y_treino, y_teste = train_test_split(','    leituras, resultado, test_size=0.2, random_state=42)','','modelo.fit(x_treino, y_treino)','print("treino:", modelo.score(x_treino, y_treino))   # ex.: 1.00','print("teste: ", modelo.score(x_teste, y_teste))     # ex.: 0.71  <- a nota que vale'),'Se a nota do treino é muito maior que a do teste, há overfitting. O número que vale é o do teste. Os valores nos comentários são só exemplos.'],
 null,['ml','metricas-ml','scikit','rede-neural','estatistica'],{alt:'Remédios: mais dados, validação cruzada, regularização, dropout e parada antecipada (early stopping). O contrário se chama underfitting: o modelo é simples demais para o problema.',tags:'overfitting sobreajuste treino teste validacao generalizacao decorar'}),

]);
