/* ===== IA e ciência de dados (parte 2: medir, dados e cuidados) ===== */
C('ia',[
E('metricas-ml','Acurácia, precisão e recall','Como medir se um modelo acerta, e quais erros custam mais',2,
 'Dizer “o modelo acerta 95%” pode enganar. Se só 1 peça em 100 é defeituosa, um modelo que sempre diz “peça boa” acerta 99% e não serve para nada. Por isso existem outras medidas, que saem da **matriz de confusão**, a contagem dos acertos e erros de cada tipo. **Precisão**: das peças que o modelo acusou de defeito, quantas realmente tinham. **Recall**: de todas as peças com defeito, quantas ele achou. Aumentar uma costuma diminuir a outra, e o peso de cada erro depende do negócio: deixar passar um defeito crítico custa mais que reinspecionar uma peça boa.',
 'É o **inspetor de qualidade**. Se ele é rigoroso demais, reprova peça boa: muito alarme falso, e a precisão cai. Se é bonzinho demais, deixa passar peça ruim: o recall cai. Cada fábrica escolhe onde regular o rigor, conforme o custo de cada erro.',
 ['Avaliar um modelo sem se enganar com a acurácia quando as classes são desbalanceadas','Escolher o ponto de corte conforme o custo de cada tipo de erro','Entender os termos: verdadeiro positivo, falso positivo, falso negativo e verdadeiro negativo','Conversar com cientistas de dados sobre qual métrica importa para o seu caso'],
 ['comparativo',L('                       Modelo disse: DEFEITO    Modelo disse: BOA','---------------------  -----------------------  ------------------------','Realmente defeituosa   verdadeiro positivo      falso negativo (perigoso)','Realmente boa          falso positivo           verdadeiro negativo','','Precisão = VP / (VP + FP)          Recall = VP / (VP + FN)'),'VP significa verdadeiros positivos, FP falsos positivos e FN falsos negativos. Na demonstração, mexa no ponto de corte e veja os números trocarem de lugar.'],
 'confusao',['classificacao-regressao','overfitting','visao-computacional','estatistica','anomalia'],{alt:'Outras medidas: F1 (junta precisão e recall), curva ROC e AUC. Para regressão: erro médio absoluto (MAE) e erro quadrático médio (RMSE).',tags:'acuracia precisao recall matriz de confusao falso positivo falso negativo f1 metricas'}),

E('datascience','Ciência de dados','Tirar respostas e previsões de dados, do levantamento ao gráfico',1,
 '**Ciência de dados** é o trabalho de transformar dados brutos em **respostas úteis**. O ciclo costuma ser: entender a pergunta do negócio; **coletar e limpar** os dados, a parte mais demorada; explorar com gráficos e estatística; **modelar**, às vezes com aprendizado de máquina; conferir se o resultado faz sentido; e **comunicar**, em relatório ou painel. Mistura estatística, programação (em geral Python ou R), bancos de dados e conhecimento do assunto. Quem faz é o cientista de dados. Perto dele ficam o analista de dados, que foca em relatórios, e o engenheiro de dados, que monta a tubulação.',
 'É o **técnico de manutenção investigando uma falha repetida**: junta os registros, descarta o que não presta, procura o padrão, testa uma hipótese e então apresenta a causa e a recomendação para a gerência. O modelo de IA é só uma das ferramentas da caixa.',
 ['Responder perguntas do negócio com dados, como por que as paradas aumentaram e o que vai acontecer no mês que vem','Aprender onde cada cargo entra: analista, cientista e engenheiro de dados','Entender por que limpar dados toma a maior parte do tempo de um projeto','Saber o caminho de estudo: estatística, Python, SQL, pandas e visualização'],
 ['estrutura',L('1. Pergunta do negócio    "Por que a linha 3 para tanto?"','2. Coleta e limpeza       juntar fontes, corrigir erros, tratar faltas','3. Exploração             gráficos, médias, outliers, correlações','4. Modelagem              estatística ou aprendizado de máquina','5. Validação              o resultado faz sentido? vale para dados novos?','6. Comunicação            relatório, painel ou recomendação'),'Costuma-se dizer que 60% a 80% do tempo vai para os passos 1 e 2. Dado sujo estraga qualquer modelo bom.'],
 null,['estatistica','pandas','jupyter','ml','bi','etl','python'],{alt:'Cargos próximos: analista de dados, engenheiro de dados, engenheiro de aprendizado de máquina e analista de BI.',tags:'ciencia de dados data science cientista de dados analista engenheiro limpeza modelo'}),

E('estatistica','Estatística básica','Média, mediana e desvio padrão: o que resumem e onde enganam',1,
 'A estatística resume muitos números em poucos. A **média** soma tudo e divide pela quantidade, mas é puxada por valores extremos. A **mediana** é o valor do meio quando tudo é ordenado, e quase não se mexe com extremos. O **desvio padrão** diz o quanto os valores costumam se afastar da média: pequeno quer dizer tudo parecido, grande quer dizer muita variação. Um valor muito fora do padrão é um **outlier**, que pode ser um erro de medição ou a informação mais importante de todas. Entender isso protege você de relatórios enganosos.',
 'Se numa semana as paradas de máquina levam 10, 12, 11 e 13 minutos, e uma leva 8 horas, a **média** mostra um número absurdo que não representa nenhuma parada normal. A **mediana** continua mostrando o que costuma acontecer. Quem lê só a média acha que toda parada é um desastre.',
 ['Resumir uma lista enorme de números em duas ou três informações úteis','Perceber quando a média engana e a mediana conta a história certa','Encontrar valores fora do padrão, que podem ser defeito de sensor ou um problema real','Ler com mais senso crítico relatórios, gráficos e notícias com números'],
 ['python',L('import statistics as st','','paradas = [12, 15, 9, 14, 11, 13, 10, 16, 12]     # minutos','print(st.mean(paradas), st.median(paradas))         # 12.44  12','','paradas.append(480)                                # uma parada de 8 horas','print(st.mean(paradas), st.median(paradas))         # 59.2  12.5   <- a média disparou'),'A mediana mudou de 12 para 12,5. A média foi de 12 para quase 60, por causa de um único valor. Na demonstração, você controla o tamanho da parada gigante.'],
 'media',['datascience','correlacao','metricas-ml','excel','bi','anomalia'],{alt:'Também importam: moda, quartis, percentis (o P95 é muito usado para medir desempenho), variância e distribuição normal.',tags:'estatistica media mediana desvio padrao outlier moda percentil variancia'}),

E('correlacao','Correlação não é causa','Duas coisas variarem juntas não prova que uma causa a outra',2,
 '**Correlação** mede o quanto duas coisas variam juntas. Se a temperatura do motor e o número de falhas sobem juntos, há correlação. Mas isso **não prova que uma causa a outra**: pode ser um terceiro fator influenciando as duas, como a carga de trabalho que aumentou, esquentou o motor e, separadamente, forçou a correia. Pode ser também coincidência, principalmente com poucos dados. Para afirmar uma causa é preciso experimento ou uma análise cuidadosa. Modelos de aprendizado de máquina acham correlações muito bem, e é aí que mora o perigo de tirar conclusões que os dados não sustentam.',
 'Vendas de ventilador e de sorvete sobem juntas, e ninguém acha que o ventilador faz vender sorvete: é o **calor** puxando os dois. Na fábrica, a produção cai nos dias de chuva, mas talvez o culpado seja o caminhão de matéria-prima que atrasa, e não a chuva em si.',
 ['Evitar conclusões erradas em relatórios e análises de falhas','Pensar em fatores escondidos antes de agir sobre uma correlação','Entender por que testes controlados, com e sem a mudança, são mais confiáveis que só observar','Desconfiar de manchetes do tipo estudo mostra que X causa Y'],
 ['estrutura',L('Se A e B variam juntos, pode ser que:','','1. A causa B','2. B causa A','3. Um terceiro fator C causa os dois    <- o mais comum e o mais esquecido','4. É coincidência (principalmente com poucos dados)'),'Antes de agir, pergunte o que mais poderia explicar os dois movimentos. Em manutenção, a causa raiz costuma estar atrás da primeira explicação.'],
 null,['estatistica','datascience','ml','anomalia'],{tags:'correlacao causa causalidade coincidencia fator oculto estatistica falacia'}),

E('etica-ia','Ética, vieses e privacidade na IA','Os cuidados que a IA exige, além de funcionar',2,
 'Um modelo aprende com os dados que recebe e **herda os problemas deles**. Se os dados têm preconceito, o resultado reproduz o preconceito, em escala. Há também questões de **privacidade**, com dados pessoais usados no treino ou colados num chat; de **direitos autorais**, com conteúdo de terceiros usado no treino; de **transparência**, que é saber por que o modelo decidiu aquilo; e de **responsabilidade**, ou seja, quem responde pelo erro. No uso em empresa: não cole dados sensíveis ou segredos num serviço sem conhecer as regras dele, confira o que a IA gerou antes de usar e mantenha uma pessoa responsável pela decisão final. A LGPD vale também aqui.',
 'É o **procedimento de segurança de uma máquina nova**: ela funciona, mas antes de operar você confere as proteções, quem pode mexer e o que fazer se algo sair do previsto. Máquina potente sem proteção é acidente esperando.',
 ['Saber o que não colar num assistente de IA: senhas, dados de clientes e segredos da empresa','Entender como o viés dos dados vira viés nas decisões do modelo','Cobrar revisão humana em decisões importantes, como crédito, contratação e saúde','Acompanhar as regras que estão surgindo, como o AI Act na Europa e a regulação da IA que o Brasil vem discutindo (a situação muda rápido)'],
 ['comparativo',L('Pode fazer                               Evite','---------------------------------------  ---------------------------------------','Pedir ajuda com texto genérico           Colar lista de clientes com CPF','Descrever o erro sem dados reais        Colar senha, token ou chave de API','Revisar tudo que a IA escreveu          Enviar o resultado sem conferir','Usar a ferramenta aprovada pela empresa  Usar conta pessoal para dado da empresa'),'Cada empresa tem as suas regras. Na dúvida, pergunte à TI ou ao jurídico antes. Resumo educativo, não é consultoria jurídica.'],
 null,['ia','llm','alucinacao','lgpd','prompt','assistentes'],{alt:'Termos: viés algorítmico, IA explicável (XAI), governança de IA, deepfake. Referências: AI Act (Europa) e as discussões sobre regulação da IA no Brasil.',tags:'etica ia vies privacidade direitos autorais responsabilidade transparencia lgpd regulacao'}),

E('gpu-ia','GPUs e aceleradores de IA','Por que a IA vive de placa de vídeo',2,
 'Treinar e rodar modelos de IA é, no fundo, **multiplicar matrizes enormes**, bilhões de vezes. A **GPU**, a placa de vídeo, tem milhares de núcleos simples que fazem muitas contas ao mesmo tempo, e isso cai como luva nesse trabalho, enquanto a CPU tem poucos núcleos mais espertos. A **NVIDIA** domina o mercado com o **CUDA**, a plataforma de programação das suas placas. Existem também chips feitos só para IA, como as **TPUs** do Google. Modelos grandes precisam de muita memória de vídeo, a **VRAM**, e por isso as GPUs de data center custam fortunas e são alugadas na nuvem por hora.',
 'A CPU é um **mestre de obras**: faz qualquer serviço, mas um de cada vez. A GPU é uma **turma de mil ajudantes**: cada um só sabe somar e multiplicar, mas todos trabalham juntos. Para um serviço repetitivo e gigante, a turma ganha longe.',
 ['Entender por que o preço das GPUs sobe quando a IA está em alta','Saber por que treinar um modelo grande leva dias ou semanas num conjunto de GPUs','Escolher entre rodar o modelo no seu computador, com GPU, ou alugar na nuvem','Reconhecer termos como CUDA, VRAM, TPU e NPU'],
 ['bash',L('# Ver a GPU NVIDIA, a memória de vídeo usada e os programas que a usam','nvidia-smi','','# Conferir se o PyTorch enxerga a GPU','python -c "import torch; print(torch.cuda.is_available())"'),'O nvidia-smi só existe em máquinas com placa NVIDIA e driver instalado. Em notebooks sem placa dedicada, modelos pequenos ainda rodam na CPU, só que mais devagar.'],
 null,['hardware','deeplearning','pytorch','cloud','ollama','llm'],{alt:'Fabricantes: NVIDIA (CUDA), AMD (ROCm), Intel, Apple (chips da série M) e Google (TPU). NPU é o acelerador de IA que vem em celulares e notebooks novos.',tags:'gpu placa de video nvidia cuda tpu npu vram acelerador treino ia'}),

]);
