/* ===== IA e ciência de dados (parte 3: modelos de linguagem e IA generativa) ===== */
C('ia',[
E('llm','Modelo de linguagem (LLM)','Um modelo que aprendeu a prever a próxima palavra, e por isso consegue conversar',2,
 'Um **LLM**, de large language model, ou modelo grande de linguagem, é uma rede neural treinada com uma quantidade enorme de texto para fazer uma coisa: **prever a próxima parte do texto**, a partir do que veio antes. Repetindo isso palavra por palavra, ele escreve respostas, resume, traduz e gera código. Ele não consulta um banco de fatos: o que ele sabe está espalhado nos bilhões de números, os **parâmetros**, ajustados no treino. Por isso é ótimo em linguagem e em padrões, e pode afirmar algo errado com toda a confiança. Exemplos: Claude, GPT, Gemini e Llama.',
 'É como um **operador que leu todos os manuais, relatórios e conversas de uma empresa** e agora completa qualquer frase do jeito mais provável. Escreve bem e rápido, mas não sabe de onde tirou cada coisa, e às vezes completa com algo que soa certo e não é.',
 ['Conversar, resumir, traduzir, explicar e reescrever textos','Escrever e revisar código, e transformar linguagem comum em consultas, tabelas e scripts','Ser o cérebro de assistentes e agentes que usam ferramentas','Entender por que ele erra, e como reduzir o erro com boas instruções e boas fontes'],
 ['estrutura',L('Texto até agora:   "A máquina parou por causa do"','','O modelo calcula a chance de cada próxima palavra:','   motor       38%','   rolamento   22%','   sensor      15%','   ...','','Escolhe uma, acrescenta ao texto e repete.'),'Esse é todo o truque: repetido bilhões de vezes no treino, e uma palavra de cada vez na resposta. As porcentagens aqui são só ilustração. Na demonstração, um modelo de brinquedo faz exatamente isso, só que com um texto minúsculo.'],
 'llm',['tokens','prompt','alucinacao','ia-generativa','assistentes','rag','finetuning','agentes','ollama'],{alt:'Modelos conhecidos: Claude (Anthropic), GPT (OpenAI), Gemini (Google), Llama (Meta), Mistral, Qwen e DeepSeek. Em inglês: large language model.',tags:'llm modelo de linguagem gpt claude gemini llama chatgpt transformer parametros'}),

E('tokens','Tokens e janela de contexto','As pecinhas em que o texto é cortado, e o tamanho da memória de curto prazo do modelo',2,
 'O modelo não lê letras nem palavras inteiras: lê **tokens**, pedaços de texto que podem ser uma palavra curta, parte de uma palavra ou um sinal. Em português, uma palavra costuma virar um ou dois tokens. Você é limitado e cobrado por tokens: tanto os que **entram**, ou seja, a sua pergunta e o que você colou, quanto os que **saem**, a resposta. A **janela de contexto** é o máximo de tokens que o modelo consegue considerar de uma vez: a conversa toda, os arquivos colados e a resposta. Passou do limite, o começo é esquecido ou cortado. Janelas grandes ajudam, mas encher demais atrapalha os detalhes.',
 'É a **bancada de trabalho**: cabe uma quantidade limitada de peças de uma vez. Se você empilha mais do que cabe, o que estava no fundo cai no chão. Os tokens são as **peças**, e ocupam espaço tanto as que você coloca quanto as que ele produz.',
 ['Entender por que a conversa esquece o começo quando fica muito longa','Estimar custo e limite de uso de uma API, que é cobrada por token','Saber por que o português gasta um pouco mais de tokens que o inglês','Ser econômico: colar só o trecho necessário, e não o arquivo inteiro'],
 ['estrutura',L('Texto:   A manutenção preventiva evita paradas.','Tokens:  A | manuten | ção | prevent | iva | evita | par | adas | .'),'Ilustração: a divisão real depende do modelo. Como regra prática, em português um token vale em torno de 3 a 4 letras, então 100 palavras ficam entre 150 e 200 tokens.'],
 null,['llm','prompt','assistentes','rag','embeddings'],{alt:'Termos: tokenizador, BPE (byte pair encoding), janela de contexto, limite de saída e cache de prompt.',tags:'tokens token janela de contexto contexto limite custo tokenizacao bpe'}),

E('prompt','Prompt e engenharia de prompt','Como pedir bem: o que escrever para a IA entregar o que você quer',1,
 '**Prompt** é o texto que você entrega ao modelo: a pergunta, as instruções e o material de apoio. A **engenharia de prompt** é o jeito de escrever isso para obter respostas melhores. Funciona como delegar a um colega muito capaz que não sabe nada do seu contexto: diga o **objetivo**, o **contexto**, o **formato** da resposta que você quer, os **limites** e, se puder, um **exemplo**. Peça para ele perguntar se faltar informação, e revise o resultado. Instruções claras e específicas ganham de truques mágicos.',
 'É a **ordem de serviço**. “Arruma a máquina” dá retrabalho. “Trocar a correia da esteira 2, com a peça do almoxarifado, e testar por 10 minutos” dá resultado. Quanto melhor a ordem, menos idas e vindas.',
 ['Receber respostas mais úteis e menos genéricas','Padronizar tarefas repetidas com modelos de prompt','Dar um papel, um formato e exemplos, para a resposta sair no jeito certo','Entender que é uma conversa: dá para pedir ajustes e correções'],
 ['prompt',L('Objetivo:  Escrever o procedimento de troca de correia da esteira 2.','Contexto:  Sou técnico de manutenção. O texto vai para o manual da oficina.','Formato:   Lista numerada, no máximo 8 passos, com um aviso de segurança no início.','Limites:   Linguagem simples. Não invente códigos de peça.','Dúvidas:   Se faltar informação, pergunte antes de escrever.'),'Cada linha responde a uma dúvida que o modelo teria. A última evita que ele invente para preencher lacunas. Depois, confira o resultado: a responsabilidade pelo que sai é sua.'],
 null,['llm','tokens','alucinacao','assistentes','agentes','rag'],{alt:'Técnicas: exemplos no próprio prompt (few-shot), raciocínio passo a passo, instruções de sistema e respostas em formato estruturado, como JSON.',tags:'prompt engenharia de prompt instrucoes pedir ia few shot sistema contexto'}),

E('alucinacao','Alucinação e limites da IA','Quando o modelo responde errado com toda a confiança',2,
 'A **alucinação** acontece quando o modelo **inventa**: cita uma lei que não existe, um artigo que ninguém escreveu, uma função que a biblioteca não tem, tudo em tom seguro. Acontece porque ele foi treinado para produzir texto **plausível**, e não para checar fatos. Reduz-se dando as fontes e pedindo que responda só com base nelas, como no **RAG**; pedindo citações e **conferindo** cada uma; dando acesso a ferramentas de busca e de cálculo; e revisando. Outros limites: conhecimento parado na data do treino, contas e contagens que falham, e dificuldade com informação muito recente ou muito específica.',
 'É o **funcionário que não admite que não sabe**: em vez de dizer “não sei”, preenche o laudo com algo que parece certo. Quem confere só o formato do laudo não percebe. Confiar sem verificar, em peça crítica, é pedir acidente.',
 ['Saber por que nunca se deve copiar a resposta da IA sem conferir, principalmente em saúde, lei, números e segurança','Aprender a pedir fontes e a verificar cada uma','Entender como o RAG e as ferramentas de busca reduzem o problema','Perceber os limites: cálculo, contagem, datas recentes e assuntos muito específicos'],
 ['comparativo',L('Pergunta arriscada                  Jeito mais seguro','---------------------------------   ---------------------------------------','"Qual norma exige isso?"            Pedir a norma, abrir a fonte e conferir','"Quanto é 18% de 4.372?"            Usar calculadora ou código','"Explique este erro" (sem o erro)   Colar o erro e o trecho de código real'),'Quando a resposta importa, trate o que a IA disse como uma sugestão a ser confirmada, e não como um fato.'],
 null,['llm','rag','prompt','etica-ia','assistentes'],{alt:'Em inglês: hallucination. Formas de reduzir: RAG, pedir citações, verificação automática e temperatura baixa.',tags:'alucinacao hallucination erro ia inventa fonte confiar verificar limites'}),

E('ia-generativa','IA generativa','IA que cria texto, imagem, áudio, vídeo e código',1,
 'A **IA generativa** é a que **cria conteúdo novo**, em vez de só classificar ou prever. Gera **texto**, com os modelos de linguagem; **imagem**, a partir de uma descrição; **áudio e música**; **voz**; **vídeo**; e **código**. Muitos modelos de imagem usam a técnica da **difusão**: partem de um ruído e vão limpando até aparecer uma imagem que combine com o pedido. O resultado impressiona, mas não é garantia de verdade: imagens e vídeos podem ser falsos de propósito, os **deepfakes**, e o conteúdo gerado pode ter problemas de direitos autorais e de qualidade.',
 'É a diferença entre o **inspetor**, que olha a peça e diz se está boa, e o **torneiro**, que faz a peça nova a partir de um desenho. A IA generativa é o torneiro, só que às vezes entrega uma peça que parece perfeita e não encaixa.',
 ['Criar rascunhos de texto, imagens, apresentações, músicas e código mais rápido','Transformar linguagem comum em protótipos de interface, planilhas e scripts','Acelerar tarefas repetitivas de escrita e de design, sempre com revisão','Reconhecer os riscos: deepfakes, golpes com voz clonada e conteúdo usado sem conferir'],
 ['comparativo',L('Texto    modelo de linguagem   "escreva um e-mail pedindo orçamento de rolamentos"','Imagem   modelo de difusão     "oficina limpa e organizada, luz natural"','Áudio    síntese de voz        "leia este aviso em tom calmo"','Código   modelo de linguagem   "crie um script que renomeia os arquivos da pasta"','Vídeo    modelo de difusão     "câmera passando por uma linha de montagem"'),'Cada tipo de conteúdo tem seus próprios modelos, mas o jeito de pedir é parecido: você descreve o que quer em linguagem comum e o modelo gera. Os pedidos acima são só exemplos.'],
 null,['llm','deeplearning','assistentes','etica-ia','prompt'],{alt:'Famílias: modelos de linguagem (texto), de difusão (imagem e vídeo), GANs e modelos de áudio. Em inglês: generative AI.',tags:'ia generativa genai imagem video audio difusao deepfake midjourney dalle stable diffusion'}),

E('assistentes','Assistentes de IA (Claude, ChatGPT, Gemini…)','Chats que usam um modelo de linguagem, com ferramentas e memória em volta',1,
 'Um **assistente de IA** é um produto que coloca um modelo de linguagem dentro de um chat e costuma somar **ferramentas**: busca na web, leitura de arquivos, geração de imagens, execução de código e conexão com apps como e-mail e agenda. Os mais conhecidos são o **Claude**, da Anthropic, o **ChatGPT**, da OpenAI, o **Gemini**, do Google, o **Copilot**, da Microsoft, e o **Meta AI**. Cada um muda em modelo, limites, preço e recursos, e tudo isso muda rápido. Escolha pela tarefa, teste mais de um e lembre das regras de privacidade: o que você digita vai para os servidores da empresa.',
 'O modelo é o **motor**; o assistente é o **carro completo**, com painel, direção, freios e porta-malas. Dois carros com motores parecidos podem ser muito diferentes de dirigir.',
 ['Ter um ajudante para escrever, estudar, pesquisar, resumir e organizar ideias','Trabalhar com arquivos: ler PDFs, planilhas e imagens, e gerar documentos','Automatizar tarefas, conectando o assistente aos seus apps','Comparar produtos e saber o que checar: privacidade, limites de uso, custo e idioma'],
 ['comparativo',L('Quero...                         Recurso do assistente','------------------------------  -------------------------------------------','Resumir um PDF                  enviar o arquivo e pedir o resumo','Dado atual (preço, notícia)     ligar a busca na web e pedir as fontes','Conta ou análise de planilha    pedir para rodar código e mostrar o resultado','Agendar ou mandar e-mail        conector do app, com a sua aprovação'),'Os nomes dos recursos mudam de um produto para outro e mudam com o tempo, mas a lógica é a mesma: o assistente conversa, e as ferramentas fazem o resto.'],
 null,['llm','prompt','agentes','mcp','ia-codigo','etica-ia','tokens'],{alt:'Também existem: Perplexity (focado em busca), Grok, Le Chat (Mistral), DeepSeek e assistentes de código como Copilot, Claude Code e Cursor.',tags:'assistente ia chatbot claude chatgpt gemini copilot meta ai perplexity chat'}),

E('ia-codigo','IA para programar','Assistentes que sugerem, explicam e escrevem código',1,
 '**Assistentes de código** usam modelos de linguagem para ajudar a programar: completam a linha que você começou, explicam um trecho, procuram bugs, escrevem testes e, os mais avançados, executam tarefas inteiras, lendo o projeto, editando vários arquivos, rodando comandos e testes e propondo as mudanças. Exemplos: **GitHub Copilot**, **Cursor**, **Claude Code** e **Codex**. Aceleram muito, mas **quem assina o código é você**: o modelo pode inventar funções que não existem, repetir falhas de segurança e escrever algo que funciona sem você entender. Para aprender, peça explicações e escreva você mesmo antes de colar.',
 'É ter um **ajudante com a bancada ao lado**: ele pega a ferramenta antes de você pedir, e às vezes monta a máquina inteira. Mas, se você nunca aprendeu a ler o esquema elétrico, não vai saber se ele ligou o fio certo.',
 ['Ganhar velocidade em tarefas repetitivas: formulários, testes, conversões e scripts','Entender código desconhecido e mensagens de erro','Aprender, pedindo explicações passo a passo e exemplos isolados','Revisar o que a IA escreveu: executar, testar e ler antes de aceitar'],
 ['prompt',L('Estou aprendendo JavaScript. Explique em linguagem simples o que este código','faz, linha por linha, e diga um erro comum que iniciantes cometem com ele.','Não reescreva o código, só explique.','','[cole aqui o trecho]'),'Pedir a explicação, em vez de só a resposta, é o que transforma a IA numa professora e não numa muleta.'],
 null,['assistentes','llm','prompt','git','testes','etica-ia','alucinacao','agentes'],{alt:'GitHub Copilot, Cursor, Claude Code, Codex, Windsurf, JetBrains AI Assistant e Gemini Code Assist.',tags:'ia para programar copilot cursor claude code codex vibe coding assistente de codigo'}),

]);
