/* ===== IA e ciência de dados (parte 4: embeddings, RAG, agentes e ferramentas de modelos) ===== */
C('ia',[
E('embeddings','Embeddings','Transformar significado em números, para o computador comparar ideias',3,
 'Um **embedding** é uma lista de números, um **vetor**, que representa o **significado** de um texto, de uma imagem ou de um áudio. Um modelo especial transforma rolamento e mancal em vetores **próximos**, e banana bem **longe**. Assim o computador mede o quanto dois significados se parecem, calculando a distância entre os vetores. É a base da **busca por significado**, que acha documentos sobre o assunto mesmo sem as mesmas palavras, das recomendações e do RAG. Os vetores são guardados em bancos próprios, os bancos vetoriais.',
 'É um **mapa da oficina onde as peças parecidas ficam na mesma prateleira**: parafusos perto de porcas, rolamentos perto de mancais, e a banana do lanche lá do outro lado do prédio. Para achar algo parecido, você não lê o nome: olha o que está perto no mapa.',
 ['Buscar por significado, em vez de só por palavra exata','Alimentar o RAG, achando os trechos certos para o modelo ler','Recomendar itens parecidos: produtos, músicas e artigos','Agrupar textos e detectar duplicatas'],
 ['python',L('import math','','# Cada texto vira um vetor (aqui, só 3 números para caber na tela)','rolamento = [0.82, 0.10, 0.31]','mancal    = [0.79, 0.14, 0.35]   # significado parecido -> números parecidos','banana    = [0.05, 0.91, 0.02]   # outro assunto -> números bem diferentes','','print(math.dist(rolamento, mancal))   # pequena: 0.06','print(math.dist(rolamento, banana))   # grande:  1.15'),'Vetores de verdade têm centenas ou milhares de números, e não três. A ideia é a mesma: distância pequena quer dizer significado parecido.'],
 'embed',['bd-vetorial','rag','llm','nlp','recomendacao'],{alt:'Modelos de embedding existem da OpenAI, do Google, da Cohere e abertos, como o BGE e o E5. Medida comum de proximidade: similaridade do cosseno.',tags:'embeddings vetor significado busca semantica similaridade cosseno'}),

E('rag','RAG','Dar ao modelo os documentos certos antes de ele responder',3,
 '**RAG**, de retrieval-augmented generation, ou geração aumentada por busca, é um jeito de fazer o modelo responder **com base em documentos seus**, sem treiná-lo de novo. Quando chega uma pergunta, o sistema primeiro **busca** os trechos mais relevantes numa base, normalmente por similaridade de embeddings, e **cola esses trechos no prompt**, junto com a pergunta. O modelo responde **usando aquele material** e pode citar de onde tirou. Reduz invenções e mantém as respostas atualizadas, porque basta atualizar os documentos. Está por trás de muitos chats sobre manuais, políticas e bases de conhecimento de empresas.',
 'É o **técnico que, antes de responder, vai ao arquivo e pega o manual da máquina certa**, em vez de responder de memória. Ele continua sendo o mesmo técnico, mas agora responde com o documento aberto à frente e pode apontar a página.',
 ['Fazer um assistente responder sobre manuais, procedimentos e políticas da empresa','Reduzir as invenções do modelo, porque ele responde com base em texto real','Manter as respostas atualizadas sem retreinar nada: basta atualizar os documentos','Mostrar a fonte da resposta, para a pessoa conferir'],
 ['estrutura',L('Pergunta: "Como troco a correia da esteira 2?"','','1. Busca nos manuais os 3 trechos mais parecidos com a pergunta','2. Monta o prompt:  [instruções] + [trecho 1, 2 e 3] + [pergunta]','3. O modelo responde usando só aqueles trechos, e cita as páginas'),'O modelo continua igual. O que muda é o material que ele recebe junto com a pergunta. A qualidade da busca decide boa parte da qualidade da resposta.'],
 'rag',['embeddings','bd-vetorial','llm','alucinacao','finetuning','agentes'],{alt:'Ferramentas: LangChain, LlamaIndex, bancos vetoriais (pgvector, Pinecone, Qdrant, Chroma) e recursos prontos dos provedores de nuvem. Em inglês: retrieval-augmented generation.',tags:'rag retrieval augmented generation busca documentos base de conhecimento chat manuais'}),

E('finetuning','Fine-tuning e como adaptar um modelo','Prompt, RAG ou ajuste fino: o que usar para cada necessidade',3,
 'Há três maneiras de adaptar um modelo ao seu caso. **Prompt**: você escreve instruções e exemplos, é a mais barata e a primeira a tentar. **RAG**: você entrega documentos na hora, ideal para **conhecimento** que muda ou que é privado. **Fine-tuning**, o ajuste fino: você treina mais um pouco o modelo com exemplos seus, para mudar o **jeito de responder**, o estilo, o formato ou uma habilidade específica. O ajuste fino não é um bom jeito de ensinar fatos novos de forma confiável, custa mais e exige dados bem preparados. A ordem de tentativa costuma ser prompt, depois RAG e só então ajuste fino.',
 'Prompt é **dar a ordem de serviço** a um técnico que já sabe o ofício. RAG é **deixar o manual aberto na bancada**. Fine-tuning é **mandar o técnico para um curso**, para ele mudar de hábito. O curso custa mais e demora, e só compensa quando as outras duas não bastam.',
 ['Escolher a técnica certa, sem gastar com treino quando um bom prompt resolve','Saber que conhecimento novo ou privado pede RAG, e que estilo e formato pedem ajuste fino','Entender termos como LoRA, que ajusta só uma parte pequena do modelo','Planejar os dados: o ajuste fino precisa de centenas ou milhares de bons exemplos'],
 ['comparativo',L('Necessidade                            Comece por','-------------------------------------  ---------------------------','Mudar o tom ou o formato da resposta   Prompt com exemplos','Responder com base em documentos       RAG','Dados que mudam toda semana            RAG','Estilo muito específico, em escala     Fine-tuning','Habilidade que o modelo não tem        Fine-tuning ou outro modelo'),'Comece sempre pelo mais simples e mais barato, e só suba de nível se o resultado não bastar. Muita gente pula direto para o ajuste fino e gasta à toa.'],
 null,['llm','rag','prompt','huggingface','pytorch','gpu-ia'],{alt:'Técnicas de ajuste: LoRA, QLoRA e RLHF (aprendizado com feedback humano). Em inglês: fine-tuning.',tags:'fine tuning ajuste fino lora treinar modelo adaptar prompt rag customizar'}),

E('agentes','Agentes de IA','Modelos que decidem os próximos passos e usam ferramentas até cumprir uma tarefa',3,
 'Um **agente de IA** é um sistema em que o modelo de linguagem não só responde: ele **decide o que fazer** para chegar a um objetivo, **usa ferramentas**, como buscar na web, ler arquivos, rodar código, chamar uma API ou mexer num app, **observa o resultado** e decide o passo seguinte, num laço até terminar. É o que permite pedir “organize a minha pasta de notas fiscais”, em vez de explicar cada etapa. Também aumenta os riscos: o agente pode errar e agir. Por isso se limitam as **permissões**, se registram as ações e se pede **aprovação humana** antes de passos irreversíveis.',
 'Um chat comum é o **colega que responde por mensagem**. O agente é o **colega que pega a chave de fenda e vai fazer**: olha a máquina, tenta uma coisa, vê o que aconteceu e tenta outra. Quanto mais ferramentas ele tem, mais ele resolve, e mais cuidado com o que se deixa ao alcance dele.',
 ['Automatizar tarefas de vários passos, como pesquisar, organizar, escrever e conferir','Fazer o modelo trabalhar em arquivos, sistemas e navegadores, e não só conversar','Ligar a IA a processos da empresa, com limites e aprovação humana','Entender os riscos e o que se faz para controlá-los: permissões mínimas, registro das ações e revisão'],
 ['estrutura',L('Objetivo: "Achar as ordens de serviço atrasadas e avisar o responsável"','','repete até terminar:','   pensa    -> "preciso listar as ordens abertas"','   age      -> chama a ferramenta  listar_ordens(status="aberta")','   observa  -> recebe a lista','   pensa    -> "3 estão atrasadas; falta saber o responsável"','   ...','   termina  -> entrega o resumo (ou pede aprovação antes de enviar a mensagem)'),'O laço pensa, age e observa é o coração de qualquer agente. A ferramenta é uma função que o sistema deixa ao alcance do modelo, e o que ela pode fazer define o que ele pode fazer.'],
 'agente',['llm','mcp','prompt','assistentes','automacao','etica-ia','rag'],{alt:'Também se fala em: agentes autônomos, sistemas multiagente, uso de ferramentas (tool use ou function calling) e uso de computador.',tags:'agente ia agentic ferramentas tool use function calling autonomo automatizar tarefas'}),

E('mcp','MCP (Model Context Protocol)','Um padrão para ligar modelos de IA a ferramentas e dados',3,
 'O **MCP**, Model Context Protocol, é um **protocolo aberto** que padroniza como um assistente ou agente de IA se conecta a **ferramentas e fontes de dados**. Em vez de cada aplicativo criar uma integração diferente para cada serviço, o serviço oferece um **servidor MCP** que descreve o que sabe fazer, como ler arquivos, consultar um banco ou criar um evento na agenda, e qualquer assistente compatível, o **cliente**, consegue usar. Foi proposto pela Anthropic em 2024 e adotado por vários fabricantes. Por segurança, o usuário aprova o que o assistente pode usar, e vale desconfiar de servidores que você não conhece.',
 'É a **tomada padrão**. Antes, cada equipamento vinha com um plugue diferente e cada fábrica precisava de um adaptador. Com a tomada padrão, qualquer máquina compatível liga em qualquer ponto de energia. O MCP faz isso entre assistentes de IA e ferramentas.',
 ['Conectar um assistente a e-mail, agenda, arquivos, bancos de dados e sistemas internos de forma padronizada','Criar uma integração uma vez e usar em vários assistentes','Dar a um agente as ferramentas de que ele precisa, com controle de permissão','Entender os riscos de servidores desconhecidos e de dar acesso demais'],
 ['json',L('{','  "mcpServers": {','    "arquivos": {','      "command": "npx",','      "args": ["-y", "@modelcontextprotocol/server-filesystem", "/home/usuario/notas"]','    }','  }','}'),'Exemplo de configuração, no formato usado por vários assistentes: cria um servidor chamado arquivos, que dá ao assistente acesso só à pasta indicada. O formato exato varia de um assistente para outro, então confira a documentação do seu.'],
 'mcp',['agentes','api','assistentes','llm','seguranca-basica','iam'],{alt:'Conceitos: servidor MCP, cliente MCP, ferramentas (tools), recursos e prompts. Em inglês: Model Context Protocol.',tags:'mcp model context protocol protocolo ferramentas servidor cliente conectores anthropic'}),

E('ollama','Rodar modelos de IA no seu computador','Ollama, LM Studio e llama.cpp: IA local, sem mandar nada para a nuvem',3,
 'Alguns modelos de linguagem são **abertos**, com os pesos disponíveis para baixar, e podem rodar **no seu próprio computador**. Programas como **Ollama**, **LM Studio** e **llama.cpp** cuidam do trabalho pesado: você baixa o modelo e ele responde sem mandar nada para a nuvem. Vantagens: **privacidade**, funcionar sem internet e custo zero por uso. Desvantagens: modelos menores costumam ser menos capazes que os maiores servidos na nuvem, e é preciso uma máquina com bastante memória e, de preferência, GPU. Para dados sensíveis e para testar, vale muito a pena.',
 'É **ter a sua própria máquina na oficina**, em vez de mandar a peça para a fábrica terceirizada. Não entrega o mesmo acabamento dos equipamentos gigantes de lá, mas ninguém vê o que você produz, funciona sem depender do transporte e não tem custo por peça.',
 ['Usar IA com dados que não podem sair da empresa ou do seu computador','Experimentar modelos sem pagar por uso','Ter um assistente funcionando offline','Aprender como os modelos abertos funcionam por dentro'],
 ['terminal',L('# Baixa e conversa com um modelo aberto (o nome muda com as versões)','ollama run llama3.2','','# Lista os modelos que já estão baixados','ollama list'),'Na primeira vez o primeiro comando baixa o modelo, e depois abre um chat no terminal. Os nomes dos modelos mudam com frequência: veja a lista atual em ollama.com.'],
 null,['llm','gpu-ia','huggingface','ia-codigo','etica-ia','docker'],{alt:'Outros: llama.cpp, vLLM (para servir em produção), Jan e GPT4All. Modelos abertos populares: Llama, Mistral, Qwen, Gemma e DeepSeek.',tags:'ollama lm studio llama cpp modelo local offline privacidade open weights'}),

E('huggingface','Hugging Face','O GitHub dos modelos de IA',2,
 'O **Hugging Face** é uma plataforma e comunidade onde se **compartilham modelos de IA, conjuntos de dados e demonstrações**. Funciona como um GitHub para modelos: milhares de modelos abertos de texto, imagem e áudio, cada um com a sua página, a documentação e o histórico. Também mantém a biblioteca **Transformers**, que carrega e usa esses modelos com poucas linhas de código, e os **Spaces**, onde dá para publicar uma demonstração. É o ponto de partida de quase todo mundo que quer baixar, testar ou ajustar um modelo aberto. Confira sempre a licença de cada modelo antes de usar em um produto.',
 'É o **catálogo de peças da oficina, com descrição, fotos e ficha técnica de cada uma**, mais um balcão onde gente do mundo todo deixa as suas criações para os outros usarem. Antes de aplicar uma peça, leia a ficha: a licença diz o que pode e o que não pode fazer com ela.',
 ['Achar e baixar modelos abertos de texto, imagem e áudio','Usar modelos prontos com poucas linhas de Python','Conferir licença, tamanho e exemplos de uso de cada modelo','Publicar uma demonstração do seu projeto de IA'],
 ['python',L('from transformers import pipeline','','# Baixa um modelo pronto de análise de sentimento e usa','analisador = pipeline("sentiment-analysis")','print(analisador("The new motor is much quieter than the old one"))'),'O pipeline escolhe um modelo padrão e baixa na primeira vez. O modelo padrão é em inglês, por isso a frase acima está em inglês. Para português, procure na plataforma modelos treinados nesse idioma.'],
 null,['llm','ollama','pytorch','finetuning','python','opensource','licencas'],{alt:'Conceitos: Hub, Spaces, datasets, Transformers e Diffusers. Alternativas: Kaggle Models e ModelScope.',tags:'hugging face huggingface modelos hub transformers spaces datasets ia aberta'}),

]);
