/* ===== IA e ciência de dados (parte 5: áreas de aplicação) ===== */
C('ia',[
E('visao-computacional','Visão computacional','Fazer o computador enxergar: reconhecer, contar e medir o que aparece numa imagem',2,
 'A **visão computacional** ensina o computador a **entender imagens e vídeos**. Tarefas comuns: **classificar**, como saber se a imagem tem uma peça com trinca; **detectar objetos**, achando onde estão as pessoas e os capacetes no vídeo, com um quadrado em volta de cada um; **segmentar**, marcando pixel a pixel o contorno do objeto; ler texto em imagens, o **OCR**; e reconhecer rostos. Hoje a maioria usa redes neurais, primeiro as convolucionais e agora também as baseadas em transformers. Na indústria aparece na **inspeção de qualidade**, na leitura de etiquetas e códigos, na segurança, como saber se o operador está de EPI, e na contagem de itens.',
 'É um **inspetor que nunca pisca**: olha cada peça na esteira, na velocidade da linha, e aponta o defeito com a mesma régua a cada vez. Mas só enxerga o que viu no treino: se nunca viu uma trinca com aquela iluminação, pode deixar passar.',
 ['Inspecionar peças e embalagens na linha de produção','Ler etiquetas, placas, notas fiscais e documentos com OCR','Detectar pessoas, EPIs e situações de risco em câmeras','Contar itens, medir dimensões e guiar robôs'],
 ['python',L('from ultralytics import YOLO','','modelo = YOLO("yolov8n.pt")        # modelo pequeno, já treinado','resultado = modelo("esteira.jpg")  # procura objetos na foto','','for caixa in resultado[0].boxes:','    print(resultado[0].names[int(caixa.cls)], float(caixa.conf))'),'Carrega um detector de objetos pronto e roda numa foto, imprimindo o que achou e a confiança de cada achado. Para detectar as suas peças, você ajusta o modelo com fotos suas, marcando onde está cada defeito. O nome do modelo muda com as versões.'],
 null,['deeplearning','opencv','metricas-ml','pytorch','anomalia','manutencao-preditiva'],{alt:'Ferramentas: OpenCV, YOLO, Detectron, MediaPipe, câmeras industriais e sistemas de visão de marcas como Cognex e Keyence. Em inglês: computer vision (CV).',tags:'visao computacional imagem video deteccao objetos ocr inspecao qualidade yolo cnn camera'}),

E('nlp','Processamento de linguagem natural','Fazer o computador lidar com texto em linguagem de gente',2,
 'O **PLN**, ou NLP, reúne as técnicas para o computador **lidar com a linguagem humana**: classificar textos, como reclamação ou elogio, e o assunto de um e-mail; **extrair informações**, como nomes, datas e valores num contrato; analisar **sentimento**; traduzir; resumir; responder perguntas; e conversar. Até uns anos atrás usava regras e estatística, e hoje a maior parte é feita por modelos de linguagem. Mesmo assim, ainda servem para tarefas simples e baratas as técnicas clássicas, como busca por palavras, expressões regulares e listas de termos.',
 'É o **funcionário do escritório que lê, separa e arquiva a papelada**: abre cada e-mail, vê se é cobrança, pedido ou reclamação e copia os dados importantes para a planilha. O PLN faz esse trabalho com milhares de textos por minuto.',
 ['Classificar e organizar e-mails, chamados e avaliações','Extrair dados de textos: datas, valores, nomes e códigos','Resumir, traduzir e responder perguntas sobre documentos','Analisar o que os clientes dizem, em escala'],
 ['python',L('import re','','texto = "Parada da prensa 02 em 14/03/2026 por falha no sensor, 45 minutos."','data = re.search(r"\\d{2}/\\d{2}/\\d{4}", texto).group()      # 14/03/2026','minutos = re.search(r"(\\d+) minutos", texto).group(1)      # 45','print(data, minutos)'),'Para textos bem padronizados, uma expressão regular basta e não custa nada. Quando os textos variam muito, entram os modelos de linguagem.'],
 null,['llm','regex','embeddings','voz','datascience'],{alt:'Tarefas: classificação de texto, reconhecimento de entidades (NER), análise de sentimento, tradução e resumo. Bibliotecas: spaCy e NLTK. Em inglês: NLP (natural language processing).',tags:'nlp pln processamento de linguagem natural texto sentimento entidades traducao resumo spacy'}),

E('voz','Reconhecimento e síntese de voz','Transformar fala em texto e texto em fala',1,
 'Há duas tarefas opostas. O **reconhecimento de fala**, ou speech-to-text, transforma áudio em texto: legendas automáticas, ditado e transcrição de reuniões. A **síntese de fala**, ou text-to-speech, faz o contrário: lê um texto em voz alta, como o leitor de tela, o GPS e o botão **Ouvir** deste guia. Hoje as vozes de IA soam bem naturais, e algumas conseguem clonar a voz de uma pessoa, o que traz o risco de golpes com voz falsa. Os navegadores trazem uma interface de síntese de fala, a Web Speech API, que é a que este guia usa.',
 'É um **tradutor entre dois mundos**: o ouvido, que transforma o som da oficina em anotação escrita, e a boca, que lê uma anotação em voz alta para quem está com as mãos ocupadas.',
 ['Transcrever reuniões, aulas e áudios','Ouvir textos longos enquanto faz outra coisa, como neste guia','Acessibilidade: leitores de tela e ditado para quem tem dificuldade de digitar ou de ver','Entender os riscos de voz clonada e de golpes por áudio'],
 ['javascript',L('// A voz do navegador, como o botão "Ouvir" deste guia','const fala = new SpeechSynthesisUtterance("A manutenção preventiva evita paradas.");','fala.lang = "pt-BR";','fala.rate = 1;                 // velocidade','speechSynthesis.speak(fala);'),'A voz que sai depende do navegador e do sistema do aparelho. Para transformar fala em texto, existem a SpeechRecognition, em alguns navegadores, e serviços de nuvem e modelos como o Whisper.'],
 null,['nlp','ia-generativa','etica-ia','a11y','js'],{alt:'Ferramentas: Web Speech API, Whisper (reconhecimento), Google Cloud Speech, Amazon Polly e ElevenLabs (síntese). Em inglês: speech-to-text (STT) e text-to-speech (TTS).',tags:'voz fala speech to text text to speech tts stt reconhecimento sintese whisper audio'}),

E('recomendacao','Sistemas de recomendação','O que faz o app sugerir o próximo vídeo, produto ou música',2,
 'Um **sistema de recomendação** sugere itens que você provavelmente vai querer: o próximo vídeo, a próxima música, o produto do tipo “quem comprou isso também comprou”. Há duas ideias básicas. **Filtragem por conteúdo**: recomenda itens parecidos com os que você gostou, com base nas características deles. **Filtragem colaborativa**: recomenda o que **pessoas parecidas com você** gostaram. Os sistemas reais misturam as duas e usam aprendizado de máquina e embeddings. Também têm efeitos colaterais, como as bolhas de conteúdo e o foco em manter você ali por mais tempo.',
 'É o **atendente do almoxarifado que conhece cada técnico**: “quem pediu esse rolamento costuma pedir também a graxa e o retentor”. Ele aprende pelas retiradas de todo mundo e sugere o que combina.',
 ['Sugerir produtos, vídeos, músicas e artigos','Aumentar vendas e tempo de uso de apps e lojas','Entender por que cada pessoa vê uma coisa diferente na mesma plataforma','Perceber os efeitos colaterais: bolhas e vício em conteúdo'],
 ['comparativo',L('Filtragem por conteúdo     "Você viu um vídeo sobre CLP, aqui vai outro sobre CLP"','Filtragem colaborativa    "Quem viu este vídeo também viu aquele, aqui vai"','Híbrida                   mistura as duas e leva em conta a hora e o contexto'),'Quase todo serviço grande usa uma versão híbrida, com modelos treinados no histórico de cliques, compras e tempo assistido.'],
 null,['embeddings','ml','datascience','etica-ia'],{alt:'Em inglês: recommender systems. Técnicas: fatoração de matrizes, vizinhos mais próximos, redes neurais e embeddings.',tags:'recomendacao recomendar netflix spotify filtragem colaborativa conteudo sugestao'}),

E('anomalia','Detecção de anomalias','Achar o que foge do normal, sem precisar ter visto a falha antes',3,
 'A **detecção de anomalias** procura **dados que fogem do padrão normal**: uma vibração fora do comum, um consumo de energia estranho, uma transação suspeita, um acesso incomum. A grande vantagem é que muitas vezes você **não tem exemplos de falha**, porque elas são raras. O modelo aprende como é o funcionamento **normal** e acusa o que destoa. Vai de métodos simples, como alertar quando o valor passa de três desvios padrão da média, até modelos de aprendizado de máquina. O maior desafio são os **falsos alarmes**: anomalia não quer dizer defeito, pode ser só uma situação nova.',
 'É o **operador experiente que, sem abrir o manual, percebe que o barulho da máquina mudou**. Ele nunca ouviu aquela falha específica, mas sabe como a máquina soa quando está boa, e estranha quando soa diferente.',
 ['Monitorar máquinas e sensores, avisando antes da falha','Detectar fraudes e acessos suspeitos','Achar erros de dados e medições com defeito','Complementar a manutenção preditiva quando faltam exemplos de falha'],
 ['python',L('import statistics as st','','historico = [4.1, 4.3, 4.0, 4.2, 4.4, 4.1, 4.3, 4.2]   # vibração normal (mm/s)','media = st.mean(historico)','desvio = st.stdev(historico)','','leitura = 5.6','if abs(leitura - media) > 3 * desvio:','    print("anomalia: fora de 3 desvios padrão")'),'Método simples e muito usado: leitura a mais de 3 desvios padrão da média é suspeita. Em máquinas reais, o normal muda com a carga e a temperatura, e por isso se usam modelos mais espertos.'],
 null,['estatistica','ml','tipos-aprendizado','manutencao-preditiva','monitoramento','iiot'],{alt:'Métodos: desvio padrão, isolation forest, autoencoders e modelos de séries temporais. Em inglês: anomaly detection ou outlier detection.',tags:'anomalia deteccao de anomalias outlier fora do padrao falha sensor vibracao fraude'}),

]);
