/* ===== IA e ciência de dados (parte 6: ferramentas do dia a dia) ===== */
C('ia',[
E('numpy','NumPy','A biblioteca que faz conta com milhões de números de uma vez',2,
 'O **NumPy** é a biblioteca de Python para **cálculo com números em grande quantidade**. Ele trabalha com **arrays**, que são tabelas de números, de uma, duas ou mais dimensões, guardadas de forma compacta. A mesma conta vale para todos os elementos de uma vez, sem você escrever um laço. É muito mais rápido que as listas comuns do Python, porque o miolo é escrito em C. Quase toda biblioteca de dados e de IA, como pandas, scikit-learn e PyTorch, é construída em cima dele ou segue as ideias dele. Quem mexe com números em Python acaba esbarrando nele.',
 'É uma **planilha turbinada, sem a interface**: em vez de arrastar a fórmula pela coluna inteira, você escreve a conta uma vez e ela vale para todas as células ao mesmo tempo.',
 ['Fazer contas em milhares ou milhões de números de uma vez, e rápido','Trabalhar com tabelas de números, imagens e sinais de sensores','Servir de base para pandas, scikit-learn, PyTorch e OpenCV','Estatística básica: média, desvio padrão, máximo e mínimo'],
 ['python',L('import numpy as np','','temps = np.array([71.2, 70.8, 73.5, 69.9, 85.1])   # temperaturas em °C','','print(temps.mean())            # média','print(temps.max())             # maior valor','print(temps * 1.8 + 32)        # todas em Fahrenheit, de uma vez'),'Cria um array com cinco temperaturas e calcula a média e o máximo. A última linha converte todos os valores de Celsius para Fahrenheit numa única expressão, sem escrever laço.'],
 null,['python','pandas','matplotlib','estatistica','scikit','opencv'],{alt:'Vizinhos: SciPy (ciência e estatística), CuPy (a mesma ideia na placa de vídeo) e JAX. O nome vem de Numerical Python.',tags:'numpy array matriz vetor calculo numerico python biblioteca'}),

E('pandas','pandas','A biblioteca do Python para trabalhar com tabelas de dados',1,
 'O **pandas** é a biblioteca de Python para **mexer em tabelas de dados**: abrir um CSV ou um Excel, filtrar linhas, juntar tabelas, agrupar, somar e limpar sujeira. A tabela dentro dele se chama **DataFrame**, que é uma planilha com linhas e colunas na memória. O que você faria no Excel com filtros, tabela dinâmica e busca vertical dá para fazer com poucas linhas de código, e **dá para repetir quando chegar o arquivo novo** do mês. É a ferramenta mais usada para analisar dados em Python.',
 'É o **Excel sem o mouse**: tudo que você faz clicando, escreve uma vez em código e depois roda sempre que chegar um arquivo novo, sem refazer o trabalho à mão.',
 ['Abrir, limpar e organizar dados de planilhas, CSV, bancos e sistemas','Filtrar, agrupar e somar para responder perguntas, como qual máquina parou mais','Automatizar os relatórios que você refaz todo mês','Preparar os dados antes de um gráfico ou de um modelo de IA'],
 ['python',L('import pandas as pd','','df = pd.read_csv("paradas.csv", sep=";")   # abre o arquivo','print(df.head())                            # mostra as primeiras linhas','','total = df.groupby("maquina")["minutos"].sum()','print(total.sort_values(ascending=False))   # quem parou mais, primeiro'),'Abre um arquivo de paradas, mostra o começo da tabela e soma os minutos parados por máquina, da pior para a melhor. O mesmo script roda no arquivo do mês seguinte sem mudar nada.'],
 null,['python','numpy','jupyter','matplotlib','excel','sql','etl','datascience'],{alt:'Alternativas: Polars (mais rápido com dados grandes), DuckDB (consulta tabelas com SQL) e o pacote dplyr, da linguagem R.',tags:'pandas dataframe tabela csv excel dados python analise biblioteca'}),

E('jupyter','Jupyter Notebook','O caderno interativo onde código, resultado e anotação ficam juntos',1,
 'O **Jupyter** é um **caderno interativo** que abre no navegador. O trabalho é dividido em **células**: numa você escreve código e executa, e o resultado, seja uma tabela, um gráfico ou um número, aparece logo abaixo; em outra você escreve texto explicando o que fez. Dá para rodar um pedaço de cada vez, ajustar e rodar de novo, sem executar o programa inteiro. É o ambiente preferido de quem **explora dados e treina modelos**. Existem versões online gratuitas, como o Google Colab, que costumam oferecer até uma placa de vídeo, dentro de limites de uso.',
 'É o **caderno de campo do técnico, com superpoderes**: você anota o que fez, executa a medição na hora e cola o resultado ao lado, tudo na mesma página.',
 ['Explorar dados e testar ideias passo a passo, vendo o resultado de cada etapa','Mostrar uma análise com código, gráficos e explicação na mesma página','Treinar modelos de IA em serviços online, como o Google Colab','Aprender Python, porque cada pedaço roda e responde na hora'],
 ['comparativo',L('Célula 1 (código)  df = pd.read_csv("paradas.csv")','Célula 2 (código)  df["minutos"].describe()','Célula 3 (texto)   Conclusão: a prensa 02 concentra as paradas','Célula 4 (código)  df.groupby("maquina")["minutos"].sum().plot.bar()'),'Cada célula roda separada e mostra o resultado logo abaixo. No Google Colab não precisa instalar nada: abre no navegador e usa.'],
 null,['python','pandas','matplotlib','datascience','ml','vscode'],{alt:'Alternativas: Google Colab e Kaggle (online, de graça), JupyterLab (versão mais completa) e o VS Code, que também abre notebooks.',tags:'jupyter notebook colab kaggle caderno celulas python dados'}),

E('matplotlib','Matplotlib','A biblioteca de gráficos do Python',1,
 'O **Matplotlib** é a biblioteca do Python para **desenhar gráficos**: barras, linhas, pontos, histogramas e muito mais. Você passa os números, escolhe o tipo de gráfico, coloca título e nomes nos eixos, e ele gera a imagem. É a base de quase tudo em gráficos no Python: outras bibliotecas, como o Seaborn, e o próprio pandas usam o Matplotlib por baixo. Serve para entender os dados antes de qualquer modelo, porque um gráfico mostra o que uma tabela esconde, como um valor fora do padrão.',
 'É o **registrador gráfico** do painel: você alimenta com os números e ele desenha a curva, para você enxergar o comportamento de relance.',
 ['Visualizar dados para achar padrões e valores estranhos','Gerar gráficos para relatórios e apresentações','Acompanhar o treino de um modelo, vendo a curva do erro cair','Servir de base para outras bibliotecas de gráficos'],
 ['python',L('import matplotlib.pyplot as plt','','dias = [1, 2, 3, 4, 5]','paradas = [3, 5, 2, 7, 4]','','plt.bar(dias, paradas)','plt.title("Paradas por dia")','plt.xlabel("Dia")','plt.ylabel("Quantidade")','plt.show()'),'Desenha um gráfico de barras com a quantidade de paradas em cada dia. No Jupyter, o gráfico aparece logo abaixo da célula.'],
 null,['python','pandas','numpy','jupyter','bi','powerbi'],{alt:'Alternativas: Seaborn (gráficos estatísticos mais bonitos), Plotly (interativo) e, no navegador, Chart.js e D3.',tags:'matplotlib grafico graficos plot barras linhas python visualizacao'}),

E('scikit','scikit-learn','A caixa de ferramentas de aprendizado de máquina clássico do Python',2,
 'O **scikit-learn** é a biblioteca de Python mais usada para o **aprendizado de máquina clássico**: classificação, regressão, agrupamento e redução de dimensões, além das ferramentas de apoio, como separar treino e teste, ajustar a escala dos dados e medir erros. Todo algoritmo segue o mesmo jeito de usar: um comando para treinar, outro para prever e outro para medir o acerto. Isso deixa fácil trocar um modelo por outro e comparar. Para dados em tabela, de tamanho pequeno ou médio, costuma resolver sem rede neural e sem placa de vídeo.',
 'É a **caixa de soquetes com uma catraca só**: cada soquete é um algoritmo diferente, mas todos encaixam no mesmo cabo. Você troca de modelo sem mudar o resto do código.',
 ['Treinar modelos de classificação e de previsão com poucas linhas','Testar vários algoritmos e comparar qual acerta mais','Preparar os dados: separar treino e teste, ajustar escala e codificar categorias','Prever falhas, classificar peças e agrupar itens parecidos em dados de tabela'],
 ['python',L('from sklearn.ensemble import RandomForestClassifier','from sklearn.model_selection import train_test_split','','# X = medidas dos sensores; y = 0 (normal) ou 1 (falha)','X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2)','','modelo = RandomForestClassifier()','modelo.fit(X_treino, y_treino)            # treina','print(modelo.score(X_teste, y_teste))     # acerto em dados nunca vistos'),'Guarda 20% dos dados só para o teste, treina uma floresta de árvores de decisão com fit e mede o acerto com score nos dados que o modelo nunca viu. Para testar outro algoritmo, em geral basta trocar a linha do RandomForestClassifier.'],
 null,['ml','classificacao-regressao','overfitting','metricas-ml','pandas','numpy','python'],{alt:'Parentes: XGBoost e LightGBM (modelos de árvores muito fortes em dados de tabela), statsmodels (estatística) e as ferramentas de AutoML.',tags:'scikit learn sklearn machine learning classificacao regressao modelo treino python'}),

E('pytorch','PyTorch','A biblioteca preferida para construir e treinar redes neurais',3,
 'O **PyTorch** é a biblioteca de Python mais usada hoje para **construir e treinar redes neurais**. Ele faz o trabalho pesado de matemática, calcula sozinho como corrigir cada peso depois de cada erro e joga as contas na **placa de vídeo**, quando existe uma. Você descreve as camadas da rede, escreve o laço de treino e deixa rodar. É a ferramenta de boa parte da pesquisa em IA e de muitos modelos famosos, incluindo boa parte dos publicados no Hugging Face. Foi criado pela Meta e hoje fica sob uma fundação aberta.',
 'É a **bancada de montagem com um assistente embutido**: você escolhe as peças, que são as camadas, e ele cuida de medir o erro e de regular cada parafuso, que são os pesos, depois de cada tentativa.',
 ['Montar e treinar redes neurais próprias','Refinar modelos prontos com os seus dados','Usar a placa de vídeo para treinar muito mais rápido','Acompanhar a pesquisa de IA, já que boa parte do código novo sai em PyTorch'],
 ['python',L('import torch','from torch import nn','','modelo = nn.Sequential(','    nn.Linear(2, 4),    # 2 entradas (vibração e temperatura), 4 neurônios','    nn.ReLU(),','    nn.Linear(4, 1),    # 1 saída: chance de falha','    nn.Sigmoid(),',')','','entrada = torch.tensor([[4.2, 71.0]])','print(modelo(entrada))   # sem treino, a saída é quase aleatória'),'Monta uma rede minúscula: 2 entradas, uma camada escondida de 4 neurônios e 1 saída entre 0 e 1. Sem treino, o resultado é quase aleatório. O treino ajusta os pesos até a saída acertar.'],
 null,['rede-neural','deeplearning','tensorflow','gpu-ia','huggingface','python','numpy'],{alt:'Alternativas: TensorFlow e Keras (Google), JAX (Google, mais voltado à pesquisa). A biblioteca Transformers, do Hugging Face, usa o PyTorch como motor principal.',tags:'pytorch torch rede neural deep learning treino gpu meta python biblioteca'}),

E('tensorflow','TensorFlow e Keras','A biblioteca de IA do Google e a camada Keras, mais fácil de usar',3,
 'O **TensorFlow** é a biblioteca de IA criada pelo Google, e o **Keras** é a camada de cima, que deixa montar redes neurais com poucas linhas, empilhando camadas como peças de montar. Foi muito usado em empresas e tem um ponto forte: levar o modelo treinado **para onde ele vai trabalhar**, como o celular, o navegador ou um microcontrolador, com versões leves feitas para isso. Na pesquisa e nos modelos de linguagem, o PyTorch ganhou espaço. Mas muita coisa em produção ainda roda em TensorFlow, e o Keras hoje também funciona sobre outros motores.',
 'É um **kit de montar com peças padronizadas**: o Keras encaixa as camadas como blocos, e o TensorFlow cuida da parte pesada e ainda ajuda a empacotar o resultado para levar para o campo.',
 ['Montar redes neurais rapidamente com o Keras','Levar modelos para celular, navegador e dispositivos pequenos','Entender e manter projetos de empresas que já usam TensorFlow','Comparar com o PyTorch e escolher a ferramenta certa para o projeto'],
 ['python',L('import tensorflow as tf','','modelo = tf.keras.Sequential([','    tf.keras.Input(shape=(2,)),                        # 2 entradas','    tf.keras.layers.Dense(4, activation="relu"),       # camada escondida','    tf.keras.layers.Dense(1, activation="sigmoid"),    # saída entre 0 e 1','])','','modelo.compile(optimizer="adam", loss="binary_crossentropy")','modelo.fit(X, y, epochs=20)        # X e y: seus dados de treino'),'É a mesma rede minúscula do exemplo do PyTorch, escrita no estilo do Keras: você empilha as camadas, compila dizendo como medir o erro e chama fit para treinar durante 20 voltas pelos dados.'],
 null,['pytorch','rede-neural','deeplearning','python','edge','embarcados'],{alt:'Parentes: TensorFlow Lite (hoje também chamado de LiteRT), TensorFlow.js (no navegador), JAX e o Keras 3, que roda também sobre PyTorch.',tags:'tensorflow keras google rede neural deep learning tflite python biblioteca'}),

E('opencv','OpenCV','A caixa de ferramentas clássica para processar imagens e vídeo',2,
 'O **OpenCV** é a biblioteca mais conhecida para **processar imagens e vídeo**. Tem centenas de ferramentas prontas: abrir imagens e câmeras, redimensionar, tirar a cor, achar bordas e contornos, medir distâncias, comparar com um modelo, ler códigos de barras e rodar redes neurais. Funciona em Python, em C++ e em outras linguagens, e é bem rápida. Antes da IA virar moda, já resolvia muito problema de visão, como achar uma peça fora de posição ou ler uma marca. Continua sendo o canivete suíço da área, muitas vezes combinado com um modelo de IA.',
 'É a **bancada de ferramentas manuais da visão**: lima, esquadro e paquímetro. Ela não decide sozinha o que é defeito, mas prepara a imagem e faz as medições, e você escolhe como usar.',
 ['Preparar imagens antes de passar para um modelo de IA','Inspeção simples: achar bordas, medir tamanhos e checar a posição da peça','Ler o vídeo de uma câmera, quadro a quadro','Ler códigos de barras'],
 ['python',L('import cv2','','imagem = cv2.imread("peca.jpg")                   # abre a foto','cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)  # tira a cor','bordas = cv2.Canny(cinza, 100, 200)               # só os contornos','cv2.imwrite("bordas.jpg", bordas)                 # salva o resultado'),'Abre uma foto, converte para tons de cinza e usa o detector de bordas Canny, que deixa só os contornos. Numa peça, uma borda quebrada ou fora do lugar pode indicar defeito.'],
 null,['visao-computacional','python','numpy','deeplearning','embarcados'],{alt:'Parentes: scikit-image, Pillow (para tarefas simples com imagens), MediaPipe (mãos, rosto e corpo) e Kornia (visão computacional em PyTorch).',tags:'opencv cv2 imagem video visao computacional bordas camera python biblioteca'}),

]);
