/* ===== Indústria e IoT (parte 1: automação e sistemas da fábrica) ===== */
C('ind',[
E('industria40','Indústria 4.0','A fábrica conectada: máquinas, dados e software trabalhando juntos',1,
 'A **Indústria 4.0** é o nome da **quarta revolução industrial**: a fábrica em que máquinas, sensores, sistemas e pessoas trocam dados o tempo todo. A primeira revolução trouxe o vapor; a segunda, a eletricidade e a linha de montagem; a terceira, a eletrônica e a automação com CLPs. A quarta junta tudo isso com **internet das coisas, nuvem, análise de dados e inteligência artificial**. O objetivo prático é enxergar a produção em tempo real, **prever falhas antes da parada**, ajustar o processo com mais precisão e desperdiçar menos. O termo surgiu na Alemanha, por volta de 2011.',
 'É a diferença entre **tratar a máquina só quando ela quebra** e **ouvir a máquina o tempo todo**. Antes, o técnico descobria o problema ao ver a linha parada. Agora o sensor avisa que a vibração mudou, o dado chega a um painel e a manutenção é marcada antes da quebra.',
 ['Entender o que as empresas querem dizer com fábrica conectada','Ligar o chão de fábrica ao mundo de TI: dados da máquina chegando ao computador','Enxergar as peças do quebra-cabeça: sensores, CLP, redes, supervisório, nuvem e análise','Perceber que a base é simples: dado confiável, rede estável e equipamento bem mantido'],
 ['estrutura',L('Camada     Quem é                  O que faz','---------  ----------------------  ---------------------------------------','ERP        compras, estoque        planeja pedidos, material e custos','MES        ordens e qualidade      acompanha a produção real','SCADA/IHM  telas e alarmes          supervisiona e comanda','CLP        controlador             lê sensores, executa a lógica','Campo      sensores e atuadores    medem e agem no processo físico'),'É o modelo clássico, a chamada pirâmide da automação, inspirada na norma ISA-95. Na Indústria 4.0, os dados também sobem direto do campo para a nuvem e a análise, e a pirâmide tende a virar uma rede.'],
 'piramide',['iot','iiot','clp','scada','mes','erp','manutencao-preditiva','twin','edge'],{alt:'Termos parecidos: fábrica inteligente (smart factory), manufatura digital e quarta revolução industrial. Em inglês: Industry 4.0.',tags:'industria 4.0 fabrica conectada automacao iot digitalizacao smart factory manufatura'}),

E('clp','CLP (controlador lógico programável)','O computador robusto que comanda máquinas lendo sensores e ligando saídas',1,
 'O **CLP**, ou PLC em inglês, é um computador feito para o chão de fábrica: aguenta calor, poeira, vibração e ruído elétrico. Ele tem **entradas**, onde ligam sensores e botões, **saídas**, que comandam contatores, válvulas e lâmpadas, e uma **memória com o programa**. Funciona num ciclo que se repete sem parar, a **varredura**: lê as entradas, executa o programa e atualiza as saídas. Substituiu os painéis cheios de relés: mudar a lógica passou a ser alterar o programa, em vez de refazer a fiação. Entre os fabricantes estão Siemens, Rockwell, Schneider, Mitsubishi, Omron e WEG.',
 'É o **painel de relés virtual**. Em vez de ligar fio entre relé, temporizador e contator, você escreve a lógica no programa. O CLP faz o papel de um operador que **olha todos os botões e sensores, decide e aciona as máquinas, de novo e de novo, dezenas ou centenas de vezes por segundo**.',
 ['Automatizar máquinas e processos: esteiras, prensas, bombas, linhas de produção','Trocar lógica de relés por programa, bem mais fácil de alterar','Ler sensores e comandar motores, válvulas e inversores','Diagnosticar uma parada: entender entradas, saídas e o programa'],
 ['estrutura',L('Ciclo de varredura (repete o tempo todo)','','1. Lê as entradas físicas e guarda uma "foto" delas na memória','2. Executa o programa, degrau por degrau, usando essa foto','3. Atualiza as saídas físicas com o resultado','4. Cuida da comunicação e do diagnóstico, e volta ao passo 1'),'A entrada só é lida no começo do ciclo. Um pulso mais curto que o ciclo pode passar despercebido, e por isso existem entradas rápidas e interrupções. Quanto mais pesado o programa, mais lento o ciclo.'],
 'scan',['ladder','ihm','scada','sensores','sinal420','modbus','redes-industriais','inversor','seguranca-maquinas'],{alt:'Siglas: CLP (português) e PLC (inglês). Parentes: mini-CLPs e relés programáveis (como o Logo!, da Siemens), PAC (controlador de automação programável) e DCS, comum em processos contínuos, como refinarias e usinas.',tags:'clp plc controlador logico programavel automacao industrial varredura entradas saidas siemens rockwell'}),

E('ladder','Ladder e a norma IEC 61131-3','A linguagem que parece diagrama elétrico, e as outras quatro da norma',2,
 'A **Ladder**, ou diagrama de escada, é a linguagem de CLP que **imita o esquema elétrico de comando**: dois trilhos nas laterais e, entre eles, **degraus** com **contatos** e **bobinas**. Se existir um caminho fechado do trilho esquerdo até a bobina, ela liga. O contato **NA**, normalmente aberto, fecha quando a entrada está ativa. O **NF**, normalmente fechado, abre. Contatos em série fazem a função E, e em paralelo fazem a função OU. A norma **IEC 61131-3** define cinco linguagens: **Ladder**, **blocos de função**, **texto estruturado**, **gráfico sequencial** e a lista de instruções, hoje quase abandonada.',
 'É o **esquema de comando elétrico que você já sabe ler**, desenhado na tela. Botão de partida, botão de parada com contato NF, contator com contato de selo: **é tudo igual**. A diferença é que, no CLP, trocar um contato de lugar é arrastar um símbolo, e não puxar fio.',
 ['Ler e entender programas de máquina feitos em Ladder','Passar um esquema de comando elétrico para o programa de um CLP','Montar o clássico liga e desliga com selo, e usar temporizadores','Conhecer as outras linguagens da norma e quando cada uma ajuda'],
 ['estrutura',L('       Liga      Desliga   Térmico            Motor','       I0.0      I0.1      I0.2               Q0.0','|---+---[ ]---+---[/]--------[/]---------------( )---|','|   |         |                                      |','|   |  Selo   |                                      |','|   +---[ ]---+                                      |','|      Q0.0                                          |','','[ ] contato NA     [/] contato NF     ( ) bobina'),'Quando o Liga é pressionado, a corrente passa pelo caminho de cima e a bobina Q0.0 liga. O contato de selo, que também é Q0.0, fecha em paralelo e mantém o circuito, mesmo soltando o botão. O Desliga e o térmico são NF: se qualquer um abrir, tudo desliga.'],
 'ladder',['clp','ihm','sensores','inversor','sinal420','seguranca-maquinas'],{alt:'Outras linguagens da norma: texto estruturado (ST, parecido com Pascal), blocos de função (FBD) e gráfico sequencial (SFC). Programas conhecidos: TIA Portal (Siemens), Studio 5000 (Rockwell), CODESYS (usado por vários fabricantes), GX Works (Mitsubishi) e Sysmac Studio (Omron).',tags:'ladder diagrama de escada iec 61131 contato bobina selo temporizador clp linguagem programacao'}),

E('ihm','IHM (interface homem-máquina)','O painel onde o operador vê o que a máquina faz e dá comandos',1,
 'A **IHM**, ou HMI em inglês, é a **tela** pela qual a pessoa conversa com a máquina. Mostra o estado, como rodando, parada ou em alarme, valores como temperatura e contagem, e deixa dar comandos e mudar parâmetros. Pode ser um painel com tela sensível ao toque preso à máquina, um tablet ou uma tela de computador. Ela **não tem a lógica de controle**: quem decide é o CLP, e a IHM apenas lê e escreve valores nele, por uma rede industrial. Uma boa IHM mostra o que importa, usa **cores com significado**, como vermelho para alarme, e evita despejar dezenas de números na tela.',
 'É o **painel de instrumentos do carro**: mostra velocidade, combustível e luzes de aviso, e tem poucos comandos. O motorista não precisa saber como o motor funciona, só precisa enxergar o que importa e agir. O CLP é o motor e a injeção, e a IHM é o painel.',
 ['Operar a máquina: ligar, desligar, escolher a receita e ajustar valores','Ver alarmes e entender o que parou e por quê','Fazer um diagnóstico rápido, olhando entradas, saídas e variáveis','Entender o limite da IHM: ela mostra e comanda, mas a lógica está no CLP'],
 ['estrutura',L('Elemento na tela          Tag no CLP (nome da variável)','------------------------  -------------------------------','Botão "Liga"              escreve 1 em  CMD_LIGA','Lâmpada "Motor ligado"    lê            MOTOR_LIGADO','Temperatura do forno      lê            TEMP_FORNO   (mostra 72,5 °C)','Alarme "Térmico"          lê            ALM_TERMICO  (acende em vermelho)'),'Cada elemento da tela aponta para uma tag, que é o nome de uma variável do CLP. Quando a tela não atualiza, o problema costuma ser a comunicação com o CLP ou uma tag apontando para o endereço errado.'],
 null,['clp','scada','ladder','redes-industriais','uxui'],{alt:'Siglas: IHM (português) e HMI (inglês). Variações: painel de operação, tela touch e aplicativo no tablet. Fabricantes: Siemens, Rockwell (PanelView), Schneider (Magelis), Weintek e Delta.',tags:'ihm hmi interface homem maquina painel touch operador tela alarme tag'}),

E('scada','SCADA (supervisório)','O sistema que enxerga a planta inteira, guarda o histórico e avisa dos alarmes',2,
 'O **SCADA**, ou supervisório, é um software que **coleta dados de vários CLPs e equipamentos**, mostra a planta em telas, registra **alarmes** e guarda um **histórico** das variáveis. Diferente da IHM, que fica na máquina e atende uma máquina só, o supervisório costuma ficar numa sala de controle e **acompanha a fábrica ou o processo inteiro**: uma estação de tratamento de água, uma subestação, uma linha de produção. Também permite comandar à distância e gerar relatórios e gráficos de tendência. O nome vem de Supervisory Control And Data Acquisition. Ele conversa com os CLPs por protocolos como Modbus e OPC UA.',
 'Se a IHM é o painel de instrumentos do carro, o SCADA é a **torre de controle do aeroporto**: enxerga todos os aviões, registra tudo o que aconteceu e chama a atenção quando algo foge do normal. Mas quem pilota cada avião é o CLP.',
 ['Supervisionar vários equipamentos a partir de uma sala de controle','Receber e tratar alarmes, com registro de quem reconheceu cada um','Ver gráficos de tendência e descobrir quando um problema começou','Gerar relatórios de produção e de funcionamento da planta'],
 ['estrutura',L('Sala de controle      Servidor SCADA  <-- Modbus / OPC UA -->  CLP 1, CLP 2, CLP 3','                           |','                     Banco de histórico   (variáveis, alarmes, eventos)','                           |','                     Telas e relatórios   (operador, manutenção, gestão)'),'O servidor pergunta aos CLPs os valores das variáveis, de tempos em tempos, e guarda tudo. Se o supervisório cair, o CLP continua controlando a máquina: o que se perde é a visão e o histórico durante a falha.'],
 null,['ihm','clp','historian','opcua','modbus','mes','monitoramento'],{alt:'Produtos conhecidos: Ignition (Inductive Automation), WinCC (Siemens), FactoryTalk (Rockwell), Elipse E3 (brasileiro), AVEVA (antigo Wonderware) e Zenon.',tags:'scada supervisorio supervisory control data acquisition sala de controle alarmes tendencia historico planta'}),

E('mes','MES (sistema de execução da manufatura)','O sistema que acompanha a produção real: ordens, apontamentos, rastreio e qualidade',2,
 'O **MES**, de manufacturing execution system, fica **entre o chão de fábrica e o ERP**. O ERP diz "produza mil peças do produto X até sexta". O MES **acompanha a execução**: qual ordem está em cada máquina, quanto já foi produzido, quanto virou refugo, quanto tempo a máquina parou e por quê, qual lote de matéria-prima foi para qual produto, que é a **rastreabilidade**, e se a qualidade está dentro da especificação. Daí saem indicadores como o **OEE**. Muita fábrica ainda faz parte disso em planilha e papel, e o MES troca a coleta manual por dados automáticos.',
 'O ERP é o **plano de produção na parede do escritório**. O MES é o **supervisor de turno com a prancheta**, anotando em tempo real o que cada máquina faz, o que parou e o que saiu errado, e avisando o escritório quando a realidade se afasta do plano.',
 ['Acompanhar a produção em tempo real, por ordem, máquina e turno','Registrar paradas, refugos e motivos, sem papel','Rastrear qual lote de material foi para qual produto','Calcular indicadores como OEE e produtividade'],
 ['estrutura',L('ERP  -->  MES  -->  Chão de fábrica   (ordens descem)','ERP  <--  MES  <--  Chão de fábrica   (resultados sobem)','','Desce: "Ordem 305: 1.000 peças do produto X"','Sobe : "Ordem 305: 940 boas, 60 refugos, 2 h de parada por falta de material"'),'O padrão ISA-95 descreve como esses níveis trocam informação. O resumo do MES alimenta o ERP, que atualiza estoque, custos e planejamento.'],
 'piramide',['erp','scada','oee','clp','industria40','historian','manutencao-preditiva'],{alt:'Parentes: MOM (gestão de operações de manufatura), APS (programação avançada da produção) e QMS (gestão da qualidade). Em inglês: manufacturing execution system.',tags:'mes manufacturing execution system producao ordens apontamento rastreabilidade qualidade oee isa-95'}),

E('erp','ERP (sistema de gestão empresarial)','O sistema que junta compras, estoque, produção, vendas e finanças da empresa',1,
 'O **ERP**, de enterprise resource planning, é o **sistema integrado de gestão da empresa**: compras, estoque, produção, vendas, notas fiscais, finanças, contabilidade e folha de pagamento, tudo conversando num banco de dados só. Se o comercial registra um pedido, o estoque vê que falta material, compras recebe a solicitação e a produção sabe quando começar. Para quem trabalha em manutenção, ele aparece principalmente no **módulo de manutenção**: ordens de serviço, peças e custos. Os mais conhecidos são o **SAP** e, no Brasil, o **TOTVS Protheus**. Costuma ser muito personalizado, e implantar um é um projeto grande.',
 'É o **livro-caixa, o almoxarifado e a agenda da empresa num sistema só**. Em vez de cada setor ter a sua planilha, todos consultam e atualizam a mesma fonte, e uma mudança num lugar aparece nos outros.',
 ['Integrar os setores da empresa num único banco de dados','Controlar estoque, compras, produção, vendas e finanças','Registrar ordens de manutenção, peças e custos por equipamento','Entender de onde vêm os números que a gestão usa'],
 ['estrutura',L('1. Técnico abre a OS 4821: troca de rolamento da prensa 02','2. ERP reserva o rolamento no estoque','3. Se não tem, gera um pedido de compra automático','4. A peça chega e a nota fiscal dá entrada no estoque','5. A OS é encerrada e o custo vai para o centro de custo da prensa'),'Todos esses passos acontecem no mesmo sistema, com o mesmo cadastro de peças e de equipamentos. É a vantagem do ERP, e o motivo de ele ser tão difícil de mudar depois de implantado.'],
 null,['mes','cmms','banco-relacional','sql','soap','oracle','sqlserver'],{alt:'Marcas: SAP S/4HANA e Business One, TOTVS Protheus e RM, Oracle NetSuite, Microsoft Dynamics 365, Senior e Odoo (código aberto). Em inglês: enterprise resource planning.',tags:'erp sap totvs protheus gestao empresarial estoque compras financeiro modulo manutencao integrado'}),

E('cmms','Gestão de manutenção (CMMS e EAM)','O sistema que organiza ordens de serviço, preventivas, peças e o histórico de cada máquina',2,
 'O **CMMS**, de computerized maintenance management system, também chamado de **EAM** ou GMAO, é o software da manutenção. Ele guarda o **cadastro dos equipamentos**, abre as **ordens de serviço** corretivas e preventivas, agenda **planos de inspeção**, controla **peças e estoque**, registra **horas e custos** e mantém o **histórico de cada máquina**. Com esse histórico saem indicadores como o **MTBF**, tempo médio entre falhas, e o **MTTR**, tempo médio de reparo, e dá para decidir quais equipamentos merecem manutenção preditiva. Alguns são módulos de ERP, como o SAP PM. Outros são sistemas próprios, como o Engeman, bastante usado no Brasil.',
 'É o **caderno de bordo de cada máquina da fábrica**, só que compartilhado e pesquisável: o que quebrou, quando, quem consertou, que peça trocou e quanto custou. Quem chega no turno seguinte lê a história em vez de adivinhar.',
 ['Abrir, atribuir e fechar ordens de serviço, com histórico','Programar a preventiva por tempo ou por uso do equipamento','Controlar peças e estoque da manutenção','Calcular indicadores como MTBF, MTTR e disponibilidade'],
 ['estrutura',L('OS 4821 · Prensa 02 · Corretiva','Sintoma ........ Para durante o ciclo, alarme de sobrecarga','Causa .......... Rolamento do motor com folga','Ação ........... Troca do rolamento e lubrificação','Peças .......... 1 rolamento, 80 g de graxa','Tempo parado ... 2 h 30 min'),'Exemplo inventado de ordem de serviço. O valor do sistema está no que se faz depois: com muitas ordens como esta, dá para ver quais equipamentos mais falham, quais peças mais se gastam e se a preventiva está funcionando.'],
 null,['erp','manutencao-preditiva','oee','sql','banco-relacional','iot'],{alt:'Outros nomes e produtos: GMAO, IBM Maximo, Infor EAM, Fiix, UpKeep, SAP PM e Engeman. Em inglês: computerized maintenance management system e enterprise asset management.',tags:'cmms eam gmao manutencao ordem de servico os preventiva corretiva mtbf mttr engeman sap pm maximo'}),

]);
