/* ===== Indústria e IoT (parte 2: campo, controle e acionamentos) ===== */
C('ind',[
E('sensores','Sensores e atuadores','Os olhos e os músculos da máquina: o que mede e o que se move',1,
 'Os **sensores** transformam uma grandeza física em sinal elétrico que o CLP entende, e os **atuadores** transformam o comando do CLP em ação física. Sensores comuns: **indutivo**, que detecta metal sem encostar; **capacitivo**, que detecta vários materiais e níveis; **fotoelétrico**, que usa luz; **fim de curso**, mecânico; **encoder**, que mede posição e velocidade; **termopar e PT100**, para temperatura; e **transmissores** de pressão, nível e vazão. Atuadores comuns: **motores**, **válvulas solenoides**, **cilindros pneumáticos**, **contatores** e **resistências**. O sinal pode ser **digital**, que só liga ou desliga, ou **analógico**, com valores contínuos, como 4 a 20 miliampères.',
 'Os sensores são os **sentidos**: olho, tato, ouvido. Os atuadores são os **músculos**. O CLP é o cérebro, que só enxerga o mundo pelo que os sentidos contam e só age pelo que os músculos conseguem fazer. Sensor sujo, desalinhado ou mal ligado é o cérebro recebendo informação errada.',
 ['Escolher o sensor certo para cada necessidade: metal, qualquer objeto, posição, temperatura','Diagnosticar paradas causadas por sensor sujo, desalinhado ou com a fiação ruim','Entender a diferença entre sinal digital, que liga ou desliga, e analógico, que varia','Conhecer o que o CLP lê e o que ele comanda'],
 ['comparativo',L('Detectar...                       Sensor típico','-------------------------------  -----------------------------','peça metálica, sem encostar      indutivo','qualquer material, nível         capacitivo','objeto cortando um feixe de luz  fotoelétrico (barreira)','posição e velocidade de eixo     encoder','temperatura                      termopar ou PT100','pressão, nível, vazão            transmissor com saída 4 a 20 mA'),'Sensores digitais costumam ser PNP ou NPN, e o tipo tem que combinar com a entrada do CLP. Ligar o tipo errado faz o sensor parecer sempre ligado ou sempre desligado. Confira a especificação antes de trocar.'],
 null,['clp','sinal420','iot','iiot','inversor','servo','rfid','embarcados'],{alt:'Outros: ultrassônico, radar, magnético (reed), laser, acelerômetro (vibração), célula de carga e câmera de visão. Sensores inteligentes podem conversar com o CLP por IO-Link.',tags:'sensores atuadores indutivo capacitivo fotoeletrico encoder termopar pt100 transmissor pnp npn fim de curso'}),

E('sinal420','Sinais analógicos: 4 a 20 mA e 0 a 10 V','Como um sensor conta um valor ao CLP usando corrente ou tensão',2,
 'Um sinal **analógico** varia de forma contínua. O padrão mais usado na indústria é a **corrente de 4 a 20 miliampères**: 4 mA é o **começo da escala**, por exemplo 0 bar ou 0 °C, e 20 mA é o **fim**, por exemplo 10 bar ou 100 °C. Os valores no meio são proporcionais. Por que começar em 4 e não em 0? Porque assim **0 mA indica falha**: fio rompido ou transmissor sem alimentação, e o CLP percebe. A corrente também sofre menos com ruído e com a distância do que a tensão. O padrão de **0 a 10 volts** é comum em curtas distâncias, como no comando de velocidade de inversores.',
 'É como o **ponteiro de um manômetro**: a posição entre o mínimo e o máximo diz quanto vale. E o 4 mA no mínimo é como uma **luz piloto que só apaga se faltar energia no painel**: se aparecer 0 mA, o problema não é o processo, é o fio.',
 ['Ler e configurar transmissores de pressão, temperatura, nível e vazão','Calcular o valor real a partir da corrente medida com o multímetro','Diagnosticar fio rompido ou transmissor sem alimentação, pelo sinal em 0 mA','Ajustar entradas analógicas de CLP e de inversor'],
 ['python',L('def ma_para_valor(ma, minimo, maximo):','    return minimo + (ma - 4) / 16 * (maximo - minimo)','','# transmissor de pressão de 0 a 10 bar','print(ma_para_valor(4, 0, 10))     # 0.0 bar','print(ma_para_valor(12, 0, 10))    # 5.0 bar  (metade da escala)','print(ma_para_valor(20, 0, 10))    # 10.0 bar'),'A faixa útil é de 16 mA (de 4 a 20), então 12 mA fica exatamente na metade. Muitos equipamentos tratam valores abaixo de cerca de 3,6 mA ou acima de cerca de 21 mA como falha (recomendação NAMUR NE 43).'],
 'ma420',['sensores','clp','inversor','pid','redes-industriais'],{alt:'Variações: 0 a 20 mA, 1 a 5 V e 0 a 5 V. Em transmissores de 2 fios, o mesmo par de fios leva a energia e o sinal (laço de corrente). O protocolo HART trafega por cima do 4 a 20 mA.',tags:'4-20ma 4 a 20 miliamperes 0-10v analogico transmissor loop corrente escala sinal clp'}),

E('pid','Controle PID','O jeito mais usado de manter temperatura, pressão, nível ou velocidade no valor desejado',2,
 'O **PID** é um algoritmo de controle que mantém uma grandeza, como temperatura, pressão, nível ou velocidade, **no valor desejado**, o **setpoint**. A cada instante ele compara o valor medido com o desejado, calcula o **erro** e decide quanto atuar. Soma três partes: a **proporcional**, que reage ao tamanho do erro agora; a **integral**, que soma o erro ao longo do tempo e **elimina a diferença que sobra**; e a **derivativa**, que reage à velocidade da mudança e **freia antes de passar do ponto**. Ajustar os três ganhos é a **sintonia**: sintonia ruim causa oscilação ou resposta lenta. Está dentro de CLPs, inversores e controladores de temperatura.',
 'É **dirigir mantendo a velocidade com o pé no acelerador**. O P é pisar mais quanto mais longe você está da velocidade desejada. O I é perceber que ficou abaixo por muito tempo e continuar pisando até chegar. O D é aliviar o pé quando você vê que está chegando rápido demais.',
 ['Controlar temperatura, pressão, nível, vazão e velocidade de forma estável','Entender os parâmetros Kp, Ki e Kd de controladores e inversores','Reconhecer sintonia ruim: oscilação, lentidão ou diferença que sobra','Ajustar um controle com método, em vez de chutar valores'],
 ['python',L('kp, ki, kd = 2.0, 0.4, 1.0','integral, erro_anterior = 0.0, 0.0','dt = 0.1                      # segundos entre os cálculos','','def pid(setpoint, medido):','    global integral, erro_anterior','    erro = setpoint - medido','    integral += erro * dt','    derivada = (erro - erro_anterior) / dt','    erro_anterior = erro','    return kp * erro + ki * integral + kd * derivada   # saída de controle'),'A saída é a soma das três partes. Na prática, ainda se limita a saída, por exemplo de 0 a 100%, e se impede que a parte integral cresça sem parar quando a saída satura. Isso se chama anti-windup.'],
 'pid',['clp','sensores','sinal420','inversor','servo','tempo-real','matlab'],{alt:'Parentes: controle liga e desliga com histerese, controle em cascata, feedforward e controle preditivo (MPC). Métodos de sintonia: Ziegler-Nichols, tentativa guiada e autotune.',tags:'pid controle proporcional integral derivativo setpoint sintonia kp ki kd malha temperatura processo'}),

E('inversor','Inversores de frequência e soft-starters','Quem controla a velocidade e a partida suave de motores de indução',2,
 'O **inversor de frequência** controla a **velocidade de um motor de indução** variando a frequência e a tensão que chegam a ele. Por dentro, **retifica** a tensão alternada da rede, transformando em contínua, e depois **recria** uma alternada com a frequência desejada, usando transistores que ligam e desligam milhares de vezes por segundo, a técnica **PWM**. Com isso o motor parte suave, tem a velocidade ajustada ao processo e **economiza energia** em bombas e ventiladores. O **soft-starter** só **suaviza a partida** e a parada, sem variar a velocidade em regime. O controle pode ser **escalar**, a relação V/f, ou **vetorial**. Tudo se configura por **parâmetros**: rampas, limites e proteções.',
 'O inversor é o **câmbio automático com infinitas marchas do motor**: em vez de o motor girar sempre na rotação da rede, ele entrega a rotação certa para cada momento. O soft-starter é só o **pé que aperta o acelerador devagar na largada** e depois solta o controle.',
 ['Variar a velocidade de bombas, ventiladores, esteiras e máquinas','Partir motores sem o tranco da partida direta','Economizar energia em cargas que não precisam rodar sempre a plena velocidade','Entender parâmetros de rampa, limite de corrente e proteções, e ler códigos de falha'],
 ['estrutura',L('Rede 3~ --> Retificador --> Barramento CC --> Inversor (PWM) --> Motor','60 Hz      (CA vira CC)    (capacitores)      (cria nova CA)     (f variável)','','Inversor em 30 Hz  --> motor de 4 polos, rotação síncrona de 900 rpm','Inversor em 60 Hz  --> motor de 4 polos, rotação síncrona de 1.800 rpm'),'A rotação síncrona é 120 vezes a frequência dividida pelo número de polos. A rotação real do motor é um pouco menor, por causa do escorregamento. Abaixo da frequência nominal, o motor mantém o torque, e acima dela perde torque.'],
 null,['clp','sensores','pid','servo','redes-industriais','sinal420','modbus','manutencao-preditiva'],{alt:'Siglas: VFD e VSD, em inglês. Linha de inversores da WEG: CFW. Parentes: soft-starter, conversor de frequência e servoacionamento. O controle escalar também é chamado de V/f.',tags:'inversor de frequencia vfd cfw soft starter motor inducao velocidade rampa pwm parametros partida'}),

E('servo','Servomotores e motores de passo','Motores que vão a uma posição exata, com velocidade e precisão controladas',2,
 'Um **servomotor** é um motor com **realimentação de posição**: um sensor, o **encoder**, diz ao acionamento onde o eixo está de verdade, e o **servoacionamento** corrige o movimento o tempo todo. O resultado é posicionamento preciso, partidas e paradas rápidas e bom torque em baixa rotação. Aparece em máquinas de embalagem, robôs, CNC e linhas de alta velocidade. O **motor de passo** é mais simples: gira em **passos fixos** e muitas vezes não tem encoder, a chamada **malha aberta**. É comum em impressoras 3D. Se a carga for maior do que ele aguenta, **perde passos** sem avisar. O servo percebe o erro e corrige, ou dispara um alarme.',
 'O motor de passo é como **andar de olhos fechados contando os passos**: funciona enquanto nada atrapalha, mas se tropeçar você perde a conta. O servo é **andar de olhos abertos com alguém ao lado dizendo "mais um pouco para a esquerda"**: sempre sabe onde está e corrige.',
 ['Entender onde se usam motores com posição exata: embalagem, robôs, CNC, impressoras 3D','Saber a diferença entre servomotor, em malha fechada, e motor de passo, em malha aberta','Reconhecer o papel do encoder e do servoacionamento','Diagnosticar alarmes de erro de posição e de seguimento'],
 ['estrutura',L('Posição desejada --> [ Servoacionamento ] --> [ Motor ] --> Carga','       ^                                          |','       |                                          |','       +--------- Encoder (posição real) <--------+','','Erro = posição desejada - posição real  -->  o acionamento corrige'),'É um laço de realimentação, como o PID: se a posição real não bate com a desejada, o acionamento aplica mais ou menos torque. Os ganhos do servo têm parâmetros parecidos com Kp, Ki e Kd.'],
 null,['sensores','inversor','pid','robotica','cnc','clp'],{alt:'Termos: malha fechada, malha aberta, encoder incremental e absoluto, resolver e drive de servo.',tags:'servo servomotor motor de passo stepper encoder posicionamento malha fechada aberta motion'}),

E('robotica','Robôs industriais e cobots','Braços programáveis que repetem tarefas com precisão, e os que trabalham ao lado de pessoas',1,
 'Um **robô industrial** é um braço mecânico com várias **juntas**, cada uma movida por um servomotor, e um **controlador** que calcula o movimento. O mais comum tem **6 eixos**. Solda, pinta, paletiza, move peças e monta. Ele é programado por um **controle portátil**, onde se **ensinam pontos** e trajetórias, pela linguagem do fabricante ou por simulação em computador. Os **cobots**, ou robôs colaborativos, são feitos para **trabalhar perto de pessoas**: força limitada, sensores de contato e, em geral, sem grades, desde que a aplicação passe por uma **análise de risco**. Fabricantes de robôs: ABB, Fanuc, KUKA e Yaskawa. De cobots: Universal Robots.',
 'O robô é o **soldador ou o pintor mais repetitivo e incansável da fábrica**: só faz o que foi ensinado, mas faz sempre igual. O cobot é o **ajudante que passa a ferramenta sem machucar ninguém**: mais fraco e mais lento, porém dá para trabalhar ao lado dele.',
 ['Entender onde robôs entram na produção: solda, pintura, paletização e montagem','Saber a diferença entre robô industrial e cobot','Conhecer como se programa um robô: ensinar pontos e escrever trajetórias','Reconhecer a importância da segurança e da análise de risco'],
 ['estrutura',L('PROGRAMA paletizar_caixa','  MOVER_LINEAR  ponto_pegar_acima','  MOVER_LINEAR  ponto_pegar','  FECHAR_GARRA','  MOVER_LINEAR  ponto_pegar_acima','  MOVER_JUNTAS  ponto_palete_acima','  MOVER_LINEAR  ponto_soltar','  ABRIR_GARRA'),'Pseudocódigo, só para mostrar a ideia. Cada fabricante tem a sua linguagem, como o RAPID, da ABB, mas todas combinam pontos ensinados com comandos de movimento e de garra.'],
 null,['servo','clp','visao-computacional','seguranca-maquinas','cnc','sensores'],{alt:'Tipos de robô: articulado, SCARA, delta (rápido, usado em embalagem) e cartesiano. Robôs móveis: AGV e AMR. Normas de segurança: ISO 10218 (robôs industriais) e ISO/TS 15066 (colaborativos).',tags:'robo industrial cobot braco 6 eixos abb fanuc kuka yaskawa universal robots paletizacao solda teach pendant'}),

E('cnc','CNC, G-code e impressão 3D','Máquinas que seguem um programa de coordenadas para cortar, furar ou construir peças',2,
 'A **CNC**, comando numérico computadorizado, é a máquina, como um torno, uma fresadora ou uma plasma, que **segue um programa de coordenadas** para mover as ferramentas. O programa é o **G-code**: linhas como G01 X10 Y20 F300, que mandam andar em linha reta até X igual a 10 e Y igual a 20, na velocidade 300. Em geral ele não é digitado: um software **CAM** gera o programa a partir do desenho feito em **CAD**. A **impressora 3D** usa a mesma ideia ao contrário: em vez de remover material, deposita camadas seguindo um G-code. Controles conhecidos: Fanuc, Siemens Sinumerik e Heidenhain, e nas máquinas pequenas o GRBL e o Marlin.',
 'É o **operador que lê o desenho e vai girando as manivelas**, só que o operador é um programa e as manivelas são servomotores. Cada linha do G-code é uma instrução do tipo "ande 10 milímetros para a direita, devagar".',
 ['Entender como um desenho vira peça: CAD, CAM, G-code e máquina','Ler as linhas básicas de um programa de CNC','Saber como uma impressora 3D recebe instruções','Conhecer o papel de servos, motores de passo e encoders nessas máquinas'],
 ['g-code',L('G21               ; unidades em milímetros','G90               ; coordenadas absolutas','G00 X0 Y0 Z5      ; vai rápido até a origem, 5 mm acima da peça','G01 Z-2 F100      ; desce 2 mm, devagar (100 mm por minuto)','G01 X40 F300      ; corta 40 mm em linha reta','G01 Y20           ; avança mais 20 mm','G00 Z5            ; sobe a ferramenta'),'G00 é movimento rápido, sem cortar, e G01 é movimento de trabalho, com velocidade controlada. O texto depois do ponto e vírgula é comentário. Os detalhes mudam de máquina para máquina, mas o núcleo é esse.'],
 null,['cad','servo','robotica','embarcados','arduino'],{alt:'Termos: G-code, M-code (comandos auxiliares, como ligar o fuso), fatiador (slicer) na impressão 3D, fresa, torno e router CNC.',tags:'cnc g-code gcode comando numerico torno fresadora impressora 3d marlin grbl cam usinagem'}),

E('cad','CAD, CAM e CAE','Desenhar a peça no computador, gerar o caminho da máquina e simular se ela aguenta',1,
 'O **CAD** é o software de **desenho técnico**: 2D, para plantas e esquemas, e 3D, para modelar peças e montagens. O **CAM** pega o desenho e gera o programa da máquina, o **G-code**. O **CAE** **simula** a peça antes de fabricar: resistência, com a análise por elementos finitos, calor, fluidos e vibração. Na parte elétrica existem programas para **esquemas de comando e painéis**. Nomes conhecidos: AutoCAD, SolidWorks, Inventor, Fusion, CATIA, FreeCAD, que é aberto, e o Blender, mais voltado a arte 3D. Os arquivos trocam de programa por formatos neutros, como o STEP, e a impressão 3D usa o STL.',
 'É a **prancheta do projetista com superpoderes**: desenha, gira a peça, monta o conjunto, pergunta "será que quebra?" e entrega o programa da máquina. Um erro descoberto na tela custa um clique, e descoberto na fábrica custa um lote de peças.',
 ['Entender as etapas entre o desenho e a peça pronta','Ler desenhos e modelos 3D e saber qual programa abre cada arquivo','Conhecer os programas de esquema elétrico e de painéis','Ver onde entram a simulação e a impressão 3D'],
 ['estrutura',L('CAD  desenha a peça e a montagem        arquivo .step, .dwg, .stl','CAE  simula esforço, calor e vibração   "aguenta a carga com folga"','CAM  gera o caminho da ferramenta       arquivo .nc (G-code)','CNC  usina a peça                       peça pronta'),'Nem todo projeto passa por todas as etapas. Para uma peça simples impressa em 3D, por exemplo, basta o CAD e o fatiador.'],
 null,['cnc','robotica','twin','blender','threejs'],{alt:'Formatos comuns: DWG e DXF (desenho 2D), STEP (modelo 3D neutro), STL (malha para impressão 3D). Parentes: BIM, na construção civil, e PLM, que gerencia o ciclo de vida do produto.',tags:'cad cam cae desenho tecnico autocad solidworks inventor fusion catia freecad 3d simulacao'}),

]);
