/* ===== Indústria e IoT (parte 3: redes, protocolos e IoT) ===== */
C('ind',[
E('redes-industriais','Redes industriais e fieldbus','Como CLPs, inversores e sensores conversam por um cabo só, em vez de um fio para cada sinal',2,
 'Uma **rede industrial** liga os equipamentos da fábrica, como CLPs, inversores, remotas de entradas e saídas, IHMs e sensores, por um **cabo compartilhado**, em vez de um fio para cada sinal. Cada equipamento tem um **endereço**, e todos seguem o mesmo **protocolo**, que é o idioma da conversa. As mais comuns são **Modbus**, **Profibus** e **Profinet**, muito ligados à Siemens, **EtherNet/IP**, da Rockwell, **EtherCAT**, para movimento rápido, e **CANopen**. As baseadas em **Ethernet** são mais rápidas, mas exigem cabos e switches próprios para o ambiente, e cuidado com a **segurança**.',
 'É a diferença entre um **ônibus** e uma frota de carros particulares. Antes, cada sensor tinha o seu fio até o painel, como cada passageiro indo no seu próprio carro. Na rede industrial, todos **sobem no mesmo ônibus**, cada um com o seu ponto de parada, que é o endereço, e o CLP vai chamando um por um.',
 ['Reduzir a fiação: um cabo em vez de centenas de fios até o painel','Ler dados do inversor, do medidor ou da remota direto no CLP, sem placa analógica','Diagnosticar falha de comunicação: endereço repetido, cabo, terminação ou velocidade errada','Entender como a máquina se liga ao supervisório e à rede da fábrica'],
 ['comparativo',L('Rede          Meio físico            Onde costuma aparecer','------------  ---------------------  -------------------------------------------','Modbus RTU    RS-485, par trançado   inversores, medidores, CLPs pequenos','Modbus TCP    Ethernet               supervisórios e gateways','Profibus DP   RS-485                 plantas existentes, muito comum','Profinet      Ethernet industrial    CLPs e remotas de linhas modernas','EtherNet/IP   Ethernet industrial    CLPs Rockwell (Allen-Bradley)','EtherCAT      Ethernet industrial    servos e movimento de alta velocidade','CANopen       CAN                    servos e equipamentos compactos','IO-Link       3 fios, ponto a ponto  sensores e atuadores inteligentes'),'Não existe uma rede melhor. A escolha costuma vir da marca do CLP e do que já está instalado. Para qualquer rede o diagnóstico começa igual: cabo e conectores, endereço único, mesma velocidade em todos e, no RS-485, resistores de terminação nas duas pontas da linha.'],
 null,['clp','modbus','opcua','mqtt','inversor','sensores','ihm','scada','seguranca-ot','redes','iiot'],{alt:'Termos: fieldbus (barramento de campo), Ethernet industrial e RS-485. Outras redes que você vai ouvir: DeviceNet, AS-Interface (AS-i), HART e PROFIsafe (para sinais de segurança). Inversores e soft-starters costumam ter Modbus RTU de fábrica e módulos opcionais para as outras redes.',tags:'redes industriais fieldbus profibus profinet ethernet/ip ethercat canopen devicenet modbus rs-485 rs485 as-i io-link barramento'}),

E('modbus','Modbus','O protocolo simples e antigo que quase todo inversor, medidor e CLP sabe falar',2,
 'O **Modbus** é um protocolo de comunicação de 1979 e ainda onipresente na indústria. Funciona em **pergunta e resposta**: um **mestre**, como um CLP ou supervisório, pergunta, e um **escravo**, como um inversor ou medidor, responde. Cada escravo tem um **endereço** de 1 a 247. Os dados ficam em **registradores**, números de 16 bits, e em **bobinas**, que são bits. O mestre pede coisas como "leia 2 registradores a partir do endereço 0" ou "escreva 1750 no registrador 4". Existem duas versões principais: o **Modbus RTU**, pela porta serial RS-485, com verificação de erros por **CRC**, e o **Modbus TCP**, pela rede Ethernet.',
 'É a **chamada na sala de aula**. O professor, que é o mestre, chama "aluno 3, qual é a sua nota?", e só o aluno 3 responde. Ninguém fala sem ser chamado. É simples e confiável, mas o professor chama um por um, então com muitos alunos a conversa demora.',
 ['Ler dados de inversores, medidores de energia, controladores de temperatura e sensores','Mudar parâmetros e comandar equipamentos de longe, como a velocidade de um inversor','Ligar o supervisório e a IHM ao CLP','Montar uma rede simples com equipamentos de marcas diferentes','Diagnosticar falhas de comunicação: endereço, velocidade, paridade e cabo'],
 ['estrutura',L('Pergunta do mestre (Modbus RTU), em hexadecimal:','','  01   03   00 00   00 02   C4 0B','  |    |    |       |       |','  |    |    |       |       CRC (detecta erro de transmissão)','  |    |    |       quantidade: 2 registradores','  |    |    endereço inicial: 0','  |    função 03: ler registradores','  endereço do escravo: 1','','Resposta do escravo:','','  01   03   04   02 58   00 7C   7B B9','            |     |       |','            |     600     124','            4 bytes de dados'),'O primeiro byte é o endereço do escravo, e o segundo é a função. A resposta repete os dois e traz os dados: 0258 em hexadecimal vale 600 e 007C vale 124. O fabricante diz o que cada registrador significa: 600 em décimos de hertz seria 60,0 Hz. Os dois últimos bytes são o CRC.'],
 'modbus',['redes-industriais','clp','inversor','scada','ihm','opcua','sensores','mqtt'],{alt:'Versões: Modbus RTU (serial, RS-485 ou RS-232), Modbus ASCII (raro) e Modbus TCP (Ethernet, porta 502). Funções mais usadas: 01 e 02 (ler bits), 03 e 04 (ler registradores), 05 e 06 (escrever um) e 15 e 16 (escrever vários). O nome moderno é cliente e servidor, mas mestre e escravo ainda é o que aparece nos manuais. Pegadinhas comuns: endereço contado a partir de 0 ou de 1, e a ordem dos bytes em números de 32 bits.',tags:'modbus rtu tcp rs485 rs-485 registrador holding coil mestre escravo cliente servidor crc inversor cfw'}),

E('opcua','OPC UA','O padrão moderno para máquinas e sistemas trocarem dados, com catálogo próprio e segurança',2,
 'O **OPC UA** é um padrão para **troca de dados industriais** entre máquinas e sistemas de marcas diferentes, como CLPs, supervisórios, MES e a nuvem. O diferencial é que o servidor **descreve o que tem**: uma árvore de **nós** com objetos, variáveis e métodos, cada um com nome, tipo e unidade. O cliente navega nessa árvore, **lê**, **escreve** e **assina** variáveis para ser avisado quando elas mudam, em vez de perguntar o tempo todo. Tem **segurança embutida**, com certificados, autenticação e criptografia, e roda em vários sistemas. Substituiu o antigo OPC clássico, que só funcionava no Windows.',
 'É um **cardápio padronizado**. Qualquer cliente abre o cardápio da máquina e vê o que ela oferece, com nome, tipo e unidade, sem precisar de manual. E o garçom só entrega o prato depois de conferir o seu crachá, que é a segurança.',
 ['Integrar CLPs de marcas diferentes a um supervisório, um MES ou um painel de dados','Receber só as mudanças de uma variável, em vez de ler tudo o tempo todo','Trocar dados com segurança, com autenticação e criptografia','Levar dados da máquina à nuvem sem escrever um conector para cada marca'],
 ['python',L('import asyncio','from asyncua import Client','','async def main():','    async with Client("opc.tcp://192.0.2.10:4840") as cliente:','        no = cliente.get_node("ns=2;s=Linha1.Esteira.Velocidade")','        print(await no.read_value())','','asyncio.run(main())'),'Conecta ao servidor, aponta para um nó pelo identificador e lê o valor. O endereço começa com opc.tcp, e 4840 é a porta padrão. O ns=2 é o espaço de nomes, e o texto depois é o nome do nó. O endereço 192.0.2.10 é fictício, de documentação. Na vida real, você também configura certificado e usuário.'],
 null,['modbus','scada','clp','mes','historian','iiot','mqtt','seguranca-ot','tls'],{alt:'Em inglês: OPC Unified Architecture. Parentes: OPC DA e OPC clássico (antigos, só no Windows), PubSub (o modelo de publicar e assinar do OPC UA) e as companion specifications, que padronizam o modelo de dados de cada tipo de máquina. Para testar: UaExpert (cliente) e Prosys (cliente e servidor de simulação).',tags:'opc ua opcua unified architecture servidor cliente nos namespace certificado seguranca industrial integracao asyncua'}),

E('mqtt','MQTT','O sistema de avisos por assunto que sensores e aplicativos usam para trocar mensagens pequenas',1,
 'O **MQTT** é um protocolo de mensagens leve, feito para dispositivos pequenos e redes ruins. Funciona por **publicar e assinar**. Quem tem um dado **publica** uma mensagem em um **tópico**, que é um nome em níveis, como fábrica, linha 1, prensa 2, temperatura. Quem quer receber **assina** o tópico. No meio fica o **broker**, que recebe tudo e entrega a quem assinou. Quem publica não sabe quem recebe, e quem recebe não sabe quem publicou. Na assinatura dá para usar curingas: o curinga **mais** troca um nível, e o curinga **cerquilha** pega todos os níveis seguintes. A **mensagem retida** guarda o último valor de um tópico.',
 'É um **grupo de avisos por assunto**, como os canais de um aplicativo de mensagens. O sensor posta no canal "temperatura da prensa 2", e quem se inscreveu no canal recebe. O sensor não precisa conhecer ninguém, e o broker é o carteiro que entrega a cada inscrito.',
 ['Mandar leituras de sensores de uma máquina para um painel ou para a nuvem','Comandar dispositivos pequenos, como placas ESP32 e Arduino, pela rede','Juntar dados de muitas fontes sem ligar cada uma a cada destino','Funcionar em redes instáveis, com mensagens pequenas e pouco consumo','Entender a base de muitas plataformas de IoT e do Sparkplug, usado na indústria'],
 ['estrutura',L('Quem publica (sensor da prensa 02):','  tópico    fabrica/linha1/prensa02/temperatura','  mensagem  72.5','','Quem assina (painel da manutenção):','  fabrica/linha1/+/temperatura   a temperatura de todas as máquinas da linha 1','  fabrica/linha1/#               tudo o que for da linha 1','','O broker (Mosquitto, EMQX, HiveMQ) recebe e entrega aos assinantes.'),'O sinal de mais troca exatamente um nível. A cerquilha vale para todos os níveis restantes e só pode aparecer no fim do filtro. A porta padrão é a 1883, ou a 8883 com criptografia. Nunca deixe um broker aberto na internet sem senha e criptografia: ele vira porta de entrada para a sua rede.'],
 'mqtt',['iot','iiot','redes-industriais','esp32','arduino','websocket','kafka','filas','opcua','seguranca-ot','tls'],{alt:'Qualidade de serviço (QoS): 0 é no máximo uma vez, 1 é pelo menos uma vez e 2 é exatamente uma vez. Outros recursos: sessão persistente, mensagem retida e last will (mensagem de despedida quando o cliente cai). Brokers: Mosquitto, EMQX e HiveMQ. Na indústria, o Sparkplug B padroniza tópicos e mensagens em cima do MQTT. Parente mais pesado: AMQP, usado pelo RabbitMQ.',tags:'mqtt broker topico publish subscribe pub sub mosquitto iot mensagens leve qos retida sparkplug curinga'}),

E('iot','Internet das Coisas (IoT)','Objetos comuns com sensor e conexão, contando o que sentem e recebendo ordens pela rede',1,
 'A **Internet das Coisas**, ou IoT, é a ideia de colocar **sensores e conexão** em objetos do dia a dia e em máquinas, para que eles **mandem dados e recebam comandos** pela rede. Uma lâmpada que liga pelo celular, um medidor de água que informa o consumo, um sensor que avisa que a caixa de água está vazia: tudo isso é IoT. O caminho costuma ser o mesmo: o **dispositivo** lê o sensor, uma **conexão** leva o dado, uma **plataforma** guarda e processa, e um **painel ou aplicativo** mostra e age. O maior problema é a **segurança**: dispositivos baratos, com senha padrão e sem atualização, viram porta de entrada para ataques.',
 'É dar **boca e ouvido** a um objeto. Antes, a caixa de água só sabia ficar cheia ou vazia, e você descobria subindo no telhado. Agora ela **conta para você**, de onde estiver, que está com 20% de água.',
 ['Monitorar máquinas, ambientes, energia, água e estoques à distância','Automatizar a casa ou a empresa com regras do tipo "se isso acontecer, faça aquilo"','Montar projetos com ESP32, Arduino e Raspberry Pi, que juntam sensores e rede','Coletar dados para análise e para manutenção preditiva','Entender os riscos de segurança de dispositivos conectados'],
 ['estrutura',L('[ Sensor de temperatura ]','        |','[ ESP32: lê o sensor a cada 10 s ]','        |   Wi-Fi + MQTT','[ Broker ]','        |','[ Banco de dados de séries temporais ]','        |','[ Painel com gráfico e alerta no celular ]'),'Cada caixa é uma etapa e pode ser trocada: o sensor pode ser outro, a conexão pode ser LoRa em vez de Wi-Fi e o painel pode ser um aplicativo. O que não muda é o caminho: ler, enviar, guardar e mostrar. Cada etapa precisa de senha própria e de atualização.'],
 null,['mqtt','iiot','esp32','arduino','raspberry','lpwan','wifi','timeseries','cloud','seguranca-ot','edge','sensores'],{alt:'Siglas: IoT (Internet of Things), M2M (máquina com máquina) e IIoT (IoT industrial). Plataformas conhecidas: AWS IoT Core, Azure IoT Hub, ThingsBoard, Home Assistant (para casa) e Node-RED (fluxos visuais de dados).',tags:'iot internet das coisas sensores conexao plataforma smart home automacao residencial dispositivos conectados'}),

E('iiot','IIoT (IoT industrial)','Levar os dados das máquinas da fábrica à análise com segurança, sem parar nem mexer na produção',2,
 'O **IIoT**, a Internet das Coisas industrial, é o IoT aplicado à fábrica, com mais exigência de **robustez** e de **segurança**. O caso mais comum é o **retrofit**: pegar máquinas antigas, sem rede, e tirar dados delas, seja **adicionando sensores por fora**, como um de vibração e temperatura no motor, seja **lendo o que o CLP já sabe**. Entre a máquina e a nuvem fica o **gateway de borda**, que converte protocolos, filtra e resume os dados e guarda tudo se a rede cair. O objetivo é prático: ver a produção em tempo real, medir indicadores e **prever falhas antes da parada**.',
 'É colocar um **monitor cardíaco** numa máquina que antes só era examinada na ronda. O monitor não substitui o médico, que é o técnico. Ele só **avisa mais cedo** que o coração, no caso o motor, está batendo diferente.',
 ['Conectar máquinas antigas à análise de dados, sem trocar o CLP','Acompanhar indicadores como OEE, vibração e consumo de energia em tempo real','Receber alertas antes da falha, e não com a linha parada','Entender o papel do gateway de borda e da separação entre rede da fábrica e rede de TI','Avaliar o que vale conectar: dado sem ação é custo, não ganho'],
 ['estrutura',L('Rede da fábrica (OT)                                  Rede de TI e nuvem','---------------------------------------------------  ---------------------','Sensor / CLP --> Gateway de borda --> Firewall --> Broker MQTT --> Painel','Modbus           converte e filtra     só saída    TLS             alertas','OPC UA           guarda se cair       controlada                  OEE'),'O dado sai da máquina por um caminho de mão única: o gateway pergunta ao CLP, e a conexão parte da rede da fábrica para fora, sem abrir portas para dentro. Essa regra protege a produção. Sem ela, cada máquina conectada vira uma porta de entrada.'],
 'iiot',['iot','mqtt','opcua','modbus','edge','manutencao-preditiva','oee','seguranca-ot','industria40','historian','twin'],{alt:'Termos parecidos: retrofit (modernizar máquinas antigas), brownfield (fábrica que já existe) e greenfield (fábrica nova). Conceitos de segurança: convergência entre TI e OT, e o modelo Purdue, que organiza em níveis a rede industrial.',tags:'iiot iot industrial retrofit gateway borda edge brownfield greenfield ti ot convergencia dados maquinas antigas'}),

E('lpwan','LoRa, LoRaWAN e NB-IoT','Redes de longo alcance e pouca energia para sensores que mandam pouca informação',2,
 'As redes **LPWAN**, de baixa potência e longa distância, servem para sensores que **mandam poucos dados** e precisam durar **anos com uma bateria**. O **LoRa** é a tecnologia de rádio, e o **LoRaWAN** é a rede construída em cima dela: o sensor fala com um **gateway**, que pode estar a vários quilômetros em campo aberto, e o gateway leva a mensagem à internet. Funciona em faixas de rádio livres, sem pagar operadora. O **NB-IoT** e o **LTE-M** são parecidos, mas usam a rede de uma operadora de celular. O preço é a **velocidade baixíssima**: mensagens de poucos bytes, de tempos em tempos. Servem para medir, não para controlar em tempo real.',
 'O Wi-Fi é uma **conversa animada dentro da sala**: fala muito, mas só se ouve de perto. O LoRa é **um grito de uma palavra só que atravessa o vale**: diz pouco, mas chega longe e quase não gasta fôlego.',
 ['Monitorar tanques, poços, bombas e medidores em locais distantes, sem cabo nem tomada','Acompanhar lavoura, rebanho, clima e solo','Rastrear ativos e contêineres, com bateria que dura anos','Escolher a rede certa para cada sensor: alcance, bateria, velocidade e custo','Entender por que essas redes não servem para comando em tempo real'],
 ['comparativo',L('Tecnologia      Alcance típico        Velocidade     Bateria  Uso comum','--------------  --------------------  -------------  -------  --------------------------','Wi-Fi           dezenas de metros     alta           curta    dentro de prédios','Bluetooth LE    dezenas de metros     média          anos     celular, etiquetas','Zigbee, Thread  dezenas de m, malha   baixa          anos     automação predial','LoRaWAN         km em campo aberto    muito baixa    anos     sensores remotos','NB-IoT, LTE-M   rede celular          baixa a média  anos     medidores, rastreadores','4G e 5G         rede celular          alta           curta    câmeras, veículos'),'Não existe a melhor rede, existe a rede certa para cada caso. Para um sensor de nível de tanque que manda uma leitura por hora, LoRaWAN ou NB-IoT é ideal. Para uma câmera, é Wi-Fi ou 4G e 5G. Para comandar uma máquina em tempo real, nenhuma delas: o caminho é cabo e rede industrial.'],
 null,['iot','iiot','mqtt','wifi','sensores','esp32','redes'],{alt:'O LoRa foi criado pela Semtech, e o LoRaWAN é mantido pela LoRa Alliance. No Brasil, costuma-se usar a faixa de 915 MHz. A segurança do LoRaWAN usa chaves de criptografia AES de 128 bits. Parentes: Sigfox (rede concorrente), Zigbee, Thread e Bluetooth de baixa energia (BLE).',tags:'lora lorawan nb-iot nbiot lte-m lpwan longo alcance baixa energia sensores remotos gateway bateria'}),

E('rfid','RFID, NFC e código de barras','Como identificar peças, ferramentas e caixas automaticamente, com luz ou com rádio',1,
 'O **código de barras** e o **QR code** identificam um item por **leitura óptica**: o leitor precisa enxergar o código, que é impresso e baratíssimo. O **RFID** identifica por **rádio**: uma etiqueta com um chip responde ao leitor, **sem contato e sem linha de visão**, e vários itens podem ser lidos de uma vez. A etiqueta **passiva** não tem bateria, pois usa a energia do próprio sinal do leitor. A **ativa** tem bateria e alcança mais longe. O **NFC** é o RFID de curtíssimo alcance, de poucos centímetros, o mesmo do pagamento por aproximação no celular. Na fábrica serve para **rastrear peças, ferramentas e paletes**, e para controlar acesso.',
 'O código de barras é o **nome escrito na camiseta**: alguém tem que olhar para ler. O RFID é o **crachá com chip**: basta passar perto da catraca, e a catraca descobre quem é, mesmo sem ver.',
 ['Rastrear peças e lotes ao longo da produção, e saber onde está cada item','Controlar ferramentas, paletes e equipamentos, e localizar o que sumiu','Contar estoque em segundos, sem abrir caixa por caixa','Ler o QR code colado na máquina para abrir o histórico de manutenção dela','Controlar acesso a áreas e a equipamentos'],
 ['comparativo',L('Tecnologia          Como lê                  Alcance típico  Exemplo','------------------  -----------------------  --------------  ----------------------------','Código de barras    luz, linha de visão      centímetros     etiqueta de produto','QR code             câmera                   centímetros     etiqueta colada na máquina','RFID baixa freq.    rádio, 125 kHz           até cerca de 10 cm  crachá antigo, chip animal','RFID e NFC (alta)   rádio, 13,56 MHz         poucos cm       cartão, celular, bilhete','RFID UHF            rádio, 860 a 960 MHz     alguns metros   estoque, paletes, logística'),'O alcance depende da frequência, da antena e do material em volta: metal e líquido atrapalham o rádio, e existem etiquetas especiais para uso sobre metal. Para identificar um equipamento da fábrica, o QR code costuma ser a opção mais barata. O RFID compensa quando a leitura precisa ser automática e em volume.'],
 null,['sensores','iot','iiot','cmms','mes','erp','clp','visao-computacional'],{alt:'Termos: tag ou etiqueta, leitor, antena, EPC (código eletrônico do produto) e rastreabilidade. Parentes: código de barras 1D e 2D (Data Matrix, muito usado para marcar peças usinadas) e NFC (RFID de alta frequência no celular).',tags:'rfid nfc codigo de barras qr code etiqueta tag leitor rastreabilidade identificacao pecas ferramentas'}),

]);
