/* ===== Indústria e IoT (parte 4: eletrônica embarcada, tempo real e dados de processo) ===== */
C('ind',[
E('embarcados','Sistemas embarcados e firmware','O computador escondido dentro de outro equipamento, com uma função só',1,
 'Um **sistema embarcado** é um computador escondido dentro de outro equipamento, com **uma função específica**: o micro-ondas, a máquina de lavar, o painel do carro, o inversor de frequência, o CLP. Ele tem processador, memória e **entradas e saídas** que falam com o mundo físico, e roda um programa chamado **firmware**, gravado de fábrica. Ao contrário do computador comum, tem **poucos recursos** de memória e de energia, e muitas vezes precisa responder em **tempo certo**. Quase sempre é programado em C ou C++, e cada vez mais em Rust e em MicroPython. É um dos tipos de computador mais numerosos que existem.',
 'É o **cérebro escondido dentro dos aparelhos**. Ninguém abre o micro-ondas para programar: ele já vem com o cérebro pronto para uma tarefa só. O computador do escritório é um canivete suíço, e o embarcado é uma chave de fenda: faz uma coisa só, mas faz sempre.',
 ['Entender o que existe dentro de inversores, CLPs, medidores e sensores inteligentes','Atualizar o firmware de um equipamento e saber os riscos de fazer isso','Criar dispositivos próprios: um sensor de temperatura, um controlador, um registrador de dados','Trabalhar com eletrônica e programação juntas, do bit ao mundo físico'],
 ['estrutura',L('Sensores  -->  [ Microcontrolador ]  -->  Atuadores','(entradas)     CPU + memória + periféricos     (saídas)','                          |','              firmware: o programa gravado na memória flash','                          |','     comunicação: UART, I2C, SPI, CAN, Wi-Fi, RS-485'),'O microcontrolador junta processador, memória e periféricos num chip só. O firmware fica na memória flash e começa a rodar quando se liga a energia. A atualização de firmware de um equipamento é isso: um programa novo gravado nessa memória. Se faltar energia no meio, o equipamento pode ficar inutilizável, por isso siga o procedimento do fabricante.'],
 null,['microcontrolador','arduino','esp32','raspberry','tempo-real','c','cpp','rust','hardware','clp','inversor','assembly'],{alt:'Termos: firmware, microcontrolador (MCU), RTOS (sistema operacional de tempo real), bootloader e periféricos. Siglas de comunicação que você vai encontrar: UART, I2C, SPI e CAN.',tags:'embarcados embedded firmware microcontrolador mcu sistemas dedicados eletronica flash gpio'}),

E('microcontrolador','Microcontroladores e periféricos','Um computador inteiro num chip só, com pinos para falar com o mundo físico',2,
 'Um **microcontrolador**, ou MCU, é um **computador inteiro num chip só**: processador, memória para o programa, memória de trabalho e **periféricos** para falar com o mundo. Os principais são os pinos de **entrada e saída digital**, os GPIO, que ligam e desligam coisas; o **conversor analógico-digital**, ou ADC, que lê tensões, como a de um sensor de temperatura; o **PWM**, que simula uma saída variável ligando e desligando muito rápido, usado em lâmpadas e motores; e as **portas de comunicação**, como UART, I2C e SPI. Fabricantes conhecidos: STMicroelectronics, com o STM32, Microchip, com PIC e AVR, Espressif, com o ESP32, NXP e Texas Instruments.',
 'É o **CLP reduzido a um chip**: ele também lê entradas, executa o programa e liga saídas. Só que sem a caixa robusta, os terminais de parafuso e a certificação industrial. É a matéria-prima de que são feitos os inversores, os sensores inteligentes e muitos outros equipamentos.',
 ['Ler sensores e comandar saídas em projetos próprios','Entender para que serve cada pino e cada porta de uma placa ou de um equipamento','Controlar a velocidade de um motor ou o brilho de uma lâmpada com PWM','Ligar dispositivos entre si por UART, I2C ou SPI','Escolher o chip certo para um projeto: custo, consumo, memória e recursos'],
 ['comparativo',L('Periférico  Para que serve                          Exemplo','----------  --------------------------------------  ------------------------------------','GPIO        liga e desliga pinos, lê botões         acender um LED, ler um fim de curso','ADC         transforma uma tensão em um número      ler um sensor de temperatura','PWM         varia a potência ligando e desligando   velocidade de motor, brilho de LED','UART        conversa serial entre dois dispositivos placa com módulo GPS ou GSM','I2C         dois fios, vários dispositivos          sensores pequenos e displays','SPI         rápido, um fio de seleção por chip      cartão SD, telas e memórias'),'A maioria dos sensores pequenos e módulos usa I2C ou SPI, e a ligação entre dois microcontroladores, ou com um computador, costuma ser UART. O RS-485 do Modbus é uma UART com um circuito elétrico a mais, para atravessar distâncias maiores e ruído.'],
 null,['embarcados','arduino','esp32','raspberry','sensores','sinal420','c','cpp','tempo-real','clp','servo'],{alt:'Famílias: AVR (Arduino Uno), ARM Cortex-M (STM32, RP2040), ESP32 (com Wi-Fi e Bluetooth) e PIC. Parentes: DSP (processamento de sinais), FPGA (circuito que se reconfigura) e SoC (sistema num chip, como o do celular).',tags:'microcontrolador mcu gpio adc pwm uart i2c spi chip stm32 pic avr perifericos'}),

E('arduino','Arduino','A plataforma de placas e programação simples que popularizou a eletrônica e os microcontroladores',1,
 'O **Arduino** é uma plataforma de **placas de microcontrolador** com um ambiente de programação bem simples, criada para ensinar e para fazer protótipos. A placa mais conhecida, o **Arduino Uno**, tem pinos digitais e analógicos onde se ligam LEDs, botões, sensores e motores. Você escreve um programa, chamado de **sketch**, numa linguagem baseada em C++, e grava na placa pelo cabo USB. Todo sketch tem duas partes: o **setup**, que roda uma vez ao ligar, e o **loop**, que se repete para sempre, como o ciclo de varredura de um CLP. Existem milhares de **bibliotecas** prontas para sensores e módulos. É código aberto, e há muitas placas compatíveis.',
 'É o **kit de Lego da eletrônica**. As peças já vêm prontas, que são a placa e as bibliotecas, os encaixes são padronizados, e você monta a ideia sem soldar o chip nem entender cada detalhe do circuito. Num projeto de verdade, depois se troca por peças mais robustas.',
 ['Aprender programação e eletrônica com resultados visíveis: acender, mover, medir','Fazer protótipos rápidos de sensores, controladores e automações','Registrar dados de temperatura, vibração ou consumo num cartão de memória','Simular na bancada um comando que depois será feito em CLP','Aprender a lógica de entradas, saídas e temporização com baixo custo'],
 ['cpp',L('const int BOTAO = 2;','const int LED = 13;','','void setup() {','  pinMode(BOTAO, INPUT_PULLUP);','  pinMode(LED, OUTPUT);','}','','void loop() {','  bool apertado = (digitalRead(BOTAO) == LOW);','  digitalWrite(LED, apertado ? HIGH : LOW);','}'),'O setup configura o pino 2 como entrada, com o resistor interno de pull-up, e o 13 como saída. O loop repete: lê o botão e acende o LED enquanto ele estiver apertado. Com pull-up, o botão ligado ao terra lê LOW quando apertado, ao contrário do que parece. É a mesma ideia da varredura de um CLP: lê a entrada, decide e escreve a saída.'],
 null,['microcontrolador','embarcados','esp32','raspberry','cpp','c','sensores','clp','iot','servo'],{alt:'Placas: Uno (a clássica), Nano (pequena), Mega (mais pinos) e as com Wi-Fi, como a Uno R4 WiFi. Ambiente de programação: Arduino IDE e Arduino Cloud. Concorrentes e parentes: PlatformIO (ambiente profissional), ESP32 e Raspberry Pi Pico.',tags:'arduino uno nano mega sketch setup loop placa prototipo eletronica microcontrolador ide'}),

E('esp32','ESP32','O microcontrolador barato com Wi-Fi e Bluetooth que virou a base de muitos projetos de IoT',1,
 'O **ESP32** é uma família de microcontroladores da empresa **Espressif** que já vêm com **Wi-Fi e Bluetooth** dentro do chip. Isso o torna o favorito dos projetos de **IoT**: ele lê um sensor e manda o dado pela rede por um custo bem baixo. A versão original tem dois núcleos de processamento, bastante memória para a categoria, entradas analógicas e digitais, PWM e portas de comunicação. Pode ser programado pelo **ambiente do Arduino**, em **C e C++** com o ESP-IDF, o kit oficial da Espressif, ou em **MicroPython**. Cuidado com o consumo de energia e com a segurança: o Wi-Fi o expõe à rede.',
 'É um **Arduino que já nasceu com internet**. A placa clássica lê sensores e liga coisas, mas não fala com a rede sozinha. O ESP32 traz o rádio dentro do chip, então o mesmo sensor já manda o dado ao celular ou à nuvem.',
 ['Montar sensores que mandam dados por Wi-Fi, como temperatura, umidade, vibração ou corrente','Criar painéis e controles pelo celular, por páginas na rede local','Publicar leituras por MQTT para um painel ou para a nuvem','Prototipar um dispositivo de IoT barato antes de comprar uma solução industrial','Fazer projetos com Bluetooth, como ler sensores pelo celular'],
 ['python',L('import network, time','from machine import Pin, ADC','','wifi = network.WLAN(network.STA_IF)','wifi.active(True)','wifi.connect("minha-rede", "senha-da-rede")','','sensor = ADC(Pin(34))','while True:','    print("leitura:", sensor.read())','    time.sleep(10)'),'Liga o Wi-Fi da placa, conecta na rede e, a cada 10 segundos, lê o valor do pino 34 e mostra. Nunca deixe o nome e a senha da rede escritos no código que você compartilha. Num projeto de verdade, o próximo passo é enviar a leitura por MQTT, com a senha guardada fora do código. Atenção: alguns pinos do ESP32 só servem como entrada ou têm função especial na partida.'],
 null,['arduino','microcontrolador','embarcados','iot','mqtt','wifi','raspberry','python','c','cpp','lpwan'],{alt:'Variações: ESP32-S3, C3 e C6, mais novas, e o ESP8266, o antecessor, só com Wi-Fi. Parentes: Raspberry Pi Pico W e as placas STM32.',tags:'esp32 espressif wifi bluetooth iot microcontrolador esp8266 devkit micropython esp-idf'}),

E('raspberry','Raspberry Pi','O computador completo do tamanho de um cartão, com Linux e pinos para ligar ao mundo físico',1,
 'O **Raspberry Pi** é um **computador completo** do tamanho de um cartão de crédito. Roda **Linux**, tem processador, memória, USB, rede e saída de vídeo, e ainda traz uma fileira de **pinos GPIO** para ligar sensores, botões e motores. É diferente de um microcontrolador, como o ESP32 ou o Arduino: ele tem **sistema operacional**, então roda programas em **Python**, bancos de dados, servidores web e até um painel de supervisão. Em compensação, gasta mais energia, demora para ligar e **não responde em tempo exato**, o que o deixa de fora de controles críticos. Na prática serve de **gateway**, servidor local, central de automação e computador de projeto.',
 'Se o ESP32 é uma **ferramenta de uma tarefa só**, o Raspberry Pi é uma **oficina inteira numa mesa pequena**: tem bancada, gavetas e energia para várias ferramentas ao mesmo tempo, mas ocupa mais espaço e gasta mais.',
 ['Montar um gateway que lê sensores ou o CLP e manda os dados para a nuvem','Rodar um broker MQTT, um banco de dados e um painel pequeno na própria fábrica','Fazer projetos de visão computacional e de IA em pequena escala','Aprender Linux e Python num computador barato e seguro de errar','Criar uma central de automação residencial'],
 ['python',L('from gpiozero import LED, Button','from signal import pause','','led = LED(17)','botao = Button(2)','','botao.when_pressed = led.on','botao.when_released = led.off','pause()'),'A biblioteca gpiozero esconde os detalhes dos pinos. O LED está no pino 17 e o botão no pino 2, e basta dizer o que fazer quando o botão for apertado ou solto. O pause mantém o programa rodando, esperando eventos. Ao contrário do Arduino, esse programa roda dentro de um Linux, que pode atrasar a resposta por alguns milissegundos.'],
 null,['esp32','arduino','embarcados','linux','python','iot','mqtt','iiot','edge','docker','visao-computacional'],{alt:'Modelos: Raspberry Pi 4 e 5 (computadores completos), Zero (pequeno e barato) e Pico (que é um microcontrolador). Alternativas: Orange Pi, Banana Pi e mini PCs industriais. Para uso em painel existem computadores industriais robustos, com certificações, que fazem o mesmo papel.',tags:'raspberry pi raspi gpio linux computador placa single board sbc gateway pico gpiozero'}),

E('tempo-real','Sistemas de tempo real','Quando acertar é responder dentro do prazo, e uma resposta atrasada vale tanto quanto uma errada',2,
 'Num **sistema de tempo real**, o resultado só está certo se chegar **dentro do prazo**. Não é sobre ser rápido, é sobre ser **previsível**: um freio ABS, um CLP e o controle de um servomotor precisam responder sempre dentro de um tempo definido, e não "em geral rápido". O tempo real **rígido** é aquele em que perder o prazo é falha grave, como em airbags e na proteção de máquinas. No **brando**, atrasar só piora a qualidade, como no vídeo. Para isso se usa um **RTOS**, sistema operacional de tempo real, com **prioridades** e **interrupções**. O Windows e o Linux comuns não garantem prazo.',
 'É a diferença entre **chegar rápido** e **chegar na hora certa**. O motorista que leva 10 minutos todo dia é mais confiável do que o que leva 2 minutos numa manhã e 40 em outra. Para controlar uma máquina, a previsibilidade vale mais do que a velocidade média.',
 ['Entender por que o CLP e o inversor são feitos como são, e não como um PC comum','Escolher a plataforma certa para o prazo exigido: microcontrolador, CLP ou Raspberry Pi','Entender o que são interrupções, prioridades e o cão de guarda','Saber que PC e Linux comuns não servem para proteção nem para controle rápido de máquina'],
 ['comparativo',L('Tarefa                       Prazo típico      Se atrasar','--------------------------  ----------------  --------------------------------------','Parada de emergência        dezenas de ms     risco de acidente (tempo real rígido)','Malha de controle de servo  cerca de 1 ms     movimento instável (rígido)','Varredura do CLP            alguns ms         saída atrasada, processo descontrolado','Atualizar a tela da IHM     centenas de ms    lentidão visível, sem dano (brando)','Mandar dados para a nuvem   segundos          o dado chega depois, e tudo bem'),'Os números são ordens de grandeza para dar a ideia, não regras: cada aplicação tem o seu requisito. O ponto é que, quanto mais perto da máquina, mais curto e mais rígido é o prazo, e mais específico precisa ser o equipamento. Por isso o CLP faz o controle e a nuvem só recebe os dados depois.'],
 null,['clp','embarcados','microcontrolador','servo','seguranca-maquinas','raspberry','linux','eventloop','processos','arduino'],{alt:'Termos: RTOS (FreeRTOS, Zephyr e VxWorks são exemplos), jitter (variação do tempo de resposta), latência, determinismo e watchdog. Em redes, o equivalente é a rede determinística, como EtherCAT e Profinet IRT.',tags:'tempo real rtos real-time deterministico prazo latencia jitter interrupcao prioridade freertos'}),

E('historian','Historiador de dados (data historian)','O banco de dados feito para guardar milhões de leituras de sensores ao longo dos anos',2,
 'O **historiador**, ou data historian, é um banco de dados especializado em guardar **leituras de sensores ao longo do tempo**: temperatura, pressão, corrente, vibração, ano após ano. Ele recebe dados do supervisório e dos CLPs, muitas vezes **vários por segundo e de milhares de pontos**, e os guarda de forma **comprimida**, registrando só quando o valor muda de verdade. Na consulta, devolve rápido a **curva** de uma variável em qualquer período e permite comparar horários, turnos e lotes. É a fonte dos **gráficos de tendência**, da investigação de falhas e do **treino de modelos de previsão**. Exemplos: o **PI System**, da AVEVA, e o InfluxDB, que é aberto.',
 'É o **caderno de anotações da planta, com leitura a cada instante e memória de elefante**. Quando algo quebra, você volta no tempo e vê a vibração da semana anterior, a temperatura da véspera e o que o operador mudou na hora, em vez de depender da lembrança de alguém.',
 ['Investigar a causa de uma parada olhando o que as variáveis faziam antes dela','Acompanhar a tendência de desgaste de um equipamento ao longo de meses','Comparar lotes, turnos e máquinas com dados reais','Alimentar relatórios, indicadores como o OEE e modelos de IA','Guardar o registro exigido para rastreabilidade'],
 ['estrutura',L('Variável               Valor   Data e hora           Qualidade','---------------------  ------  --------------------  ---------','Prensa02.Temperatura   72,5    2026-03-14 09:15:02   boa','Prensa02.Temperatura   72,6    2026-03-14 09:15:03   boa','Prensa02.Vibração      3,1     2026-03-14 09:15:03   boa','Prensa02.Corrente      0,0     2026-03-14 09:15:03   ruim: sensor sem sinal','','Consulta típica: temperatura da Prensa02 entre 8h e 10h de ontem'),'São milhões de linhas assim por dia, e por isso o banco é específico: grava rápido, comprime e responde bem a consultas por período. Num banco comum, a tabela ficaria enorme e lenta. A coluna de qualidade avisa se o sensor estava funcionando, para você não confiar num zero que era um fio solto.'],
 null,['scada','timeseries','mes','oee','manutencao-preditiva','opcua','banco-dados','sql','iiot','anomalia','cmms'],{alt:'Termos: série temporal (time series), compressão por banda morta, tag (o nome de cada ponto) e tendência (trend). Parentes abertos: InfluxDB, TimescaleDB, Prometheus (mais usado em TI) e Grafana, para os gráficos.',tags:'historian historiador data historian pi system series temporais tendencia tags influxdb timescaledb scada'}),

E('twin','Gêmeo digital','Uma cópia virtual de uma máquina ou fábrica, alimentada com dados reais para testar e prever',2,
 'Um **gêmeo digital** é um **modelo virtual** de uma máquina, de uma linha ou de uma fábrica inteira, **ligado aos dados reais** dela. O modelo recebe as leituras dos sensores e se comporta como o equipamento de verdade, o que permite **testar mudanças sem arriscar a produção**, ver o que não dá para medir por dentro da máquina e **prever** quando uma peça vai falhar. Pode ser um **modelo simples**, como a curva de temperatura esperada, ou uma **simulação 3D completa**. Muita coisa chamada de gêmeo digital hoje é só um painel bonito: o que o define é a **ligação com o equipamento real** e a capacidade de simular.',
 'É a **maquete viva** de uma fábrica: a maquete recebe, em tempo real, os mesmos números da fábrica. Antes de mudar a velocidade da linha, você muda na maquete e vê se o motor aguenta.',
 ['Testar mudanças de processo, velocidade ou layout no modelo, sem parar a produção','Prever desgaste e falhas combinando dados reais com um modelo físico','Treinar operadores e técnicos num ambiente seguro','Validar o programa do CLP antes de a máquina existir, o chamado comissionamento virtual','Acompanhar à distância o estado de uma máquina vendida a um cliente'],
 ['estrutura',L('Máquina real  --- sensores --->  Gêmeo digital (modelo + dados)','     ^                                       |','     |                                       v','     +--- decisão ou ajuste  <---  simula, compara e prevê','','Exemplo: o gêmeo do motor calcula a temperatura que o enrolamento DEVERIA ter.','Se o sensor mostra 15 °C a mais, há algo errado: filtro sujo, rolamento, sobrecarga.'),'O gêmeo compara o que deveria acontecer com o que de fato acontece. A diferença entre os dois é o sinal de alerta. É parecido com a manutenção preditiva, só que com um modelo do equipamento por trás.'],
 null,['iiot','manutencao-preditiva','cad','historian','industria40','threejs','ia','anomalia','edge'],{alt:'Termos: simulação, comissionamento virtual, modelo físico (baseado em equações) e modelo de dados (baseado em aprendizado de máquina). Parentes: CAE (simulação de engenharia) e o metaverso industrial, nome dado a ambientes 3D compartilhados de fábrica.',tags:'gemeo digital digital twin simulacao modelo virtual comissionamento virtual previsao fabrica'}),

]);
