/* ===== Indústria e IoT (parte 5: manutenção, indicadores, segurança e energia) ===== */
C('ind',[
E('manutencao-preditiva','Manutenção preditiva e análise de vibração','Descobrir que a máquina vai falhar antes da parada, ouvindo vibração, temperatura e corrente',2,
 'A **manutenção preditiva** acompanha o **estado real** da máquina e programa a intervenção **antes da falha**, em vez de trocar peças por tempo ou consertar depois da quebra. Os dados vêm de **medições**: a **vibração**, que revela desbalanceamento, desalinhamento, folga e defeitos de rolamento; a **temperatura**, inclusive por termografia; a **corrente do motor**; o ruído; e a análise do óleo. A vibração é medida por **acelerômetros** e analisada na **frequência**: o **espectro** mostra picos ligados à rotação do eixo, e cada tipo de defeito deixa uma assinatura. Hoje se juntam a isso o **IIoT** e a **IA**, que detectam mudanças sozinhas, mas o diagnóstico exige conhecer a máquina.',
 'É o **médico que escuta o coração com o estetoscópio**: ele não espera o paciente cair para agir, e uma batida diferente já indica o que investigar. A vibração é o batimento da máquina, e cada defeito tem o seu sopro característico.',
 ['Programar a parada antes da quebra, no momento mais barato','Reduzir paradas inesperadas e trocas de peças que ainda tinham vida útil','Identificar a causa de um problema: desbalanceamento, desalinhamento, folga ou rolamento','Decidir quais equipamentos merecem monitoramento contínuo','Entender o que os sensores e os relatórios de condição querem dizer'],
 ['comparativo',L('Defeito               Onde aparece no espectro              Pista extra','--------------------  ------------------------------------  ---------------------------------','Desbalanceamento      pico forte em 1x a rotação            maior na direção radial','Desalinhamento        1x e 2x, às vezes 3x                  vibração axial alta','Folga mecânica        várias harmônicas e meia rotação      piora com base ou parafuso solto','Rolamento com defeito frequências próprias do rolamento,    aparecem cedo, em alta frequência','                      que não são múltiplas da rotação','Elétrico (motor)      2x a frequência da rede (120 Hz)      some ao cortar a energia'),'São regras gerais, e não um diagnóstico: o diagnóstico de verdade combina espectro, fase, tendência ao longo do tempo e conhecimento da máquina, e é trabalho de um analista de vibração certificado (norma ISO 18436). A tendência pesa mais que o valor isolado: subir 40% em duas semanas diz mais do que um número que já era alto.'],
 'vibra',['sensores','iiot','cmms','historian','anomalia','inversor','twin','energia','oee'],{alt:'Termos: acelerômetro, FFT (a conta que gera o espectro), 1x (a rotação), harmônica, BPFO e BPFI (frequências de defeito das pistas do rolamento), envelope, termografia e análise de óleo. Normas: ISO 20816 (limites de vibração) e ISO 18436 (certificação de analistas). Parentes: manutenção corretiva (depois da quebra) e preventiva (por tempo).',tags:'manutencao preditiva vibracao espectro fft rolamento desbalanceamento desalinhamento folga termografia acelerometro analise condicao monitoramento'}),

E('oee','OEE (eficácia global do equipamento)','O indicador que diz quanto do tempo planejado a máquina realmente produziu peças boas',1,
 'O **OEE**, de overall equipment effectiveness, mede **quanto do tempo planejado a máquina realmente produziu peças boas**. É o produto de três fatores: a **disponibilidade**, que desconta as paradas; o **desempenho**, que desconta a velocidade abaixo da ideal; e a **qualidade**, que desconta as peças ruins. Como os três **se multiplicam**, três números que parecem bons dão um resultado bem menor: 90%, 90% e 95% resultam em cerca de 77%. O valor do cálculo está em separar o **tipo de perda**, para saber onde agir. Um OEE em torno de 85% costuma ser citado como referência de excelência, mas o que importa é comparar a máquina com ela mesma ao longo do tempo.',
 'É o **aproveitamento de uma viagem**. Você planejou 8 horas de estrada: quanto tempo andou de fato, sem paradas? Quão perto da velocidade ideal andou? Quanto do caminho foi na direção certa, sem se perder? O OEE multiplica as três respostas.',
 ['Saber onde a máquina está perdendo: parada, velocidade baixa ou refugo','Comparar máquinas, turnos e meses com o mesmo critério','Escolher onde investir: manutenção, ajuste de processo ou treinamento','Entender o número que o MES, o supervisório e a gestão mostram nos painéis'],
 ['python',L('tempo_planejado = 450     # minutos de produção planejada no turno','paradas = 45               # minutos parada sem querer','pecas_totais = 365','tempo_ciclo_ideal = 1.0     # minutos por peça','pecas_boas = 347','','operando = tempo_planejado - paradas','disponibilidade = operando / tempo_planejado','desempenho = (pecas_totais * tempo_ciclo_ideal) / operando','qualidade = pecas_boas / pecas_totais','oee = disponibilidade * desempenho * qualidade','print(round(oee * 100, 1))      # 77.1'),'As paradas planejadas, como a refeição, ficam fora do tempo planejado e não pesam no OEE. Cada fator ataca um tipo de perda: a disponibilidade, as quebras, os ajustes e a falta de material; o desempenho, as microparadas e o ritmo reduzido; a qualidade, o refugo e o retrabalho.'],
 'oee',['mes','scada','historian','cmms','manutencao-preditiva','industria40','erp','sql'],{alt:'Termos parecidos: TEEP (usa o tempo total do calendário, e não só o planejado), MTBF e MTTR (confiabilidade), e TPM (manutenção produtiva total), a escola de onde o OEE vem. As seis grandes perdas do TPM: quebras, setups e ajustes, microparadas, velocidade reduzida, defeitos e perdas de partida.',tags:'oee eficacia global do equipamento disponibilidade desempenho qualidade indicador tpm perdas producao kpi'}),

E('seguranca-maquinas','Segurança de máquinas (NR-12) e bloqueio','Como as máquinas protegem quem trabalha com elas, e como mexer nelas sem se machucar',2,
 'A **segurança de máquinas** é o conjunto de medidas que impede que uma máquina machuque quem trabalha com ela. No Brasil, a referência é a **NR-12**, que exige **proteções** nas partes perigosas, **dispositivos de segurança** e **procedimentos**. Os principais dispositivos são as **proteções com intertravamento**, que param a máquina ao abrir a porta; as **cortinas de luz**, que detectam a mão na zona de perigo; o **comando bimanual**; e a **parada de emergência**. Esses sinais passam por **relés ou CLPs de segurança**, com circuitos redundantes, e não pelo CLP comum. Antes de qualquer intervenção vale o **bloqueio e etiquetagem**: desenergizar, travar com cadeado, sinalizar e testar a ausência de energia.',
 'É o **cinto de segurança, o airbag e o freio ABS da fábrica**, todos juntos. Ninguém espera o acidente para instalar: o cinto já está lá antes. E um bom sistema não depende da atenção de uma pessoa: a máquina para sozinha quando a porta se abre.',
 ['Entender por que as máquinas têm portas intertravadas, cortinas de luz e botões de emergência','Fazer manutenção com bloqueio e etiquetagem, sem depender da sorte','Reconhecer um dispositivo burlado, como um sensor travado com fita, e o risco disso','Saber que circuito de segurança não se altera sem preparo e autorização'],
 ['estrutura',L('Procedimento típico de bloqueio e etiquetagem (resumo):','','1. Avisar a equipe e a operação, e parar a máquina de forma normal','2. Desligar e isolar TODAS as fontes de energia:','   elétrica, pneumática, hidráulica, mola e gravidade','3. Bloquear com o seu cadeado pessoal e etiquetar com nome e data','4. Descarregar a energia residual: ar, óleo, capacitores, peças suspensas','5. Testar: tentar ligar e confirmar a ausência de energia','6. Só então executar o serviço','7. No fim: retirar ferramentas, conferir as pessoas e tirar o SEU cadeado'),'Isto é um resumo para entender a ideia, e não o procedimento da sua empresa. Siga sempre o procedimento oficial e o treinamento recebido: a NR-10 vale para serviços elétricos e a NR-12 para máquinas. Cada pessoa usa o seu cadeado e só ela o retira. Nunca anule, ponte ou burle um dispositivo de segurança.'],
 null,['clp','sensores','inversor','servo','robotica','seguranca-ot','manutencao-preditiva','tempo-real','cmms'],{alt:'Normas e siglas: NR-12 (máquinas e equipamentos), NR-10 (instalações elétricas), ISO 13849 e IEC 62061 (projeto das funções de segurança), PL e SIL (níveis de desempenho e de integridade da segurança). LOTO é a sigla inglesa de lockout e tagout, que é o bloqueio e a etiquetagem. Esta ficha é conceitual: a norma e o treinamento valem mais.',tags:'seguranca de maquinas nr-12 nr12 nr-10 loto bloqueio etiquetagem cortina de luz intertravamento parada de emergencia bimanual rele de seguranca pl sil'}),

E('energia','Eficiência e qualidade de energia','Quanto a fábrica gasta de energia, e quão boa é a energia que chega às máquinas',2,
 'A energia elétrica da fábrica tem duas faces: **quanto se gasta** e **quão boa é** a energia que chega às máquinas. Na primeira, a conta depende do **consumo**, em quilowatt-hora, e da **demanda**, que é o pico de potência. Dá para economizar com **motores de alto rendimento**, classificados em IE2, IE3 e IE4, com **inversores** em bombas e ventiladores e desligando o que está ligado à toa. Na segunda, a **qualidade da energia** trata de defeitos como **queda e oscilação de tensão**, **desequilíbrio entre as fases**, **fator de potência** baixo e **harmônicas**, geradas por cargas como inversores, que distorcem a onda. Isso aquece motores, queima equipamentos e pode gerar multa.',
 'É o **consumo do carro e a qualidade do combustível**. De nada adianta um motor econômico se o combustível tiver água: ele falha, aquece e quebra mais cedo. Por isso se medem e se cuidam as duas coisas.',
 ['Ler a conta de energia e entender o que dá para reduzir','Escolher motor e inversor pensando em rendimento e retorno do investimento','Diagnosticar aquecimento e falhas causadas por tensão desequilibrada ou harmônicas','Acompanhar o consumo por máquina com medidores e supervisório','Entender o que é fator de potência e por que ele aparece na conta'],
 ['python',L('potencia_kw = 15.0        # potência elétrica da bomba a plena velocidade','horas_ano = 6000','tarifa = 0.80             # R$ por kWh (valor de exemplo)','','custo_pleno = potencia_kw * horas_ano * tarifa','','# com inversor, a bomba roda a 80% da velocidade;','# em bomba e ventilador, a potência cai com o cubo da velocidade','potencia_80 = potencia_kw * 0.8 ** 3','custo_inversor = potencia_80 * horas_ano * tarifa','','print(round(custo_pleno), round(custo_inversor))   # 72000 36864'),'A lei de afinidade diz que, em bombas e ventiladores centrífugos, a potência cai com o cubo da velocidade: 80% da velocidade pede só 51% da potência. É o cálculo ideal. Em bombas com muita altura de elevação a economia é menor, e o inversor e o motor também têm perdas. Os valores e a tarifa são de exemplo.'],
 null,['inversor','modbus','scada','historian','manutencao-preditiva','sinal420','iiot','python'],{alt:'Termos: kWh (energia), kW (potência), demanda contratada, fator de potência, harmônicas (THD), classes de rendimento IE1 a IE4 e desequilíbrio de tensão. Ferramentas: medidor de energia multifunção, analisador de qualidade de energia e termografia dos quadros.',tags:'energia eletrica eficiencia fator de potencia harmonicas demanda kwh motor ie3 qualidade de energia inversor consumo'}),

]);
